platform/avr/adc/adc.h File Reference
Read analog inputs.
#include <types.h>
Macros
#define ADC_CHANNEL_NOISE 5
Functions
void adc_init (void)
Initialize the ADC module.
u16 adc_read (u8 channel)
Read the analog value of a channel.
Detailed Description
Read analog inputs.
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
16.05.2023
Definition in file adc.h.
Macro Definition Documentation
ADC_CHANNEL_NOISE
#define ADC_CHANNEL_NOISE 5
Channel with noise used for random number generator
Definition at line 15 of file adc.h.
Function Documentation
adc_init()
void adc_init (void)
Initialize the ADC module.
Definition at line 13 of file adc.c.
{
    ADMUX = (1 << REFS0);
    ADCSRA = (1 << ADPS1) | (1 << ADPS0);
    ADCSRA |= (1 << ADEN);
    adc_read(ADC_CHANNEL_NOISE);
    log_boot_P(LOG_INIT, PSTR("ADC initialized"));
}
References ADC_CHANNEL_NOISE, adc_read(), and log_boot_P().
adc_read()
u16 adc_read (u8 channel)
Read the analog value of a channel.
Parameters
channel The analog channel to read
Returns
The 10-bit analog value (0-1023)
Definition at line 22 of file adc.c.
{
    ADMUX = (ADMUX & ~(0x1F)) | (channel & 0x1F);
    ADCSRA |= (1 << ADSC);
    while (ADCSRA & (1 << ADSC)) {}
    return ADCW;
}
Referenced by adc_init(), and random_init().