stdlib/alloc/alloc.c File Reference
#include <alloc.h>
Data Structures
struct CHUNK_HEADER
Macros
#define ALIGN 4
#define MIN_ALLOC 8
#define END 0xFFFFFFFF
Typedefs
typedef struct CHUNK_HEADER ChunkHeader
Functions
static void * _chunk_data (ChunkHeader *header)
Get a pointer to the data region of a memory chunk.
static ChunkHeader * _chunk_header (void *p)
Get the chunk header for a pointer that is about to be freed.
static ChunkHeader * _get_next (u32 next)
Get the next chunk header in the linked list.
static u32 _get_offset (ChunkHeader *header)
Get to offset of a chunk header on the heap.
void memalloc_init (ptr heap_start, i32 size)
Initialize the memory allocator. Do NOT call this function.
void * memalloc (u32 size)
Request a block of memory of size bytes This function will always return a valid pointer (never NULL). If the memory could not be allocated, the program will panic.
void memfree (void *p)
Frees memory previously allocated with memalloc
Variables
static ptr _heap_start
static ChunkHeader _first
static MemAllocInfo _info
Detailed Description
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
08.05.2023
Definition in file alloc.c.
Macro Definition Documentation
ALIGN
#define ALIGN 4
Allocation alignment
Definition at line 11 of file alloc.c.
END
#define END 0xFFFFFFFF
Heap end
Definition at line 17 of file alloc.c.
MIN_ALLOC
#define MIN_ALLOC 8
Minimum allocation size in bytes
Definition at line 14 of file alloc.c.
Typedef Documentation
ChunkHeader
typedef struct CHUNK_HEADER ChunkHeader
Linked list chunk header
Function Documentation
_chunk_data()
static void * _chunk_data (ChunkHeader * header) [inline], [static]
Get a pointer to the data region of a memory chunk.
Parameters
header Chunk header
Returns
Pointer to data area
Definition at line 46 of file alloc.c.
{
    return (void *)((ptr)header + sizeof(ChunkHeader));
}
Referenced by memalloc().
_chunk_header()
static ChunkHeader * _chunk_header (void * p) [inline], [static]
Get the chunk header for a pointer that is about to be freed.
Parameters
p Pointer
Returns
The corresponding header
Definition at line 57 of file alloc.c.
{
    return (ChunkHeader *)((ptr)p - sizeof(ChunkHeader));
}
Referenced by memfree().
_get_next()
static ChunkHeader * _get_next (u32 next) [inline], [static]
Get the next chunk header in the linked list.
Parameters
next Chunk offset
Returns
Pointer to next chunk header or NULL if it is the last one
Definition at line 68 of file alloc.c.
{
    if(next == END)
    {
        return NULL;
    }
    return (ChunkHeader *)(_heap_start + next);
}
References _heap_start, and END.
Referenced by memalloc(), memalloc_init(), and memfree().
_get_offset()
static u32 _get_offset (ChunkHeader * header) [inline], [static]
Get to offset of a chunk header on the heap.
Parameters
header Pointer to chunk header
Returns
Offset in bytes after the start of the heap
Definition at line 84 of file alloc.c.
{
    return (ptr)header - _heap_start;
}
References _heap_start.
Referenced by memalloc(), and memfree().
memalloc()
void * memalloc (u32 size)
Request a block of memory of size bytes This function will always return a valid pointer (never NULL). If the memory could not be allocated, the program will panic.
Parameters
size Number of bytes
Returns
Pointer to allocated memory
Definition at line 104 of file alloc.c.
{
    ChunkHeader *cur, *prev;
    if(size == 0)
    {
        return NULL;
    }
    /* Minimum allocation size */
    if(size < MIN_ALLOC)
    {
        size = MIN_ALLOC;
    }
    /* Ensure alignment */
    size = ((size + ALIGN - 1) / ALIGN) * ALIGN;
    _info.Used += size;
    _info.Total += size + sizeof(ChunkHeader);
    /* Find free chunk */
    for(prev = &_first, cur = _get_next(prev->Next);
        cur; prev = cur, cur = _get_next(cur->Next))
    {
        if(size + sizeof(ChunkHeader) == cur->Size)
        {
            /* --- Perfect fit --- */
            /* Remove chunk from free list */
            prev->Next = cur->Next;
            /* Return pointer to data area */
            return _chunk_data(cur);
        }
        else if(size + 2 * sizeof(ChunkHeader) < cur->Size)
        {
            /* --- First fit --- */
            /* Split chunk in two */
            ChunkHeader *second =
                (ChunkHeader *)((ptr)cur + sizeof(ChunkHeader) + size);
            second->Size = cur->Size - sizeof(ChunkHeader) - size;
            second->Next = cur->Next;
            prev->Next = _get_offset(second);
            /* Reduce the size of first part by the size of the second part */
            cur->Size = size + sizeof(ChunkHeader);
            /* Return pointer to data area of second part */
            return _chunk_data(cur);
        }
    }
    /* Very unlikely */
    return NULL;
}
References _chunk_data(), _first, _get_next(), _get_offset(), _info, ALIGN, MIN_ALLOC, CHUNK_HEADER::Next, CHUNK_HEADER::Size, MemAllocInfo::Total, and MemAllocInfo::Used.
Referenced by vector_init(), and vector_replace().
memalloc_init()
void memalloc_init (ptr heap_start, i32 size)
Initialize the memory allocator. Do NOT call this function.
Parameters
heap_start Heap start address
size Maximum size of the heap
Definition at line 90 of file alloc.c.
{
    ChunkHeader *next;
    _heap_start = heap_start;
    _info.Size = size;
    _first.Next = 0;
    next = _get_next(_first.Next);
    next->Size = size;
    next->Next = END;
}
References _first, _get_next(), _heap_start, _info, END, CHUNK_HEADER::Next, CHUNK_HEADER::Size, and MemAllocInfo::Size.
memfree()
void memfree (void * p)
Frees memory previously allocated with memalloc
Parameters
p Pointer
Definition at line 160 of file alloc.c.
{
    ChunkHeader *next, *prev, *header;
    header = _chunk_header(p);
    _info.Used -= header->Size - sizeof(ChunkHeader);
    _info.Total -= header->Size;
    for(prev = &_first, next = _get_next(prev->Next);
        next; prev = next, next = _get_next(next->Next))
    {
        if(next > header)
        {
            /* Merge chunks if possible */
            bool mergePrev = ((ptr)prev + prev->Size == (ptr)header);
            bool mergeNext = ((ptr)header + header->Size == (ptr)next);
            if(mergeNext && mergePrev)
            {
                /* Both Prev and Next are free */
                prev->Next = next->Next;
                prev->Size += header->Size + next->Size;
            }
            else if(mergePrev)
            {
                /* Prev is free */
                prev->Size += header->Size;
            }
            else if(mergeNext)
            {
                /* Next is free */
                header->Size += next->Size;
                header->Next = next->Next;
                prev->Next = _get_offset(header);
            }
            else
            {
                /* Both sides are used */
                header->Next = prev->Next;
                prev->Next = _get_offset(header);
            }
            return;
        }
    }
}
References _chunk_header(), _first, _get_next(), _get_offset(), _info, CHUNK_HEADER::Next, CHUNK_HEADER::Size, MemAllocInfo::Total, and MemAllocInfo::Used.
Referenced by vector_destroy(), and vector_replace().
Variable Documentation
_first
ChunkHeader _first [static]
First dummy memory chunk
Definition at line 33 of file alloc.c.
Referenced by memalloc(), memalloc_init(), and memfree().
_heap_start
ptr _heap_start [static]
Heap start address
Definition at line 30 of file alloc.c.
Referenced by _get_next(), _get_offset(), and memalloc_init().
_info
MemAllocInfo _info [static]
Memory allocator state info
Definition at line 36 of file alloc.c.
Referenced by memalloc(), memalloc_init(), and memfree().