stdlib/alloc/alloc.h File Reference
Manual memory allocator.
#include <types.h>
Data Structures
struct MemAllocInfo
Functions
void memalloc_init (ptr heap_start, i32 size)
Initialize the memory allocator. Do NOT call this function.
void * memalloc (u32 size)
Request a block of memory of size bytes This function will always return a valid pointer (never NULL). If the memory could not be allocated, the program will panic.
void memfree (void *p)
Frees memory previously allocated with memalloc
MemAllocInfo * memalloc_info (void)
Returns memory allocator information and status.
Detailed Description
Manual memory allocator.
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
15.05.2023
Definition in file alloc.h.
Function Documentation
memalloc()
void * memalloc (u32 size)
Request a block of memory of size bytes This function will always return a valid pointer (never NULL). If the memory could not be allocated, the program will panic.
Parameters
size Number of bytes
Returns
Pointer to allocated memory
Definition at line 104 of file alloc.c.
{
    ChunkHeader *cur, *prev;
    if(size == 0)
    {
        return NULL;
    }
    /* Minimum allocation size */
    if(size < MIN_ALLOC)
    {
        size = MIN_ALLOC;
    }
    /* Ensure alignment */
    size = ((size + ALIGN - 1) / ALIGN) * ALIGN;
    _info.Used += size;
    _info.Total += size + sizeof(ChunkHeader);
    /* Find free chunk */
    for(prev = &_first, cur = _get_next(prev->Next);
        cur; prev = cur, cur = _get_next(cur->Next))
    {
        if(size + sizeof(ChunkHeader) == cur->Size)
        {
            /* --- Perfect fit --- */
            /* Remove chunk from free list */
            prev->Next = cur->Next;
            /* Return pointer to data area */
            return _chunk_data(cur);
        }
        else if(size + 2 * sizeof(ChunkHeader) < cur->Size)
        {
            /* --- First fit --- */
            /* Split chunk in two */
            ChunkHeader *second =
                (ChunkHeader *)((ptr)cur + sizeof(ChunkHeader) + size);
            second->Size = cur->Size - sizeof(ChunkHeader) - size;
            second->Next = cur->Next;
            prev->Next = _get_offset(second);
            /* Reduce the size of first part by the size of the second part */
            cur->Size = size + sizeof(ChunkHeader);
            /* Return pointer to data area of second part */
            return _chunk_data(cur);
        }
    }
    /* Very unlikely */
    return NULL;
}
References _chunk_data(), _first, _get_next(), _get_offset(), _info, ALIGN, MIN_ALLOC, CHUNK_HEADER::Next, CHUNK_HEADER::Size, MemAllocInfo::Total, and MemAllocInfo::Used.
Referenced by vector_init(), and vector_replace().
memalloc_info()
MemAllocInfo * memalloc_info (void)
Returns memory allocator information and status.
Returns
Pointer to memalloc info struct
memalloc_init()
void memalloc_init (ptr heap_start, i32 size)
Initialize the memory allocator. Do NOT call this function.
Parameters
heap_start Heap start address
size Maximum size of the heap
Definition at line 90 of file alloc.c.
{
    ChunkHeader *next;
    _heap_start = heap_start;
    _info.Size = size;
    _first.Next = 0;
    next = _get_next(_first.Next);
    next->Size = size;
    next->Next = END;
}
References _first, _get_next(), _heap_start, _info, END, CHUNK_HEADER::Next, CHUNK_HEADER::Size, and MemAllocInfo::Size.
memfree()
void memfree (void * p)
Frees memory previously allocated with memalloc
Parameters
p Pointer
Definition at line 160 of file alloc.c.
{
    ChunkHeader *next, *prev, *header;
    header = _chunk_header(p);
    _info.Used -= header->Size - sizeof(ChunkHeader);
    _info.Total -= header->Size;
    for(prev = &_first, next = _get_next(prev->Next);
        next; prev = next, next = _get_next(next->Next))
    {
        if(next > header)
        {
            /* Merge chunks if possible */
            bool mergePrev = ((ptr)prev + prev->Size == (ptr)header);
            bool mergeNext = ((ptr)header + header->Size == (ptr)next);
            if(mergeNext && mergePrev)
            {
                /* Both Prev and Next are free */
                prev->Next = next->Next;
                prev->Size += header->Size + next->Size;
            }
            else if(mergePrev)
            {
                /* Prev is free */
                prev->Size += header->Size;
            }
            else if(mergeNext)
            {
                /* Next is free */
                header->Size += next->Size;
                header->Next = next->Next;
                prev->Next = _get_offset(header);
            }
            else
            {
                /* Both sides are used */
                header->Next = prev->Next;
                prev->Next = _get_offset(header);
            }
            return;
        }
    }
}
References _chunk_header(), _first, _get_next(), _get_offset(), _info, CHUNK_HEADER::Next, CHUNK_HEADER::Size, MemAllocInfo::Total, and MemAllocInfo::Used.
Referenced by vector_destroy(), and vector_replace().