apps/tetris/main.c File Reference
Tetris game for the OS.
#include <std.h>
Data Structures
struct Piece
struct PieceData
Macros
#define FIELD_WIDTH 10
#define FIELD_HEIGHT 20
#define FIELD_SIZE (FIELD_WIDTH * FIELD_HEIGHT)
#define BLOCK_SIZE 20
#define FALL_SPEED_DEFAULT 200
#define FALL_SPEED_FAST 30
#define WINDOW_TITLE `Tetris`
#define STATUS_RUNNING 1
Typedefs
typedef u8 FieldType
Enumerations
enum PieceType {
I
, J
, L
, O
,
S
, T
, Z
 }
Functions
static i32 _field_get (FieldType *field, i32 x, i32 y)
Get the piece at a position inside a field.
static void _field_shift (FieldType *field, i32 row)
Clear a row and shift down rows above.
static i32 _field_rows (FieldType *field)
Remove full rows and update score.
static void _draw_grid (void)
Draw field grid.
static PieceType _new_piece (Piece *p)
Get the next random tetris piece.
static bool _valid_position (FieldType *field, Piece *p)
Check if the position of a piece is valid, meaning that it is not outside of the frame and not colliding with pieces on the field.
static void _to_field (FieldType *field, Piece *p)
Place a piece into a field.
static void _draw_field (void)
Draw the tetris field to the screen.
void event_key (Key key, i32 chr, KeyState state)
Main key event handler.
void setup (void)
Main setup function, initialize game.
void loop (void)
Main game loop, update state.
Variables
const PieceData Pieces []
static Piece _cp
static Piece _np
static Status _status
static i32 _ticks_update = FALL_SPEED_DEFAULT
static bool _changed
static FieldType _field [FIELD_SIZE]
Detailed Description
Tetris game for the OS.
Author
Anton Tchekov
Version
0.1
Date
24.05.2023
Definition in file main.c.
Macro Definition Documentation
BLOCK_SIZE
#define BLOCK_SIZE 20
Size of each block in pixels
Definition at line 22 of file main.c.
FALL_SPEED_DEFAULT
#define FALL_SPEED_DEFAULT 200
Default falling speed in milliseconds
Definition at line 25 of file main.c.
FALL_SPEED_FAST
#define FALL_SPEED_FAST 30
Falling speed when down button is pressed
Definition at line 28 of file main.c.
FIELD_HEIGHT
#define FIELD_HEIGHT 20
Field height in blocks
Definition at line 16 of file main.c.
FIELD_SIZE
#define FIELD_SIZE (FIELD_WIDTH * FIELD_HEIGHT)
Field size in blocks
Definition at line 19 of file main.c.
FIELD_WIDTH
#define FIELD_WIDTH 10
Field width in blocks
Definition at line 13 of file main.c.
STATUS_RUNNING
#define STATUS_RUNNING 1
Game state: running
Definition at line 34 of file main.c.
WINDOW_TITLE
#define WINDOW_TITLE `Tetris`
Window title string
Definition at line 31 of file main.c.
Typedef Documentation
FieldType
typedef u8 FieldType
VARIABLES Type that stores what piece type a tile in a field belongs to
Definition at line 108 of file main.c.
Enumeration Type Documentation
PieceType
enum PieceType
Piece Type
Definition at line 37 of file main.c.
{ I, J, L, O, S, T, Z } PieceType;
Function Documentation
_draw_field()
static void _draw_field (void) [static]
Draw the tetris field to the screen.
Definition at line 318 of file main.c.
{
    static FieldType new[FIELD_SIZE], prev[FIELD_SIZE];
    i32 x, y, offset;
    PieceType type;
    memcpy(new, _field, sizeof(_field));
    _to_field(new, &_cp);
    //_to_field(new, &_np);
    for(y = 0; y < FIELD_HEIGHT; ++y)
    {
        for(x = 0; x < FIELD_WIDTH; ++x)
        {
            offset = y * FIELD_WIDTH + x;
            type = new[offset];
            Color color = type ? Pieces[type - 1].Fill : COLOR_BLACK;
            if(type != prev[offset])
            {
                gfx_rect(
                    x * BLOCK_SIZE + 1,
                    y * BLOCK_SIZE + 1,
                    BLOCK_SIZE - 1,
                    BLOCK_SIZE - 1,
                    color);
            }
        }
    }
    memcpy(prev, new, sizeof(_field));
}
References _cp, _field, _to_field(), BLOCK_SIZE, COLOR_BLACK, FIELD_HEIGHT, FIELD_SIZE, FIELD_WIDTH, PieceData::Fill, gfx_rect(), memcpy(), and Pieces.
Referenced by loop().
_draw_grid()
static void _draw_grid (void) [static]
Draw field grid.
Definition at line 197 of file main.c.
{
    i32 i;
    for(i = 0; i <= BLOCK_SIZE * FIELD_WIDTH; i += BLOCK_SIZE)
    {
        gfx_rect(i, 0, 1, BLOCK_SIZE * FIELD_HEIGHT, COLOR_WHITE);
    }
    for(i = 0; i <= BLOCK_SIZE * FIELD_HEIGHT; i += BLOCK_SIZE)
    {
        gfx_rect(0, i, BLOCK_SIZE * FIELD_WIDTH, 1, COLOR_WHITE);
    }
}
References BLOCK_SIZE, COLOR_WHITE, FIELD_HEIGHT, FIELD_WIDTH, and gfx_rect().
Referenced by setup().
_field_get()
static i32 _field_get (FieldType * field, i32 x, i32 y) [static]
Get the piece at a position inside a field.
Parameters
field The field
x X-coordinate
y Y-coordinate
Returns
Definition at line 138 of file main.c.
{
    return (x < 0 || x >= FIELD_WIDTH || y < 0 || y >= FIELD_HEIGHT) ? -1 :
        field[y * FIELD_WIDTH + x];
}
References FIELD_HEIGHT, and FIELD_WIDTH.
Referenced by _valid_position().
_field_rows()
static i32 _field_rows (FieldType * field) [static]
Remove full rows and update score.
Parameters
field Playing field
Returns
Score change
Definition at line 169 of file main.c.
{
    i32 x, y, score;
    score = 0;
    for(y = 0; y < FIELD_HEIGHT; ++y)
    {
        for(x = 0; x < FIELD_WIDTH; ++x)
        {
            if(!field[y * FIELD_WIDTH + x])
            {
                break;
            }
        }
        if(x == FIELD_WIDTH)
        {
            _field_shift(field, y);
            score += 100;
        }
    }
    return score;
}
References _field_shift(), FIELD_HEIGHT, and FIELD_WIDTH.
Referenced by loop().
_field_shift()
static void _field_shift (FieldType * field, i32 row) [static]
Clear a row and shift down rows above.
Parameters
field Playing field
row The row to remove
Definition at line 150 of file main.c.
{
    i32 x, y;
    for(y = row; y > 0; --y)
    {
        for(x = 0; x < FIELD_WIDTH; ++x)
        {
            field[y * FIELD_WIDTH + x] =
                field[(y - 1) * FIELD_WIDTH + x];
        }
    }
}
References FIELD_WIDTH.
Referenced by _field_rows().
_new_piece()
static PieceType _new_piece (Piece * p) [static]
Get the next random tetris piece.
Parameters
p Output parameter for new piece
Returns
Piece type of the following piece
Definition at line 217 of file main.c.
{
    static PieceType next, bag[7];
    static i32 idx = 6;
    if(idx == 6)
    {
        /* create a new shuffled bag of pieces */
        int i, j, tmp;
        for(i = 0; i < 7; ++i)
        {
            bag[i] = i;
        }
        for(i = 0; i < 7; ++i)
        {
            j = rand() % 7;
            tmp = bag[i];
            bag[i] = bag[j];
            bag[j] = tmp;
        }
        idx = 0;
    }
    p->X = 4;
    p->Y = 0;
    p->Rotation = 0;
    p->Type = next;
    next = bag[idx++];
    return next;
}
References rand(), Piece::Rotation, Piece::Type, Piece::X, and Piece::Y.
Referenced by loop(), and setup().
_to_field()
static void _to_field (FieldType * field, Piece * p) [static]
Place a piece into a field.
Parameters
field Pointer to the field on which to put the piece
p Pointer to the piece that should be placed
Definition at line 290 of file main.c.
{
    i32 x, y, bit, row, col;
    u16 blocks;
    row = col = 0;
    blocks = Pieces[p->Type].Blocks[p->Rotation];
    for(bit = 0x8000; bit > 0; bit >>= 1)
    {
        if(blocks & bit)
        {
            x = p->X + col;
            y = p->Y + row;
            field[y * FIELD_WIDTH + x] = p->Type + 1;
        }
        if(++col == 4)
        {
            col = 0;
            ++row;
        }
    }
}
References PieceData::Blocks, FIELD_WIDTH, Pieces, Piece::Rotation, Piece::Type, Piece::X, and Piece::Y.
Referenced by _draw_field(), and loop().
_valid_position()
static bool _valid_position (FieldType * field, Piece * p) [static]
Check if the position of a piece is valid, meaning that it is not outside of the frame and not colliding with pieces on the field.
Parameters
field Pointer to field aray
p Pointer to piece
Returns
true if position is valid, false otherwise
Definition at line 258 of file main.c.
{
    i32 bit, row, col;
    u16 blocks;
    row = 0;
    col = 0;
    blocks = Pieces[p->Type].Blocks[p->Rotation];
    for(bit = 0x8000; bit > 0; bit >>= 1)
    {
        if((blocks & bit) && _field_get(field, p->X + col, p->Y + row))
        {
            return false;
        }
        if(++col == 4)
        {
            col = 0;
            ++row;
        }
    }
    return true;
}
References _field_get(), PieceData::Blocks, Pieces, Piece::Rotation, Piece::Type, Piece::X, and Piece::Y.
Referenced by event_key(), and loop().
event_key()
void event_key (Key key, i32 chr, KeyState state)
Main key event handler.
Parameters
key The key that was pressed
chr The character corresponding to the key
state Key state (pressed, repeat, released)
Definition at line 356 of file main.c.
{
    if(state == KEYSTATE_RELEASED)
    {
        switch(key)
        {
        case KEY_DOWN:
            _ticks_update = FALL_SPEED_DEFAULT;
            break;
        }
    }
    else
    {
        switch(key)
        {
        case KEY_DOWN:
            _ticks_update = FALL_SPEED_FAST;
            break;
        case KEY_UP:
            if(--_cp.Rotation == -1)
            {
                _cp.Rotation = 3;
            }
            if(_valid_position(_field, &_cp))
            {
                if(++_cp.Rotation == 4)
                {
                    _cp.Rotation = 0;
                }
            }
            _changed = true;
            break;
        case KEY_LEFT:
            --_cp.X;
            _changed = true;
            if(_valid_position(_field, &_cp))
            {
                ++_cp.X;
            }
            break;
        case KEY_RIGHT:
            ++_cp.X;
            _changed = true;
            if(_valid_position(_field, &_cp))
            {
                --_cp.X;
            }
            break;
        }
    }
    (void)chr;
}
References _changed, _cp, _field, _ticks_update, _valid_position(), FALL_SPEED_DEFAULT, FALL_SPEED_FAST, Piece::Rotation, and Piece::X.
loop()
void loop (void)
Main game loop, update state.
Loop function that is called repeatedly Must be implemented by user.
Definition at line 434 of file main.c.
{
    static u32 last_ticks, score;
    u32 ticks;
    if((ticks = millis()) > last_ticks + _ticks_update)
    {
        last_ticks = ticks;
        ++_cp.Y;
        if(_valid_position(_field, &_cp))
        {
            --_cp.Y;
            _to_field(_field, &_cp);
            score += _field_rows(_field);
            _np.Type = _new_piece(&_cp);
            _ticks_update = FALL_SPEED_DEFAULT;
            if(_valid_position(_field, &_cp))
            {
                memset(_field, 0, sizeof(_field));
            }
        }
        _changed = true;
    }
    if(_changed)
    {
        _changed = false;
        _draw_field();
    }
}
References _changed, _cp, _draw_field(), _field, _field_rows(), _new_piece(), _np, _ticks_update, _to_field(), _valid_position(), exit(), FALL_SPEED_DEFAULT, memset(), millis(), Piece::Type, and Piece::Y.
setup()
void setup (void)
Main setup function, initialize game.
Setup function that is called at program start. Must be implemented by user.
Definition at line 418 of file main.c.
{
    keyboard_register_event(event_key);
    _np.X = 11;
    _np.Y = 0;
    _np.Rotation = 1;
    memset(_field, 0, sizeof(_field));
    _np.Type = _new_piece(&_cp);
    _status = STATUS_RUNNING;
    _draw_grid();
    font_string(210, 10, "Next piece:", font_default, COLOR_WHITE, COLOR_BLACK);
}
References _cp, _draw_grid(), _field, _new_piece(), _np, _status, COLOR_BLACK, COLOR_WHITE, event_key(), font_string(), GFX_HEIGHT, gfx_image_rgb(), gfx_rect(), GFX_WIDTH, keyboard_register_event(), memset(), millis(), Piece::Rotation, STATUS_RUNNING, Piece::Type, Piece::X, and Piece::Y.
Variable Documentation
_changed
bool _changed [static]
Indicates that the field has changed and should be redrawn
Definition at line 123 of file main.c.
Referenced by event_key(), and loop().
_cp
Piece _cp [static]
Current Piece
Definition at line 111 of file main.c.
Referenced by _draw_field(), event_key(), loop(), and setup().
_field
FieldType _field[FIELD_SIZE] [static]
Array that stores landed, non-moving pieces
Definition at line 126 of file main.c.
Referenced by _draw_field(), event_key(), loop(), and setup().
_np
Piece _np [static]
Next Piece
Definition at line 114 of file main.c.
Referenced by loop(), and setup().
_status
Status _status [static]
Current game status (see enum above)
Definition at line 117 of file main.c.
Referenced by setup().
_ticks_update
i32 _ticks_update = FALL_SPEED_DEFAULT [static]
Milliseconds duration for a tile to move down by one tile
Definition at line 120 of file main.c.
Referenced by event_key(), and loop().
Pieces
const PieceData Pieces[]
All 7 tetrominos
Definition at line 66 of file main.c.
Referenced by _draw_field(), _to_field(), and _valid_position().