apps/test/main.c File Reference
Init program.
#include <std.h>
Macros
#define INPUT_WIDTH 220
#define BUTTON_WIDTH 140
#define BUTTON_HEIGHT 28
#define INPUT_USERNAME_Y 110
#define INPUT_PASSWORD_Y 160
#define BUTTON_LOGIN_Y 204
#define INPUT_LABEL_OFFSET 16
#define SHOW_ERROR_DELAY 2000
#define BLINK_DELAY 300
#define LABEL_ERROR_Y 60
#define LABEL_NO_APPS_Y 50
Functions
static void _show_error (void)
Show wrong password error.
static void _hide_error (void)
Hide wrong password error.
static void button_login_onclick (void)
Login button onclick and form enter submit handler.
static void window_login_onkey (Key key, i32 chr, KeyState state)
Window key event handler. Submit form on enter pressed.
static void event_key (Key key, i32 chr, KeyState state)
Main key event handler.
void setup (void)
Main setup function, called on program startup.
void loop (void)
Main loop function, called repeatedly.
Variables
static Window _window_login
static Window _window_apps
static Button _button_login
static Label _label_username
static Label _label_password
static Label _label_no_apps
static Label _label_response
static Input _input_username
static Input _input_password
static u32 _millis_error
static u32 _millis_blink
static bool _error
static bool _visible
static void * elements_login []
static void * elements_apps []
Detailed Description
Init program.
Author
Anton Tchekov
Version
0.1
Date
24.05.2023
Definition in file main.c.
Macro Definition Documentation
BLINK_DELAY
#define BLINK_DELAY 300
Blink interval
Definition at line 39 of file main.c.
BUTTON_HEIGHT
#define BUTTON_HEIGHT 28
Height of the login button
Definition at line 21 of file main.c.
BUTTON_LOGIN_Y
#define BUTTON_LOGIN_Y 204
Y-coordinate of the login button
Definition at line 30 of file main.c.
BUTTON_WIDTH
#define BUTTON_WIDTH 140
Width of the login button
Definition at line 18 of file main.c.
INPUT_LABEL_OFFSET
#define INPUT_LABEL_OFFSET 16
Offset of a label belonging to an input
Definition at line 33 of file main.c.
INPUT_PASSWORD_Y
#define INPUT_PASSWORD_Y 160
Y-coordinate of the password input
Definition at line 27 of file main.c.
INPUT_USERNAME_Y
#define INPUT_USERNAME_Y 110
Y-coordinate of the username input
Definition at line 24 of file main.c.
INPUT_WIDTH
#define INPUT_WIDTH 220
Width of all login input fields
Definition at line 15 of file main.c.
LABEL_ERROR_Y
#define LABEL_ERROR_Y 60
Error label Y-coordinate
Definition at line 42 of file main.c.
LABEL_NO_APPS_Y
#define LABEL_NO_APPS_Y 50
No Apps label Y-coordinate
Definition at line 45 of file main.c.
SHOW_ERROR_DELAY
#define SHOW_ERROR_DELAY 2000
Duration for which to show the error
Definition at line 36 of file main.c.
Function Documentation
_hide_error()
static void _hide_error (void) [static]
Hide wrong password error.
Definition at line 121 of file main.c.
{
    _error = false;
    label_show(&_label_response, false);
}
References _error, _label_response, and label_show().
Referenced by loop().
_show_error()
static void _show_error (void) [static]
Show wrong password error.
Definition at line 110 of file main.c.
{
    _error = true;
    _visible = true;
    _millis_blink = _millis_error = millis();
    label_show(&_label_response, true);
}
References _error, _label_response, _millis_blink, _millis_error, _visible, label_show(), and millis().
Referenced by button_login_onclick().
button_login_onclick()
static void button_login_onclick (void) [static]
Login button onclick and form enter submit handler.
Yes I know calling this is a bad practice is an understatement. I apologise in advance to the programming gods for hardcoding credentials in plain text.
The whole point of this is to showcase the GUI and have it look cool.
Definition at line 130 of file main.c.
{
    if(!strncmp(vector_data(&_input_username.Text), "Anton", 5) &&
        !strncmp(vector_data(&_input_password.Text), "OSDEV1234", 9))
    {
        window_open(&_window_apps);
    }
    else
    {
        _show_error();
    }
}
References _input_password, _input_username, _show_error(), _window_apps, strncmp(), Input::Text, vector_data(), and window_open().
Referenced by setup(), and window_login_onkey().
event_key()
static void event_key (Key key, i32 chr, KeyState state) [static]
Main key event handler.
Parameters
key The key that was pressed
chr Character corresponding to the key
state Current key state
Definition at line 174 of file main.c.
{
    window_event_key(key, chr, state);
}
References window_event_key().
loop()
void loop (void)
Main loop function, called repeatedly.
Loop function that is called repeatedly Must be implemented by user.
Definition at line 242 of file main.c.
{
    if(_error)
    {
        u32 now = millis();
        if(now > _millis_error + SHOW_ERROR_DELAY)
        {
            _hide_error();
        }
        else if(now > _millis_blink + BLINK_DELAY)
        {
            _visible = !_visible;
            label_show(&_label_response, _visible);
            _millis_blink = now;
        }
    }
}
References _error, _hide_error(), _label_response, _millis_blink, _millis_error, _visible, BLINK_DELAY, label_show(), millis(), and SHOW_ERROR_DELAY.
setup()
void setup (void)
Main setup function, called on program startup.
Setup function that is called at program start. Must be implemented by user.
Definition at line 182 of file main.c.
{
    keyboard_register_event(event_key);
    label_init(&_label_response,
        GFX_WIDTH / 2,
        LABEL_ERROR_Y,
        FLAG_ALIGN_CENTER | FLAG_INVERTED | FLAG_INVISIBLE,
        "Wrong username or password");
    label_init(&_label_username,
        GFX_WIDTH / 2 - INPUT_WIDTH / 2,
        INPUT_USERNAME_Y - INPUT_LABEL_OFFSET,
        FLAG_ALIGN_LEFT,
        "Username:");
    input_init(&_input_username,
        GFX_WIDTH / 2 - INPUT_WIDTH / 2,
        INPUT_USERNAME_Y,
        INPUT_WIDTH);
    label_init(&_label_password,
        GFX_WIDTH / 2 - INPUT_WIDTH / 2,
        INPUT_PASSWORD_Y - INPUT_LABEL_OFFSET,
        FLAG_ALIGN_LEFT,
        "Password:");
    input_init(&_input_password,
        GFX_WIDTH / 2 - INPUT_WIDTH / 2,
        INPUT_PASSWORD_Y,
        INPUT_WIDTH);
    _input_password.Flags |= FLAG_PASSWORD;
    button_init(&_button_login,
        GFX_WIDTH / 2 - BUTTON_WIDTH / 2,
        BUTTON_LOGIN_Y,
        BUTTON_WIDTH,
        BUTTON_HEIGHT,
        "[ Login ]",
        button_login_onclick);
    label_init(&_label_no_apps,
        GFX_WIDTH / 2,
        LABEL_NO_APPS_Y,
        FLAG_ALIGN_CENTER,
        "No apps installed");
    window_init(&_window_apps, "Apps", elements_apps,
        ARRLEN(elements_apps), NULL);
    window_init(&_window_login, "Login", elements_login,
        ARRLEN(elements_login), window_login_onkey);
    window_open(&_window_login);
}
References _button_login, _input_password, _input_username, _label_no_apps, _label_password, _label_response, _label_username, _window_apps, _window_login, ARRLEN, BUTTON_HEIGHT, button_init(), button_login_onclick(), BUTTON_LOGIN_Y, BUTTON_WIDTH, elements_apps, elements_login, event_key(), FLAG_ALIGN_CENTER, FLAG_ALIGN_LEFT, FLAG_INVERTED, FLAG_INVISIBLE, FLAG_PASSWORD, Input::Flags, GFX_WIDTH, input_init(), INPUT_LABEL_OFFSET, INPUT_PASSWORD_Y, INPUT_USERNAME_Y, INPUT_WIDTH, keyboard_register_event(), LABEL_ERROR_Y, label_init(), LABEL_NO_APPS_Y, window_init(), window_login_onkey(), and window_open().
window_login_onkey()
static void window_login_onkey (Key key, i32 chr, KeyState state) [static]
Window key event handler. Submit form on enter pressed.
Parameters
key The key that was pressed
chr Character corresponding to the key
state Current key state
Definition at line 157 of file main.c.
{
    if(key == KEY_RETURN && state == KEYSTATE_PRESSED)
    {
        button_login_onclick();
    }
    (void)chr;
}
References button_login_onclick().
Referenced by setup().
Variable Documentation
_button_login
Button _button_login [static]
Login button
Definition at line 56 of file main.c.
Referenced by setup().
_error
bool _error [static]
Boolean indicator that there is an error
Definition at line 83 of file main.c.
Referenced by _hide_error(), _show_error(), and loop().
_input_password
Input _input_password [static]
Password input field (characters are hidden with asterisks)
Definition at line 74 of file main.c.
Referenced by button_login_onclick(), and setup().
_input_username
Input _input_username [static]
Username input field
Definition at line 71 of file main.c.
Referenced by button_login_onclick(), and setup().
_label_no_apps
Label _label_no_apps [static]
Label to indicate that there are no installed apps
Definition at line 65 of file main.c.
Referenced by setup().
_label_password
Label _label_password [static]
Label for password input field
Definition at line 62 of file main.c.
Referenced by setup().
_label_response
Label _label_response [static]
Blinking error label for when password is wrong
Definition at line 68 of file main.c.
Referenced by _hide_error(), _show_error(), loop(), and setup().
_label_username
Label _label_username [static]
Label for username input field
Definition at line 59 of file main.c.
Referenced by setup().
_millis_blink
u32 _millis_blink [static]
TImestamp since the last blink
Definition at line 80 of file main.c.
Referenced by _show_error(), and loop().
_millis_error
u32 _millis_error [static]
Timestamp when the error occured
Definition at line 77 of file main.c.
Referenced by _show_error(), and loop().
_visible
bool _visible [static]
Boolean indicating that the label is visible
Definition at line 86 of file main.c.
Referenced by _show_error(), and loop().
_window_apps
Window _window_apps [static]
Apps window with icons
Definition at line 53 of file main.c.
Referenced by button_login_onclick(), and setup().
_window_login
Window _window_login [static]
Login window with username and password field and login button
Definition at line 50 of file main.c.
Referenced by setup().
elements_apps
void* elements_apps[] [static]
Initial value:
=
{
    &_label_no_apps
}
Elements array of the apps window
Definition at line 100 of file main.c.
Referenced by setup().
elements_login
void* elements_login[] [static]
Initial value:
=
{
    &_label_response,
    &_label_username,
    &_input_username,
    &_label_password,
    &_input_password,
    &_button_login,
}
Elements array of the login window
Definition at line 89 of file main.c.
Referenced by setup().