apps/editor/main.c File Reference
Text/Code Editor App.
#include <std.h>
#include <ubuntu_regular.h>
#include `keyword.h`
Macros
#define INITIAL_CODE_CAPACITY 16
#define LINE_HEIGHT 12
Functions
void event_key (Key key, i32 chr, KeyState state)
Main key event handler.
static void _draw_line_numbers (i32 max_line)
Draw editor line numbers.
static Color _get_brace_color (i32 nesting)
Get the color of a brace at a nesting level.
static Color _get_bracket_color (i32 nesting)
Get the color of a bracket at a nesting level.
static Color _get_paren_color (i32 nesting)
Get the color of a parenthesis at a nesting level.
static void _draw_code (void)
Render code to screen with syntax highlighting.
void setup (void)
Setup function that is called at program start. Must be implemented by user.
void loop (void)
Loop function that is called repeatedly Must be implemented by user.
Variables
static const char _file []
static Vector _code
static Window _window_editor
Detailed Description
Text/Code Editor App.
Author
Anton Tchekov
Version
0.1
Date
24.05.2023
Definition in file main.c.
Macro Definition Documentation
INITIAL_CODE_CAPACITY
#define INITIAL_CODE_CAPACITY 16
Initial code vector capacity
Definition at line 15 of file main.c.
LINE_HEIGHT
#define LINE_HEIGHT 12
Editor line height in pixels
Definition at line 18 of file main.c.
Function Documentation
_draw_code()
static void _draw_code (void) [static]
Render code to screen with syntax highlighting.
Definition at line 172 of file main.c.
{
    i32 i, j, braces, brackets, parens, len, line, col, keyword_remain;
    bool in_comment, in_string, in_char;
    char *text, c;
    Color color;
    len = vector_len(&_code);
    text = vector_data(&_code);
    in_comment = false;
    in_string = false;
    in_char = false;
    keyword_remain = 0;
    col = 0;
    line = 0;
    braces = 0;
    brackets = 0;
    parens = 0;
    for(i = 0; i < len; ++i)
    {
        color = COLOR_WHITE;
        c = text[i];
        if(!keyword_remain && !isalnum(text[i - 1]))
        {
            i32 word_len;
            /* Find end of word */
            for (j = i; j < len; ++j)
            {
                if (!isalnum(text[j]))
                {
                    break;
                }
            }
            word_len = j - i;
            if(keyword_detect(&text[i], word_len))
            {
                keyword_remain = word_len;
                color = COLOR_BLUE;
            }
        }
        if(c == '{')
        {
            color = _get_brace_color(braces);
            ++braces;
        }
        else if(c == '}')
        {
            --braces;
            color = _get_brace_color(braces);
        }
        else if(c == '[')
        {
            color = _get_bracket_color(brackets);
            ++brackets;
        }
        else if(c == ']')
        {
            --brackets;
            color = _get_bracket_color(brackets);
        }
        else if(c == '(')
        {
            color = _get_paren_color(parens);
            ++parens;
        }
        else if(c == ')')
        {
            --parens;
            color = _get_paren_color(parens);
        }
        else if(isdigit(c))
        {
            color = COLOR_LIME;
        }
        if(keyword_remain)
        {
            --keyword_remain;
            color = COLOR_BLUE;
        }
        if(c == '\'' && text[i - 1] != '\\' && !in_string)
        {
            color = COLOR_ORANGE;
            in_char = !in_char;
        }
        if(c == '"' && text[i - 1] != '\\' && !in_char)
        {
            color = COLOR_ORANGE;
            in_string = !in_string;
        }
        if(c == '/' && text[i + 1] == '*')
        {
            color = COLOR_GREEN;
            in_comment = true;
        }
        if(c == '/' && text[i - 1] == '*')
        {
            color = COLOR_GREEN;
            in_comment = false;
        }
        if(in_char || in_string)
        {
            color = COLOR_ORANGE;
        }
        if(in_comment)
        {
            color = COLOR_GREEN;
        }
        if(c == '\n')
        {
            col = 0;
            ++line;
        }
        else
        {
            i32 x, y;
            x = col * 8 + 33;
            y = line * LINE_HEIGHT + 22;
            ++col;
            if (x <= GFX_WIDTH - 10 && y <= GFX_HEIGHT - 10)
            {
                font_string_len(x, y, &c, 1, ubuntu_regular, color, COLOR_BLACK);
            }
        }
    }
}
References _code, _get_brace_color(), _get_bracket_color(), _get_paren_color(), COLOR_BLACK, COLOR_BLUE, COLOR_GREEN, COLOR_WHITE, font_string_len(), GFX_HEIGHT, GFX_WIDTH, isalnum(), isdigit(), keyword_detect(), LINE_HEIGHT, vector_data(), and vector_len().
Referenced by setup().
_draw_line_numbers()
static void _draw_line_numbers (i32 max_line) [static]
Draw editor line numbers.
Parameters
max_line Number of line numbers to draw
Definition at line 79 of file main.c.
{
    static i32 lines_count = 0;
    if(lines_count == max_line)
    {
        return;
    }
    if(lines_count > max_line)
    {
        i32 start;
        /* Remove line numbers by drawing rectangle on top */
        start = max_line * LINE_HEIGHT + TITLE_BAR_HEIGHT;
        gfx_rect(0, start, GFX_HEIGHT - start, 29, THEME_BLACK);
    }
    else
    {
        char buf[16];
        i32 i;
        /* Add line numbers */
        for(i = lines_count; i <= max_line; ++i)
        {
            snprintf(buf, sizeof(buf), "%d", i);
            font_string(
                25 - font_string_width(buf, ubuntu_regular),
                i * LINE_HEIGHT + 22,
                buf, ubuntu_regular, COLOR_WHITE, THEME_BLACK);
        }
    }
    lines_count = max_line;
}
References COLOR_WHITE, font_string(), font_string_width(), GFX_HEIGHT, gfx_rect(), LINE_HEIGHT, snprintf(), THEME_BLACK, and TITLE_BAR_HEIGHT.
Referenced by setup().
_get_brace_color()
static Color _get_brace_color (i32 nesting) [static]
Get the color of a brace at a nesting level.
Parameters
nesting At how many nesting levels the brace is located
Returns
Color the brace should receive
Definition at line 121 of file main.c.
{
    static Color _colors[] =
    {
        0xD4D4AAFF,
        0xD1A06EFF,
        0x742704FF
    };
    return _colors[nesting % ARRLEN(_colors)];
}
References ARRLEN.
Referenced by _draw_code().
_get_bracket_color()
static Color _get_bracket_color (i32 nesting) [static]
Get the color of a bracket at a nesting level.
Parameters
nesting At how many nesting levels the bracket is located
Returns
Color the bracket should receive
Definition at line 139 of file main.c.
{
    static Color _colors[] =
    {
        0xD4D4AAFF,
        0xD1A06EFF,
        0x742704FF
    };
    return _colors[nesting % ARRLEN(_colors)];
}
References ARRLEN.
Referenced by _draw_code().
_get_paren_color()
static Color _get_paren_color (i32 nesting) [static]
Get the color of a parenthesis at a nesting level.
Parameters
nesting At how many nesting levels the parenthesis is located
Returns
Color the parenthesis should receive
Definition at line 157 of file main.c.
{
    static Color _colors[] =
    {
        0xD4D4AAFF,
        0xD1A06EFF,
        0x742704FF
    };
    return _colors[nesting % ARRLEN(_colors)];
}
References ARRLEN.
Referenced by _draw_code().
event_key()
void event_key (Key key, i32 chr, KeyState state)
Main key event handler.
Parameters
key The key that was pressed
chr The character corresponding to the key
state Key state (pressed, repeat, released)
Definition at line 69 of file main.c.
{
    (void)key, (void)chr, (void)state;
}
Referenced by setup().
loop()
void loop (void)
Loop function that is called repeatedly Must be implemented by user.
Definition at line 331 of file main.c.
{
}
setup()
void setup (void)
Setup function that is called at program start. Must be implemented by user.
Definition at line 315 of file main.c.
{
    keyboard_register_event(event_key);
    keyword_init();
    vector_init(&_code, sizeof(char), INITIAL_CODE_CAPACITY);
    vector_set(&_code, _file, ARRLEN(_file));
    window_init(&_window_editor, "Editor", NULL, 0, NULL);
    window_open(&_window_editor);
    gfx_rect(30, 20, 1, GFX_HEIGHT - 20, THEME_LIGHT);
    _draw_line_numbers(37);
    _draw_code();
}
References _code, _draw_code(), _draw_line_numbers(), _file, _window_editor, ARRLEN, event_key(), GFX_HEIGHT, gfx_rect(), INITIAL_CODE_CAPACITY, keyboard_register_event(), keyword_init(), THEME_LIGHT, vector_init(), vector_set(), window_init(), and window_open().
Variable Documentation
_code
Vector _code [static]
Vector containing source code
Definition at line 57 of file main.c.
Referenced by _draw_code(), and setup().
_file
const char _file[] [static]
TODO: File for testing syntax highligher, remove when file loading done
Definition at line 21 of file main.c.
Referenced by setup().
_window_editor
Window _window_editor [static]
Editor source code window
Definition at line 60 of file main.c.
Referenced by setup().