platform/avr/platform.c File Reference
Platform specific functions for AVR.
#include <platform.h>
#include <serial.h>
#include <lcd.h>
#include <xmem.h>
#include <random.h>
#include <timer.h>
#include <avr/pgmspace.h>
Functions
u32 env_memory_size (void)
Get the size of the installed memory.
void env_memory_read (u32 addr, void *data, u32 size)
Read data from physical memory.
void env_memory_write (u32 addr, const void *data, u32 size)
Write data to physical memory.
static u8 _abgr_r (u32 color)
static u8 _abgr_g (u32 color)
static u8 _abgr_b (u32 color)
static u8 _gamma_correction (u8 value)
Perform gamma correction on a color channel.
static RGB565 _abgr_to_rgb565 (u32 color)
Convert ABGR8888 to RGB565 and do gamma correction for LCD with low contrast.
void env_gfx_rect (u16 x, u16 y, u16 w, u16 h, u32 color)
Draw rectangle.
void env_gfx_image_rgb565 (u16 x, u16 y, u16 w, u16 h, u32 addr)
Draw an RGB565 image.
void env_gfx_image_grayscale (u16 x, u16 y, u16 w, u16 h, u32 addr, u32 fg, u32 bg)
Draw a colored grayscale image.
void env_gfx_image_1bit (u16 x, u16 y, u16 w, u16 h, u32 addr, u32 fg, u32 bg)
Draw a colored 1-bit image.
void env_serial_write (const void *data, u32 len)
Send data over the serial interface.
u32 env_random_get (void)
Generate a pseudo-random number.
u32 env_millis (void)
Get the number of milliseconds since boot.
Variables
static const u8 PROGMEM _gamma []
Detailed Description
Platform specific functions for AVR.
Author
Anton Tchekov
Version
0.1
Date
22.05.2023
Definition in file platform.c.
Function Documentation
_abgr_b()
static u8 _abgr_b (u32 color) [inline], [static]
Extract blue channel from ABGR color
Definition at line 43 of file platform.c.
{ return (color >> 8) & 0xFF; }
Referenced by _abgr_to_argb(), _abgr_to_rgb565(), _color_merge(), and _color_merge().
_abgr_g()
static u8 _abgr_g (u32 color) [inline], [static]
Extract green channel from ABGR color
Definition at line 40 of file platform.c.
{ return (color >> 16) & 0xFF; }
Referenced by _abgr_to_argb(), _abgr_to_rgb565(), _color_merge(), and _color_merge().
_abgr_r()
static u8 _abgr_r (u32 color) [inline], [static]
Extract red channel from ABGR color
Definition at line 37 of file platform.c.
{ return (color >> 24) & 0xFF; }
Referenced by _abgr_to_argb(), _abgr_to_rgb565(), _color_merge(), and _color_merge().
_abgr_to_rgb565()
static RGB565 _abgr_to_rgb565 (u32 color) [static]
Convert ABGR8888 to RGB565 and do gamma correction for LCD with low contrast.
Parameters
color The color to be converted
Returns
RGB565 color
Definition at line 84 of file platform.c.
{
    return lcd_color(
        _gamma_correction(_abgr_r(color)),
        _gamma_correction(_abgr_g(color)),
        _gamma_correction(_abgr_b(color)));
}
References _abgr_b(), _abgr_g(), _abgr_r(), _gamma_correction(), and lcd_color().
Referenced by env_gfx_image_1bit(), and env_gfx_rect().
_gamma_correction()
static u8 _gamma_correction (u8 value) [inline], [static]
Perform gamma correction on a color channel.
Parameters
value Input color channel value
Returns
Gamma corrected output value
Definition at line 72 of file platform.c.
{
    return pgm_read_byte(_gamma + value);
}
References _gamma.
Referenced by _abgr_to_rgb565().
env_gfx_image_1bit()
void env_gfx_image_1bit (u16 x, u16 y, u16 w, u16 h, u32 addr, u32 fg, u32 bg)
Draw a colored 1-bit image.
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h Height
addr Image memory address
fg ABGR foreground color
bg ABGR background color
Definition at line 108 of file platform.c.
{
    lcd_image_1bit(x, y, w, h, addr,
        _abgr_to_rgb565(fg),
        _abgr_to_rgb565(bg));
}
References _abgr_to_rgb565(), and lcd_image_1bit().
Referenced by syscall_gfx_image_1bit().
env_gfx_image_grayscale()
void env_gfx_image_grayscale (u16 x, u16 y, u16 w, u16 h, u32 addr, u32 fg, u32 bg)
Draw a colored grayscale image.
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h Height
addr Image memory address
fg ABGR foreground color
bg ABGR background color
Definition at line 102 of file platform.c.
{
    lcd_image_grayscale(x, y, w, h, addr, fg, bg);
}
References lcd_image_grayscale().
Referenced by syscall_gfx_image_grayscale().
env_gfx_image_rgb565()
void env_gfx_image_rgb565 (u16 x, u16 y, u16 w, u16 h, u32 addr)
Draw an RGB565 image.
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h Height
addr Image memory address
Definition at line 97 of file platform.c.
{
    lcd_image_rgb565(x, y, w, h, addr);
}
References lcd_image_rgb565().
Referenced by syscall_gfx_image_rgb565().
env_gfx_rect()
void env_gfx_rect (u16 x, u16 y, u16 w, u16 h, u32 color)
Draw rectangle.
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h Height
color Fill color
Definition at line 92 of file platform.c.
{
    lcd_rect(x, y, w, h, _abgr_to_rgb565(color));
}
References _abgr_to_rgb565(), and lcd_rect().
Referenced by syscall_gfx_rect().
env_memory_read()
void env_memory_read (u32 addr, void * data, u32 size)
Read data from physical memory.
Parameters
addr Start address
data Data buffer
size Size in bytes
Definition at line 24 of file platform.c.
{
    xmem_read(addr, data, size);
}
References xmem_read().
Referenced by memory_lb(), memory_lbu(), memory_lh(), memory_lhu(), memory_lw(), syscall_gfx_image_1bit(), syscall_gfx_image_grayscale(), and syscall_serial_write().
env_memory_size()
u32 env_memory_size (void)
Get the size of the installed memory.
Returns
The size of the memory in bytes
Definition at line 19 of file platform.c.
{
    return xmem_size();
}
References xmem_size().
Referenced by kernel_init().
env_memory_write()
void env_memory_write (u32 addr, const void * data, u32 size)
Write data to physical memory.
Parameters
addr Start address
data Data buffer
size Size in bytes
Definition at line 29 of file platform.c.
{
    xmem_write(addr, data, size);
}
References xmem_write().
Referenced by memory_sb(), memory_sh(), and memory_sw().
env_millis()
u32 env_millis (void)
Get the number of milliseconds since boot.
Returns
The number of milliseconds
Definition at line 137 of file platform.c.
{
    return millis();
}
References millis().
Referenced by syscall_millis().
env_random_get()
u32 env_random_get (void)
Generate a pseudo-random number.
Returns
The number
Definition at line 130 of file platform.c.
{
    return random_get();
}
References random_get().
Referenced by syscall_rand().
env_serial_write()
void env_serial_write (const void * data, u32 len)
Send data over the serial interface.
Parameters
data The data to send
len The number of bytes
Definition at line 118 of file platform.c.
{
    u32 i;
    const char *data8 = data;
    for(i = 0; i < len; ++i)
    {
        serial_tx(data8[i]);
    }
}
References serial_tx().
Referenced by syscall_serial_write().
Variable Documentation
_gamma
const u8 PROGMEM _gamma[] [static]
Initial value:
=
{
      0, 21, 28, 34, 39, 43, 46, 50, 53, 56, 59, 61, 64, 66, 68, 70,
     72, 74, 76, 78, 80, 82, 84, 85, 87, 89, 90, 92, 93, 95, 96, 98,
     99, 101, 102, 103, 105, 106, 107, 109, 110, 111, 112, 114, 115, 116, 117, 118,
    119, 120, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135,
    136, 137, 138, 139, 140, 141, 142, 143, 144, 144, 145, 146, 147, 148, 149, 150,
    151, 151, 152, 153, 154, 155, 156, 156, 157, 158, 159, 160, 160, 161, 162, 163,
    164, 164, 165, 166, 167, 167, 168, 169, 170, 170, 171, 172, 173, 173, 174, 175,
    175, 176, 177, 178, 178, 179, 180, 180, 181, 182, 182, 183, 184, 184, 185, 186,
    186, 187, 188, 188, 189, 190, 190, 191, 192, 192, 193, 194, 194, 195, 195, 196,
    197, 197, 198, 199, 199, 200, 200, 201, 202, 202, 203, 203, 204, 205, 205, 206,
    206, 207, 207, 208, 209, 209, 210, 210, 211, 212, 212, 213, 213, 214, 214, 215,
    215, 216, 217, 217, 218, 218, 219, 219, 220, 220, 221, 221, 222, 223, 223, 224,
    224, 225, 225, 226, 226, 227, 227, 228, 228, 229, 229, 230, 230, 231, 231, 232,
    232, 233, 233, 234, 234, 235, 235, 236, 236, 237, 237, 238, 238, 239, 239, 240,
    240, 241, 241, 242, 242, 243, 243, 244, 244, 245, 245, 246, 246, 247, 247, 248,
    248, 249, 249, 249, 250, 250, 251, 251, 252, 252, 253, 253, 254, 254, 255, 255
}
Reverse gamma correction table
Definition at line 46 of file platform.c.
Referenced by _gamma_correction().