stdlib/clipboard/clipboard.h File Reference
Implement a OS-wide Clipboard.
#include <types.h>
Enumerations
enum ClipboardType { CLIPBOARD_TYPE_TEXT
 }
Functions
void clipboard_save_text (const char *text)
Save Text to clipboard.
void clipboard_save_text_len (const char *text, i32 len)
Save Text to the clipboard when the length is known.
const void * clipboard_get (void)
Get data from clipboard.
i32 clipboard_len (void)
Get the length of the data in the clipboard.
ClipboardType clipboard_type (void)
Get the stored Datatype from the clipboard.
Detailed Description
Implement a OS-wide Clipboard.
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
14.05.2023
Definition in file clipboard.h.
Enumeration Type Documentation
ClipboardType
enum ClipboardType
Clipboard content type
Enumerator
CLIPBOARD_TYPE_TEXT Textual data
Definition at line 15 of file clipboard.h.
{
    CLIPBOARD_TYPE_TEXT
} ClipboardType;
Function Documentation
clipboard_get()
const void * clipboard_get (void)
Get data from clipboard.
Returns
Pointer to raw clipboard data
Definition at line 54 of file clipboard.c.
{
    return _get_memory(-1);
}
References _get_memory().
clipboard_len()
i32 clipboard_len (void)
Get the length of the data in the clipboard.
Returns
Clipboard size in bytes
Definition at line 59 of file clipboard.c.
{
    return _clipboard_len;
}
References _clipboard_len.
clipboard_save_text()
void clipboard_save_text (const char * text)
Save Text to clipboard.
Parameters
text The text to copy
Definition at line 40 of file clipboard.c.
{
    _clipboard_type = CLIPBOARD_TYPE_TEXT;
    char *clipboard = _get_memory(strlen(text));
    strcpy(clipboard, text);
}
References _clipboard_type, _get_memory(), CLIPBOARD_TYPE_TEXT, strcpy(), and strlen().
clipboard_save_text_len()
void clipboard_save_text_len (const char * text, i32 len)
Save Text to the clipboard when the length is known.
Parameters
text The text to copy
len The length of the text
Definition at line 47 of file clipboard.c.
{
    _clipboard_type = CLIPBOARD_TYPE_TEXT;
    char *clipboard = _get_memory(len);
    strncpy(clipboard, text, len);
}
References _clipboard_type, _get_memory(), CLIPBOARD_TYPE_TEXT, and strncpy().
clipboard_type()
ClipboardType clipboard_type (void)
Get the stored Datatype from the clipboard.
Definition at line 64 of file clipboard.c.
{
    return _clipboard_type;
}
References _clipboard_type.