stdlib/clipboard/clipboard.c File Reference
#include <clipboard.h>
#include <string.h>
Functions
static char * _get_memory (i32 space)
Get memory to place clipboard contents into.
void clipboard_save_text (const char *text)
Save Text to clipboard.
void clipboard_save_text_len (const char *text, i32 len)
Save Text to the clipboard when the length is known.
const void * clipboard_get (void)
Get data from clipboard.
i32 clipboard_len (void)
Get the length of the data in the clipboard.
ClipboardType clipboard_type (void)
Get the stored Datatype from the clipboard.
Variables
static i32 _clipboard_len
static ClipboardType _clipboard_type
Detailed Description
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
14.05.2023
Definition in file clipboard.c.
Function Documentation
_get_memory()
static char * _get_memory (i32 space) [static]
Get memory to place clipboard contents into.
Parameters
space Number of bytes needed, -1 to get previous clipboard content
Returns
Pointer to buffer
TODO: Clipboard should be shared across processes. The following is a hack and just temporary, not to mention a potential overflow risk.
Definition at line 23 of file clipboard.c.
{
    static char arr[1024];
    if(space >= 0)
    {
        _clipboard_len = space;
    }
    return arr;
}
References _clipboard_len.
Referenced by clipboard_get(), clipboard_save_text(), and clipboard_save_text_len().
clipboard_get()
const void * clipboard_get (void)
Get data from clipboard.
Returns
Pointer to raw clipboard data
Definition at line 54 of file clipboard.c.
{
    return _get_memory(-1);
}
References _get_memory().
clipboard_len()
i32 clipboard_len (void)
Get the length of the data in the clipboard.
Returns
Clipboard size in bytes
Definition at line 59 of file clipboard.c.
{
    return _clipboard_len;
}
References _clipboard_len.
clipboard_save_text()
void clipboard_save_text (const char * text)
Save Text to clipboard.
Parameters
text The text to copy
Definition at line 40 of file clipboard.c.
{
    _clipboard_type = CLIPBOARD_TYPE_TEXT;
    char *clipboard = _get_memory(strlen(text));
    strcpy(clipboard, text);
}
References _clipboard_type, _get_memory(), CLIPBOARD_TYPE_TEXT, strcpy(), and strlen().
clipboard_save_text_len()
void clipboard_save_text_len (const char * text, i32 len)
Save Text to the clipboard when the length is known.
Parameters
text The text to copy
len The length of the text
Definition at line 47 of file clipboard.c.
{
    _clipboard_type = CLIPBOARD_TYPE_TEXT;
    char *clipboard = _get_memory(len);
    strncpy(clipboard, text, len);
}
References _clipboard_type, _get_memory(), CLIPBOARD_TYPE_TEXT, and strncpy().
clipboard_type()
ClipboardType clipboard_type (void)
Get the stored Datatype from the clipboard.
Definition at line 64 of file clipboard.c.
{
    return _clipboard_type;
}
References _clipboard_type.
Variable Documentation
_clipboard_len
i32 _clipboard_len [static]
Length of the clipboard in bytes
Definition at line 12 of file clipboard.c.
Referenced by _get_memory(), and clipboard_len().
_clipboard_type
ClipboardType _clipboard_type [static]
Type of the current data in the clipboad
Definition at line 15 of file clipboard.c.
Referenced by clipboard_save_text(), clipboard_save_text_len(), and clipboard_type().