stdlib/ctype/ctype.h File Reference
Standard C functions to check for and convert between ASCII characters.
#include <types.h>
Functions
bool isalnum (i32 c)
This function checks whether the passed character is alphanumeric.
bool isalpha (i32 c)
This function checks whether the passed character is alphabetic.
bool iscntrl (i32 c)
This function checks whether the passed character is a control character.
bool isdigit (i32 c)
This function checks whether the passed character is decimal digit.
bool isgraph (i32 c)
This function checks whether the passed character has a graphical representation.
bool islower (i32 c)
This function checks whether the passed character is lowercase letter.
bool isprint (i32 c)
This function checks whether the passed character is printable.
bool ispunct (i32 c)
This function checks whether the passed character is a punctuation character.
bool isspace (i32 c)
This function checks whether the passed character is white-space.
bool isupper (i32 c)
This function checks whether the passed character is an uppercase letter.
bool isxdigit (i32 c)
This function checks whether the passed character is a hexadecimal digit.
i32 tolower (i32 c)
This function converts uppercase letters to lowercase.
i32 toupper (i32 c)
This function converts lowercase letters to uppercase.
Detailed Description
Standard C functions to check for and convert between ASCII characters.
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
23.04.2023
Definition in file ctype.h.
Function Documentation
isalnum()
bool isalnum (i32 c)
This function checks whether the passed character is alphanumeric.
Parameters
c The character
Returns
Boolean
Definition at line 11 of file ctype.c.
{
    return isalpha(c) || isdigit(c);
}
References isalpha(), and isdigit().
Referenced by _draw_code().
isalpha()
bool isalpha (i32 c)
This function checks whether the passed character is alphabetic.
Parameters
c The character
Returns
Boolean
Definition at line 16 of file ctype.c.
{
    return islower(c) || isupper(c);
}
References islower(), and isupper().
Referenced by isalnum().
iscntrl()
bool iscntrl (i32 c)
This function checks whether the passed character is a control character.
Parameters
c The character
Returns
Boolean
Definition at line 21 of file ctype.c.
{
    return !isprint(c);
}
References isprint().
isdigit()
bool isdigit (i32 c)
This function checks whether the passed character is decimal digit.
Parameters
c The character
Returns
Boolean
Definition at line 26 of file ctype.c.
{
    return c >= '0' && c <= '9';
}
Referenced by _draw_code(), isalnum(), and isxdigit().
isgraph()
bool isgraph (i32 c)
This function checks whether the passed character has a graphical representation.
Parameters
c The character
Returns
Boolean
Definition at line 31 of file ctype.c.
{
    return c >= 33 && c <= 126;
}
islower()
bool islower (i32 c)
This function checks whether the passed character is lowercase letter.
Parameters
c The character
Returns
Boolean
Definition at line 36 of file ctype.c.
{
    return c >= 'a' && c <= 'z';
}
Referenced by isalpha(), and toupper().
isprint()
bool isprint (i32 c)
This function checks whether the passed character is printable.
Parameters
c The character
Returns
Boolean
Definition at line 41 of file ctype.c.
{
    return c >= 32 && c <= 126;
}
Referenced by input_event_key(), iscntrl(), and memory_dump().
ispunct()
bool ispunct (i32 c)
This function checks whether the passed character is a punctuation character.
Parameters
c The character
Returns
Boolean
Definition at line 46 of file ctype.c.
{
    return strchr("!\"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~", c) != NULL;
}
References strchr().
isspace()
bool isspace (i32 c)
This function checks whether the passed character is white-space.
Parameters
c The character
Returns
Boolean
Definition at line 51 of file ctype.c.
{
    return strchr(" \n\t\v\f\r", c) != NULL;
}
References strchr().
isupper()
bool isupper (i32 c)
This function checks whether the passed character is an uppercase letter.
Parameters
c The character
Returns
Boolean
Definition at line 56 of file ctype.c.
{
    return c >= 'A' && c <= 'Z';
}
Referenced by isalpha(), and tolower().
isxdigit()
bool isxdigit (i32 c)
This function checks whether the passed character is a hexadecimal digit.
Parameters
c The character
Returns
Boolean
Definition at line 61 of file ctype.c.
{
    return isdigit(c) ||
           (c >= 'A' && c <= 'F') ||
           (c >= 'a' && c <= 'f');
}
References isdigit().
tolower()
i32 tolower (i32 c)
This function converts uppercase letters to lowercase.
Parameters
c The character
Returns
The character converted to lowercase. If the input was not uppercase, returns the same character
Definition at line 68 of file ctype.c.
{
    return isupper(c) ? c - 'A' + 'a' : c;
}
References isupper().
toupper()
i32 toupper (i32 c)
This function converts lowercase letters to uppercase.
Parameters
c The character
Returns
The character converted to uppercase. If the input was not lowercase, returns the same character
Definition at line 73 of file ctype.c.
{
    return islower(c) ? c - 'a' + 'A' : c;
}
References islower().
Referenced by key_to_codepoint().