emulator/emulator.c File Reference
#include <types.h>
#include <platform.h>
#include <emulator.h>
#include <gfx-types.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <util.h>
Macros
#define EMU_LOG(...)
#define OPCODE_LOAD 0x00
#define OPCODE_IMM 0x04
#define OPCODE_AUIPC 0x05 /* Add Upper Immediate to Program Counter */
#define OPCODE_STORE 0x08
#define OPCODE_REG 0x0C
#define OPCODE_LUI 0x0D /* Load Upper Immediate */
#define OPCODE_BRANCH 0x18
#define OPCODE_JALR 0x19 /* Jump and Link Register */
#define OPCODE_JAL 0x1B /* Jump and Link */
#define OPCODE_ECALL 0x1C /* Environment Call */
Functions
static u32 sext (u8 bits, u32 value)
Sign extend twos-complement value to 32-bit.
void kernel_init (void)
Initialize emulator kernel and load first process (NOT systemd)
void os_update (void)
Call this function periodically in main loop.
void keyboard_event (Key key, i32 chr, KeyState down)
Inform the emulator about a key press.
static u8 _gfx_check_bounds (u16 x, u16 y, u16 w, u16 h)
Checks if a render window is out ot bounds.
static u8 _memory_check_bounds (u32 addr, u32 size)
Check memory location permissions.
static u8 memory_sb (u32 addr, u32 value)
Store byte.
static u8 memory_sh (u32 addr, u32 value)
Store 16-bit half-word.
static u8 memory_sw (u32 addr, u32 value)
Store 32-bit word.
static u8 memory_lb (u32 addr, u32 *out)
Load a signed byte and perform sign-extension.
static u8 memory_lh (u32 addr, u32 *out)
Load a 16-bit signed half-word and perform sign extension.
static u8 memory_lw (u32 addr, u32 *out)
Load a 32-bit word.
static u8 memory_lbu (u32 addr, u32 *out)
Load an unsigned byte.
static u8 memory_lhu (u32 addr, u32 *out)
Load an unsigned 16-bit half-word.
static u8 syscall_exit (u32 *args)
Exit program.
static u8 syscall_finish (u32 *args)
Yield function to pass control to the scheduler.
static u8 syscall_event_register (u32 *args)
Register an event handler.
static u8 syscall_millis (u32 *args)
System call to get the number of milliseconds since startup.
static u8 syscall_rand (u32 *args)
System call to get a random number.
static u8 syscall_serial_write (u32 *args)
System call to send data over the serial interface.
static u8 syscall_gfx_rect (u32 *args)
System call to draw a rectangle.
static u8 syscall_gfx_image_rgba (u32 *args)
System call to draw an RGBA image.
static u8 syscall_gfx_image_rgb (u32 *args)
System call to draw an RGB image.
static u8 syscall_gfx_image_rgb565 (u32 *args)
System call to draw an RGB565 image.
static u8 syscall_gfx_image_grayscale (u32 *args)
System call to draw a grayscale image.
static u8 syscall_gfx_image_1bit (u32 *args)
System call to draw a 1-bit-per-pixel image.
static u8 syscall (u32 id, u32 *args)
Perform a system call.
static u8 emulator_next (Emulator *emu)
Execute the next instruction of the emulator.
u8 emulator_call (Emulator *emu, u32 addr, u32 *args, u8 num, u32 sp)
Call an emulated RISC-V function.
Variables
static bool _finished
static Emulator _cur
static Emulator * _emu = &_cur
static u32 _memory_size
static u8(* syscalls [])(u32 *)
Detailed Description
Author
Anton Tchekov
Version
0.1
Date
24.05.2023
Definition in file emulator.c.
Macro Definition Documentation
EMU_LOG
#define EMU_LOG(...)
Empty logger
Definition at line 59 of file emulator.c.
OPCODE_AUIPC
#define OPCODE_AUIPC 0x05 /* Add Upper Immediate to Program Counter */
Opcode for AUIPC instruction
Definition at line 72 of file emulator.c.
OPCODE_BRANCH
#define OPCODE_BRANCH 0x18
Opcode for branch instructions
Definition at line 84 of file emulator.c.
OPCODE_ECALL
#define OPCODE_ECALL 0x1C /* Environment Call */
Opcode for ECALL instructions
Definition at line 93 of file emulator.c.
OPCODE_IMM
#define OPCODE_IMM 0x04
Opcodes for instructions with immediate values
Definition at line 69 of file emulator.c.
OPCODE_JAL
#define OPCODE_JAL 0x1B /* Jump and Link */
Opcode for JAL instructions
Definition at line 90 of file emulator.c.
OPCODE_JALR
#define OPCODE_JALR 0x19 /* Jump and Link Register */
Opcode for JALR instructions
Definition at line 87 of file emulator.c.
OPCODE_LOAD
#define OPCODE_LOAD 0x00
Opcode for Load instructions
Definition at line 66 of file emulator.c.
OPCODE_LUI
#define OPCODE_LUI 0x0D /* Load Upper Immediate */
Opcode for LUI instruction
Definition at line 81 of file emulator.c.
OPCODE_REG
#define OPCODE_REG 0x0C
Opcodes for instructions on registers
Definition at line 78 of file emulator.c.
OPCODE_STORE
#define OPCODE_STORE 0x08
Opcode for store instructions
Definition at line 75 of file emulator.c.
Function Documentation
_gfx_check_bounds()
static u8 _gfx_check_bounds (u16 x, u16 y, u16 w, u16 h) [static]
Checks if a render window is out ot bounds.
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h Height
Returns
Non-zero if invalid
Definition at line 157 of file emulator.c.
{
    return (x >= GFX_WIDTH) ||
        (y >= GFX_HEIGHT) ||
        (w > GFX_WIDTH) ||
        (h > GFX_HEIGHT) ||
        (x + w > GFX_WIDTH) ||
        (y + h > GFX_HEIGHT);
}
References GFX_HEIGHT, and GFX_WIDTH.
Referenced by syscall_gfx_image_1bit(), syscall_gfx_image_grayscale(), syscall_gfx_image_rgb(), syscall_gfx_image_rgb565(), syscall_gfx_image_rgba(), and syscall_gfx_rect().
_memory_check_bounds()
static u8 _memory_check_bounds (u32 addr, u32 size) [static]
Check memory location permissions.
Parameters
addr Start address
size Size of the block to be accessed
Returns
Non-zero if invalid
Definition at line 174 of file emulator.c.
{
    return (addr >= _emu->SegmentEnd) ||
        (size >= _emu->SegmentSize) ||
        (addr + size >= _emu->SegmentEnd);
}
References _emu, Emulator::SegmentEnd, and Emulator::SegmentSize.
Referenced by memory_lb(), memory_lbu(), memory_lh(), memory_lhu(), memory_lw(), memory_sb(), memory_sh(), memory_sw(), syscall_gfx_image_1bit(), syscall_gfx_image_grayscale(), syscall_gfx_image_rgb(), syscall_gfx_image_rgb565(), syscall_gfx_image_rgba(), and syscall_serial_write().
emulator_call()
u8 emulator_call (Emulator * emu, u32 addr, u32 * args, u8 num, u32 sp)
Call an emulated RISC-V function.
Parameters
emu Pointer to emulator struct
addr Function start address
args Function arguments
num Number of arguments
sp Stack pointer start
Definition at line 1231 of file emulator.c.
{
    u32 i;
    /* Initialize Stack Pointer at end of memory */
    emu->Registers[2] = sp - 4;
    emu->PC = addr;
    memcpy(&emu->Registers[10], args, num * sizeof(*emu->Registers));
    i = 0;
    _finished = false;
    while(!_finished)
    {
        ++i;
        if(emulator_next(emu))
        {
            return 1;
        }
    }
    EMU_LOG(PSTR("%"PRIu32" Cycles"), i);
    return 0;
}
References _finished, EMU_LOG, emulator_next(), memcpy(), Emulator::PC, and Emulator::Registers.
Referenced by kernel_init(), keyboard_event(), and os_update().
emulator_next()
static u8 emulator_next (Emulator * emu) [static]
Execute the next instruction of the emulator.
Parameters
emu The emulator
Returns
Non-zero on failure
Definition at line 724 of file emulator.c.
{
    u32 instr, opcode;
    if(memory_lw(emu->PC, &instr))
    {
        return 1;
    }
    /* r0 = Zero Register */
    emu->Registers[0] = 0;
    /* bits 7 .. 0 */
    opcode = instr & 0x7F;
    if((opcode & 0x03) != 0x03)
    {
        EMU_LOG(PSTR("INVALID"));
        return 1;
    }
    opcode >>= 2;
    switch(opcode)
    {
        case OPCODE_ECALL:
            if(syscall(emu->Registers[17], &emu->Registers[10]))
            {
                EMU_LOG(PSTR("SYSCALL ERROR"));
                return 1;
            }
            break;
        case OPCODE_LOAD:
        {
            i32 offset;
            u32 imm;
            u8 rd, rs1, funct3;
            rd = (instr >> 7) & 0x1F;
            funct3 = (instr >> 12) & 0x07;
            rs1 = (instr >> 15) & 0x1F;
            imm = (instr >> 20);
            offset = sext(12, imm);
            switch(funct3)
            {
                case 0:
                    /* LB */
                    EMU_LOG(PSTR("lb r%"PRIu8", r%"PRIu8"%+"PRIi32), rd, rs1, offset);
                    if(memory_lb(emu->Registers[rs1] + offset, &emu->Registers[rd]))
                    {
                        return 1;
                    }
                    break;
                case 1:
                    /* LH */
                    EMU_LOG(PSTR("lh r%"PRIu8", r%"PRIu8"%+"PRIi32), rd, rs1, offset);
                    if(memory_lh(emu->Registers[rs1] + offset, &emu->Registers[rd]))
                    {
                        return 1;
                    }
                    break;
                case 2:
                    /* LW */
                    EMU_LOG(PSTR("lw r%"PRIu8", r%"PRIu8"%+"PRIi32), rd, rs1, offset);
                    if(memory_lw(emu->Registers[rs1] + offset, &emu->Registers[rd]))
                    {
                        return 1;
                    }
                    break;
                case 4:
                    /* LBU */
                    EMU_LOG(PSTR("lbu r%"PRIu8", r%"PRIu8"%+"PRIi32), rd, rs1, offset);
                    if(memory_lbu(emu->Registers[rs1] + offset, &emu->Registers[rd]))
                    {
                        return 1;
                    }
                    break;
                case 5:
                    /* LHU */
                    EMU_LOG(PSTR("lhu r%"PRIu8", r%"PRIu8"%+"PRIi32), rd, rs1, offset);
                    if(memory_lhu(emu->Registers[rs1] + offset, &emu->Registers[rd]))
                    {
                        return 1;
                    }
                    break;
                default:
                    EMU_LOG(PSTR("INVALID"));
                    return 1;
            }
            break;
        }
        case OPCODE_IMM:
        {
            u8 rd, rs1, funct3;
            u32 imm;
            rd = (instr >> 7) & 0x1F;
            funct3 = (instr >> 12) & 0x07;
            rs1 = (instr >> 15) & 0x1F;
            imm = (instr >> 20);
            switch(funct3)
            {
                case 0:
                    /* ADDI */
                    imm = sext(12, imm);
                    EMU_LOG(PSTR("addi r%"PRIu8", r%"PRIu8", %"PRIi32), rd, rs1, imm);
                    emu->Registers[rd] = emu->Registers[rs1] + imm;
                    break;
                case 1:
                    /* SLLI */
                    imm &= 0x1F;
                    EMU_LOG(PSTR("slli r%"PRIu8", r%"PRIu8", %"PRIi32), rd, rs1, imm);
                    emu->Registers[rd] = emu->Registers[rs1] << imm;
                    break;
                case 2:
                    /* SLTI */
                    imm = sext(12, imm);
                    EMU_LOG(PSTR("slti r%"PRIu8", r%"PRIu8", %"PRIi32), rd, rs1, imm);
                    emu->Registers[rd] = (i32)emu->Registers[rs1] < (i32)imm;
                    break;
                case 3:
                    /* SLTIU */
                    EMU_LOG(PSTR("sltiu r%"PRIu8", r%"PRIu8", %"PRIi32), rd, rs1, imm);
                    emu->Registers[rd] = emu->Registers[rs1] < imm;
                    break;
                case 4:
                    /* XORI */
                    imm = sext(12, imm);
                    EMU_LOG(PSTR("xori r%"PRIu8", r%"PRIu8", 0x%08"PRIx32), rd, rs1, imm);
                    emu->Registers[rd] = emu->Registers[rs1] ^ imm;
                    break;
                case 5:
                    if(imm >> 5)
                    {
                        /* SRAI */
                        imm &= 0x1F;
                        EMU_LOG(PSTR("srai r%"PRIu8", r%"PRIu8", %"PRIi32), rd, rs1, imm);
                        emu->Registers[rd] = (i32)emu->Registers[rs1] >> imm;
                    }
                    else
                    {
                        /* SRLI */
                        imm &= 0x1F;
                        EMU_LOG(PSTR("srli r%"PRIu8", r%"PRIu8", %"PRIi32), rd, rs1, imm);
                        emu->Registers[rd] = emu->Registers[rs1] >> imm;
                    }
                    break;
                case 6:
                    /* ORI */
                    imm = sext(12, imm);
                    EMU_LOG(PSTR("ori r%"PRIu8", r%"PRIu8", 0x%08"PRIx32), rd, rs1, imm);
                    emu->Registers[rd] = emu->Registers[rs1] | imm;
                    break;
                case 7:
                    /* ANDI */
                    imm = sext(12, imm);
                    EMU_LOG(PSTR("andi r%"PRIu8", r%"PRIu8", 0x%08"PRIx32), rd, rs1, imm);
                    emu->Registers[rd] = emu->Registers[rs1] & imm;
                    break;
            }
            break;
        }
        case OPCODE_AUIPC:
        {
            u8 rd;
            u32 imm;
            rd = (instr >> 7) & 0x1F;
            imm = (instr >> 12);
            EMU_LOG(PSTR("auipc r%"PRIu8", 0x%08"PRIx32), rd, imm);
            emu->Registers[rd] = emu->PC + (imm << 12);
            break;
        }
        case OPCODE_STORE:
        {
            i32 offset;
            u32 imm;
            u8 rs1, rs2, funct3;
            funct3 = (instr >> 12) & 0x07;
            rs1 = (instr >> 15) & 0x1F;
            rs2 = (instr >> 20) & 0x1F;
            imm = ((instr & 0xF80) >> 7) | ((instr & 0xFE000000) >> 20);
            offset = sext(12, imm);
            switch(funct3)
            {
                case 0:
                    /* SB */
                    EMU_LOG(PSTR("sb r%"PRIu8"%+"PRIi32", r%"PRIu8), rs1, offset, rs2);
                    if(memory_sb(emu->Registers[rs1] + offset, emu->Registers[rs2]))
                    {
                        return 1;
                    }
                    break;
                case 1:
                    /* SH */
                    EMU_LOG(PSTR("sh r%"PRIu8"%+"PRIi32", r%"PRIu8), rs1, offset, rs2);
                    if(memory_sh(emu->Registers[rs1] + offset, emu->Registers[rs2]))
                    {
                        return 1;
                    }
                    break;
                case 2:
                    /* SW */
                    EMU_LOG(PSTR("sw r%"PRIu8"%+"PRIi32", r%"PRIu8), rs1, offset, rs2);
                    if(memory_sw(emu->Registers[rs1] + offset, emu->Registers[rs2]))
                    {
                        return 1;
                    }
                    break;
                default:
                    EMU_LOG(PSTR("INVALID"));
                    return 1;
            }
            break;
        }
        case OPCODE_REG:
        {
            u8 rd, rs1, rs2, funct3, funct7;
            rd = (instr >> 7) & 0x1F;
            funct3 = (instr >> 12) & 0x07;
            rs1 = (instr >> 15) & 0x1F;
            rs2 = (instr >> 20) & 0x1F;
            funct7 = (instr >> 25);
            if(funct7 == 1)
            {
                /* Multiplication Extension */
                switch(funct3)
                {
                    case 0:
                        /* MUL */
                        EMU_LOG(PSTR("mul r%"PRIu8", r%"PRIu8", r%"PRIu8), rd, rs1, rs2);
                        emu->Registers[rd] = (i32)emu->Registers[rs1] * (i32)emu->Registers[rs2];
                        break;
                    case 1:
                        /* MULH */
                        EMU_LOG(PSTR("mulh r%"PRIu8", r%"PRIu8", r%"PRIu8), rd, rs1, rs2);
                        emu->Registers[rd] = ((i64)emu->Registers[rs1] * (i64)emu->Registers[rs2]) >> 32;
                        break;
                    case 2:
                        /* MULHSU */
                        EMU_LOG(PSTR("mulhsu r%"PRIu8", r%"PRIu8", r%"PRIu8), rd, rs1, rs2);
                        emu->Registers[rd] = ((i64)emu->Registers[rs1] * (u64)emu->Registers[rs2]) >> 32;
                        break;
                    case 3:
                        /* MULHU */
                        EMU_LOG(PSTR("mulhu r%"PRIu8", r%"PRIu8", r%"PRIu8), rd, rs1, rs2);
                        emu->Registers[rd] = ((u64)emu->Registers[rs1] * (u64)emu->Registers[rs2]) >> 32;
                        break;
                    case 4:
                        /* DIV */
                        EMU_LOG(PSTR("div r%"PRIu8", r%"PRIu8", r%"PRIu8), rd, rs1, rs2);
                        emu->Registers[rd] = (i32)emu->Registers[rs1] / (i32)emu->Registers[rs2];
                        break;
                    case 5:
                        /* DIVU */
                        EMU_LOG(PSTR("divu r%"PRIu8", r%"PRIu8", r%"PRIu8), rd, rs1, rs2);
                        emu->Registers[rd] = emu->Registers[rs1] / emu->Registers[rs2];
                        break;
                    case 6:
                        /* REM */
                        EMU_LOG(PSTR("rem r%"PRIu8", r%"PRIu8", r%"PRIu8), rd, rs1, rs2);
                        emu->Registers[rd] = (i32)emu->Registers[rs1] % (i32)emu->Registers[rs2];
                        break;
                    case 7:
                        /* REMU */
                        EMU_LOG(PSTR("remu r%"PRIu8", r%"PRIu8", r%"PRIu8), rd, rs1, rs2);
                        emu->Registers[rd] = emu->Registers[rs1] % emu->Registers[rs2];
                        break;
                }
            }
            else
            {
                switch(funct3)
                {
                    case 0:
                        if(funct7)
                        {
                            /* SUB */
                            EMU_LOG(PSTR("sub r%"PRIu8", r%"PRIu8", r%"PRIu8), rd, rs1, rs2);
                            emu->Registers[rd] = emu->Registers[rs1] - emu->Registers[rs2];
                        }
                        else
                        {
                            /* ADD */
                            EMU_LOG(PSTR("add r%"PRIu8", r%"PRIu8", r%"PRIu8), rd, rs1, rs2);
                            emu->Registers[rd] = emu->Registers[rs1] + emu->Registers[rs2];
                        }
                        break;
                    case 1:
                        /* SLL */
                        EMU_LOG(PSTR("sll r%"PRIu8", r%"PRIu8", r%"PRIu8), rd, rs1, rs2);
                        emu->Registers[rd] = emu->Registers[rs1] << (emu->Registers[rs2] & 0x1F);
                        break;
                    case 2:
                        /* SLT */
                        EMU_LOG(PSTR("slt r%"PRIu8", r%"PRIu8", r%"PRIu8), rd, rs1, rs2);
                        emu->Registers[rd] = (i32)emu->Registers[rs1] < (i32)emu->Registers[rs2];
                        break;
                    case 3:
                        /* SLTU */
                        EMU_LOG(PSTR("sltu r%"PRIu8", r%"PRIu8", r%"PRIu8), rd, rs1, rs2);
                        emu->Registers[rd] = emu->Registers[rs1] < emu->Registers[rs2];
                        break;
                    case 4:
                        /* XOR */
                        EMU_LOG(PSTR("xor r%"PRIu8", r%"PRIu8", r%"PRIu8), rd, rs1, rs2);
                        emu->Registers[rd] = emu->Registers[rs1] ^ emu->Registers[rs2];
                        break;
                    case 5:
                        if(funct7)
                        {
                            /* SRA */
                            EMU_LOG(PSTR("srl r%"PRIu8", r%"PRIu8", r%"PRIu8), rd, rs1, rs2);
                            emu->Registers[rd] = (i32)emu->Registers[rs1] >> (emu->Registers[rs2] & 0x1F);
                        }
                        else
                        {
                            /* SRL */
                            EMU_LOG(PSTR("sra r%"PRIu8", r%"PRIu8", r%"PRIu8), rd, rs1, rs2);
                            emu->Registers[rd] = emu->Registers[rs1] >> (emu->Registers[rs2] & 0x1F);
                        }
                        break;
                    case 6:
                        /* OR */
                        EMU_LOG(PSTR("or r%"PRIu8", r%"PRIu8", r%"PRIu8), rd, rs1, rs2);
                        emu->Registers[rd] = emu->Registers[rs1] | emu->Registers[rs2];
                        break;
                    case 7:
                        /* AND */
                        EMU_LOG(PSTR("and r%"PRIu8", r%"PRIu8", r%"PRIu8), rd, rs1, rs2);
                        emu->Registers[rd] = emu->Registers[rs1] & emu->Registers[rs2];
                        break;
                }
            }
            break;
        }
        case OPCODE_LUI:
        {
            u8 rd;
            u32 imm;
            rd = (instr >> 7) & 0x1F;
            imm = (instr >> 12);
            EMU_LOG(PSTR("lui r%"PRIu8", 0x%08"PRIx32), rd, imm);
            emu->Registers[rd] = (imm << 12);
            break;
        }
        case OPCODE_BRANCH:
        {
            i32 offset;
            u32 imm;
            u8 rs1, rs2, funct3;
            funct3 = (instr >> 12) & 0x07;
            rs1 = (instr >> 15) & 0x1F;
            rs2 = (instr >> 20) & 0x1F;
            imm = ((instr & 0xF00) >> 7) |
                ((instr & 0x7E000000) >> 20) |
                ((instr & 0x80) << 4) |
                ((instr & 0x80000000) >> 20);
            offset = sext(12, imm);
            switch(funct3)
            {
                case 0:
                    /* BEQ */
                    EMU_LOG(PSTR("beq r%"PRIu8", r%"PRIu8", pc%+"PRIi32), rs1, rs2, offset);
                    if(emu->Registers[rs1] == emu->Registers[rs2])
                    {
                        emu->PC += offset;
                        return 0;
                    }
                    break;
                case 1:
                    /* BNE */
                    EMU_LOG(PSTR("bne r%"PRIu8", r%"PRIu8", pc%+"PRIi32), rs1, rs2, offset);
                    if(emu->Registers[rs1] != emu->Registers[rs2])
                    {
                        emu->PC += offset;
                        return 0;
                    }
                    break;
                case 4:
                    /* BLT */
                    EMU_LOG(PSTR("blt r%"PRIu8", r%"PRIu8", pc%+"PRIi32), rs1, rs2, offset);
                    if((i32)emu->Registers[rs1] < (i32)emu->Registers[rs2])
                    {
                        emu->PC += offset;
                        return 0;
                    }
                    break;
                case 5:
                    /* BGE */
                    EMU_LOG(PSTR("bge r%"PRIu8", r%"PRIu8", pc%+"PRIi32), rs1, rs2, offset);
                    if((i32)emu->Registers[rs1] >= (i32)emu->Registers[rs2])
                    {
                        emu->PC += offset;
                        return 0;
                    }
                    break;
                case 6:
                    /* BLTU */
                    EMU_LOG(PSTR("bltu r%"PRIu8", r%"PRIu8", pc%+"PRIi32), rs1, rs2, offset);
                    if(emu->Registers[rs1] < emu->Registers[rs2])
                    {
                        emu->PC += offset;
                        return 0;
                    }
                    break;
                case 7:
                    /* BGEU */
                    EMU_LOG(PSTR("bgeu r%"PRIu8", r%"PRIu8", pc%+"PRIi32), rs1, rs2, offset);
                    if(emu->Registers[rs1] >= emu->Registers[rs2])
                    {
                        emu->PC += offset;
                        return 0;
                    }
                    break;
                default:
                    EMU_LOG(PSTR("INVALID"));
                    return 1;
            }
            break;
        }
        case OPCODE_JAL:
        {
            i32 offset;
            u32 imm;
            u8 rd;
            rd = (instr >> 7) & 0x1F;
            imm = ((instr & 0x80000000) >> 12) |
                    (instr & 0xFF000) |
                    ((instr & 0x100000) >> 9) |
                    ((instr & 0x7FE00000) >> 20);
            offset = sext(20, imm);
            EMU_LOG(PSTR("jal r%"PRIu8", pc%+"PRIi32), rd, offset);
            emu->Registers[rd] = emu->PC + 4;
            emu->PC += offset;
            return 0;
        }
        case OPCODE_JALR:
        {
            u8 rd, rs1;
            i32 offset;
            u32 imm;
            rd = (instr >> 7) & 0x1F;
            rs1 = (instr >> 15) & 0x1F;
            imm = (instr >> 20) & ~1;
            offset = sext(12, imm);
            EMU_LOG(PSTR("jalr r%"PRIu8", r%"PRIu8"%+"PRIi32),
                rd, rs1, offset);
            emu->Registers[rd] = emu->PC + 4;
            emu->PC = emu->Registers[rs1] + offset;
            return 0;
        }
        default:
            EMU_LOG(PSTR("INVALID"));
            return 1;
    }
    emu->PC += 4;
    return 0;
}
References EMU_LOG, memory_lb(), memory_lbu(), memory_lh(), memory_lhu(), memory_lw(), memory_sb(), memory_sh(), memory_sw(), OPCODE_AUIPC, OPCODE_BRANCH, OPCODE_ECALL, OPCODE_IMM, OPCODE_JAL, OPCODE_JALR, OPCODE_LOAD, OPCODE_LUI, OPCODE_REG, OPCODE_STORE, Emulator::PC, Emulator::Registers, sext(), and syscall().
Referenced by emulator_call().
kernel_init()
void kernel_init (void)
Initialize emulator kernel and load first process (NOT systemd)
Definition at line 120 of file emulator.c.
{
    _memory_size = env_memory_size();
    _emu->SegmentStart = 0;
    _emu->SegmentSize = _memory_size;
    _emu->SegmentEnd = _memory_size;
    emulator_call(_emu, 0, NULL, 0, _memory_size);
}
References _emu, _memory_size, emulator_call(), env_memory_size(), Emulator::SegmentEnd, Emulator::SegmentSize, and Emulator::SegmentStart.
Referenced by main().
keyboard_event()
void keyboard_event (Key key, i32 chr, KeyState state)
Inform the emulator about a key press.
Parameters
key The scancode
chr The unicode codepoint of the scancode or 0
state The state of the key (pressed, repeat, released)
Definition at line 138 of file emulator.c.
{
    u32 addr = _emu->Events[EVENT_KEY];
    if(addr)
    {
        u32 args[] = { key, chr, down };
        emulator_call(_emu, addr, args, ARRLEN(args), _memory_size);
    }
}
References _emu, _memory_size, ARRLEN, emulator_call(), EVENT_KEY, and Emulator::Events.
Referenced by main().
memory_lb()
static u8 memory_lb (u32 addr, u32 * out) [static]
Load a signed byte and perform sign-extension.
Parameters
addr The address from which to load the value
out Output parameter for the loaded value
Returns
Non-zero if out ouf bounds
Definition at line 250 of file emulator.c.
{
    i8 value8;
    addr += _emu->SegmentStart;
    if(_memory_check_bounds(addr, sizeof(value8)))
    {
        return 1;
    }
    env_memory_read(addr, &value8, sizeof(value8));
    *out = (i32)value8;
    return 0;
}
References _emu, _memory_check_bounds(), env_memory_read(), and Emulator::SegmentStart.
Referenced by emulator_next().
memory_lbu()
static u8 memory_lbu (u32 addr, u32 * out) [static]
Load an unsigned byte.
Parameters
addr The address from which to load the value
out Output parameter for the loaded value
Returns
Non-zero if out ouf bounds
Definition at line 313 of file emulator.c.
{
    u8 value8;
    addr += _emu->SegmentStart;
    if(_memory_check_bounds(addr, sizeof(value8)))
    {
        return 1;
    }
    env_memory_read(addr, &value8, sizeof(value8));
    *out = value8;
    return 0;
}
References _emu, _memory_check_bounds(), env_memory_read(), and Emulator::SegmentStart.
Referenced by emulator_next().
memory_lh()
static u8 memory_lh (u32 addr, u32 * out) [static]
Load a 16-bit signed half-word and perform sign extension.
Parameters
addr The address from which to load the value
out Output parameter for the loaded value
Returns
Non-zero if out ouf bounds
Definition at line 271 of file emulator.c.
{
    i16 value16;
    addr += _emu->SegmentStart;
    if(_memory_check_bounds(addr, sizeof(value16)))
    {
        return 1;
    }
    env_memory_read(addr, &value16, sizeof(value16));
    *out = (i32)value16;
    return 0;
}
References _emu, _memory_check_bounds(), env_memory_read(), and Emulator::SegmentStart.
Referenced by emulator_next().
memory_lhu()
static u8 memory_lhu (u32 addr, u32 * out) [static]
Load an unsigned 16-bit half-word.
Parameters
addr The address from which to load the value
out Output parameter for the loaded value
Returns
Non-zero if out ouf bounds
Definition at line 334 of file emulator.c.
{
    u16 value16;
    addr += _emu->SegmentStart;
    if(_memory_check_bounds(addr, sizeof(value16)))
    {
        return 1;
    }
    env_memory_read(addr, &value16, sizeof(value16));
    *out = value16;
    return 0;
}
References _emu, _memory_check_bounds(), env_memory_read(), and Emulator::SegmentStart.
Referenced by emulator_next().
memory_lw()
static u8 memory_lw (u32 addr, u32 * out) [static]
Load a 32-bit word.
Parameters
addr The address from which to load the value
out Output parameter for the loaded value
Returns
Non-zero if out ouf bounds
Definition at line 292 of file emulator.c.
{
    u32 value;
    addr += _emu->SegmentStart;
    if(_memory_check_bounds(addr, sizeof(value)))
    {
        return 1;
    }
    env_memory_read(addr, &value, sizeof(value));
    *out = value;
    return 0;
}
References _emu, _memory_check_bounds(), env_memory_read(), and Emulator::SegmentStart.
Referenced by emulator_next().
memory_sb()
static u8 memory_sb (u32 addr, u32 value) [static]
Store byte.
Parameters
addr The address at which to store the value
value The value to store
Returns
Non-zero if out ouf bounds
Definition at line 190 of file emulator.c.
{
    i8 value8 = (i8)value;
    addr += _emu->SegmentStart;
    if(_memory_check_bounds(addr, sizeof(value8)))
    {
        return 1;
    }
    env_memory_write(addr, &value8, sizeof(value8));
    return 0;
}
References _emu, _memory_check_bounds(), env_memory_write(), and Emulator::SegmentStart.
Referenced by emulator_next().
memory_sh()
static u8 memory_sh (u32 addr, u32 value) [static]
Store 16-bit half-word.
Parameters
addr The address at which to store the value
value The value to store
Returns
Non-zero if out ouf bounds
Definition at line 210 of file emulator.c.
{
    i16 value16 = (i16)value;
    addr += _emu->SegmentStart;
    if(_memory_check_bounds(addr, sizeof(value16)))
    {
        return 1;
    }
    env_memory_write(addr, &value16, sizeof(value16));
    return 0;
}
References _emu, _memory_check_bounds(), env_memory_write(), and Emulator::SegmentStart.
Referenced by emulator_next().
memory_sw()
static u8 memory_sw (u32 addr, u32 value) [static]
Store 32-bit word.
Parameters
addr The address at which to store the value
value The value to store
Returns
Non-zero if out ouf bounds
Definition at line 230 of file emulator.c.
{
    addr += _emu->SegmentStart;
    if(_memory_check_bounds(addr, sizeof(value)))
    {
        return 1;
    }
    env_memory_write(addr, &value, sizeof(value));
    return 0;
}
References _emu, _memory_check_bounds(), env_memory_write(), and Emulator::SegmentStart.
Referenced by emulator_next().
os_update()
void os_update (void)
Call this function periodically in main loop.
Definition at line 129 of file emulator.c.
{
    u32 addr = _emu->Events[EVENT_LOOP];
    if(addr)
    {
        emulator_call(_emu, addr, NULL, 0, _memory_size);
    }
}
References _emu, _memory_size, emulator_call(), EVENT_LOOP, and Emulator::Events.
Referenced by main().
sext()
static u32 sext (u8 bits, u32 value) [inline], [static]
Sign extend twos-complement value to 32-bit.
Parameters
bits Number of bits
value Value to sign extent
Returns
Result
Definition at line 102 of file emulator.c.
{
    u32 m = ((u32)1) << (bits - 1);
    return (value ^ m) - m;
}
Referenced by emulator_next().
syscall()
static u8 syscall (u32 id, u32 * args) [static]
Perform a system call.
Parameters
id System call ID
args System call arguments, return value is placed in args[0]
Returns
Non-zero on failure
Definition at line 706 of file emulator.c.
{
    if(id >= ARRLEN(syscalls))
    {
        return 1;
    }
    return syscalls[id](args);
}
References ARRLEN, and syscalls.
Referenced by emulator_next().
syscall_event_register()
static u8 syscall_event_register (u32 * args) [static]
Register an event handler.
Parameters
args args[0]: Event Type, args[1]: Event Handler Address
Returns
Non-zero on error
Definition at line 384 of file emulator.c.
{
    u32 type, addr;
    type = args[0];
    addr = args[1];
    if(type >= EVENT_COUNT)
    {
        return 1;
    }
    EMU_LOG(PSTR("Registered Event Type: %"PRIu32" - Addr: %"PRIu32), type, addr);
    _emu->Events[type] = addr;
    return 0;
}
References _emu, EMU_LOG, EVENT_COUNT, and Emulator::Events.
syscall_exit()
static u8 syscall_exit (u32 * args) [static]
Exit program.
Parameters
args args[0]: Exit code
Returns
Non-zero on error
Definition at line 356 of file emulator.c.
{
    /* No parameter checking necessary */
    return 1;
    (void)args;
}
syscall_finish()
static u8 syscall_finish (u32 * args) [static]
Yield function to pass control to the scheduler.
Parameters
args Unused
Returns
Non-zero on error
Definition at line 369 of file emulator.c.
{
    /* No parameter checking necessary */
    _finished = true;
    return 0;
    (void)args;
}
References _finished.
syscall_gfx_image_1bit()
static u8 syscall_gfx_image_1bit (u32 * args) [static]
System call to draw a 1-bit-per-pixel image.
Parameters
args args[0]: Pointer to rectangle struct args[1]: Pointer to 1bpp image args[2]: ABGR Foreground color args[3]: ABGR Background color
Returns
Non-zero on error
Definition at line 645 of file emulator.c.
{
    u16 x, y, w, h;
    u32 image, bytes, rect_addr, fg, bg;
    Rectangle rect;
    rect_addr = args[0];
    if(_memory_check_bounds(rect_addr, sizeof(rect)))
    {
        return 1;
    }
    env_memory_read(rect_addr, &rect, sizeof(rect));
    x = rect.X;
    y = rect.Y;
    w = rect.W;
    h = rect.H;
    if(_gfx_check_bounds(x, y, w, h))
    {
        return 1;
    }
    image = args[1];
    bytes = (u32)w * (u32)h;
    if(_memory_check_bounds(image, bytes))
    {
        return 1;
    }
    fg = args[2];
    bg = args[3];
    env_gfx_image_1bit(x, y, w, h, image, fg, bg);
    return 0;
}
References _gfx_check_bounds(), _memory_check_bounds(), env_gfx_image_1bit(), env_memory_read(), Rectangle::H, Rectangle::W, Rectangle::X, and Rectangle::Y.
syscall_gfx_image_grayscale()
static u8 syscall_gfx_image_grayscale (u32 * args) [static]
System call to draw a grayscale image.
Parameters
args args[0]: Pointer to rectangle struct args[1]: Pointer to grayscale image args[2]: ABGR Foreground color args[3]: ABGR Background color
Returns
Non-zero on error
Definition at line 601 of file emulator.c.
{
    u16 x, y, w, h;
    u32 image, bytes, rect_addr, fg, bg;
    Rectangle rect;
    rect_addr = args[0];
    if(_memory_check_bounds(rect_addr, sizeof(rect)))
    {
        return 1;
    }
    env_memory_read(rect_addr, &rect, sizeof(rect));
    x = rect.X;
    y = rect.Y;
    w = rect.W;
    h = rect.H;
    if(_gfx_check_bounds(x, y, w, h))
    {
        return 1;
    }
    image = args[1];
    bytes = (u32)w * (u32)h;
    if(_memory_check_bounds(image, bytes))
    {
        return 1;
    }
    fg = args[2];
    bg = args[3];
    env_gfx_image_grayscale(x, y, w, h, image, fg, bg);
    return 0;
}
References _gfx_check_bounds(), _memory_check_bounds(), env_gfx_image_grayscale(), env_memory_read(), Rectangle::H, Rectangle::W, Rectangle::X, and Rectangle::Y.
syscall_gfx_image_rgb()
static u8 syscall_gfx_image_rgb (u32 * args) [static]
System call to draw an RGB image.
Parameters
args args[0]: X-Coordinate args[1]: Y-Coordinate args[2]: Width args[3]: Height args[4]: Pointer to RGB image
Returns
Non-zero on error
Definition at line 532 of file emulator.c.
{
    u16 x, y, w, h;
    u32 image, bytes;
    x = args[0];
    y = args[1];
    w = args[2];
    h = args[3];
    if(_gfx_check_bounds(x, y, w, h))
    {
        return 1;
    }
    image = args[4];
    bytes = (u32)3 * (u32)w * (u32)h;
    if(_memory_check_bounds(image, bytes))
    {
        return 1;
    }
    env_gfx_image_rgb(x, y, w, h, image);
    return 0;
}
References _gfx_check_bounds(), _memory_check_bounds(), and env_gfx_image_rgb().
syscall_gfx_image_rgb565()
static u8 syscall_gfx_image_rgb565 (u32 * args) [static]
System call to draw an RGB565 image.
Parameters
args args[0]: X-Coordinate args[1]: Y-Coordinate args[2]: Width args[3]: Height args[4]: Pointer to RGB565 image
Returns
Non-zero on error
Definition at line 567 of file emulator.c.
{
    u32 image, bytes;
    u16 x, y, w, h;
    x = args[0];
    y = args[1];
    w = args[2];
    h = args[3];
    if(_gfx_check_bounds(x, y, w, h))
    {
        return 1;
    }
    image = args[4];
    bytes = (u32)2 * (u32)w * (u32)h;
    if(_memory_check_bounds(image, bytes))
    {
        return 1;
    }
    env_gfx_image_rgb565(x, y, w, h, image);
    return 0;
}
References _gfx_check_bounds(), _memory_check_bounds(), and env_gfx_image_rgb565().
syscall_gfx_image_rgba()
static u8 syscall_gfx_image_rgba (u32 * args) [static]
System call to draw an RGBA image.
Parameters
args args[0]: X-Coordinate args[1]: Y-Coordinate args[2]: Width args[3]: Height args[4]: Pointer to RGBA image
Returns
Non-zero on error
Definition at line 497 of file emulator.c.
{
    u16 x, y, w, h;
    u32 image, bytes;
    x = args[0];
    y = args[1];
    w = args[2];
    h = args[3];
    if(_gfx_check_bounds(x, y, w, h))
    {
        return 1;
    }
    image = args[4];
    bytes = (u32)4 * (u32)w * (u32)h;
    if(_memory_check_bounds(image, bytes))
    {
        return 1;
    }
    env_gfx_image_rgba(x, y, w, h, image);
    return 0;
}
References _gfx_check_bounds(), _memory_check_bounds(), and env_gfx_image_rgba().
syscall_gfx_rect()
static u8 syscall_gfx_rect (u32 * args) [static]
System call to draw a rectangle.
Parameters
args args[0]: X-Coordinate args[1]: Y-Coordinate args[2]: Width args[3]: Height args[4]: ABGR Color
Returns
Non-zero on error
Definition at line 468 of file emulator.c.
{
    u16 x, y, w, h;
    u32 color;
    x = args[0];
    y = args[1];
    w = args[2];
    h = args[3];
    if(_gfx_check_bounds(x, y, w, h))
    {
        return 1;
    }
    color = args[4];
    env_gfx_rect(x, y, w, h, color);
    return 0;
}
References _gfx_check_bounds(), and env_gfx_rect().
syscall_millis()
static u8 syscall_millis (u32 * args) [static]
System call to get the number of milliseconds since startup.
Parameters
args args[0]: Return value (milliseconds)
Returns
Non-zero on error
Definition at line 406 of file emulator.c.
{
    /* No parameter checking necessary */
    args[0] = env_millis();
    return 0;
}
References env_millis().
syscall_rand()
static u8 syscall_rand (u32 * args) [static]
System call to get a random number.
Parameters
args args[0]: Return value (random number)
Returns
Non-zero on error
Definition at line 419 of file emulator.c.
{
    /* No parameter checking necessary */
    args[0] = env_random_get();
    return 0;
}
References env_random_get().
syscall_serial_write()
static u8 syscall_serial_write (u32 * args) [static]
System call to send data over the serial interface.
Parameters
args args[0]: Pointer to string to send args[1]: Number of bytes to send
Returns
Non-zero on error
Definition at line 433 of file emulator.c.
{
    u8 buf[128];
    u16 cur;
    u32 ptr, len;
    ptr = args[0];
    len = args[1];
    if(_memory_check_bounds(ptr, len))
    {
        return 1;
    }
    while(len)
    {
        cur = len > sizeof(buf) ? sizeof(buf) : len;
        env_memory_read(ptr, buf, cur);
        env_serial_write(buf, cur);
        len -= cur;
        ptr += cur;
    }
    return 0;
}
References _memory_check_bounds(), env_memory_read(), and env_serial_write().
Variable Documentation
_cur
Emulator _cur [static]
TODO: To be removed when multitasking is implemented
Definition at line 112 of file emulator.c.
_emu
Emulator* _emu = &_cur [static]
TODO: To be removed when multitasking is implemented
Definition at line 115 of file emulator.c.
Referenced by _memory_check_bounds(), kernel_init(), keyboard_event(), memory_lb(), memory_lbu(), memory_lh(), memory_lhu(), memory_lw(), memory_sb(), memory_sh(), memory_sw(), os_update(), and syscall_event_register().
_finished
bool _finished [static]
Called function finished flag
Definition at line 109 of file emulator.c.
Referenced by emulator_call(), and syscall_finish().
_memory_size
u32 _memory_size [static]
Total size of the memory in bytes
Definition at line 118 of file emulator.c.
Referenced by kernel_init(), keyboard_event(), and os_update().
syscalls
u8(* syscalls[])(u32 *) (u32 *) [static]
Initial value:
=
{
    syscall_exit,
    syscall_finish,
    syscall_event_register,
    syscall_gfx_rect,
    syscall_gfx_image_rgba,
    syscall_gfx_image_rgb,
    syscall_gfx_image_rgb565,
    syscall_gfx_image_grayscale,
    syscall_gfx_image_1bit,
    syscall_rand,
    syscall_serial_write,
    syscall_millis
}
System call function pointer array
Definition at line 681 of file emulator.c.
Referenced by syscall().