emulator/emulator.h File Reference
RISC-V Emulator.
#include <types.h>
#include <event-types.h>
#include <keyboard-shared.h>
#include <inttypes.h>
Data Structures
struct Emulator
Functions
void kernel_init (void)
Initialize emulator kernel and load first process (NOT systemd)
void os_update (void)
Call this function periodically in main loop.
void keyboard_event (Key key, i32 chr, KeyState state)
Inform the emulator about a key press.
u8 emulator_call (Emulator *emu, u32 addr, u32 *args, u8 num, u32 sp)
Call an emulated RISC-V function.
Detailed Description
RISC-V Emulator.
Author
Anton Tchekov
Version
0.1
Date
17.05.2023
Definition in file emulator.h.
Function Documentation
emulator_call()
u8 emulator_call (Emulator * emu, u32 addr, u32 * args, u8 num, u32 sp)
Call an emulated RISC-V function.
Parameters
emu Pointer to emulator struct
addr Function start address
args Function arguments
num Number of arguments
sp Stack pointer start
Definition at line 1165 of file emulator.c.
{
    u32 i;
    /* Initialize Stack Pointer at end of memory */
    emu->Registers[2] = sp - 4;
    emu->PC = addr;
    memcpy(&emu->Registers[10], args, num * sizeof(*emu->Registers));
    i = 0;
    _finished = false;
    while(!_finished)
    {
        ++i;
        if(emulator_next(emu))
        {
            return 1;
        }
    }
    EMU_LOG(PSTR("%"PRIu32" Cycles"), i);
    return 0;
}
References _finished, EMU_LOG, emulator_next(), memcpy(), Emulator::PC, and Emulator::Registers.
Referenced by kernel_init(), keyboard_event(), and os_update().
kernel_init()
void kernel_init (void)
Initialize emulator kernel and load first process (NOT systemd)
Definition at line 120 of file emulator.c.
{
    _memory_size = env_memory_size();
    _emu->SegmentStart = 0;
    _emu->SegmentSize = _memory_size;
    _emu->SegmentEnd = _memory_size;
    emulator_call(_emu, 0, NULL, 0, _memory_size);
}
References _emu, _memory_size, emulator_call(), env_memory_size(), Emulator::SegmentEnd, Emulator::SegmentSize, and Emulator::SegmentStart.
Referenced by main().
keyboard_event()
void keyboard_event (Key key, i32 chr, KeyState state)
Inform the emulator about a key press.
Parameters
key The scancode
chr The unicode codepoint of the scancode or 0
state The state of the key (pressed, repeat, released)
Definition at line 138 of file emulator.c.
{
    u32 addr = _emu->Events[EVENT_KEY];
    if(addr)
    {
        u32 args[] = { key, chr, down };
        emulator_call(_emu, addr, args, ARRLEN(args), _memory_size);
    }
}
References _emu, _memory_size, ARRLEN, emulator_call(), EVENT_KEY, and Emulator::Events.
Referenced by main().
os_update()
void os_update (void)
Call this function periodically in main loop.
Definition at line 129 of file emulator.c.
{
    u32 addr = _emu->Events[EVENT_LOOP];
    if(addr)
    {
        emulator_call(_emu, addr, NULL, 0, _memory_size);
    }
}
References _emu, _memory_size, emulator_call(), EVENT_LOOP, and Emulator::Events.
Referenced by main().