stdlib/event/event.h File Reference
Event handling functions.
#include <types.h>
#include <event-types.h>
Functions
void finish (void)
Finish an event handler. Do NOT call this function.
void setup (void)
Setup function that is called at program start. Must be implemented by user.
void loop (void)
Loop function that is called repeatedly Must be implemented by user.
void event_register (Event type, u32 event)
Register an event. Do NOT call this function.
Detailed Description
Event handling functions.
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
29.04.2023
Definition in file event.h.
Function Documentation
event_register()
void event_register (Event type, u32 event)
Register an event. Do NOT call this function.
Parameters
type Event Type, see enum above
event Event handler function address
Definition at line 40 of file event.c.
{
    syscall2(SYSCALL_EVENT_REGISTER, type, event);
}
References syscall2().
Referenced by keyboard_init().
finish()
void finish (void)
Finish an event handler. Do NOT call this function.
Definition at line 13 of file event.c.
{
    syscall0(SYSCALL_FINISH);
}
References syscall0().
Referenced by _event_key_handler(), and _event_loop_handler().
loop()
void loop (void)
Loop function that is called repeatedly Must be implemented by user.
Loop function that is called repeatedly Must be implemented by user.
Definition at line 270 of file main.c.
{
}
References _changed, _cp, _draw_field(), _error, _field, _field_rows(), _hide_error(), _label_response, _millis_blink, _millis_error, _new_piece(), _np, _ticks_update, _to_field(), _valid_position(), _visible, BLINK_DELAY, FALL_SPEED_DEFAULT, label_show(), memset(), millis(), SHOW_ERROR_DELAY, Piece::Type, and Piece::Y.
Referenced by _event_loop_handler().
setup()
void setup (void)
Setup function that is called at program start. Must be implemented by user.
Setup function that is called at program start. Must be implemented by user.
Definition at line 254 of file main.c.
{
    keyboard_register_event(event_key);
    keyword_init();
    vector_init(&_code, sizeof(char), INITIAL_CODE_CAPACITY);
    vector_set(&_code, _file, ARRLEN(_file));
    window_init(&_window_editor, "Editor", NULL, 0, NULL);
    window_open(&_window_editor);
    gfx_rect(30, 20, 1, GFX_HEIGHT - 20, THEME_LIGHT);
    _draw_line_numbers(37);
    _draw_code();
}
References _button_login, _code, _cp, _draw_code(), _draw_grid(), _draw_line_numbers(), _field, _file, _input_password, _input_username, _label_no_apps, _label_password, _label_response, _label_username, _new_piece(), _np, _status, _window_apps, _window_editor, _window_login, ARRLEN, BUTTON_HEIGHT, button_init(), button_login_onclick(), BUTTON_LOGIN_Y, BUTTON_WIDTH, COLOR_BLACK, COLOR_WHITE, elements_apps, elements_login, event_key(), FLAG_ALIGN_CENTER, FLAG_ALIGN_LEFT, FLAG_INVERTED, FLAG_INVISIBLE, FLAG_PASSWORD, Input::Flags, font_string(), GFX_HEIGHT, gfx_rect(), GFX_WIDTH, INITIAL_CODE_CAPACITY, input_init(), INPUT_LABEL_OFFSET, INPUT_PASSWORD_Y, INPUT_USERNAME_Y, INPUT_WIDTH, keyboard_register_event(), keyword_init(), LABEL_ERROR_Y, label_init(), LABEL_NO_APPS_Y, memset(), Piece::Rotation, STATUS_RUNNING, THEME_LIGHT, Piece::Type, vector_init(), vector_set(), window_init(), window_login_onkey(), window_open(), Piece::X, and Piece::Y.