stdlib/event/event.c File Reference
#include <event.h>
#include <syscall.h>
#include <keyboard.h>
#include <alloc.h>
Functions
void finish (void)
Finish an event handler. Do NOT call this function.
static void _event_loop_handler (void)
void __setup (void)
void event_register (Event type, u32 event)
Register an event. Do NOT call this function.
Detailed Description
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
29.04.2023
Definition in file event.c.
Function Documentation
__setup()
void __setup (void)
Wrapper function for setup function
Definition at line 25 of file event.c.
{
    event_register(EVENT_LOOP, (u32)_event_loop_handler);
    /* TODO: What are good values? */
    memalloc_init(0x10000, 0x40000);
    keyboard_init();
    setup();
    finish();
}
_event_loop_handler()
static void _event_loop_handler (void) [static]
Wrapper function for main loop
Definition at line 19 of file event.c.
{
    loop();
    finish();
}
References finish().
event_register()
void event_register (Event type, u32 event)
Register an event. Do NOT call this function.
Parameters
type Event Type, see enum above
event Event handler function address
Definition at line 40 of file event.c.
{
    syscall2(SYSCALL_EVENT_REGISTER, type, event);
}
References syscall2().
Referenced by keyboard_init().
finish()
void finish (void)
Finish an event handler. Do NOT call this function.
Definition at line 13 of file event.c.
{
    syscall0(SYSCALL_FINISH);
}
References syscall0().
Referenced by _event_key_handler(), and _event_loop_handler().