stdlib/font/font.h File Reference
Font rendering with UTF-8 support.
#include <types.h>
#include <gfx.h>
Data Structures
struct FontChar
struct FONT
Macros
#define FONT_FLAG_GRAYSCALE 1
Typedefs
typedef struct FONT Font
Functions
i32 font_string_len (i32 x, i32 y, const char *s, u32 len, Font *font, Color fg, Color bg)
Draw an UTF-8 string s with a maximum number of chars. This function will also stop at a '\0' character.
i32 font_string_width_len (const char *s, u32 len, Font *font)
Calculate the width of a string in pixels.
static i32 font_string (i32 x, i32 y, const char *s, Font *font, Color fg, Color bg)
Draw an NUL-terminated UTF-8 string s
static i32 font_string_width (const char *s, Font *font)
Calculate the width of a string in pixels.
Detailed Description
Font rendering with UTF-8 support.
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
23.04.2023
Definition in file font.h.
Macro Definition Documentation
FONT_FLAG_GRAYSCALE
#define FONT_FLAG_GRAYSCALE 1
Font flags bit mask: 1: grayscale, 0: 1 bit per pixel
Definition at line 16 of file font.h.
Typedef Documentation
Font
typedef struct FONT Font
Font Data struct
Function Documentation
font_string()
static i32 font_string (i32 x, i32 y, const char * s, Font * font, Color fg, Color bg) [inline], [static]
Draw an NUL-terminated UTF-8 string s
Parameters
x X-Coordinate (Top)
y Y-Coordinate (Left)
s Character array
font The font to use
fg Foreground color
bg Background color
Definition at line 90 of file font.h.
{
    return font_string_len(x, y, s, UINT32_MAX, font, fg, bg);
}
References font_string_len().
Referenced by _draw_line_numbers(), button_render(), label_render(), setup(), and window_render().
font_string_len()
i32 font_string_len (i32 x, i32 y, const char * s, u32 len, Font * font, Color fg, Color bg)
Draw an UTF-8 string s with a maximum number of chars. This function will also stop at a '\0' character.
Parameters
x X-Coordinate (Top)
y Y-Coordinate (Left)
s Character array
len Maximum number of unicode characters
font The font to use
fg Foreground color
bg Background color
Definition at line 37 of file font.c.
{
    u32 i;
    i32 c;
    FontChar *fc;
    void (*render_char)(i32, i32, i32, i32, const u8 *, Color, Color) =
        font->Flags & FONT_FLAG_GRAYSCALE ?
        gfx_image_grayscale : gfx_image_1bit;
    for(i = 0; i < len; ++i)
    {
        s = utf8_codepoint(s, &c);
        if(!c)
        {
            break;
        }
        if(!(fc = _font_char(c, font)))
        {
            continue;
        }
        if(fc->Size[0] && fc->Size[1])
        {
            render_char(
                x + fc->Bearing[0],
                y + (font->Size - fc->Bearing[1]),
                fc->Size[0],
                fc->Size[1],
                font->Bitmap + fc->Offset,
                fg, bg);
        }
        x += fc->Advance;
    }
    return x;
}
References _font_char(), FontChar::Advance, FontChar::Bearing, Font::Flags, FONT_FLAG_GRAYSCALE, gfx_image_1bit(), gfx_image_grayscale(), FontChar::Offset, FontChar::Size, Font::Size, and utf8_codepoint().
Referenced by _draw_code(), font_string(), and input_render().
font_string_width()
static i32 font_string_width (const char * s, Font * font) [inline], [static]
Calculate the width of a string in pixels.
Parameters
s The string
font The font
Definition at line 102 of file font.h.
{
    return font_string_width_len(s, UINT32_MAX, font);
}
References font_string_width_len().
Referenced by _draw_line_numbers(), button_render(), and label_render().
font_string_width_len()
i32 font_string_width_len (const char * s, u32 len, Font * font)
Calculate the width of a string in pixels.
Parameters
s The string
len Maximum number of unicode characters
font The font
Definition at line 77 of file font.c.
{
    i32 c, width;
    u32 i;
    FontChar *fc;
    width = 0;
    for(i = 0; i < len; ++i)
    {
        s = utf8_codepoint(s, &c);
        if(!c)
        {
            break;
        }
        if((fc = _font_char(c, font)))
        {
            width += fc->Advance;
        }
    }
    return width;
}
References _font_char(), FontChar::Advance, and utf8_codepoint().
Referenced by font_string_width(), input_render(), and input_selection_replace().