tools/font-convert/font-convert.c File Reference
Bitmap font from TTF generator.
#include <stdio.h>
#include <locale.h>
#include <types.h>
#include <utf8.h>
#include ft2build.h
Data Structures
struct FontChar
struct Font
Functions
static void * _malloc (u32 size)
Malloc wrapper that prints an error and exits if the memory allocation failed.
static i32 _compare_i32 (const void *a, const void *b)
Compare two i32 numbers for qsort.
static i32 _sort_unique (i32 *elements, i32 count)
Sort an array of i32 numbers in place and remove duplicates.
static i32 * _unique_codepoints (const char *s, i32 *length)
Get an array of unique unicode codepoints from a UTF-8 string.
int main (int argc, char *argv[])
Font converter main function.
Detailed Description
Bitmap font from TTF generator.
Author
Anton Tchekov
Version
0.1
Date
25.05.2023
Definition in file font-convert.c.
Function Documentation
_compare_i32()
static i32 _compare_i32 (const void * a, const void * b) [static]
Compare two i32 numbers for qsort.
Parameters
a First element
b Second element
Returns
Comparison result (ordering)
Definition at line 82 of file font-convert.c.
{
    return *(const i32 *)a - *(const i32 *)b;
}
Referenced by _sort_unique().
_malloc()
static void * _malloc (u32 size) [static]
Malloc wrapper that prints an error and exits if the memory allocation failed.
Parameters
size Number of bytes to allocate
Returns
Block of memory with the requested size
Definition at line 61 of file font-convert.c.
{
    void *p = malloc(size);
    if(!p)
    {
        fprintf(stderr, "Memory allocation failed\n");
        exit(1);
    }
    return p;
}
References exit().
Referenced by _unique_codepoints(), and main().
_sort_unique()
static i32 _sort_unique (i32 * elements, i32 count) [static]
Sort an array of i32 numbers in place and remove duplicates.
Parameters
elements Pointer to array of numbers
count Number of elements in the array
Returns
New count after duplocates have been removed
Definition at line 94 of file font-convert.c.
{
    i32 a, b;
    qsort(elements, count, sizeof(*elements), _compare_i32);
    /* Remove duplicates */
    for(a = 1, b = 1; a < count; ++a)
    {
        if(elements[a] == elements[a - 1])
        {
            continue;
        }
        elements[b++] = elements[a];
    }
    return b;
}
References _compare_i32().
Referenced by _unique_codepoints().
_unique_codepoints()
static i32 * _unique_codepoints (const char * s, i32 * length) [static]
Get an array of unique unicode codepoints from a UTF-8 string.
Parameters
s The string
length Output parameter for number of unique codepoints
Returns
Pointer to heap-allocated unicode codepoint array
Definition at line 120 of file font-convert.c.
{
    const char *p;
    i32 *cp, c, count;
    if(!strcmp(s, "printable_ascii"))
    {
        s = " !\"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ"
            "[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~";
    }
    count = utf8_length(s);
    cp = _malloc(count * sizeof(*cp));
    p = s;
    for(count = 0; ; ++count)
    {
        p = utf8_codepoint(p, &c);
        if(!c)
        {
            break;
        }
        cp[count] = c;
    }
    *length = _sort_unique(cp, count);
    return cp;
}
References _malloc(), _sort_unique(), strcmp(), utf8_codepoint(), and utf8_length().
Referenced by main().
main()
int main (int argc, char * argv[])
Font converter main function.
Parameters
argc Command line argument count
argv Command line arguments array
Returns
Exit code
Definition at line 156 of file font-convert.c.
{
    FT_Library library;
    FT_Face face;
    Font font;
    FontChar *fc;
    const char *input_filename, *font_name;
    i32 *codepoints, i, c, x, y, num_chars, font_size, bytes, offset;
    /* Set locale so that non-ascii characters are displayed correctly */
    setlocale(LC_CTYPE, "");
    /* Check correct usage */
    if(argc != 6)
    {
        fprintf(stderr, "Usage: "
            "./font-convert input-file font-name font-size char-list mode\n"
            "Mode: 1bit or grayscale\n");
        return 1;
    }
    /* Initialize FreeType */
    if(FT_Init_FreeType(&library))
    {
        fprintf(stderr, "FreeType initialization failed\n");
        return 1;
    }
    if(!strcmp(argv[5], "1bit"))
    {
        font.Flags = 0;
    }
    else if(!strcmp(argv[5], "grayscale"))
    {
        font.Flags = 1;
    }
    else
    {
        fprintf(stderr, "Invalid mode\n");
        return 1;
    }
    input_filename = argv[1];
    font_name = argv[2];
    if(!(font_size = strtol(argv[3], NULL, 10)))
    {
        fprintf(stderr, "Invalid font size\n");
        return 1;
    }
    codepoints = _unique_codepoints(argv[4], &num_chars);
    /* Load Input */
    /* fprintf(stderr, "Loading font \"%s\"\n", input_filename); */
    if(FT_New_Face(library, input_filename, 0, &face))
    {
        fprintf(stderr, "Failed to load font \"%s\"\n", input_filename);
        return 1;
    }
    font.Size = font_size;
    font.NumCharacters = num_chars;
    font.Characters = _malloc(num_chars * sizeof(FontChar));
    FT_Set_Pixel_Sizes(face, 0, font_size);
    offset = 0;
    for(i = 0; i < num_chars; ++i)
    {
        c = codepoints[i];
        /* fprintf(stderr, "Loading character \'%lc\'\n", c); */
        if(FT_Load_Char(face, c, FT_LOAD_RENDER))
        {
            fprintf(stderr, "Failed to load character: \'%lc\'", c);
            return 1;
        }
        fc = &font.Characters[i];
        fc->Codepoint = c;
        fc->Advance = face->glyph->advance.x >> 6;
        fc->Size[0] = face->glyph->bitmap.width;
        fc->Size[1] = face->glyph->bitmap.rows;
        fc->Bearing[0] = face->glyph->bitmap_left;
        fc->Bearing[1] = face->glyph->bitmap_top;
        bytes = fc->Size[0] * fc->Size[1];
        fc->Bitmap = _malloc(bytes);
        fc->Offset = offset;
        memcpy(fc->Bitmap, face->glyph->bitmap.buffer, bytes);
        if(font.Flags & 1)
        {
            offset += bytes;
        }
        else
        {
            offset += fc->Size[1] * ((fc->Size[0] + 7) / 8);
        }
    }
    /* Write Output */
    fprintf(stdout,
        "#include <%s.h>\n"
        "\n", font_name);
    fprintf(stdout,
        "static FontChar _chars[] =\n"
        "{\n");
    for(i = 0; i < num_chars; ++i)
    {
        fc = &font.Characters[i];
        fprintf(stdout,
            "\t{\n"
            "\t\t.Codepoint = %d,\n"
            "\t\t.Advance = %d,\n"
            "\t\t.Size = { %d, %d },\n"
            "\t\t.Bearing = { %d, %d },\n"
            "\t\t.Offset = %d\n"
            "\t}%s\n",
            fc->Codepoint,
            fc->Advance,
            fc->Size[0],
            fc->Size[1],
            fc->Bearing[0],
            fc->Bearing[1],
            fc->Offset,
            i == num_chars - 1 ? "" : ",");
    }
    fprintf(stdout, "};\n"
        "\n");
    fprintf(stdout, "static u8 _bitmap[] =\n"
        "{\n");
    for(i = 0; i < num_chars; ++i)
    {
        fc = &font.Characters[i];
        for(y = 0; y < fc->Size[1]; ++y)
        {
            fprintf(stdout, "\t\t");
            if(font.Flags & 1)
            {
                /* grayscale */
                for(x = 0; x < fc->Size[0]; ++x)
                {
                    fprintf(stdout, "0x%02X, ", fc->Bitmap[y * fc->Size[0] + x]);
                }
                fprintf(stdout, "\n");
            }
            else
            {
                /* 1bit */
                i32 byte = 0, bit = 1;
                for(x = 0; x < fc->Size[0]; ++x)
                {
                    if(bit == 0x100)
                    {
                        fprintf(stdout, "0x%02X, ", byte);
                        byte = 0;
                        bit = 1;
                    }
                    if(fc->Bitmap[y * fc->Size[0] + x] > 128)
                    {
                        byte |= bit;
                    }
                    bit <<= 1;
                }
                if(bit != 1)
                {
                    fprintf(stdout, "0x%02X, ", byte);
                }
                fprintf(stdout, "/* ");
                for(x = 0; x < fc->Size[0]; ++x)
                {
                    fprintf(stdout, "%c",
                        fc->Bitmap[y * fc->Size[0] + x] > 128 ? '#' : ' ');
                }
                fprintf(stdout, " */\n");
            }
        }
        fprintf(stdout, "\n");
    }
    fprintf(stdout, "};\n"
        "\n");
    fprintf(stdout,
        "static Font _%s =\n"
        "{\n"
        "\t.Characters = _chars,\n"
        "\t.Size = %d,\n"
        "\t.NumCharacters = %d,\n"
        "\t.Flags = %d,\n"
        "\t.Bitmap = _bitmap\n"
        "};\n\n"
        "Font *%s = &_%s;\n"
        "\n",
        font_name, font_size, num_chars, font.Flags, font_name, font_name);
    /* Cleanup */
    for(i = 0; i < num_chars; ++i)
    {
        free(font.Characters[i].Bitmap);
    }
    free(font.Characters);
    free(codepoints);
    FT_Done_Face(face);
    FT_Done_FreeType(library);
    return 0;
}
References _malloc(), _unique_codepoints(), FontChar::Advance, FontChar::Bearing, FontChar::Bitmap, Font::Characters, FontChar::Codepoint, Font::Flags, memcpy(), Font::NumCharacters, FontChar::Offset, FontChar::Size, Font::Size, and strcmp().