stdlib/font/font.c File Reference
#include <font.h>
#include <utf8.h>
#include <algo.h>
Functions
static i32 _find_char (const void *key, const void *elem)
Compare function for bsearch in _font_char
static FontChar * _font_char (i32 c, Font *font)
Finds the FontChar from a Font for a unicode codepoint.
i32 font_string_len (i32 x, i32 y, const char *s, u32 len, Font *font, Color fg, Color bg)
Draw an UTF-8 string s with a maximum number of chars. This function will also stop at a '\0' character.
i32 font_string_width_len (const char *s, u32 len, Font *font)
Calculate the width of a string in pixels.
Detailed Description
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
23.04.2023
Definition in file font.c.
Function Documentation
_find_char()
static i32 _find_char (const void * key, const void * elem) [static]
Compare function for bsearch in _font_char
Parameters
key The codepoint for which we want to find the FontChar
elem The FontChar we are comparing with
Returns
Ordering (-1: before, 0: match, 1: after)
Definition at line 19 of file font.c.
{
    return *(const i32 *)key - ((const FontChar *)elem)->Codepoint;
}
Referenced by _font_char().
_font_char()
static FontChar * _font_char (i32 c, Font * font) [static]
Finds the FontChar from a Font for a unicode codepoint.
Parameters
c The Unicode Codepoint
font Pointer to a Font
Returns
Pointer to a FontChar or NULL if not found
Definition at line 31 of file font.c.
{
    return bsearch(&c, font->Characters, font->NumCharacters,
            sizeof(FontChar), _find_char);
}
References _find_char(), bsearch(), Font::Characters, and Font::NumCharacters.
Referenced by font_string_len(), and font_string_width_len().
font_string_len()
i32 font_string_len (i32 x, i32 y, const char * s, u32 len, Font * font, Color fg, Color bg)
Draw an UTF-8 string s with a maximum number of chars. This function will also stop at a '\0' character.
Parameters
x X-Coordinate (Top)
y Y-Coordinate (Left)
s Character array
len Maximum number of unicode characters
font The font to use
fg Foreground color
bg Background color
Definition at line 37 of file font.c.
{
    u32 i;
    i32 c;
    FontChar *fc;
    void (*render_char)(i32, i32, i32, i32, const u8 *, Color, Color) =
        font->Flags & FONT_FLAG_GRAYSCALE ?
        gfx_image_grayscale : gfx_image_1bit;
    for(i = 0; i < len; ++i)
    {
        s = utf8_codepoint(s, &c);
        if(!c)
        {
            break;
        }
        if(!(fc = _font_char(c, font)))
        {
            continue;
        }
        if(fc->Size[0] && fc->Size[1])
        {
            render_char(
                x + fc->Bearing[0],
                y + (font->Size - fc->Bearing[1]),
                fc->Size[0],
                fc->Size[1],
                font->Bitmap + fc->Offset,
                fg, bg);
        }
        x += fc->Advance;
    }
    return x;
}
References _font_char(), FontChar::Advance, FontChar::Bearing, Font::Flags, FONT_FLAG_GRAYSCALE, gfx_image_1bit(), gfx_image_grayscale(), FontChar::Offset, FontChar::Size, Font::Size, and utf8_codepoint().
Referenced by _draw_code(), font_string(), and input_render().
font_string_width_len()
i32 font_string_width_len (const char * s, u32 len, Font * font)
Calculate the width of a string in pixels.
Parameters
s The string
len Maximum number of unicode characters
font The font
Definition at line 77 of file font.c.
{
    i32 c, width;
    u32 i;
    FontChar *fc;
    width = 0;
    for(i = 0; i < len; ++i)
    {
        s = utf8_codepoint(s, &c);
        if(!c)
        {
            break;
        }
        if((fc = _font_char(c, font)))
        {
            width += fc->Advance;
        }
    }
    return width;
}
References _font_char(), FontChar::Advance, and utf8_codepoint().
Referenced by font_string_width(), input_render(), and input_selection_replace().