stdlib/format/format.h File Reference
String formatting.
#include <types.h>
#include <stdarg.h>
Functions
i32 sprintf (char *str, const char *format,...)
Formats and stores a series of characters and values in the provided character array buffer, according to the specified format string.
i32 snprintf (char *str, u32 size, const char *format,...)
Formats and stores a series of characters and values in the provided character array buffer, according to the specified format string and a maximum buffer size.
i32 vsnprintf (char *str, u32 size, const char *format, va_list arg)
Formats and stores a series of characters and values in the provided character array buffer, according to the specified format string and a maximum buffer size, taking a va_list argument instead of variable arguments.
Detailed Description
String formatting.
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
23.04.2023
Definition in file format.h.
Function Documentation
snprintf()
i32 snprintf (char * str, u32 size, const char * format, ...)
Formats and stores a series of characters and values in the provided character array buffer, according to the specified format string and a maximum buffer size.
Parameters
str A pointer to the character array buffer where the resulting formatted string will be stored
size The maximum number of characters to be written to the buffer, including the terminating null character
format A string that specifies how subsequent arguments are converted for output
... A variable number of additional arguments to be formatted and inserted into the resulting string, according to the format string
Returns
The total number of characters that would have been written to the buffer, if the output had not been truncated, not including the terminating null character.
Referenced by _draw_line_numbers(), and memory_dump().
sprintf()
i32 sprintf (char * str, const char * format, ...)
Formats and stores a series of characters and values in the provided character array buffer, according to the specified format string.
Parameters
str A pointer to the character array buffer where the resulting formatted string will be stored.
format A string that specifies how subsequent arguments are converted for output
... A variable number of additional arguments to be formatted and inserted into the resulting string, according to the format string
Returns
The total number of characters written to the buffer, not including the terminating null character.
vsnprintf()
i32 vsnprintf (char * str, u32 size, const char * format, va_list arg)
Formats and stores a series of characters and values in the provided character array buffer, according to the specified format string and a maximum buffer size, taking a va_list argument instead of variable arguments.
Parameters
str A pointer to the character array buffer where the resulting formatted string will be stored.
size The maximum number of characters to be written to the buffer, including the terminating null character.
format A string that specifies how subsequent arguments are converted for output.
arg A va_list object containing the variable arguments to be formatted and inserted into the resulting string, according to the format string.
Returns
The total number of characters that would have been written to the buffer, if the output had not been truncated, not including the terminating null character.
Referenced by debug_print().