temp/fs/fs.h File Reference
File system access.
#include <status.h>
#include <types.h>
#include <atfs.h>
Data Structures
struct File
struct Dir
struct DirEntry
Functions
char * path_join (char *path, const char *append)
Join two paths by copying the second path to the end of the first path and adding a dot in between. The first string must have enough space to contain the whole path. The validity of the path is not checked.
char * path_parent (char *path)
Remove the last component of the path in place. The validity of the path is not checked.
bool path_valid (const char *path)
Check if a path is valid.
bool identifier_valid (const char *path)
Check if a identifier is valid.
Status fs_format (u32 disk)
Format disk with ATFS.
Status fs_mount (u32 disk, const char *ident)
Mount disk with ATFS.
Status fs_fcreate (const char *path, u32 size)
Create a file. If the file already exists, it is resized to the specified size. When a file is resized, all file handles to it are invalidated and need to be reopened.
Status fs_fopen (const char *path, File *file)
Open a file to get a file handle. It is not neccessary to close a file, therefore there is no fs_fclose function.
Status fs_fread (File *file, u32 block, void *buf)
Reads one block from the file.
Status fs_fwrite (File *file, u32 block, const void *buf)
Write one block to the file.
Status fs_delete (const char *path)
Recursively delete a files and directories.
Status fs_rename (const char *dest, const char *src)
Move or rename a file or a directory.
Status fs_copy (const char *dest, const char *src)
Recursively copy files and directories.
Status fs_dopen (const char *path, Dir *dir)
Open a directory.
Status fs_dread (Dir *dir, u32 index, DirEntry *entry)
Read a directory entry.
Detailed Description
File system access.
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
23.04.2023
Definition in file fs.h.
Function Documentation
fs_copy()
Status fs_copy (const char * dest, const char * src)
Recursively copy files and directories.
Parameters
dest Destination path
src Source path
Returns
Status
Definition at line 405 of file fs.c.
{
    return STATUS_OK;
    (void)dest, (void)src;
}
fs_delete()
Status fs_delete (const char * path)
Recursively delete a files and directories.
Parameters
path Path to file
Returns
Status
Definition at line 387 of file fs.c.
{
    return STATUS_OK;
    (void)path;
}
fs_dopen()
Status fs_dopen (const char * path, Dir * dir)
Open a directory.
Parameters
path Path to directory
dir Output parameter directory handle
Returns
Status
Definition at line 411 of file fs.c.
{
    u8 buf[ATFS_BLOCK_SIZE];
    RETURN_IF(fs_fopen(path, &dir->InternalFile));
    RETURN_IF(fs_fread(&dir->InternalFile, 0, buf));
    dir->NumEntries = load_le_32(buf);
    return STATUS_OK;
}
References ATFS_BLOCK_SIZE, fs_fopen(), fs_fread(), Dir::InternalFile, load_le_32(), Dir::NumEntries, and RETURN_IF.
fs_dread()
Status fs_dread (Dir * dir, u32 index, DirEntry * entry)
Read a directory entry.
Parameters
dir Directory handle
index File index
entry Output parameter directory entry
Returns
Status
Definition at line 421 of file fs.c.
{
    u8 buf[ATFS_BLOCK_SIZE];
    u32 offset, block;
    if(index >= dir->NumEntries)
    {
        return STATUS_OUT_OF_BOUNDS;
    }
    /* Add one because the first directory entry is reserved for metadata */
    offset = (index + 1) * ATFS_DIR_ENTRY_SIZE;
    block = offset / ATFS_BLOCK_SIZE;
    offset -= block * ATFS_BLOCK_SIZE;
    RETURN_IF(fs_fread(&dir->InternalFile, block, buf));
    dir_entry_get(buf + offset, entry);
    return STATUS_OK;
}
References ATFS_BLOCK_SIZE, ATFS_DIR_ENTRY_SIZE, dir_entry_get(), fs_fread(), Dir::InternalFile, Dir::NumEntries, and RETURN_IF.
fs_fcreate()
Status fs_fcreate (const char * path, u32 size)
Create a file. If the file already exists, it is resized to the specified size. When a file is resized, all file handles to it are invalidated and need to be reopened.
Parameters
path Path to file
size Capacity of the file in blocks
Returns
Status
Definition at line 257 of file fs.c.
{
    #ifdef AAA
    Dir dir;
    DirEntry entry;
    if(_traverse(path, &dir))
    {
        u32 start;
        /* New file */
        RETURN_IF(fs_alloc(size, &start));
    }
    else if(file.SizeBlocks != size)
    {
        /* TODO: Resize file */
    }
    #endif
    return STATUS_OK;
}
References fs_alloc(), and RETURN_IF.
fs_fopen()
Status fs_fopen (const char * path, File * file)
Open a file to get a file handle. It is not neccessary to close a file, therefore there is no fs_fclose function.
Parameters
path Path to file
file Output parameter file handle
Returns
Status
Definition at line 317 of file fs.c.
{
    u8 buf[ATFS_BLOCK_SIZE];
    DirEntry entry;
    const char *s, *name;
    char c;
    u32 name_len;
    /* Check path format beforehand for simplicity */
    if(!path_valid(path))
    {
        return STATUS_PATH_FORMAT_INVALID;
    }
    /* Traverse directory structure starting in root directory */
    RETURN_IF(disk_read(ATFS_SECTOR_BOOT, buf));
    entry.StartBlock = load_le_32(buf + ATFS_OFFSET_ROOT_BLOCK);
    entry.SizeBlocks = load_le_32(buf + ATFS_OFFSET_ROOT_SIZE);
    s = path;
    while(*s)
    {
        /* Get next part of path string */
        name = s;
        for(; (c = *s) && c != ATFS_DIR_SEPARATOR; ++s) {}
        name_len = s - name;
        /* Search current directory */
        RETURN_IF(_find_entry(name, name_len, entry.StartBlock, &entry));
        /* If in the middle of a path */
        if(!*s)
        {
            /* Skip directory separator */
            ++s;
            /* Found entry must be a directory */
            if(entry.Type)
            {
                return STATUS_NO_SUCH_FILE_OR_DIR;
            }
        }
    }
    /* Entry was found */
    file->StartBlock = entry.StartBlock;
    file->SizeBlocks = entry.SizeBlocks;
    return STATUS_OK;
}
References _find_entry(), ATFS_BLOCK_SIZE, ATFS_DIR_SEPARATOR, ATFS_OFFSET_ROOT_BLOCK, ATFS_OFFSET_ROOT_SIZE, ATFS_SECTOR_BOOT, disk_read(), load_le_32(), path_valid(), RETURN_IF, File::SizeBlocks, DirEntry::SizeBlocks, File::StartBlock, DirEntry::StartBlock, and DirEntry::Type.
Referenced by fs_dopen().
fs_format()
Status fs_format (u32 disk)
Format disk with ATFS.
Parameters
disk Drive number
fs_fread()
Status fs_fread (File * file, u32 block, void * buf)
Reads one block from the file.
Parameters
file File handle
block The block to read
buf Buffer for read data (512 bytes)
Returns
Status
Definition at line 366 of file fs.c.
{
    if(block >= file->SizeBlocks)
    {
        return STATUS_OUT_OF_BOUNDS;
    }
    return disk_read(file->StartBlock + block, buf);
}
References disk_read(), File::SizeBlocks, and File::StartBlock.
Referenced by fs_dopen(), and fs_dread().
fs_fwrite()
Status fs_fwrite (File * file, u32 block, const void * buf)
Write one block to the file.
Parameters
file File handle
block The block to write
buf Buffer with data to write (512 bytes)
Returns
Status
Definition at line 376 of file fs.c.
{
    if(block >= file->SizeBlocks)
    {
        return STATUS_OUT_OF_BOUNDS;
    }
    return disk_write(file->StartBlock + block, buf);
}
References disk_write(), File::SizeBlocks, and File::StartBlock.
fs_mount()
Status fs_mount (u32 disk, const char * ident)
Mount disk with ATFS.
Parameters
disk Drive number
ident Identifier
fs_rename()
Status fs_rename (const char * dest, const char * src)
Move or rename a file or a directory.
Parameters
dest Destination path
src Source path
Returns
Status
Definition at line 394 of file fs.c.
{
    /* Create new directory entries */
    /* Delete old directory entries */
    return STATUS_OK;
    (void)dest, (void)src;
}
identifier_valid()
bool identifier_valid (const char * path)
Check if a identifier is valid.
Parameters
ident The identifier to check
Returns
true if valid, else false
path_join()
char * path_join (char * path, const char * append)
Join two paths by copying the second path to the end of the first path and adding a dot in between. The first string must have enough space to contain the whole path. The validity of the path is not checked.
Parameters
path First part of the path
append Path that should be added to the end of the first path
Returns
path
Definition at line 187 of file fs.c.
{
    u32 len = strlen(path);
    path[len] = ATFS_DIR_SEPARATOR;
    strcpy(path + len + 1, append);
    return path;
}
References ATFS_DIR_SEPARATOR, strcpy(), and strlen().
path_parent()
char * path_parent (char * path)
Remove the last component of the path in place. The validity of the path is not checked.
Parameters
path The path to remove the last part of
Returns
path
Definition at line 195 of file fs.c.
{
    char c, *s, *last_sep;
    last_sep = path;
    for(s = path; (c = *s); ++s)
    {
        if(c == ATFS_DIR_SEPARATOR)
        {
            last_sep = s;
        }
    }
    *last_sep = '\0';
    return path;
}
References ATFS_DIR_SEPARATOR.
path_valid()
bool path_valid (const char * path)
Check if a path is valid.
Parameters
path The path to check
Returns
true if valid, else false
Definition at line 212 of file fs.c.
{
    bool was_sep;
    char c;
    const char *s;
    /* Initialize with true because path may not start with separator */
    was_sep = true;
    for(s = path; (c = *s); ++s)
    {
        if(c == ATFS_DIR_SEPARATOR)
        {
            if(was_sep)
            {
                /* Two separators in a row are not allowed */
                return false;
            }
            was_sep = true;
        }
        else if(isdigit(c))
        {
            if(was_sep)
            {
                /* Path component may not start with a digit */
                return false;
            }
            was_sep = false;
        }
        else if(c == '_' || islower(c))
        {
            was_sep = false;
        }
        else
        {
            /* Invalid character */
            return false;
        }
    }
    /* Path may not end with separator, but allow empty path */
    return !was_sep || *path == '\0';
}
References ATFS_DIR_SEPARATOR, isdigit(), and islower().
Referenced by fs_fopen().