temp/fs/fs.c File Reference
#include fs.h
#include <ctype.h>
#include <string.h>
Functions
static Status disk_size (u32 *size)
Get the size of the disk.
static Status disk_read (u32 block, void *buf)
Read one block from the disk.
static Status disk_write (u32 block, const void *buf)
Write one block to the disk.
static void dir_entry_get (void *buf, DirEntry *entry)
Read directory entry in a endianness-independant way.
static Status _find_entry (const char *name, u32 name_len, u32 block, DirEntry *entry)
Find a directory entry in a directory.
static Status fs_alloc (u32 size, u32 *start)
Allocate size contiguous blocks on disk.
static void fs_free (u32 block, u32 count)
Free count blocks starting at block
char * path_join (char *path, const char *append)
Join two paths by copying the second path to the end of the first path and adding a dot in between. The first string must have enough space to contain the whole path. The validity of the path is not checked.
char * path_parent (char *path)
Remove the last component of the path in place. The validity of the path is not checked.
bool path_valid (const char *path)
Check if a path is valid.
Status fs_fcreate (const char *path, u32 size)
Create a file. If the file already exists, it is resized to the specified size. When a file is resized, all file handles to it are invalidated and need to be reopened.
bool fs_exists (const char *path)
Status fs_format (void)
Status fs_fopen (const char *path, File *file)
Open a file to get a file handle. It is not neccessary to close a file, therefore there is no fs_fclose function.
Status fs_fread (File *file, u32 block, void *buf)
Reads one block from the file.
Status fs_fwrite (File *file, u32 block, const void *buf)
Write one block to the file.
Status fs_delete (const char *path)
Recursively delete a files and directories.
Status fs_rename (const char *dest, const char *src)
Move or rename a file or a directory.
Status fs_copy (const char *dest, const char *src)
Recursively copy files and directories.
Status fs_dopen (const char *path, Dir *dir)
Open a directory.
Status fs_dread (Dir *dir, u32 index, DirEntry *entry)
Read a directory entry.
Variables
static u8 _ramdisk [ATFS_BLOCK_SIZE *128]
Detailed Description
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
03.06.2023
Definition in file fs.c.
Function Documentation
_find_entry()
static Status _find_entry (const char * name, u32 name_len, u32 block, DirEntry * entry) [static]
Find a directory entry in a directory.
Parameters
name
name_len
block
entry
Returns
Status
Definition at line 81 of file fs.c.
{
    u8 buf[ATFS_BLOCK_SIZE];
    u32 i, num_entries, offset;
    RETURN_IF(disk_read(block, buf));
    num_entries = load_le_32(buf + ATFS_DIR_OFFSET_NUM_ENTRIES);
    offset = ATFS_DIR_ENTRY_SIZE;
    for(i = 0; i < num_entries; ++i)
    {
        if(offset == ATFS_BLOCK_SIZE)
        {
            offset = 0;
            ++block;
            RETURN_IF(disk_read(block, buf));
        }
        dir_entry_get(buf + offset, entry);
        /* Compare name with each directory entry */
        if(strlen(entry->Name) == name_len &&
            !strncmp(name, entry->Name, name_len))
        {
            return STATUS_OK;
        }
        offset += ATFS_DIR_ENTRY_SIZE;
    }
    return STATUS_NO_SUCH_FILE_OR_DIR;
}
References ATFS_BLOCK_SIZE, ATFS_DIR_ENTRY_SIZE, ATFS_DIR_OFFSET_NUM_ENTRIES, dir_entry_get(), disk_read(), load_le_32(), DirEntry::Name, RETURN_IF, strlen(), and strncmp().
Referenced by fs_fopen().
dir_entry_get()
static void dir_entry_get (void * buf, DirEntry * entry) [static]
Read directory entry in a endianness-independant way.
Parameters
buf Data buffer
entry Directory entry output
Definition at line 62 of file fs.c.
{
    u8 *buf8 = buf;
    entry->StartBlock = load_le_32(buf8 + ATFS_DIR_ENTRY_OFFSET_START);
    entry->SizeBlocks = load_le_32(buf8 + ATFS_DIR_ENTRY_OFFSET_SIZE);
    memcpy(entry->Name, buf8 + ATFS_DIR_ENTRY_OFFSET_NAME,
        ATFS_MAX_FILE_NAME_LENGTH + 1);
    entry->Type = buf8[ATFS_DIR_ENTRY_OFFSET_TYPE];
}
References ATFS_DIR_ENTRY_OFFSET_NAME, ATFS_DIR_ENTRY_OFFSET_SIZE, ATFS_DIR_ENTRY_OFFSET_START, ATFS_DIR_ENTRY_OFFSET_TYPE, ATFS_MAX_FILE_NAME_LENGTH, load_le_32(), memcpy(), DirEntry::Name, DirEntry::SizeBlocks, DirEntry::StartBlock, and DirEntry::Type.
Referenced by _find_entry(), and fs_dread().
disk_read()
static Status disk_read (u32 block, void * buf) [static]
Read one block from the disk.
Parameters
block Block number to read from
buf Buffer for read data
Returns
Status
Definition at line 35 of file fs.c.
{
    /* TODO: Use system call */
    memcpy(buf, _ramdisk + block * ATFS_BLOCK_SIZE, ATFS_BLOCK_SIZE);
    return STATUS_OK;
}
References _ramdisk, ATFS_BLOCK_SIZE, and memcpy().
Referenced by _find_entry(), fs_alloc(), fs_fopen(), and fs_fread().
disk_size()
static Status disk_size (u32 * size) [static]
Get the size of the disk.
Parameters
size Output parameter for size in blocks
Returns
Status
Definition at line 22 of file fs.c.
{
    *size = sizeof(_ramdisk) / ATFS_BLOCK_SIZE;
    return STATUS_OK;
}
References _ramdisk, and ATFS_BLOCK_SIZE.
disk_write()
static Status disk_write (u32 block, const void * buf) [static]
Write one block to the disk.
Parameters
block Block number to write to
buf Buffer with data to write
Returns
Status
Definition at line 49 of file fs.c.
{
    /* TODO: Use system call */
    memcpy(_ramdisk + block * ATFS_BLOCK_SIZE, buf, ATFS_BLOCK_SIZE);
    return STATUS_OK;
}
References _ramdisk, ATFS_BLOCK_SIZE, and memcpy().
Referenced by fs_alloc(), and fs_fwrite().
fs_alloc()
static Status fs_alloc (u32 size, u32 * start) [static]
Allocate size contiguous blocks on disk.
Parameters
size Number of blocks to allocate
start Output parameter starting block
Returns
Status
Definition at line 121 of file fs.c.
{
    u8 buf[ATFS_BLOCK_SIZE];
    u32 cur, cur_size, prev, next;
    /* Find first area of sufficient size */
    // THIS HAS A BUG !!!
    cur = ATFS_SECTOR_BOOT;
    cur_size = 0;
    next = 1;
    while(next && cur_size < size)
    {
        prev = cur;
        RETURN_IF(disk_read(cur, buf));
        cur = load_le_32(buf + ATFS_FREE_OFFSET_NEXT);
        cur_size = load_le_32(buf + ATFS_FREE_OFFSET_SIZE);
    }
    // --------------------
    if(cur_size < size)
    {
        /* We have searched the entire chain */
        return STATUS_NO_SPACE_LEFT_ON_DEVICE;
    }
    else if(cur_size == size)
    {
        /* Perfect Fit: Make previous area point to next area */
        RETURN_IF(disk_read(prev, buf));
        write_le_32(buf + ATFS_FREE_OFFSET_NEXT, next);
        RETURN_IF(disk_write(prev, buf));
    }
    else /* cur_size > size */
    {
        /* Split area */
        u32 new_start, new_size;
        new_start = cur + size;
        new_size = cur_size - size;
        RETURN_IF(disk_read(prev, buf));
        write_le_32(buf + ATFS_FREE_OFFSET_NEXT, new_start);
        RETURN_IF(disk_write(prev, buf));
        write_le_32(buf + ATFS_FREE_OFFSET_SIZE, new_size);
        write_le_32(buf + ATFS_FREE_OFFSET_NEXT, next);
        RETURN_IF(disk_write(new_start, buf));
    }
    *start = cur;
    return STATUS_OK;
}
References ATFS_BLOCK_SIZE, ATFS_FREE_OFFSET_NEXT, ATFS_FREE_OFFSET_SIZE, ATFS_SECTOR_BOOT, disk_read(), disk_write(), load_le_32(), RETURN_IF, and write_le_32().
Referenced by fs_fcreate().
fs_copy()
Status fs_copy (const char * dest, const char * src)
Recursively copy files and directories.
Parameters
dest Destination path
src Source path
Returns
Status
Definition at line 405 of file fs.c.
{
    return STATUS_OK;
    (void)dest, (void)src;
}
fs_delete()
Status fs_delete (const char * path)
Recursively delete a files and directories.
Parameters
path Path to file
Returns
Status
Definition at line 387 of file fs.c.
{
    return STATUS_OK;
    (void)path;
}
fs_dopen()
Status fs_dopen (const char * path, Dir * dir)
Open a directory.
Parameters
path Path to directory
dir Output parameter directory handle
Returns
Status
Definition at line 411 of file fs.c.
{
    u8 buf[ATFS_BLOCK_SIZE];
    RETURN_IF(fs_fopen(path, &dir->InternalFile));
    RETURN_IF(fs_fread(&dir->InternalFile, 0, buf));
    dir->NumEntries = load_le_32(buf);
    return STATUS_OK;
}
References ATFS_BLOCK_SIZE, fs_fopen(), fs_fread(), Dir::InternalFile, load_le_32(), Dir::NumEntries, and RETURN_IF.
fs_dread()
Status fs_dread (Dir * dir, u32 index, DirEntry * entry)
Read a directory entry.
Parameters
dir Directory handle
index File index
entry Output parameter directory entry
Returns
Status
Definition at line 421 of file fs.c.
{
    u8 buf[ATFS_BLOCK_SIZE];
    u32 offset, block;
    if(index >= dir->NumEntries)
    {
        return STATUS_OUT_OF_BOUNDS;
    }
    /* Add one because the first directory entry is reserved for metadata */
    offset = (index + 1) * ATFS_DIR_ENTRY_SIZE;
    block = offset / ATFS_BLOCK_SIZE;
    offset -= block * ATFS_BLOCK_SIZE;
    RETURN_IF(fs_fread(&dir->InternalFile, block, buf));
    dir_entry_get(buf + offset, entry);
    return STATUS_OK;
}
References ATFS_BLOCK_SIZE, ATFS_DIR_ENTRY_SIZE, dir_entry_get(), fs_fread(), Dir::InternalFile, Dir::NumEntries, and RETURN_IF.
fs_exists()
bool fs_exists (const char * path)
Definition at line 278 of file fs.c.
{
    File f;
    return fs_fopen(path, &f);
}
fs_fcreate()
Status fs_fcreate (const char * path, u32 size)
Create a file. If the file already exists, it is resized to the specified size. When a file is resized, all file handles to it are invalidated and need to be reopened.
Parameters
path Path to file
size Capacity of the file in blocks
Returns
Status
Definition at line 257 of file fs.c.
{
    #ifdef AAA
    Dir dir;
    DirEntry entry;
    if(_traverse(path, &dir))
    {
        u32 start;
        /* New file */
        RETURN_IF(fs_alloc(size, &start));
    }
    else if(file.SizeBlocks != size)
    {
        /* TODO: Resize file */
    }
    #endif
    return STATUS_OK;
}
References fs_alloc(), and RETURN_IF.
fs_fopen()
Status fs_fopen (const char * path, File * file)
Open a file to get a file handle. It is not neccessary to close a file, therefore there is no fs_fclose function.
Parameters
path Path to file
file Output parameter file handle
Returns
Status
Definition at line 317 of file fs.c.
{
    u8 buf[ATFS_BLOCK_SIZE];
    DirEntry entry;
    const char *s, *name;
    char c;
    u32 name_len;
    /* Check path format beforehand for simplicity */
    if(!path_valid(path))
    {
        return STATUS_PATH_FORMAT_INVALID;
    }
    /* Traverse directory structure starting in root directory */
    RETURN_IF(disk_read(ATFS_SECTOR_BOOT, buf));
    entry.StartBlock = load_le_32(buf + ATFS_OFFSET_ROOT_BLOCK);
    entry.SizeBlocks = load_le_32(buf + ATFS_OFFSET_ROOT_SIZE);
    s = path;
    while(*s)
    {
        /* Get next part of path string */
        name = s;
        for(; (c = *s) && c != ATFS_DIR_SEPARATOR; ++s) {}
        name_len = s - name;
        /* Search current directory */
        RETURN_IF(_find_entry(name, name_len, entry.StartBlock, &entry));
        /* If in the middle of a path */
        if(!*s)
        {
            /* Skip directory separator */
            ++s;
            /* Found entry must be a directory */
            if(entry.Type)
            {
                return STATUS_NO_SUCH_FILE_OR_DIR;
            }
        }
    }
    /* Entry was found */
    file->StartBlock = entry.StartBlock;
    file->SizeBlocks = entry.SizeBlocks;
    return STATUS_OK;
}
References _find_entry(), ATFS_BLOCK_SIZE, ATFS_DIR_SEPARATOR, ATFS_OFFSET_ROOT_BLOCK, ATFS_OFFSET_ROOT_SIZE, ATFS_SECTOR_BOOT, disk_read(), load_le_32(), path_valid(), RETURN_IF, File::SizeBlocks, DirEntry::SizeBlocks, File::StartBlock, DirEntry::StartBlock, and DirEntry::Type.
Referenced by fs_dopen().
fs_format()
Status fs_format (void)
Definition at line 284 of file fs.c.
{
    u32 size;
    u8 buf[ATFS_BLOCK_SIZE];
    RETURN_IF(disk_size(&size));
    /* Boot Sector */
    memcpy(buf + ATFS_OFFSET_SIGNATURE, _atfs_signature,
        sizeof(_atfs_signature));
    write_le_32(buf + ATFS_OFFSET_REVISION, ATFS_REVISION);
    write_le_32(buf + ATFS_OFFSET_INIT_BLOCK, 0);
    write_le_32(buf + ATFS_OFFSET_INIT_SIZE, 0);
    write_le_32(buf + ATFS_OFFSET_ROOT_BLOCK, 1);
    write_le_32(buf + ATFS_OFFSET_ROOT_SIZE, 1);
    write_le_32(buf + ATFS_FREE_OFFSET_NEXT, 2);
    write_le_32(buf + ATFS_FREE_OFFSET_SIZE, 0);
    RETURN_IF(disk_write(ATFS_SECTOR_BOOT, buf));
    /* Root Dir */
    memset(buf, 0, ATFS_BLOCK_SIZE);
    RETURN_IF(disk_write(1, buf));
    /* Free List */
    write_le_32(buf + ATFS_FREE_OFFSET_NEXT, 0);
    write_le_32(buf + ATFS_FREE_OFFSET_SIZE, size - 2);
    RETURN_IF(disk_write(2, buf));
    return STATUS_OK;
}
fs_fread()
Status fs_fread (File * file, u32 block, void * buf)
Reads one block from the file.
Parameters
file File handle
block The block to read
buf Buffer for read data (512 bytes)
Returns
Status
Definition at line 366 of file fs.c.
{
    if(block >= file->SizeBlocks)
    {
        return STATUS_OUT_OF_BOUNDS;
    }
    return disk_read(file->StartBlock + block, buf);
}
References disk_read(), File::SizeBlocks, and File::StartBlock.
Referenced by fs_dopen(), and fs_dread().
fs_free()
static void fs_free (u32 block, u32 count) [static]
Free count blocks starting at block
Parameters
block Start block
count Number of blocks to free
Definition at line 180 of file fs.c.
{
    /* TODO: Implement this */
    (void)block, (void)count;
}
fs_fwrite()
Status fs_fwrite (File * file, u32 block, const void * buf)
Write one block to the file.
Parameters
file File handle
block The block to write
buf Buffer with data to write (512 bytes)
Returns
Status
Definition at line 376 of file fs.c.
{
    if(block >= file->SizeBlocks)
    {
        return STATUS_OUT_OF_BOUNDS;
    }
    return disk_write(file->StartBlock + block, buf);
}
References disk_write(), File::SizeBlocks, and File::StartBlock.
fs_rename()
Status fs_rename (const char * dest, const char * src)
Move or rename a file or a directory.
Parameters
dest Destination path
src Source path
Returns
Status
Definition at line 394 of file fs.c.
{
    /* Create new directory entries */
    /* Delete old directory entries */
    return STATUS_OK;
    (void)dest, (void)src;
}
path_join()
char * path_join (char * path, const char * append)
Join two paths by copying the second path to the end of the first path and adding a dot in between. The first string must have enough space to contain the whole path. The validity of the path is not checked.
Parameters
path First part of the path
append Path that should be added to the end of the first path
Returns
path
Definition at line 187 of file fs.c.
{
    u32 len = strlen(path);
    path[len] = ATFS_DIR_SEPARATOR;
    strcpy(path + len + 1, append);
    return path;
}
References ATFS_DIR_SEPARATOR, strcpy(), and strlen().
path_parent()
char * path_parent (char * path)
Remove the last component of the path in place. The validity of the path is not checked.
Parameters
path The path to remove the last part of
Returns
path
Definition at line 195 of file fs.c.
{
    char c, *s, *last_sep;
    last_sep = path;
    for(s = path; (c = *s); ++s)
    {
        if(c == ATFS_DIR_SEPARATOR)
        {
            last_sep = s;
        }
    }
    *last_sep = '\0';
    return path;
}
References ATFS_DIR_SEPARATOR.
path_valid()
bool path_valid (const char * path)
Check if a path is valid.
Parameters
path The path to check
Returns
true if valid, else false
Definition at line 212 of file fs.c.
{
    bool was_sep;
    char c;
    const char *s;
    /* Initialize with true because path may not start with separator */
    was_sep = true;
    for(s = path; (c = *s); ++s)
    {
        if(c == ATFS_DIR_SEPARATOR)
        {
            if(was_sep)
            {
                /* Two separators in a row are not allowed */
                return false;
            }
            was_sep = true;
        }
        else if(isdigit(c))
        {
            if(was_sep)
            {
                /* Path component may not start with a digit */
                return false;
            }
            was_sep = false;
        }
        else if(c == '_' || islower(c))
        {
            was_sep = false;
        }
        else
        {
            /* Invalid character */
            return false;
        }
    }
    /* Path may not end with separator, but allow empty path */
    return !was_sep || *path == '\0';
}
References ATFS_DIR_SEPARATOR, isdigit(), and islower().
Referenced by fs_fopen().
Variable Documentation
_ramdisk
u8 _ramdisk[ATFS_BLOCK_SIZE *128] [static]
For testing
Definition at line 13 of file fs.c.
Referenced by disk_read(), disk_size(), and disk_write().