stdlib/gfx/gfx.h File Reference
Basic Graphics Functions.
#include <types.h>
#include <colors.h>
#include <gfx-types.h>
Functions
static Color gfx_color (i32 r, i32 g, i32 b, i32 a)
Create a color from R, G, B, A values.
void gfx_rect (i32 x, i32 y, i32 w, i32 h, Color color)
Draws a rectangle from position (x|y), w pixels to left and h pixels down.
static void gfx_vline (i32 x, i32 y, i32 h, Color color)
Draws a 1 pixel wide vertical line.
static void gfx_hline (i32 x, i32 y, i32 w, Color color)
Draws a 1 pixel tall horizontal line.
void gfx_rect_border (i32 x, i32 y, i32 w, i32 h, i32 border, Color color)
Draws a rectangular frame.
void gfx_image_rgba (i32 x, i32 y, i32 w, i32 h, const u8 *data)
Draws an image in RGBA format.
void gfx_image_rgb (i32 x, i32 y, i32 w, i32 h, const u8 *data)
Draws an image in RGB format.
void gfx_image_rgb565 (i32 x, i32 y, i32 w, i32 h, const u8 *data)
Draws an image in RGB565 format.
void gfx_image_grayscale (i32 x, i32 y, i32 w, i32 h, const u8 *data, Color fg, Color bg)
Draws a grayscale image. The color of each pixel is a mix of the foreground and background colors where the ratio depends on the grayscale value.
void gfx_image_1bit (i32 x, i32 y, i32 w, i32 h, const u8 *data, Color fg, Color bg)
Draws a 1-bit-per-pixel image. Every image row starts at a new byte.
Detailed Description
Basic Graphics Functions.
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
23.04.2023
Definition in file gfx.h.
Function Documentation
gfx_color()
static Color gfx_color (i32 r, i32 g, i32 b, i32 a) [inline], [static]
Create a color from R, G, B, A values.
Parameters
r Red channel (0-255)
g Green channel (0-255)
b Blue channel (0-255)
a Alpha channel (0-255)
Returns
Color value
Definition at line 25 of file gfx.h.
{
    return a | (b << 8) | (g << 16) | (r << 24);
}
gfx_hline()
static void gfx_hline (i32 x, i32 y, i32 w, Color color) [inline], [static]
Draws a 1 pixel tall horizontal line.
Parameters
x Starting X-Coordinate (Left)
y Starting Y-Coordinate (Top)
w Length of the line
color Color from gfx_color or color.h
Definition at line 63 of file gfx.h.
{
    gfx_rect(x, y, w, 1, color);
}
References gfx_rect().
gfx_image_1bit()
void gfx_image_1bit (i32 x, i32 y, i32 w, i32 h, const u8 * data, Color fg, Color bg)
Draws a 1-bit-per-pixel image. Every image row starts at a new byte.
Parameters
x X-Coordinate (Left)
y Y-Coordinate (Top)
w Width
h Height
data Pixel data (1 bit per pixel)
fg Foreground color (bit 1)
bg Background color (bit 0)
Definition at line 47 of file gfx.c.
{
    volatile Rectangle rect = { x, y, w, h };
    syscall4(SYSCALL_GFX_IMAGE_1BIT, (u32)&rect, (u32)data, fg, bg);
}
References syscall4().
Referenced by font_string_len().
gfx_image_grayscale()
void gfx_image_grayscale (i32 x, i32 y, i32 w, i32 h, const u8 * data, Color fg, Color bg)
Draws a grayscale image. The color of each pixel is a mix of the foreground and background colors where the ratio depends on the grayscale value.
Parameters
x X-Coordinate (Left)
y Y-Coordinate (Top)
w Width
h Height
data Pixel data (8 bit per pixel)
fg Foreground color
bg Background color
Definition at line 40 of file gfx.c.
{
    volatile Rectangle rect = { x, y, w, h };
    syscall4(SYSCALL_GFX_IMAGE_GRAYSCALE, (u32)&rect, (u32)data, fg, bg);
}
References syscall4().
Referenced by font_string_len().
gfx_image_rgb()
void gfx_image_rgb (i32 x, i32 y, i32 w, i32 h, const u8 * data)
Draws an image in RGB format.
Parameters
x X-Coordinate (Left)
y Y-Coordinate (Top)
w Width
h Height
data Pixel data (24 bits per pixel)
Definition at line 30 of file gfx.c.
{
    syscall5(SYSCALL_GFX_IMAGE_RGB, x, y, w, h, (u32)data);
}
References syscall5().
Referenced by setup().
gfx_image_rgb565()
void gfx_image_rgb565 (i32 x, i32 y, i32 w, i32 h, const u8 * data)
Draws an image in RGB565 format.
Parameters
x X-Coordinate (Left)
y Y-Coordinate (Top)
w Width
h Height
data Pixel data (16 bit per pixel)
Definition at line 35 of file gfx.c.
{
    syscall5(SYSCALL_GFX_IMAGE_RGB565, x, y, w, h, (u32)data);
}
References syscall5().
gfx_image_rgba()
void gfx_image_rgba (i32 x, i32 y, i32 w, i32 h, const u8 * data)
Draws an image in RGBA format.
Parameters
x X-Coordinate (Left)
y Y-Coordinate (Top)
w Width
h Height
data Pixel data (32 bits per pixel)
Definition at line 25 of file gfx.c.
{
    syscall5(SYSCALL_GFX_IMAGE_RGBA, x, y, w, h, (u32)data);
}
References syscall5().
gfx_rect()
void gfx_rect (i32 x, i32 y, i32 w, i32 h, Color color)
Draws a rectangle from position (x|y), w pixels to left and h pixels down.
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h Height
color Color from gfx_color or color.h
Definition at line 11 of file gfx.c.
{
    syscall5(SYSCALL_GFX_RECT, x, y, w, h, color);
}
References syscall5().
Referenced by _draw_field(), _draw_grid(), _draw_line_numbers(), button_render(), gfx_hline(), gfx_rect_border(), gfx_vline(), input_render(), label_render(), setup(), and window_render().
gfx_rect_border()
void gfx_rect_border (i32 x, i32 y, i32 w, i32 h, i32 border, Color color)
Draws a rectangular frame.
Parameters
x X-Coordinate (Left)
y Y-Coordinate (Top)
w Width
h Height
border Inset border width in pixels
color Color of the border
Definition at line 16 of file gfx.c.
{
    gfx_rect(x, y, w, border, color);
    gfx_rect(x, y + h - border, w, border, color);
    gfx_rect(x, y + border, border, h - 2 * border, color);
    gfx_rect(x + w - border, y + border, border, h - 2 * border, color);
}
References gfx_rect().
Referenced by button_render(), and input_render().
gfx_vline()
static void gfx_vline (i32 x, i32 y, i32 h, Color color) [inline], [static]
Draws a 1 pixel wide vertical line.
Parameters
x Starting X-Coordinate (Left)
y Starting Y-Coordinate (Top)
h Length of the line
color Color from gfx_color or color.h
Definition at line 50 of file gfx.h.
{
    gfx_rect(x, y, 1, h, color);
}
References gfx_rect().