stdlib/gui/gui.h File Reference
Graphical User Interface Toolkit.
#include <vector.h>
#include <types.h>
#include <keyboard.h>
#include <gfx.h>
Data Structures
struct Label
struct Button
struct Input
struct Theme
struct Window
Macros
#define ALIGN_MASK 0x03
#define FLAG_ALIGN_LEFT 0x00
#define FLAG_ALIGN_CENTER 0x01
#define FLAG_ALIGN_RIGHT 0x02
#define FLAG_LINE_NUMBERS 0x04
#define FLAG_SYNTAX_HIGHLIGHT 0x08
#define FLAG_PASSWORD 0x10
#define FLAG_INVERTED 0x20
#define FLAG_INVISIBLE 0x40
#define THEME_BLACK 0x0F0000FF
#define THEME_DARK 0x2F0000FF
#define THEME_MIDDLE 0x4F0000FF
#define THEME_LIGHT 0xFF8000FF
Enumerations
enum ElementType { ELEMENT_TYPE_BUTTON
, ELEMENT_TYPE_INPUT
, ELEMENT_TYPE_LABEL
 }
Functions
void window_open (Window *window)
Open and render a window.
void window_event_key (Key key, i32 chr, KeyState state)
Forward a key event to the currently open window.
void window_init (Window *window, char *title, void *elems, i32 count, KeyEvent onkey)
Initialize a window.
void label_init (Label *label, i32 x, i32 y, u32 flags, char *text)
Initialize a label.
void label_show (Label *label, bool show)
Hide/Show a label.
void button_init (Button *button, i32 x, i32 y, i32 w, i32 h, char *text, void(*onclick)(void))
Initialize a button.
void input_init (Input *input, i32 x, i32 y, i32 w)
Initialize an input field.
void input_clear (Input *i)
Clear an input field.
void element_render (void *e)
Render an element by taking its selection status from the current window.
void theme_set (Theme *theme)
Set the current GUI Theme.
void theme_default (void)
Reset the current GUI Theme to default values.
Detailed Description
Graphical User Interface Toolkit.
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
23.04.2023
Definition in file gui.h.
Macro Definition Documentation
ALIGN_MASK
#define ALIGN_MASK 0x03
Align bitmask
Definition at line 26 of file gui.h.
FLAG_ALIGN_CENTER
#define FLAG_ALIGN_CENTER 0x01
Center align
Definition at line 32 of file gui.h.
FLAG_ALIGN_LEFT
#define FLAG_ALIGN_LEFT 0x00
Left align (default)
Definition at line 29 of file gui.h.
FLAG_ALIGN_RIGHT
#define FLAG_ALIGN_RIGHT 0x02
Right align
Definition at line 35 of file gui.h.
FLAG_INVERTED
#define FLAG_INVERTED 0x20
Invert label foreground and background colors
Definition at line 47 of file gui.h.
FLAG_INVISIBLE
#define FLAG_INVISIBLE 0x40
Element visibility state
Definition at line 50 of file gui.h.
FLAG_LINE_NUMBERS
#define FLAG_LINE_NUMBERS 0x04
Enable/Disable Line numbers in input field
Definition at line 38 of file gui.h.
FLAG_PASSWORD
#define FLAG_PASSWORD 0x10
Display content as stars in input field
Definition at line 44 of file gui.h.
FLAG_SYNTAX_HIGHLIGHT
#define FLAG_SYNTAX_HIGHLIGHT 0x08
Enable/Disable Syntax highlighting in input field
Definition at line 41 of file gui.h.
THEME_BLACK
#define THEME_BLACK 0x0F0000FF
Theme Black Color
Definition at line 55 of file gui.h.
THEME_DARK
#define THEME_DARK 0x2F0000FF
Theme Dark Color
Definition at line 58 of file gui.h.
THEME_LIGHT
#define THEME_LIGHT 0xFF8000FF
Theme Light Color
Definition at line 64 of file gui.h.
THEME_MIDDLE
#define THEME_MIDDLE 0x4F0000FF
Theme Middle Color
Definition at line 61 of file gui.h.
Enumeration Type Documentation
ElementType
enum ElementType
Element type
Definition at line 18 of file gui.h.
{
    ELEMENT_TYPE_BUTTON,
    ELEMENT_TYPE_INPUT,
    ELEMENT_TYPE_LABEL
} ElementType;
Function Documentation
button_init()
void button_init (Button * button, i32 x, i32 y, i32 w, i32 h, char * text, void(*)(void) onclick)
Initialize a button.
Parameters
button The button
x X-Coordinate
y Y-Coordinate
w Width
h Height
text Button text
onclick Click event
Definition at line 867 of file gui.c.
{
    button->Type = ELEMENT_TYPE_BUTTON;
    button->X = x;
    button->Y = y;
    button->W = w;
    button->H = h;
    button->Text = text;
    button->Click = onclick;
}
References Button::Click, Button::H, Button::Text, Button::Type, Button::W, Button::X, and Button::Y.
Referenced by setup().
element_render()
void element_render (void * e)
Render an element by taking its selection status from the current window.
Parameters
e Pointer to the Element
Definition at line 651 of file gui.c.
{
    element_render_sel(e, _current_window->Selected >= 0 &&
                              _current_window->Elements[_current_window->Selected] == e);
}
References _current_window, element_render_sel(), Window::Elements, and Window::Selected.
Referenced by window_render().
input_clear()
void input_clear (Input * i)
Clear an input field.
Parameters
i The input field
Definition at line 294 of file gui.c.
{
    vector_clear(&i->Text);
    input_render(i, true);
}
References input_render(), and vector_clear().
input_init()
void input_init (Input * input, i32 x, i32 y, i32 w)
Initialize an input field.
Parameters
input The input field
x X-Coordinate
y Y-Coordinate
w Width
Definition at line 879 of file gui.c.
{
    input->Type = ELEMENT_TYPE_INPUT;
    input->X = x;
    input->Y = y;
    input->W = w;
    input->Position = 0;
    input->Selection = 0;
    vector_init(&input->Text, sizeof(char), INPUT_CAPACITY);
}
References INPUT_CAPACITY, Input::Position, Input::Selection, Input::Text, Input::Type, vector_init(), Input::W, Input::X, and Input::Y.
Referenced by setup().
label_init()
void label_init (Label * label, i32 x, i32 y, u32 flags, char * text)
Initialize a label.
Parameters
label The label
x X-Coordinate
y Y-Coordinate
flags Label flags
text Label text
Definition at line 858 of file gui.c.
{
    label->Type = ELEMENT_TYPE_LABEL;
    label->X = x;
    label->Y = y;
    label->Flags = flags;
    label->Text = text;
}
References Label::Flags, Label::Text, Label::Type, Label::X, and Label::Y.
Referenced by setup().
label_show()
void label_show (Label * label, bool show)
Hide/Show a label.
Parameters
label Pointer to the label
show true to show, false to hide
Definition at line 900 of file gui.c.
{
    if ((show && (label->Flags & FLAG_INVISIBLE)) ||
        (!show && !(label->Flags & FLAG_INVISIBLE)))
    {
        label->Flags ^= FLAG_INVISIBLE;
        label_render(label);
    }
}
References FLAG_INVISIBLE, Label::Flags, and label_render().
Referenced by _hide_error(), _show_error(), and loop().
theme_default()
void theme_default (void)
Reset the current GUI Theme to default values.
Definition at line 895 of file gui.c.
{
    _current_theme = &_default_theme;
}
References _current_theme, and _default_theme.
theme_set()
void theme_set (Theme * theme)
Set the current GUI Theme.
Parameters
theme Pointer to new theme
Definition at line 890 of file gui.c.
{
    _current_theme = theme;
}
References _current_theme.
window_event_key()
void window_event_key (Key key, i32 chr, KeyState state)
Forward a key event to the currently open window.
Parameters
key Key code
chr Character for key code
state Key State
Definition at line 795 of file gui.c.
{
    void *ce;
    if (!_current_window)
    {
        return;
    }
    if (_current_window->OnKey)
    {
        _current_window->OnKey(key, chr, state);
    }
    if (_current_window->Selected < 0)
    {
        return;
    }
    if (state == KEYSTATE_RELEASED)
    {
        return;
    }
    ce = _current_window->Elements[_current_window->Selected];
    if (key == KEY_TAB)
    {
        element_next();
    }
    else if (key == (KEY_TAB | MOD_SHIFT))
    {
        element_prev();
    }
    else
    {
        ElementType type = ((Element *)ce)->Type;
        if (type == ELEMENT_TYPE_BUTTON)
        {
            if (key == KEY_RETURN)
            {
                Button *b = ce;
                if (b->Click)
                {
                    b->Click();
                }
            }
        }
        else if (type == ELEMENT_TYPE_INPUT)
        {
            input_event_key((Input *)ce, key, chr);
        }
    }
}
References _current_window, Button::Click, element_next(), element_prev(), Window::Elements, input_event_key(), Window::OnKey, and Window::Selected.
Referenced by event_key().
window_init()
void window_init (Window * window, char * title, void * elems, i32 count, KeyEvent onkey)
Initialize a window.
Parameters
window The window
title Window title
elems Pointer to elements array
count Number of elements
onkey Key event
Definition at line 848 of file gui.c.
{
    window->Selected = -1;
    window->Title = title;
    window->Elements = elems;
    window->Count = count;
    window->OnKey = onkey;
}
References Window::Count, Window::Elements, Window::OnKey, Window::Selected, and Window::Title.
Referenced by setup().
window_open()
void window_open (Window * window)
Open and render a window.
Parameters
window Pointer to Window structure
Definition at line 784 of file gui.c.
{
    _current_window = window;
    if (window->Selected < 0)
    {
        element_first();
    }
    window_render(window);
}
References _current_window, element_first(), Window::Selected, and window_render().
Referenced by button_login_onclick(), and setup().