stdlib/gui/gui.c File Reference
#include <gui.h>
#include <gfx.h>
#include <font.h>
#include <colors.h>
#include <font_default.h>
#include <ctype.h>
#include <utf8.h>
#include <clipboard.h>
Data Structures
struct Element
Macros
#define TITLE_OFFSET_X 4
#define TITLE_OFFSET_Y 4
#define BORDER_SIZE 1
#define BORDER_SIZE_SEL 2
#define INPUT_HEIGHT 24
#define INPUT_PADDING_X 6
#define INPUT_PADDING_Y 7
#define CURSOR_WIDTH 1
#define CURSOR_HEIGHT 14
#define CURSOR_OFFSET -1
#define CURSOR_OFFSET_Y 5
#define INPUT_CAPACITY 16
#define LABEL_Y_PADDING 3
#define LABEL_X_PADDING 10
Functions
static void label_render (Label *l)
Render a label on the screen.
static void button_render (Button *b, bool sel)
Renders an button on the screen.
static const char * _input_get_display_text (Input *i)
Get the text to display when an input is rendered.
static void input_render (Input *i, bool sel)
Renders an input field on the screen.
void input_clear (Input *i)
Clear an input field.
static void input_selection_replace (Input *i, const char *str, i32 len)
Inserts a string into an input field's buffer at the current cursor position, replacing the current selection.
static void input_left (Input *i)
Move input cursor one position to the left and render input.
static void input_select_left (Input *i)
Move the cursor one position to the left and select.
static void input_right (Input *i)
Move input cursor one position to the right and render input.
static void input_select_right (Input *i)
Move the cursor one position to the right and select.
static void input_backspace (Input *i)
Delete the character before the cursor.
static void input_delete (Input *i)
Delete the character after the cursor.
static void input_home (Input *i)
Move the cursor to the beginning of the input field.
static void input_select_home (Input *i)
Select the characters from the current cursor position to the beginning.
static void input_end (Input *i)
Move the cursor to the end of the input field.
static void input_select_end (Input *i)
Select the characters from the current cursor position to the end.
static void input_char (Input *i, i32 chr)
Insert a character at the cursor position.
static void input_select_all (Input *i)
Do a CTRL+A select all operation on an input field.
static void _selection_save (Input *i)
Save the current selection of an input to the clipboard.
static void input_copy (Input *i)
Do a CTRL+C copy operation on an input field.
static void input_cut (Input *i)
Do a CTRL+X cut operation on an input field.
static void input_paste (Input *i)
Do a CTRL+V paste operation on an input field.
static void input_event_key (Input *i, Key key, i32 chr)
Forward a key event to an input field.
static void element_render_sel (Element *e, u32 sel)
Render an element based on its type and selection status.
void element_render (void *e)
Render an element by taking its selection status from the current window.
static bool _selectable (i32 index)
Checks if an element can be selected.
static void _select (i32 index)
Selects the element.
static void element_first (void)
Select the first element.
static void element_next (void)
Select the next element.
static void element_prev (void)
Select the previous element.
static void window_render (Window *window)
Draw a window.
void window_open (Window *window)
Open and render a window.
void window_event_key (Key key, i32 chr, KeyState state)
Forward a key event to the currently open window.
void window_init (Window *window, char *title, void *elems, i32 count, KeyEvent onkey)
Initialize a window.
void label_init (Label *label, i32 x, i32 y, u32 flags, char *text)
Initialize a label.
void button_init (Button *button, i32 x, i32 y, i32 w, i32 h, char *text, void(*onclick)(void))
Initialize a button.
void input_init (Input *input, i32 x, i32 y, i32 w)
Initialize an input field.
void theme_set (Theme *theme)
Set the current GUI Theme.
void theme_default (void)
Reset the current GUI Theme to default values.
void label_show (Label *label, bool show)
Hide/Show a label.
Variables
static Window * _current_window
static Theme _default_theme
static Theme * _current_theme = &_default_theme
Detailed Description
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
23.04.2023
Definition in file gui.c.
Macro Definition Documentation
BORDER_SIZE
#define BORDER_SIZE 1
Border width when not selected
Definition at line 24 of file gui.c.
BORDER_SIZE_SEL
#define BORDER_SIZE_SEL 2
Border width when selected
Definition at line 27 of file gui.c.
CURSOR_HEIGHT
#define CURSOR_HEIGHT 14
Input field cursor height
Definition at line 44 of file gui.c.
CURSOR_OFFSET
#define CURSOR_OFFSET -1
Input field cursor X offset
Definition at line 47 of file gui.c.
CURSOR_OFFSET_Y
#define CURSOR_OFFSET_Y 5
Input field cursor Y offset
Definition at line 50 of file gui.c.
CURSOR_WIDTH
#define CURSOR_WIDTH 1
Input field cursor width
Definition at line 41 of file gui.c.
INPUT_CAPACITY
#define INPUT_CAPACITY 16
Input field initial capacity
Definition at line 53 of file gui.c.
INPUT_HEIGHT
#define INPUT_HEIGHT 24
Height of an input field
Definition at line 32 of file gui.c.
INPUT_PADDING_X
#define INPUT_PADDING_X 6
Input field text X padding
Definition at line 35 of file gui.c.
INPUT_PADDING_Y
#define INPUT_PADDING_Y 7
Input field text Y padding
Definition at line 38 of file gui.c.
LABEL_X_PADDING
#define LABEL_X_PADDING 10
Label padding in x direction in inverted mode on each side
Definition at line 61 of file gui.c.
LABEL_Y_PADDING
#define LABEL_Y_PADDING 3
Label padding in y direction in inverted mode on each side
Definition at line 58 of file gui.c.
TITLE_OFFSET_X
#define TITLE_OFFSET_X 4
Title bar text left offset
Definition at line 18 of file gui.c.
TITLE_OFFSET_Y
#define TITLE_OFFSET_Y 4
Title bar text top offset
Definition at line 21 of file gui.c.
Function Documentation
_input_get_display_text()
static const char * _input_get_display_text (Input * i) [static]
Get the text to display when an input is rendered.
Parameters
i The input
Returns
Input content or password stars
Definition at line 200 of file gui.c.
{
    static const char _password_stars[] = "***********************************";
    return i->Flags & FLAG_PASSWORD ? _password_stars : vector_data(&i->Text);
}
References FLAG_PASSWORD, and vector_data().
Referenced by input_render(), and input_selection_replace().
_select()
static void _select (i32 index) [static]
Selects the element.
Parameters
index Element index
Definition at line 683 of file gui.c.
{
    void **elems = _current_window->Elements;
    element_render_sel(elems[_current_window->Selected], false);
    _current_window->Selected = index;
    element_render_sel(elems[_current_window->Selected], true);
}
References _current_window, element_render_sel(), Window::Elements, and Window::Selected.
Referenced by element_next(), and element_prev().
_selectable()
static bool _selectable (i32 index) [static]
Checks if an element can be selected.
Parameters
index Element index
Returns
Boolean true if the element is selectable
Definition at line 671 of file gui.c.
{
    ElementType type = ((Element *)_current_window->Elements[index])->Type;
    return type == ELEMENT_TYPE_BUTTON ||
           type == ELEMENT_TYPE_INPUT;
}
References _current_window, and Window::Elements.
Referenced by element_first(), element_next(), and element_prev().
_selection_save()
static void _selection_save (Input * i) [static]
Save the current selection of an input to the clipboard.
Parameters
i Pointer to the input structure
Definition at line 522 of file gui.c.
{
    i32 sel_start, sel_len;
    sel_start = i32_min(i->Selection, i->Position);
    sel_len = i32_max(i->Selection, i->Position) - sel_start;
    clipboard_save_text_len(vector_get(&i->Text, sel_start), sel_len);
}
References clipboard_save_text_len(), i32_max(), i32_min(), and vector_get().
Referenced by input_copy(), and input_cut().
button_init()
void button_init (Button * button, i32 x, i32 y, i32 w, i32 h, char * text, void(*)(void) onclick)
Initialize a button.
Parameters
button The button
x X-Coordinate
y Y-Coordinate
w Width
h Height
text Button text
onclick Click event
Definition at line 875 of file gui.c.
{
    button->Type = ELEMENT_TYPE_BUTTON;
    button->X = x;
    button->Y = y;
    button->W = w;
    button->H = h;
    button->Text = text;
    button->Click = onclick;
}
References Button::Click, Button::H, Button::Text, Button::Type, Button::W, Button::X, and Button::Y.
Referenced by setup().
button_render()
static void button_render (Button * b, bool sel) [static]
Renders an button on the screen.
Parameters
b Pointer to the button structure
sel A boolean value indicating if the input field is selected or not
Definition at line 163 of file gui.c.
{
    Color inner_color;
    i32 x, y;
    y = TITLE_BAR_HEIGHT + b->Y;
    inner_color = sel ? _current_theme->ElementSelBG : _current_theme->ElementBG;
    gfx_rect(b->X, y, b->W, b->H, inner_color);
    if (sel)
    {
        gfx_rect_border(b->X, y, b->W, b->H, BORDER_SIZE_SEL,
                        _current_theme->ColorBorderSel);
    }
    else
    {
        gfx_rect_border(b->X, y, b->W, b->H, BORDER_SIZE,
                        _current_theme->ColorBorder);
    }
    x = b->X + b->W / 2 - font_string_width(b->Text, font_default) / 2;
    font_string(x, y + b->H / 2 - 5,
                b->Text, font_default,
                _current_theme->ColorFG,
                inner_color);
}
References _current_theme, BORDER_SIZE, BORDER_SIZE_SEL, Theme::ColorBorder, Theme::ColorBorderSel, Theme::ColorFG, Theme::ElementBG, Theme::ElementSelBG, font_string(), font_string_width(), gfx_rect(), gfx_rect_border(), Button::H, Button::Text, TITLE_BAR_HEIGHT, Button::W, Button::X, and Button::Y.
Referenced by element_render_sel().
element_first()
static void element_first (void) [static]
Select the first element.
Definition at line 694 of file gui.c.
{
    i32 i, count = _current_window->Count;
    for (i = 0; i < count; ++i)
    {
        if (_selectable(i))
        {
            _current_window->Selected = i;
            break;
        }
    }
}
References _current_window, _selectable(), Window::Count, and Window::Selected.
Referenced by window_open().
element_next()
static void element_next (void) [static]
Select the next element.
Definition at line 710 of file gui.c.
{
    i32 i, count = _current_window->Count;
    for (i = _current_window->Selected + 1; i < count; ++i)
    {
        if (_selectable(i))
        {
            _select(i);
            return;
        }
    }
    /* Wrap around */
    for (i = 0; i < count; ++i)
    {
        if (_selectable(i))
        {
            _select(i);
            return;
        }
    }
}
References _current_window, _select(), _selectable(), Window::Count, and Window::Selected.
Referenced by window_event_key().
element_prev()
static void element_prev (void) [static]
Select the previous element.
Definition at line 736 of file gui.c.
{
    i32 i;
    for (i = _current_window->Selected - 1; i >= 0; --i)
    {
        if (_selectable(i))
        {
            _select(i);
            return;
        }
    }
    /* Wrap around */
    for (i = _current_window->Count - 1; i >= 0; --i)
    {
        if (_selectable(i))
        {
            _select(i);
            return;
        }
    }
}
References _current_window, _select(), _selectable(), Window::Count, and Window::Selected.
Referenced by window_event_key().
element_render()
void element_render (void * e)
Render an element by taking its selection status from the current window.
Parameters
e Pointer to the Element
Definition at line 659 of file gui.c.
{
    element_render_sel(e, _current_window->Selected >= 0 &&
                              _current_window->Elements[_current_window->Selected] == e);
}
References _current_window, element_render_sel(), Window::Elements, and Window::Selected.
Referenced by window_render().
element_render_sel()
static void element_render_sel (Element * e, u32 sel) [static]
Render an element based on its type and selection status.
Parameters
e Pointer to the Element
sel Selection status of the element.
Definition at line 641 of file gui.c.
{
    switch (e->Type)
    {
    case ELEMENT_TYPE_LABEL:
        label_render((Label *)e);
        break;
    case ELEMENT_TYPE_BUTTON:
        button_render((Button *)e, sel);
        break;
    case ELEMENT_TYPE_INPUT:
        input_render((Input *)e, sel);
        break;
    }
}
References button_render(), input_render(), label_render(), and Element::Type.
Referenced by _select(), and element_render().
input_backspace()
static void input_backspace (Input * i) [static]
Delete the character before the cursor.
Parameters
i Pointer to the input structure
Definition at line 413 of file gui.c.
{
    if (i->Selection != i->Position)
    {
        input_selection_replace(i, NULL, 0);
    }
    else if (i->Position > 0)
    {
        --i->Position;
        i->Selection = i->Position;
        vector_remove(&i->Text, i->Position);
        input_render(i, true);
    }
}
References input_render(), input_selection_replace(), and vector_remove().
Referenced by input_event_key().
input_char()
static void input_char (Input * i, i32 chr) [static]
Insert a character at the cursor position.
Parameters
i Pointer to the input structure
chr
Definition at line 499 of file gui.c.
{
    char ins = chr;
    input_selection_replace(i, &ins, 1);
}
References input_selection_replace().
Referenced by input_event_key().
input_clear()
void input_clear (Input * i)
Clear an input field.
Parameters
i The input field
Definition at line 300 of file gui.c.
{
    vector_clear(&i->Text);
    input_render(i, true);
}
References input_render(), and vector_clear().
input_copy()
static void input_copy (Input * i) [static]
Do a CTRL+C copy operation on an input field.
Parameters
i Pointer to the input structure
Definition at line 536 of file gui.c.
{
    _selection_save(i);
}
References _selection_save().
Referenced by input_event_key().
input_cut()
static void input_cut (Input * i) [static]
Do a CTRL+X cut operation on an input field.
Parameters
i Pointer to the input structure
Definition at line 546 of file gui.c.
{
    _selection_save(i);
    input_selection_replace(i, NULL, 0);
}
References _selection_save(), and input_selection_replace().
Referenced by input_event_key().
input_delete()
static void input_delete (Input * i) [static]
Delete the character after the cursor.
Parameters
i Pointer to the input structure
Definition at line 433 of file gui.c.
{
    if (i->Selection != i->Position)
    {
        input_selection_replace(i, NULL, 0);
    }
    else if (i->Position < (i32)vector_len(&i->Text))
    {
        vector_remove(&i->Text, i->Position);
        input_render(i, true);
    }
}
References input_render(), input_selection_replace(), vector_len(), and vector_remove().
Referenced by input_event_key().
input_end()
static void input_end (Input * i) [static]
Move the cursor to the end of the input field.
Parameters
i Pointer to the input structure
Definition at line 475 of file gui.c.
{
    i->Position = vector_len(&i->Text);
    i->Selection = i->Position;
    input_render(i, true);
}
References input_render(), and vector_len().
Referenced by input_event_key().
input_event_key()
static void input_event_key (Input * i, Key key, i32 chr) [static]
Forward a key event to an input field.
Parameters
i The input
key The key that was pressed
chr The character that corresponds to the key
Definition at line 569 of file gui.c.
{
    if (key == KEY_HOME)
    {
        input_home(i);
    }
    else if (key == (KEY_HOME | MOD_SHIFT))
    {
        input_select_home(i);
    }
    else if (key == KEY_END)
    {
        input_end(i);
    }
    else if (key == (KEY_END | MOD_SHIFT))
    {
        input_select_end(i);
    }
    else if (key == KEY_LEFT)
    {
        input_left(i);
    }
    else if (key == (KEY_LEFT | MOD_SHIFT))
    {
        input_select_left(i);
    }
    else if (key == KEY_RIGHT)
    {
        input_right(i);
    }
    else if (key == (KEY_RIGHT | MOD_SHIFT))
    {
        input_select_right(i);
    }
    else if (key == KEY_BACKSPACE)
    {
        input_backspace(i);
    }
    else if (key == KEY_DELETE)
    {
        input_delete(i);
    }
    else if (key == (KEY_A | MOD_CTRL))
    {
        input_select_all(i);
    }
    else if (key == (KEY_C | MOD_CTRL))
    {
        input_copy(i);
    }
    else if (key == (KEY_X | MOD_CTRL))
    {
        input_cut(i);
    }
    else if (key == (KEY_V | MOD_CTRL))
    {
        input_paste(i);
    }
    else if (isprint(chr))
    {
        input_char(i, chr);
    }
}
References input_backspace(), input_char(), input_copy(), input_cut(), input_delete(), input_end(), input_home(), input_left(), input_paste(), input_right(), input_select_all(), input_select_end(), input_select_home(), input_select_left(), input_select_right(), and isprint().
Referenced by window_event_key().
input_home()
static void input_home (Input * i) [static]
Move the cursor to the beginning of the input field.
Parameters
i Pointer to the input structure
Definition at line 451 of file gui.c.
{
    i->Selection = 0;
    i->Position = 0;
    input_render(i, true);
}
References input_render().
Referenced by input_event_key().
input_init()
void input_init (Input * input, i32 x, i32 y, i32 w)
Initialize an input field.
Parameters
input The input field
x X-Coordinate
y Y-Coordinate
w Width
Definition at line 887 of file gui.c.
{
    input->Type = ELEMENT_TYPE_INPUT;
    input->X = x;
    input->Y = y;
    input->W = w;
    input->Position = 0;
    input->Selection = 0;
    vector_init(&input->Text, sizeof(char), INPUT_CAPACITY);
}
References INPUT_CAPACITY, Input::Position, Input::Selection, Input::Text, Input::Type, vector_init(), Input::W, Input::X, and Input::Y.
Referenced by setup().
input_left()
static void input_left (Input * i) [static]
Move input cursor one position to the left and render input.
Parameters
i Pointer to the input structure
Definition at line 345 of file gui.c.
{
    if (i->Selection != i->Position)
    {
        i->Selection = i->Position;
        input_render(i, true);
    }
    else if (i->Position > 0)
    {
        --i->Position;
        i->Selection = i->Position;
        input_render(i, true);
    }
}
References input_render().
Referenced by input_event_key().
input_paste()
static void input_paste (Input * i) [static]
Do a CTRL+V paste operation on an input field.
Parameters
i Pointer to the input structure
Definition at line 557 of file gui.c.
{
    input_selection_replace(i, clipboard_get_text(), clipboard_get_text_len());
}
References clipboard_get_text(), clipboard_get_text_len(), and input_selection_replace().
Referenced by input_event_key().
input_render()
static void input_render (Input * i, bool sel) [static]
Renders an input field on the screen.
Parameters
i Pointer to the input structure
sel A boolean value indicating if the input field is selected or not
Definition at line 212 of file gui.c.
{
    Color inner_color;
    i32 y = TITLE_BAR_HEIGHT + i->Y;
    const char *text = _input_get_display_text(i);
    inner_color = sel ? _current_theme->ElementSelBG : _current_theme->ElementBG;
    gfx_rect(i->X + BORDER_SIZE,
             TITLE_BAR_HEIGHT + i->Y + BORDER_SIZE,
             i->W - 2 * BORDER_SIZE,
             INPUT_HEIGHT - 2 + BORDER_SIZE,
             inner_color);
    if (sel)
    {
        gfx_rect_border(i->X, TITLE_BAR_HEIGHT + i->Y,
                        i->W, INPUT_HEIGHT, BORDER_SIZE_SEL,
                        _current_theme->ColorBorderSel);
    }
    else
    {
        gfx_rect_border(i->X, y, i->W, INPUT_HEIGHT, BORDER_SIZE,
                        _current_theme->ColorBorder);
    }
    if (i->Selection == i->Position)
    {
        font_string_len(i->X + INPUT_PADDING_X, y + INPUT_PADDING_Y,
                        text, vector_len(&i->Text),
                        font_default,
                        _current_theme->ColorFG,
                        inner_color);
    }
    else
    {
        i32 sel_start, sel_len, sel_x;
        sel_start = i32_min(i->Selection, i->Position);
        sel_len = i32_max(i->Selection, i->Position) - sel_start;
        /* Before selection */
        font_string_len(i->X + INPUT_PADDING_X,
                        y + INPUT_PADDING_Y,
                        text, sel_start,
                        font_default,
                        _current_theme->ColorFG,
                        inner_color);
        /* Selection */
        sel_x = font_string_width_len(text, sel_start, font_default);
        gfx_rect(i->X + INPUT_PADDING_X + sel_x, y + CURSOR_OFFSET_Y,
                 font_string_width_len(text + sel_start, sel_len, font_default),
                 CURSOR_HEIGHT,
                 _current_theme->ColorFG);
        font_string_len(i->X + INPUT_PADDING_X + sel_x, y + INPUT_PADDING_Y,
                        text + sel_start, sel_len,
                        font_default,
                        _current_theme->ColorTextSelFG,
                        _current_theme->ColorTextSelBG);
        /* After selection */
        font_string_len(i->X + INPUT_PADDING_X +
                            font_string_width_len(text, sel_start + sel_len, font_default),
                        y + INPUT_PADDING_Y,
                        text + sel_start + sel_len,
                        vector_len(&i->Text) - sel_start - sel_len,
                        font_default,
                        _current_theme->ColorFG,
                        inner_color);
    }
    if (sel)
    {
        /* Cursor */
        gfx_rect(i->X + INPUT_PADDING_X +
                     font_string_width_len(text, i->Position, font_default) +
                     CURSOR_OFFSET,
                 TITLE_BAR_HEIGHT + i->Y + CURSOR_OFFSET_Y,
                 CURSOR_WIDTH,
                 CURSOR_HEIGHT,
                 _current_theme->ColorCursor);
    }
}
References _current_theme, _input_get_display_text(), BORDER_SIZE, BORDER_SIZE_SEL, Theme::ColorBorder, Theme::ColorBorderSel, Theme::ColorCursor, Theme::ColorFG, Theme::ColorTextSelBG, Theme::ColorTextSelFG, CURSOR_HEIGHT, CURSOR_OFFSET, CURSOR_OFFSET_Y, CURSOR_WIDTH, Theme::ElementBG, Theme::ElementSelBG, font_string_len(), font_string_width_len(), gfx_rect(), gfx_rect_border(), i32_max(), i32_min(), INPUT_HEIGHT, INPUT_PADDING_X, INPUT_PADDING_Y, TITLE_BAR_HEIGHT, and vector_len().
Referenced by element_render_sel(), input_backspace(), input_clear(), input_delete(), input_end(), input_home(), input_left(), input_right(), input_select_all(), input_select_end(), input_select_home(), input_select_left(), input_select_right(), and input_selection_replace().
input_right()
static void input_right (Input * i) [static]
Move input cursor one position to the right and render input.
Parameters
i Pointer to the input structure
Definition at line 379 of file gui.c.
{
    if (i->Selection != i->Position)
    {
        i->Selection = i->Position;
        input_render(i, true);
    }
    else if (i->Position < (i32)vector_len(&i->Text))
    {
        ++i->Position;
        i->Selection = i->Position;
        input_render(i, true);
    }
}
References input_render(), and vector_len().
Referenced by input_event_key().
input_select_all()
static void input_select_all (Input * i) [static]
Do a CTRL+A select all operation on an input field.
Parameters
i Pointer to the input structure
Definition at line 510 of file gui.c.
{
    i->Selection = 0;
    i->Position = vector_len(&i->Text);
    input_render(i, true);
}
References input_render(), and vector_len().
Referenced by input_event_key().
input_select_end()
static void input_select_end (Input * i) [static]
Select the characters from the current cursor position to the end.
Parameters
i Pointer to the input structure
Definition at line 487 of file gui.c.
{
    i->Position = vector_len(&i->Text);
    input_render(i, true);
}
References input_render(), and vector_len().
Referenced by input_event_key().
input_select_home()
static void input_select_home (Input * i) [static]
Select the characters from the current cursor position to the beginning.
Parameters
i Pointer to the input structure
Definition at line 464 of file gui.c.
{
    i->Position = 0;
    input_render(i, true);
}
References input_render().
Referenced by input_event_key().
input_select_left()
static void input_select_left (Input * i) [static]
Move the cursor one position to the left and select.
Parameters
i Pointer to the input structure
Definition at line 365 of file gui.c.
{
    if (i->Position > 0)
    {
        --i->Position;
        input_render(i, true);
    }
}
References input_render().
Referenced by input_event_key().
input_select_right()
static void input_select_right (Input * i) [static]
Move the cursor one position to the right and select.
Parameters
i Pointer to the input structure
Definition at line 399 of file gui.c.
{
    if (i->Position < (i32)vector_len(&i->Text))
    {
        ++i->Position;
        input_render(i, true);
    }
}
References input_render(), and vector_len().
Referenced by input_event_key().
input_selection_replace()
static void input_selection_replace (Input * i, const char * str, i32 len) [static]
Inserts a string into an input field's buffer at the current cursor position, replacing the current selection.
Parameters
i Pointer to the Input structure
str The string to insert into the input buffer
len The length of the string to be inserted
Definition at line 314 of file gui.c.
{
    const char *text;
    i32 sel_start, sel_len, w_new, w_start, w_end;
    sel_start = i32_min(i->Selection, i->Position);
    sel_len = i32_max(i->Selection, i->Position) - sel_start;
    text = _input_get_display_text(i);
    w_new = font_string_width_len(str, len, font_default);
    w_start = font_string_width_len(text, sel_start, font_default);
    w_end = font_string_width_len(text + sel_start + sel_len,
        vector_len(&i->Text) - sel_start - sel_len, font_default);
    if (w_new + w_start + w_end >= i->W - 2 * INPUT_PADDING_X)
    {
        return;
    }
    vector_replace(&i->Text, sel_start, sel_len, str, len);
    i->Position = sel_start + len;
    i->Selection = i->Position;
    input_render(i, true);
}
References _input_get_display_text(), font_string_width_len(), i32_max(), i32_min(), INPUT_PADDING_X, input_render(), vector_len(), and vector_replace().
Referenced by input_backspace(), input_char(), input_cut(), input_delete(), and input_paste().
label_init()
void label_init (Label * label, i32 x, i32 y, u32 flags, char * text)
Initialize a label.
Parameters
label The label
x X-Coordinate
y Y-Coordinate
flags Label flags
text Label text
Definition at line 866 of file gui.c.
{
    label->Type = ELEMENT_TYPE_LABEL;
    label->X = x;
    label->Y = y;
    label->Flags = flags;
    label->Text = text;
}
References Label::Flags, Label::Text, Label::Type, Label::X, and Label::Y.
Referenced by setup().
label_render()
static void label_render (Label * l) [static]
Render a label on the screen.
Parameters
l The label
Definition at line 101 of file gui.c.
{
    u32 align, w = 0, y, rx = 0, h = 12 + 2 * LABEL_Y_PADDING;
    Color fg, bg;
    y = TITLE_BAR_HEIGHT + l->Y;
    align = l->Flags & ALIGN_MASK;
    if (l->Flags & FLAG_INVERTED)
    {
        fg = _current_theme->ColorBG;
        bg = _current_theme->ColorFG;
    }
    else
    {
        fg = _current_theme->ColorFG;
        bg = _current_theme->ColorBG;
    }
    if (align == FLAG_ALIGN_CENTER)
    {
        w = font_string_width(l->Text, font_default) + 2 * LABEL_X_PADDING;
        rx = w / 2;
    }
    else if (align == FLAG_ALIGN_RIGHT)
    {
        w = font_string_width(l->Text, font_default) + 2 * LABEL_X_PADDING;
        rx = w;
    }
    else if (align == FLAG_ALIGN_LEFT)
    {
        if (l->Flags & FLAG_INVERTED)
        {
            w = font_string_width(l->Text, font_default) + 2 * LABEL_X_PADDING;
        }
    }
    if (l->Flags & FLAG_INVERTED)
    {
        if (l->Flags & FLAG_INVISIBLE)
        {
            gfx_rect(l->X - rx - LABEL_X_PADDING, y - LABEL_Y_PADDING, w, h,
                     _current_theme->ColorBG);
            return;
        }
        else
        {
            gfx_rect(l->X - rx - LABEL_X_PADDING, y - LABEL_Y_PADDING, w, h, bg);
        }
    }
    font_string(l->X - rx, y, l->Text, font_default, fg, bg);
}
References _current_theme, ALIGN_MASK, Theme::ColorBG, Theme::ColorFG, FLAG_ALIGN_CENTER, FLAG_ALIGN_LEFT, FLAG_ALIGN_RIGHT, FLAG_INVERTED, FLAG_INVISIBLE, Label::Flags, font_string(), font_string_width(), gfx_rect(), LABEL_X_PADDING, LABEL_Y_PADDING, Label::Text, TITLE_BAR_HEIGHT, Label::X, and Label::Y.
Referenced by element_render_sel(), and label_show().
label_show()
void label_show (Label * label, bool show)
Hide/Show a label.
Parameters
label Pointer to the label
show true to show, false to hide
Definition at line 908 of file gui.c.
{
    if ((show && (label->Flags & FLAG_INVISIBLE)) ||
        (!show && !(label->Flags & FLAG_INVISIBLE)))
    {
        label->Flags ^= FLAG_INVISIBLE;
        label_render(label);
    }
}
References FLAG_INVISIBLE, Label::Flags, and label_render().
Referenced by _hide_error(), _show_error(), and loop().
theme_default()
void theme_default (void)
Reset the current GUI Theme to default values.
Definition at line 903 of file gui.c.
{
    _current_theme = &_default_theme;
}
References _current_theme, and _default_theme.
theme_set()
void theme_set (Theme * theme)
Set the current GUI Theme.
Parameters
theme Pointer to new theme
Definition at line 898 of file gui.c.
{
    _current_theme = theme;
}
References _current_theme.
window_event_key()
void window_event_key (Key key, i32 chr, KeyState state)
Forward a key event to the currently open window.
Parameters
key Key code
chr Character for key code
state Key State
Definition at line 803 of file gui.c.
{
    void *ce;
    if (!_current_window)
    {
        return;
    }
    if (_current_window->OnKey)
    {
        _current_window->OnKey(key, chr, state);
    }
    if (_current_window->Selected < 0)
    {
        return;
    }
    if (state == KEYSTATE_RELEASED)
    {
        return;
    }
    ce = _current_window->Elements[_current_window->Selected];
    if (key == KEY_TAB)
    {
        element_next();
    }
    else if (key == (KEY_TAB | MOD_SHIFT))
    {
        element_prev();
    }
    else
    {
        ElementType type = ((Element *)ce)->Type;
        if (type == ELEMENT_TYPE_BUTTON)
        {
            if (key == KEY_RETURN)
            {
                Button *b = ce;
                if (b->Click)
                {
                    b->Click();
                }
            }
        }
        else if (type == ELEMENT_TYPE_INPUT)
        {
            input_event_key((Input *)ce, key, chr);
        }
    }
}
References _current_window, Button::Click, element_next(), element_prev(), Window::Elements, input_event_key(), Window::OnKey, and Window::Selected.
Referenced by event_key().
window_init()
void window_init (Window * window, char * title, void * elems, i32 count, KeyEvent onkey)
Initialize a window.
Parameters
window The window
title Window title
elems Pointer to elements array
count Number of elements
onkey Key event
Definition at line 856 of file gui.c.
{
    window->Selected = -1;
    window->Title = title;
    window->Elements = elems;
    window->Count = count;
    window->OnKey = onkey;
}
References Window::Count, Window::Elements, Window::OnKey, Window::Selected, and Window::Title.
Referenced by setup().
window_open()
void window_open (Window * window)
Open and render a window.
Parameters
window Pointer to Window structure
Definition at line 792 of file gui.c.
{
    _current_window = window;
    if (window->Selected < 0)
    {
        element_first();
    }
    window_render(window);
}
References _current_window, element_first(), Window::Selected, and window_render().
Referenced by button_login_onclick(), and setup().
window_render()
static void window_render (Window * window) [static]
Draw a window.
Parameters
window The window
Definition at line 766 of file gui.c.
{
    i32 i;
    /* Title Bar */
    gfx_rect(0, 0, GFX_WIDTH, TITLE_BAR_HEIGHT - 1,
             _current_theme->ColorTitleBar);
    gfx_rect(0, TITLE_BAR_HEIGHT - 1, GFX_WIDTH, 1,
             _current_theme->ColorFG);
    /* Background */
    gfx_rect(0, TITLE_BAR_HEIGHT, GFX_WIDTH, GFX_HEIGHT - TITLE_BAR_HEIGHT,
             _current_theme->ColorBG);
    /* Title */
    font_string(TITLE_OFFSET_X, TITLE_OFFSET_Y, window->Title,
                font_default, _current_theme->ColorFG,
                _current_theme->ColorTitleBar);
    for (i = 0; i < window->Count; ++i)
    {
        element_render(window->Elements[i]);
    }
}
References _current_theme, Theme::ColorBG, Theme::ColorFG, Theme::ColorTitleBar, Window::Count, element_render(), Window::Elements, font_string(), GFX_HEIGHT, gfx_rect(), GFX_WIDTH, Window::Title, TITLE_BAR_HEIGHT, TITLE_OFFSET_X, and TITLE_OFFSET_Y.
Referenced by window_open().
Variable Documentation
_current_theme
Theme* _current_theme = &_default_theme [static]
Pointer to the currently used theme
Definition at line 82 of file gui.c.
Referenced by button_render(), input_render(), label_render(), theme_default(), theme_set(), and window_render().
_current_window
Window* _current_window [static]
Pointer to the currently open window
Definition at line 64 of file gui.c.
Referenced by _select(), _selectable(), element_first(), element_next(), element_prev(), element_render(), window_event_key(), and window_open().
_default_theme
Theme _default_theme [static]
Initial value:
=
    {
        .ColorFG = THEME_LIGHT,
        .ColorBG = THEME_BLACK,
        .ColorTextSelBG = THEME_LIGHT,
        .ColorTextSelFG = THEME_DARK,
        .ColorBorder = THEME_MIDDLE,
        .ColorBorderSel = THEME_LIGHT,
        .ElementBG = THEME_DARK,
        .ElementSelBG = THEME_MIDDLE,
        .ColorCursor = THEME_LIGHT,
        .ColorTitleBar = THEME_DARK,
}
Default Theme
Definition at line 67 of file gui.c.
Referenced by theme_default().