platform/avr/initrd/initrd.h File Reference
Load INIT program from reserved area on disk. This module contains a very rudimentary ATFS driver to do that. It is kind of a hack to avoid a chicken-egg problem because we want the filesystem driver to be in userspace but we can't load the FS driver without already having an FS driver.
Functions
void initrd_load (void)
Load the INIT program from special area on disk. The fully featured filesystem driver is in userspace.
Detailed Description
Load INIT program from reserved area on disk. This module contains a very rudimentary ATFS driver to do that. It is kind of a hack to avoid a chicken-egg problem because we want the filesystem driver to be in userspace but we can't load the FS driver without already having an FS driver.
Author
Anton Tchekov
Version
0.1
Date
21.05.2023
Definition in file initrd.h.
Function Documentation
initrd_load()
void initrd_load (void)
Load the INIT program from special area on disk. The fully featured filesystem driver is in userspace.
Definition at line 20 of file initrd.c.
{
    u8 buf[BLOCK_SIZE];
    u16 num_sectors;
    u32 addr, block, revision, start_init, size_init;
    log_boot_P(LOG_INIT, PSTR("Loading INIT Binary"));
    sd_read(ATFS_SECTOR_BOOT, buf);
    /* Check signature */
    if(memcmp(buf + ATFS_OFFSET_SIGNATURE,
        _atfs_signature, sizeof(_atfs_signature)))
    {
        panic(PSTR("Wrong FS signature"));
    }
    /* Check revision */
    revision = load_le_32(buf + ATFS_OFFSET_REVISION);
    if(revision != ATFS_REVISION)
    {
        panic(PSTR("Unsupported ATFS revision"));
    }
    /* Get INIT Start and Size */
    start_init = load_le_32(buf + ATFS_OFFSET_INIT_BLOCK);
    size_init = load_le_32(buf + ATFS_OFFSET_INIT_SIZE);
    log_boot_P(LOG_EXT, PSTR("INIT Start: %"PRIu32), start_init);
    log_boot_P(LOG_EXT, PSTR("INIT Size: %"PRIu32), size_init);
    num_sectors = (size_init + BLOCK_SIZE - 1) >> BLOCK_SIZE_POT;
    log_boot_P(LOG_EXT, PSTR("INIT Sectors: %" PRIu16), num_sectors);
    /* Load INIT */
    for(addr = RAM_OFFSET_INIT, block = start_init;
        block < start_init + num_sectors;
        ++block, addr += BLOCK_SIZE)
    {
        if(sd_read(block, buf))
        {
            panic(PSTR("Loading INIT failed"));
        }
        xmem_write(addr, buf, BLOCK_SIZE);
    }
}
References _atfs_signature, ATFS_OFFSET_INIT_BLOCK, ATFS_OFFSET_INIT_SIZE, ATFS_OFFSET_REVISION, ATFS_OFFSET_SIGNATURE, ATFS_REVISION, ATFS_SECTOR_BOOT, BLOCK_SIZE, BLOCK_SIZE_POT, load_le_32(), log_boot_P(), memcmp(), panic(), RAM_OFFSET_INIT, sd_read(), and xmem_write().
Referenced by main().