platform/avr/initrd/initrd.c File Reference
#include <atfs.h>
#include <initrd.h>
#include <types.h>
#include <sd.h>
#include <xmem.h>
#include <logger.h>
#include <string.h>
#include <avr/pgmspace.h>
Macros
#define RAM_OFFSET_STDLIB 0
#define RAM_OFFSET_INIT 0
Functions
void initrd_load (void)
Load the INIT program and Standard Shared Library from special area on disk. The full featured filesystem driver is in userspace.
Detailed Description
Author
Anton Tchekov
Version
0.1
Date
21.05.2023
Definition in file initrd.c.
Macro Definition Documentation
RAM_OFFSET_INIT
#define RAM_OFFSET_INIT 0
RAM Offset of INIT Program
Definition at line 23 of file initrd.c.
RAM_OFFSET_STDLIB
#define RAM_OFFSET_STDLIB 0
RAM Offset of STDLIB
Definition at line 20 of file initrd.c.
Function Documentation
initrd_load()
void initrd_load (void)
Load the INIT program and Standard Shared Library from special area on disk. The full featured filesystem driver is in userspace.
Definition at line 25 of file initrd.c.
{
    u8 buf[BLOCK_SIZE];
    u16 block, num_sectors;
    u32 addr, revision, size_stdlib, size_init;
    log_boot_P(LOG_INIT, PSTR("Loading Init Binary"));
    sd_read(ATFS_SECTOR_BOOT, buf);
    /* Check signature */
    if(memcmp(buf + ATFS_OFFSET_SIGNATURE, _atfs_signature, sizeof(_atfs_signature)))
    {
        panic(PSTR("Wrong FS signature"));
    }
    /* Check revision */
    revision = load_le_32(buf + ATFS_OFFSET_REVISION);
    if(revision != ATFS_REVISION)
    {
        panic(PSTR("Unsupported ATFS revision"));
    }
    /* Get STDLIB Size */
    size_stdlib = load_le_32(buf + ATFS_OFFSET_STDLIB_SIZE);
    /* Get INIT Size */
    size_init = load_le_32(buf + ATFS_OFFSET_INIT_SIZE);
    /* Load STDLIB */
    /* _load_xmem(RAM_OFFSET_STDLIB, SECTOR_STDLIB, size_stdlib >> BLOCK_SIZE_POT); */
    log_boot_P(LOG_EXT, PSTR("INIT Size: %"PRIu32), size_init);
    log_boot_P(LOG_EXT, PSTR("STDLIB Size: %"PRIu32), size_stdlib);
    num_sectors = (size_init + BLOCK_SIZE - 1) >> BLOCK_SIZE_POT;
    log_boot_P(LOG_EXT, PSTR("INIT Sectors: %d"), num_sectors);
    /* Load INIT */
    for(addr = 0, block = ATFS_SECTOR_INIT;
        block < ATFS_SECTOR_INIT + num_sectors;
        ++block, addr += BLOCK_SIZE)
    {
        if(sd_read(block, buf))
        {
            panic(PSTR("Loading InitRD failed"));
        }
        xmem_write(addr, buf, BLOCK_SIZE);
    }
}
References _atfs_signature, ATFS_OFFSET_INIT_SIZE, ATFS_OFFSET_REVISION, ATFS_OFFSET_SIGNATURE, ATFS_OFFSET_STDLIB_SIZE, ATFS_REVISION, ATFS_SECTOR_BOOT, ATFS_SECTOR_INIT, BLOCK_SIZE, BLOCK_SIZE_POT, load_le_32(), log_boot_P(), memcmp(), panic(), sd_read(), and xmem_write().
Referenced by main().