stdlib/keyboard/keyboard.c File Reference
Keyboard types and utilities.
#include <keyboard.h>
#include <syscall.h>
#include <event.h>
Functions
static void _event_key_handler (Key key, i32 chr, KeyState state)
void keyboard_init (void)
Initialize keyboard, do NOT call this function.
void keyboard_register_event (KeyEvent event)
Register an OnKeyboardInput event.
Variables
static KeyEvent _event_key
Detailed Description
Keyboard types and utilities.
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
14.05.2023
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
23.04.2023
Definition in file keyboard.c.
Function Documentation
_event_key_handler()
static void _event_key_handler (Key key, i32 chr, KeyState state) [static]
Wrapper for key event handler
Definition at line 16 of file keyboard.c.
{
    if(_event_key)
    {
        _event_key(key, chr, state);
    }
    finish();
}
References _event_key, and finish().
Referenced by keyboard_init().
keyboard_init()
void keyboard_init (void)
Initialize keyboard, do NOT call this function.
Definition at line 26 of file keyboard.c.
{
    event_register(EVENT_KEY, (u32)_event_key_handler);
}
References _event_key_handler(), EVENT_KEY, and event_register().
keyboard_register_event()
void keyboard_register_event (KeyEvent event)
Register an OnKeyboardInput event.
Parameters
event Function pointer to a Function that takes the Key and the KeyState
Definition at line 31 of file keyboard.c.
{
    _event_key = event;
}
References _event_key.
Variable Documentation
_event_key
KeyEvent _event_key [static]
Pointer to user-defined key event handler function
Definition at line 13 of file keyboard.c.
Referenced by _event_key_handler(), and keyboard_register_event().