stdlib/keyboard/keyboard.h File Reference
Keyboard input using event callbacks or polling.
#include <types.h>
#include <keyboard-shared.h>
Typedefs
typedef void(* KeyEvent) (Key, i32, KeyState)
Functions
void keyboard_init (void)
Initialize keyboard, do NOT call this function.
void keyboard_register_event (KeyEvent event)
Register an OnKeyboardInput event.
Detailed Description
Keyboard input using event callbacks or polling.
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
23.04.2023
Definition in file keyboard.h.
Typedef Documentation
KeyEvent
typedef void(* KeyEvent) (Key, i32, KeyState)
Keyboard event handler function pointer
Definition at line 16 of file keyboard.h.
Function Documentation
keyboard_init()
void keyboard_init (void)
Initialize keyboard, do NOT call this function.
Definition at line 26 of file keyboard.c.
{
    event_register(EVENT_KEY, (u32)_event_key_handler);
}
References _event_key_handler(), EVENT_KEY, and event_register().
keyboard_register_event()
void keyboard_register_event (KeyEvent event)
Register an OnKeyboardInput event.
Parameters
event Function pointer to a Function that takes the Key and the KeyState
Definition at line 31 of file keyboard.c.
{
    _event_key = event;
}
References _event_key.
Referenced by setup().