apps/editor/keyword.h File Reference
Keyword lookup function for syntax highlighting.
#include <types.h>
Functions
void keyword_init (void)
Initialize keyword module.
bool keyword_detect (const char *str, u32 len)
Detects if a string is a keyword.
Detailed Description
Keyword lookup function for syntax highlighting.
Author
Anton Tchekov
Version
0.1
Date
28.05.2023
Definition in file keyword.h.
Function Documentation
keyword_detect()
bool keyword_detect (const char * str, u32 len)
Detects if a string is a keyword.
Parameters
str The string to check for
len The length of the string
Returns
true if the input string is a keyword
Definition at line 146 of file keyword.c.
{
    u32 i, hash;
    hash = _keyword_hash(str, len);
    for(i = 0; i < COLLISION_LIMIT; ++i)
    {
        i32 index = _hashmap[hash % HASHMAP_SIZE];
        if(index != -1 && len == strlen(_keywords[index]) &&
            !strncmp(str, _keywords[index], len))
        {
            return true;
        }
        ++hash;
    }
    return false;
}
References _hashmap, _keyword_hash(), _keywords, COLLISION_LIMIT, HASHMAP_SIZE, strlen(), and strncmp().
Referenced by _draw_code().
keyword_init()
void keyword_init (void)
Initialize keyword module.
Definition at line 120 of file keyword.c.
{
    u32 i, hash, steps;
    for(i = 0; i < HASHMAP_SIZE; ++i)
    {
        _hashmap[i] = -1;
    }
    for(i = 0; i < ARRLEN(_keywords); ++i)
    {
        steps = 0;
        hash = _keyword_hash(_keywords[i], UINT32_MAX);
        while(_hashmap[hash % HASHMAP_SIZE] != -1)
        {
            ++hash;
            if(++steps >= COLLISION_LIMIT)
            {
                PANIC("Keyword hashmap collision limit exceeded");
            }
        }
        _hashmap[hash % HASHMAP_SIZE] = i;
    }
}
References _hashmap, _keyword_hash(), _keywords, ARRLEN, COLLISION_LIMIT, HASHMAP_SIZE, and PANIC.
Referenced by setup().