apps/editor/keyword.c File Reference
#include `keyword.h`
#include <std.h>
Macros
#define HASHMAP_SIZE (ARRLEN(_keywords) * 3)
#define COLLISION_LIMIT 4
Functions
static u32 _keyword_hash (const char *word, u32 len)
Calculate a hash for a string.
void keyword_init (void)
Initialize keyword module.
bool keyword_detect (const char *str, u32 len)
Detects if a string is a keyword.
Variables
static const char * _keywords []
static i32 _hashmap [HASHMAP_SIZE]
Detailed Description
Author
Anton Tchekov
Version
0.1
Date
28.05.2023
Definition in file keyword.c.
Macro Definition Documentation
COLLISION_LIMIT
#define COLLISION_LIMIT 4
Maximum number of collisions when initializing the hashmap
Definition at line 15 of file keyword.c.
HASHMAP_SIZE
#define HASHMAP_SIZE (ARRLEN(_keywords) * 3)
Maximum number of elements in the hashmap
Definition at line 12 of file keyword.c.
Function Documentation
_keyword_hash()
static u32 _keyword_hash (const char * word, u32 len) [static]
Calculate a hash for a string.
Parameters
word The string to hash
len The length of the string
Returns
Hash value
Definition at line 106 of file keyword.c.
{
    u32 i, hash;
    i32 c;
    hash = 5381;
    for(i = 0; i < len && (c = word[i]); ++i)
    {
        hash = ((hash << 5) + hash) + c;
    }
    return hash;
}
Referenced by keyword_detect(), and keyword_init().
keyword_detect()
bool keyword_detect (const char * str, u32 len)
Detects if a string is a keyword.
Parameters
str The string to check for
len The length of the string
Returns
true if the input string is a keyword
Definition at line 146 of file keyword.c.
{
    u32 i, hash;
    hash = _keyword_hash(str, len);
    for(i = 0; i < COLLISION_LIMIT; ++i)
    {
        i32 index = _hashmap[hash % HASHMAP_SIZE];
        if(index != -1 && len == strlen(_keywords[index]) &&
            !strncmp(str, _keywords[index], len))
        {
            return true;
        }
        ++hash;
    }
    return false;
}
References _hashmap, _keyword_hash(), _keywords, COLLISION_LIMIT, HASHMAP_SIZE, strlen(), and strncmp().
keyword_init()
void keyword_init (void)
Initialize keyword module.
Definition at line 120 of file keyword.c.
{
    u32 i, hash, steps;
    for(i = 0; i < HASHMAP_SIZE; ++i)
    {
        _hashmap[i] = -1;
    }
    for(i = 0; i < ARRLEN(_keywords); ++i)
    {
        steps = 0;
        hash = _keyword_hash(_keywords[i], UINT32_MAX);
        while(_hashmap[hash % HASHMAP_SIZE] != -1)
        {
            ++hash;
            if(++steps >= COLLISION_LIMIT)
            {
                PANIC("Keyword hashmap collision limit exceeded");
            }
        }
        _hashmap[hash % HASHMAP_SIZE] = i;
    }
}
References _hashmap, _keyword_hash(), _keywords, ARRLEN, COLLISION_LIMIT, HASHMAP_SIZE, and PANIC.
Referenced by setup().
Variable Documentation
_hashmap
i32 _hashmap[HASHMAP_SIZE] [static]
Hashmap is initialized with -1
Definition at line 97 of file keyword.c.
Referenced by keyword_detect(), and keyword_init().
_keywords
const char* _keywords[] [static]
Keyword list
Definition at line 18 of file keyword.c.
Referenced by keyword_detect(), and keyword_init().