platform/avr/lcd/lcd.c File Reference
#include <lcd.h>
#include <logger.h>
#include <spi.h>
#include <gpio.h>
#include <xmem.h>
#include <avr/pgmspace.h>
#include <util/delay.h>
Macros
#define SCAN_DIR L2R_U2D
#define FONT_WIDTH 5
#define FONT_HEIGHT 7
Enumerations
enum {
L2R_U2D
, L2R_D2U
, R2L_U2D
, R2L_D2U
,
U2D_L2R
, U2D_R2L
, D2U_L2R
, D2U_R2L
 }
Functions
static u8 _gamma_correction (u8 value)
Perform gamma correction on a color channel.
static void _lcd_reset (void)
Reset the LCD.
static void _lcd_write_reg (u8 reg)
Write an LCD register.
static void _lcd_write_data (u8 data)
Send data to the LCD.
static void _lcd_window_start (u16 x, u16 y, u16 w, u16 h)
Start an LCD drawing rectangle.
static void _lcd_pixel (RGB565 data)
Send the color of one pixel to the LCD.
static void _lcd_window_end (void)
End LCD drawing rectangle.
static void _lcd_init_reg (void)
Send LCD initialization commands.
static void _lcd_set_gram_scan_dir (u8 scan_dir)
Set LCD orientation.
void lcd_backlight (u8 value)
Set LCD backlight brightness.
void lcd_init (u8 backlight, RGB565 bg)
Initialize LCD.
void lcd_rect (u16 x, u16 y, u16 w, u16 h, RGB565 color)
Draw rectangle.
RGB565 lcd_color (u8 r, u8 g, u8 b)
Convert RGB888 to RGB565.
void lcd_logo_P (u16 x, u16 y, u16 w, u16 h, const u8 *image)
Draw boot logo(s)
u8 lcd_char (u16 x, u16 y, RGB565 fg, RGB565 bg, char c)
Draw a character in the standard font.
u16 lcd_string (u16 x, u16 y, RGB565 fg, RGB565 bg, const char *s)
Draw a string in the default font.
u16 lcd_string_P (u16 x, u16 y, RGB565 fg, RGB565 bg, const char *s)
Draw a string from program memory in the default font.
void lcd_image_rgba (u16 x, u16 y, u16 w, u16 h, u32 addr)
Draw an RGBA image from XMEM.
void lcd_image_rgb (u16 x, u16 y, u16 w, u16 h, u32 addr)
Draw an RGB image from XMEM.
void lcd_image_rgb565 (u16 x, u16 y, u16 w, u16 h, u32 addr)
Draw an RGB565 image from XMEM.
void lcd_image_grayscale (u16 x, u16 y, u16 w, u16 h, RGB565 fg, RGB565 bg, u32 addr)
Draw a colored Grayscale image from XMEM.
void lcd_image_1bit (u16 x, u16 y, u16 w, u16 h, RGB565 fg, RGB565 bg, u32 addr)
Draw a colored 1-bit image from XMEM.
Variables
static const u8 _font5x7[] PROGMEM
static const u8 PROGMEM _gamma []
Detailed Description
Author
Anton Tchekov
Version
0.2
Date
17.05.2023
Definition in file lcd.c.
Macro Definition Documentation
FONT_HEIGHT
#define FONT_HEIGHT 7
Default font height in pixels
Definition at line 35 of file lcd.c.
FONT_WIDTH
#define FONT_WIDTH 5
Default font width in pixels
Definition at line 32 of file lcd.c.
SCAN_DIR
#define SCAN_DIR L2R_U2D
LCD orientation
Definition at line 29 of file lcd.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Definition at line 16 of file lcd.c.
{
    L2R_U2D,
    L2R_D2U,
    R2L_U2D,
    R2L_D2U,
    U2D_L2R,
    U2D_R2L,
    D2U_L2R,
    D2U_R2L
};
Function Documentation
_gamma_correction()
static u8 _gamma_correction (u8 value) [inline], [static]
Perform gamma correction on a color channel.
Parameters
value Input color channel value
Returns
Gamma corrected output value
Definition at line 172 of file lcd.c.
{
    return pgm_read_byte(_gamma + value);
}
References _gamma.
_lcd_init_reg()
static void _lcd_init_reg (void) [static]
Send LCD initialization commands.
Definition at line 271 of file lcd.c.
{
    _lcd_write_reg(0xF9);
    _lcd_write_data(0x00);
    _lcd_write_data(0x08);
    _lcd_write_reg(0xC0);
    _lcd_write_data(0x19);
    _lcd_write_data(0x1a);
    _lcd_write_reg(0xC1);
    _lcd_write_data(0x45);
    _lcd_write_data(0x00);
    _lcd_write_reg(0xC2);
    _lcd_write_data(0x33);
    _lcd_write_reg(0xC5);
    _lcd_write_data(0x00);
    _lcd_write_data(0x28);
    _lcd_write_reg(0xB1);
    _lcd_write_data(0xA0);
    _lcd_write_data(0x11);
    _lcd_write_reg(0xB4);
    _lcd_write_data(0x02);
    _lcd_write_reg(0xB6);
    _lcd_write_data(0x00);
    _lcd_write_data(0x42);
    _lcd_write_data(0x3B);
    _lcd_write_reg(0xB7);
    _lcd_write_data(0x07);
    _lcd_write_reg(0xE0);
    _lcd_write_data(0x1F);
    _lcd_write_data(0x25);
    _lcd_write_data(0x22);
    _lcd_write_data(0x0B);
    _lcd_write_data(0x06);
    _lcd_write_data(0x0A);
    _lcd_write_data(0x4E);
    _lcd_write_data(0xC6);
    _lcd_write_data(0x39);
    _lcd_write_data(0x00);
    _lcd_write_data(0x00);
    _lcd_write_data(0x00);
    _lcd_write_data(0x00);
    _lcd_write_data(0x00);
    _lcd_write_data(0x00);
    _lcd_write_reg(0xE1);
    _lcd_write_data(0x1F);
    _lcd_write_data(0x3F);
    _lcd_write_data(0x3F);
    _lcd_write_data(0x0F);
    _lcd_write_data(0x1F);
    _lcd_write_data(0x0F);
    _lcd_write_data(0x46);
    _lcd_write_data(0x49);
    _lcd_write_data(0x31);
    _lcd_write_data(0x05);
    _lcd_write_data(0x09);
    _lcd_write_data(0x03);
    _lcd_write_data(0x1C);
    _lcd_write_data(0x1A);
    _lcd_write_data(0x00);
    _lcd_write_reg(0xF1);
    _lcd_write_data(0x36);
    _lcd_write_data(0x04);
    _lcd_write_data(0x00);
    _lcd_write_data(0x3C);
    _lcd_write_data(0x0F);
    _lcd_write_data(0x0F);
    _lcd_write_data(0xA4);
    _lcd_write_data(0x02);
    _lcd_write_reg(0xF2);
    _lcd_write_data(0x18);
    _lcd_write_data(0xA3);
    _lcd_write_data(0x12);
    _lcd_write_data(0x02);
    _lcd_write_data(0x32);
    _lcd_write_data(0x12);
    _lcd_write_data(0xFF);
    _lcd_write_data(0x32);
    _lcd_write_data(0x00);
    _lcd_write_reg(0xF4);
    _lcd_write_data(0x40);
    _lcd_write_data(0x00);
    _lcd_write_data(0x08);
    _lcd_write_data(0x91);
    _lcd_write_data(0x04);
    _lcd_write_reg(0xF8);
    _lcd_write_data(0x21);
    _lcd_write_data(0x04);
    _lcd_write_reg(0x3A);
    _lcd_write_data(0x55);
}
References _lcd_write_data(), and _lcd_write_reg().
Referenced by lcd_init().
_lcd_pixel()
static void _lcd_pixel (RGB565 data) [inline], [static]
Send the color of one pixel to the LCD.
Parameters
data RGB565 color
Definition at line 254 of file lcd.c.
{
    spi_xchg(data >> 8);
    spi_xchg(data);
}
References spi_xchg().
Referenced by lcd_char(), lcd_image_1bit(), lcd_logo_P(), and lcd_rect().
_lcd_reset()
static void _lcd_reset (void) [static]
Reset the LCD.
Definition at line 180 of file lcd.c.
{
    LCD_RST_1;
    _delay_ms(500);
    LCD_RST_0;
    _delay_ms(500);
    LCD_RST_1;
    _delay_ms(500);
}
References LCD_RST_0, and LCD_RST_1.
Referenced by lcd_init().
_lcd_set_gram_scan_dir()
static void _lcd_set_gram_scan_dir (u8 scan_dir) [static]
Set LCD orientation.
Parameters
scan_dir LCD orientation (see enum above)
Definition at line 367 of file lcd.c.
{
    u16 a, b;
    switch(scan_dir)
    {
    case L2R_U2D:
        a = 0x08;
        b = 0x22;
        break;
    case L2R_D2U:
        a = 0x08;
        b = 0x62;
        break;
    case R2L_U2D:
        a = 0x08;
        b = 0x02;
        break;
    case R2L_D2U:
        a = 0x08;
        b = 0x42;
        break;
    case U2D_L2R:
        a = 0x28;
        b = 0x22;
        break;
    case U2D_R2L:
        a = 0x28;
        b = 0x02;
        break;
    case D2U_L2R:
        a = 0x28;
        b = 0x62;
        break;
    case D2U_R2L:
        a = 0x28;
        b = 0x42;
        break;
    }
    _lcd_write_reg(0xB6);
    _lcd_write_data(0x00);
    _lcd_write_data(b);
    _lcd_write_reg(0x36);
    _lcd_write_data(a);
}
References _lcd_write_data(), and _lcd_write_reg().
Referenced by lcd_init().
_lcd_window_end()
static void _lcd_window_end (void) [inline], [static]
End LCD drawing rectangle.
Definition at line 263 of file lcd.c.
{
    LCD_CS_1;
}
References LCD_CS_1.
Referenced by lcd_char(), lcd_image_1bit(), lcd_logo_P(), and lcd_rect().
_lcd_window_start()
static void _lcd_window_start (u16 x, u16 y, u16 w, u16 h) [static]
Start an LCD drawing rectangle.
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h Height
Definition at line 225 of file lcd.c.
{
    u16 x_end, y_end;
    x_end = x + w - 1;
    y_end = y + h - 1;
    spi_fast();
    _lcd_write_reg(0x2A);
    _lcd_write_data(x >> 8);
    _lcd_write_data(x);
    _lcd_write_data(x_end >> 8);
    _lcd_write_data(x_end);
    _lcd_write_reg(0x2B);
    _lcd_write_data(y >> 8);
    _lcd_write_data(y);
    _lcd_write_data(y_end >> 8);
    _lcd_write_data(y_end);
    _lcd_write_reg(0x2C);
    LCD_DC_1;
    LCD_CS_0;
}
References _lcd_write_data(), _lcd_write_reg(), LCD_CS_0, LCD_DC_1, and spi_fast().
Referenced by lcd_char(), lcd_image_1bit(), lcd_logo_P(), and lcd_rect().
_lcd_write_data()
static void _lcd_write_data (u8 data) [static]
Send data to the LCD.
Parameters
data Data value
Definition at line 208 of file lcd.c.
{
    LCD_DC_1;
    LCD_CS_0;
    spi_xchg(0);
    spi_xchg(data);
    LCD_CS_1;
}
References LCD_CS_0, LCD_CS_1, LCD_DC_1, and spi_xchg().
Referenced by _lcd_init_reg(), _lcd_set_gram_scan_dir(), and _lcd_window_start().
_lcd_write_reg()
static void _lcd_write_reg (u8 reg) [static]
Write an LCD register.
Parameters
reg Register value
Definition at line 195 of file lcd.c.
{
    LCD_DC_0;
    LCD_CS_0;
    spi_xchg(reg);
    LCD_CS_1;
}
References LCD_CS_0, LCD_CS_1, LCD_DC_0, and spi_xchg().
Referenced by _lcd_init_reg(), _lcd_set_gram_scan_dir(), _lcd_window_start(), and lcd_init().
lcd_backlight()
void lcd_backlight (u8 value)
Set LCD backlight brightness.
Parameters
value Backlight brightness from 0-255
Definition at line 421 of file lcd.c.
{
    /* TODO: Write PWM Value */
    (void)value;
}
Referenced by lcd_init().
lcd_char()
u8 lcd_char (u16 x, u16 y, RGB565 fg, RGB565 bg, char c)
Draw a character in the standard font.
Parameters
x X-Coordinate
y Y-Coordinate
fg Foreground text color
bg Background color
c ASCII character
Returns
Width of the character that was drawn
Definition at line 483 of file lcd.c.
{
    u8 w0, h0;
    const u8 *start;
    start = _font5x7 + (c - 32) * FONT_WIDTH;
    _lcd_window_start(x, y, FONT_WIDTH, FONT_HEIGHT);
    for(h0 = 0; h0 < FONT_HEIGHT; ++h0)
    {
        for(w0 = 0; w0 < FONT_WIDTH; ++w0)
        {
            _lcd_pixel(((pgm_read_byte(start + w0) >> h0) & 1) ? fg : bg);
        }
    }
    _lcd_window_end();
    return FONT_WIDTH + 1;
}
References _lcd_pixel(), _lcd_window_end(), _lcd_window_start(), FONT_HEIGHT, and FONT_WIDTH.
Referenced by _lcd_log(), lcd_string(), and lcd_string_P().
lcd_color()
RGB565 lcd_color (u8 r, u8 g, u8 b)
Convert RGB888 to RGB565.
Parameters
r Red channel 0-255
g Green channel 0-255
b Blue channel 0-255
Returns
RGB565 color
Definition at line 462 of file lcd.c.
{
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3);
}
Referenced by _abgr_to_rgb565(), and lcd_logo_P().
lcd_image_1bit()
void lcd_image_1bit (u16 x, u16 y, u16 w, u16 h, RGB565 fg, RGB565 bg, u32 addr)
Draw a colored 1-bit image from XMEM.
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h Height
fg Foreground color
bg Background color
addr XMEM-Address
Definition at line 552 of file lcd.c.
{
    u8 byte, stride, bit_mask;
    u16 x0, y0, byte_offset;
    u8 image[64];
    stride = (w + 7) / 8;
    for(y0 = y; y0 < y + h; ++y0)
    {
        xmem_read(addr, image, stride);
        _lcd_window_start(x, y0, w, 1);
        bit_mask = 0x80;
        byte_offset = 0;
        for(x0 = x; x0 < x + w; ++x0)
        {
            if(bit_mask == 0x80)
            {
                byte = image[byte_offset++];
                bit_mask = 1;
            }
            _lcd_pixel((byte & bit_mask) ? fg : bg);
            bit_mask <<= 1;
        }
        _lcd_window_end();
        addr += stride;
    }
}
References _lcd_pixel(), _lcd_window_end(), _lcd_window_start(), and xmem_read().
lcd_image_grayscale()
void lcd_image_grayscale (u16 x, u16 y, u16 w, u16 h, RGB565 fg, RGB565 bg, u32 addr)
Draw a colored Grayscale image from XMEM.
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h Height
fg Foreground color
bg Background color
addr XMEM-Address
Definition at line 546 of file lcd.c.
{
}
lcd_image_rgb()
void lcd_image_rgb (u16 x, u16 y, u16 w, u16 h, u32 addr)
Draw an RGB image from XMEM.
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h Height
addr XMEM-Address
Definition at line 536 of file lcd.c.
{
}
lcd_image_rgb565()
void lcd_image_rgb565 (u16 x, u16 y, u16 w, u16 h, u32 addr)
Draw an RGB565 image from XMEM.
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h Height
addr XMEM-Address
Definition at line 541 of file lcd.c.
{
}
lcd_image_rgba()
void lcd_image_rgba (u16 x, u16 y, u16 w, u16 h, u32 addr)
Draw an RGBA image from XMEM.
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h Height
addr XMEM-Address
Definition at line 531 of file lcd.c.
{
}
lcd_init()
void lcd_init (u8 backlight, RGB565 bg)
Initialize LCD.
Parameters
backlight Backlight brightness from 0-255
bg Init background color
Definition at line 427 of file lcd.c.
{
    /* Initialize LCD */
    log_boot_P(LOG_INIT, PSTR("LCD driver starting"));
    spi_fast();
    _lcd_reset();
    lcd_backlight(backlight);
    _lcd_init_reg();
    _lcd_set_gram_scan_dir(SCAN_DIR);
    _delay_ms(200);
    _lcd_write_reg(0x11);
    _delay_ms(120);
    _lcd_write_reg(0x29);
    lcd_rect(0, 0, LCD_WIDTH, LCD_HEIGHT, bg);
    log_boot_P(LOG_INIT, PSTR("LCD driver initialized"));
}
References _lcd_init_reg(), _lcd_reset(), _lcd_set_gram_scan_dir(), _lcd_write_reg(), lcd_backlight(), LCD_HEIGHT, lcd_rect(), LCD_WIDTH, log_boot_P(), SCAN_DIR, and spi_fast().
Referenced by main().
lcd_logo_P()
void lcd_logo_P (u16 x, u16 y, u16 w, u16 h, const u8 * image)
Draw boot logo(s)
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h Height
image Image data (grayscale, red channel)
Definition at line 467 of file lcd.c.
{
    u16 w0, h0;
    _lcd_window_start(x, y, w, h);
    for(h0 = 0; h0 < h; ++h0)
    {
        for(w0 = 0; w0 < w; ++w0)
        {
            _lcd_pixel(lcd_color(pgm_read_byte(&image[h0 * w + w0]), 0, 0));
        }
    }
    _lcd_window_end();
}
References _lcd_pixel(), _lcd_window_end(), _lcd_window_start(), and lcd_color().
Referenced by logger_lcd_init().
lcd_rect()
void lcd_rect (u16 x, u16 y, u16 w, u16 h, RGB565 color)
Draw rectangle.
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h height
color Fill color
Definition at line 446 of file lcd.c.
{
    u16 w0, h0;
    _lcd_window_start(x, y, w, h);
    for(h0 = 0; h0 < h; ++h0)
    {
        for(w0 = 0; w0 < w; ++w0)
        {
            _lcd_pixel(color);
        }
    }
    _lcd_window_end();
}
References _lcd_pixel(), _lcd_window_end(), and _lcd_window_start().
Referenced by env_gfx_rect(), and lcd_init().
lcd_string()
u16 lcd_string (u16 x, u16 y, RGB565 fg, RGB565 bg, const char * s)
Draw a string in the default font.
Parameters
x X-Coordinate
y Y-Coordinate
fg Foreground text color
bg Background color
s ASCII string
Returns
Width of the string that was drawn
Definition at line 503 of file lcd.c.
{
    u16 i;
    char c;
    i = 0;
    while((c = *s++))
    {
        i += lcd_char(x + i, y, fg, bg, c);
    }
    return i;
}
References lcd_char().
lcd_string_P()
u16 lcd_string_P (u16 x, u16 y, RGB565 fg, RGB565 bg, const char * s)
Draw a string from program memory in the default font.
Parameters
x X-Coordinate
y Y-Coordinate
fg Foreground text color
bg Background color
s ASCII string in PROGMEM
Returns
Width of the string that was drawn
Definition at line 517 of file lcd.c.
{
    u16 i;
    char c;
    i = 0;
    while((c = pgm_read_byte(s++)))
    {
        i += lcd_char(x + i, y, fg, bg, c);
    }
    return i;
}
References lcd_char().
Referenced by _lcd_log().
Variable Documentation
_gamma
const u8 PROGMEM _gamma[] [static]
Initial value:
=
{
      0, 21, 28, 34, 39, 43, 46, 50, 53, 56, 59, 61, 64, 66, 68, 70,
     72, 74, 76, 78, 80, 82, 84, 85, 87, 89, 90, 92, 93, 95, 96, 98,
     99, 101, 102, 103, 105, 106, 107, 109, 110, 111, 112, 114, 115, 116, 117, 118,
    119, 120, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135,
    136, 137, 138, 139, 140, 141, 142, 143, 144, 144, 145, 146, 147, 148, 149, 150,
    151, 151, 152, 153, 154, 155, 156, 156, 157, 158, 159, 160, 160, 161, 162, 163,
    164, 164, 165, 166, 167, 167, 168, 169, 170, 170, 171, 172, 173, 173, 174, 175,
    175, 176, 177, 178, 178, 179, 180, 180, 181, 182, 182, 183, 184, 184, 185, 186,
    186, 187, 188, 188, 189, 190, 190, 191, 192, 192, 193, 194, 194, 195, 195, 196,
    197, 197, 198, 199, 199, 200, 200, 201, 202, 202, 203, 203, 204, 205, 205, 206,
    206, 207, 207, 208, 209, 209, 210, 210, 211, 212, 212, 213, 213, 214, 214, 215,
    215, 216, 217, 217, 218, 218, 219, 219, 220, 220, 221, 221, 222, 223, 223, 224,
    224, 225, 225, 226, 226, 227, 227, 228, 228, 229, 229, 230, 230, 231, 231, 232,
    232, 233, 233, 234, 234, 235, 235, 236, 236, 237, 237, 238, 238, 239, 239, 240,
    240, 241, 241, 242, 242, 243, 243, 244, 244, 245, 245, 246, 246, 247, 247, 248,
    248, 249, 249, 249, 250, 250, 251, 251, 252, 252, 253, 253, 254, 254, 255, 255
}
Reverse gamma correction table
Definition at line 144 of file lcd.c.
Referenced by _gamma_correction().
PROGMEM
const u8 _font5x7 [] PROGMEM [static]
Default 5x7 monospace font
Definition at line 38 of file lcd.c.