platform/avr/lcd/lcd.h File Reference
LCD Driver.
#include <types.h>
Macros
#define COLOR_RED 0xF800
#define COLOR_YELLOW 0xFFE0
#define COLOR_GREEN 0x07E0
#define COLOR_CYAN 0x07FF
#define COLOR_BLUE 0x001F
#define COLOR_MAGENTA 0xF81F
#define COLOR_WHITE 0xFFFF
#define COLOR_BLACK 0x0000
#define LCD_HEIGHT 480
#define LCD_WIDTH 320
Typedefs
typedef u16 RGB565
Functions
void lcd_backlight (u8 value)
Set LCD backlight brightness.
void lcd_init (u8 backlight, RGB565 bg)
Initialize LCD.
RGB565 lcd_color (u8 r, u8 g, u8 b)
Convert RGB888 to RGB565.
void lcd_rect (u16 x, u16 y, u16 w, u16 h, RGB565 color)
Draw rectangle.
void lcd_logo_P (u16 x, u16 y, u16 w, u16 h, const u8 *image)
Draw boot logo(s)
u8 lcd_char (u16 x, u16 y, RGB565 fg, RGB565 bg, char c)
Draw a character in the standard font.
u16 lcd_string (u16 x, u16 y, RGB565 fg, RGB565 bg, const char *s)
Draw a string in the default font.
u16 lcd_string_P (u16 x, u16 y, RGB565 fg, RGB565 bg, const char *s)
Draw a string from program memory in the default font.
void lcd_image_rgb565 (u16 x, u16 y, u16 w, u16 h, u32 addr)
Draw an RGB565 image from XMEM.
void lcd_image_grayscale (u16 x, u16 y, u16 w, u16 h, u32 addr, u32 fg, u32 bg)
Draw a colored Grayscale image from XMEM.
void lcd_image_1bit (u16 x, u16 y, u16 w, u16 h, u32 addr, RGB565 fg, RGB565 bg)
Draw a colored 1-bit image from XMEM.
Detailed Description
LCD Driver.
Author
Anton Tchekov
Version
0.2
Date
17.05.2023
Definition in file lcd.h.
Macro Definition Documentation
COLOR_BLACK
#define COLOR_BLACK 0x0000
Black Color as RGB565
Definition at line 38 of file lcd.h.
COLOR_BLUE
#define COLOR_BLUE 0x001F
Blue Color as RGB565
Definition at line 29 of file lcd.h.
COLOR_CYAN
#define COLOR_CYAN 0x07FF
Cyan Color as RGB565
Definition at line 26 of file lcd.h.
COLOR_GREEN
#define COLOR_GREEN 0x07E0
Green Color as RGB565
Definition at line 23 of file lcd.h.
COLOR_MAGENTA
#define COLOR_MAGENTA 0xF81F
Magenta Color as RGB565
Definition at line 32 of file lcd.h.
COLOR_RED
#define COLOR_RED 0xF800
Red Color as RGB565
Definition at line 17 of file lcd.h.
COLOR_WHITE
#define COLOR_WHITE 0xFFFF
White Color as RGB565
Definition at line 35 of file lcd.h.
COLOR_YELLOW
#define COLOR_YELLOW 0xFFE0
Yellow Color as RGB565
Definition at line 20 of file lcd.h.
LCD_HEIGHT
#define LCD_HEIGHT 480
Height of the display
Definition at line 41 of file lcd.h.
LCD_WIDTH
#define LCD_WIDTH 320
Width of the display
Definition at line 44 of file lcd.h.
Typedef Documentation
RGB565
typedef u16 RGB565
RGB565 data type
Definition at line 47 of file lcd.h.
Function Documentation
lcd_backlight()
void lcd_backlight (u8 value)
Set LCD backlight brightness.
Parameters
value Backlight brightness from 0-255
Definition at line 389 of file lcd.c.
{
    /* TODO: Write PWM Value
     * CHANGE BACKLIGHT PIN TO PIN 3 (TIMER 2)
     */
    (void)value;
}
Referenced by lcd_init().
lcd_char()
u8 lcd_char (u16 x, u16 y, RGB565 fg, RGB565 bg, char c)
Draw a character in the standard font.
Parameters
x X-Coordinate
y Y-Coordinate
fg Foreground text color
bg Background color
c ASCII character
Returns
Width of the character that was drawn
Definition at line 453 of file lcd.c.
{
    u8 w0, h0;
    const u8 *start;
    start = _font5x7 + (c - 32) * FONT_WIDTH;
    _lcd_window_start(x, y, FONT_WIDTH, FONT_HEIGHT);
    for(h0 = 0; h0 < FONT_HEIGHT; ++h0)
    {
        for(w0 = 0; w0 < FONT_WIDTH; ++w0)
        {
            _lcd_pixel(((pgm_read_byte(start + w0) >> h0) & 1) ? fg : bg);
        }
    }
    _lcd_window_end();
    return FONT_WIDTH + 1;
}
References _lcd_pixel(), _lcd_window_end(), _lcd_window_start(), FONT_HEIGHT, and FONT_WIDTH.
Referenced by _lcd_log(), lcd_string(), and lcd_string_P().
lcd_color()
RGB565 lcd_color (u8 r, u8 g, u8 b)
Convert RGB888 to RGB565.
Parameters
r Red channel 0-255
g Green channel 0-255
b Blue channel 0-255
Returns
RGB565 color
Definition at line 432 of file lcd.c.
{
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3);
}
Referenced by _abgr_to_rgb565(), _color_merge(), and lcd_logo_P().
lcd_image_1bit()
void lcd_image_1bit (u16 x, u16 y, u16 w, u16 h, u32 addr, RGB565 fg, RGB565 bg)
Draw a colored 1-bit image from XMEM.
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h Height
fg Foreground color
bg Background color
addr XMEM-Address
Definition at line 570 of file lcd.c.
{
    u8 byte, stride, bit_mask;
    u16 x0, y0;
    u8 *ci, image[LCD_WIDTH / 8];
    stride = (w + 7) / 8;
    for(y0 = y; y0 < y + h; ++y0)
    {
        xmem_read(addr, image, stride);
        _lcd_window_start(x, y0, w, 1);
        bit_mask = 0x80;
        ci = image;
        for(x0 = x; x0 < x + w; ++x0)
        {
            if(bit_mask == 0x80)
            {
                byte = *ci++;
                bit_mask = 1;
            }
            _lcd_pixel((byte & bit_mask) ? fg : bg);
            bit_mask <<= 1;
        }
        _lcd_window_end();
        addr += stride;
    }
}
References _lcd_pixel(), _lcd_window_end(), _lcd_window_start(), LCD_WIDTH, and xmem_read().
Referenced by env_gfx_image_1bit().
lcd_image_grayscale()
void lcd_image_grayscale (u16 x, u16 y, u16 w, u16 h, u32 addr, u32 fg, u32 bg)
Draw a colored Grayscale image from XMEM.
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h Height
fg Foreground color
bg Background color
addr XMEM-Address
Definition at line 549 of file lcd.c.
{
    u16 x0, y0, offset;
    u8 *ci, image[LCD_WIDTH];
    for(y0 = y; y0 < y + h; ++y0)
    {
        xmem_read(addr, image, w);
        _lcd_window_start(x, y0, w, 1);
        ci = image;
        for(x0 = x; x0 < x + w; ++x0)
        {
            _lcd_pixel(_color_merge(fg, bg, *ci++));
        }
        _lcd_window_end();
        addr += w;
    }
}
References _color_merge(), _lcd_pixel(), _lcd_window_end(), _lcd_window_start(), LCD_WIDTH, and xmem_read().
Referenced by env_gfx_image_grayscale().
lcd_image_rgb565()
void lcd_image_rgb565 (u16 x, u16 y, u16 w, u16 h, u32 addr)
Draw an RGB565 image from XMEM.
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h Height
addr XMEM-Address
Definition at line 501 of file lcd.c.
{
    u16 x0, y0, stride;
    u16 *ci, image[LCD_WIDTH];
    stride = w * sizeof(RGB565);
    for(y0 = y; y0 < y + h; ++y0)
    {
        xmem_read(addr, image, stride);
        _lcd_window_start(x, y0, w, 1);
        ci = image;
        for(x0 = x; x0 < x + w; ++x0)
        {
            _lcd_pixel(*ci++);
        }
        _lcd_window_end();
        addr += stride;
    }
}
References _lcd_pixel(), _lcd_window_end(), _lcd_window_start(), LCD_WIDTH, and xmem_read().
Referenced by env_gfx_image_rgb565().
lcd_init()
void lcd_init (u8 backlight, RGB565 bg)
Initialize LCD.
Parameters
backlight Backlight brightness from 0-255
bg Init background color
Definition at line 397 of file lcd.c.
{
    /* Initialize LCD */
    log_boot_P(LOG_INIT, PSTR("LCD driver starting"));
    spi_fast();
    _lcd_reset();
    lcd_backlight(backlight);
    _lcd_init_reg();
    _lcd_set_gram_scan_dir(SCAN_DIR);
    _delay_ms(200);
    _lcd_write_reg(0x11);
    _delay_ms(120);
    _lcd_write_reg(0x29);
    lcd_rect(0, 0, LCD_WIDTH, LCD_HEIGHT, bg);
    log_boot_P(LOG_INIT, PSTR("LCD driver initialized"));
}
References _lcd_init_reg(), _lcd_reset(), _lcd_set_gram_scan_dir(), _lcd_write_reg(), lcd_backlight(), LCD_HEIGHT, lcd_rect(), LCD_WIDTH, log_boot_P(), SCAN_DIR, and spi_fast().
Referenced by main().
lcd_logo_P()
void lcd_logo_P (u16 x, u16 y, u16 w, u16 h, const u8 * image)
Draw boot logo(s)
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h Height
image Image data (grayscale, red channel)
Definition at line 437 of file lcd.c.
{
    u16 w0, h0;
    _lcd_window_start(x, y, w, h);
    for(h0 = 0; h0 < h; ++h0)
    {
        for(w0 = 0; w0 < w; ++w0)
        {
            _lcd_pixel(lcd_color(pgm_read_byte(&image[h0 * w + w0]), 0, 0));
        }
    }
    _lcd_window_end();
}
References _lcd_pixel(), _lcd_window_end(), _lcd_window_start(), and lcd_color().
Referenced by logger_lcd_init().
lcd_rect()
void lcd_rect (u16 x, u16 y, u16 w, u16 h, RGB565 color)
Draw rectangle.
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h height
color Fill color
Definition at line 416 of file lcd.c.
{
    u16 w0, h0;
    _lcd_window_start(x, y, w, h);
    for(h0 = 0; h0 < h; ++h0)
    {
        for(w0 = 0; w0 < w; ++w0)
        {
            _lcd_pixel(color);
        }
    }
    _lcd_window_end();
}
References _lcd_pixel(), _lcd_window_end(), and _lcd_window_start().
Referenced by env_gfx_rect(), and lcd_init().
lcd_string()
u16 lcd_string (u16 x, u16 y, RGB565 fg, RGB565 bg, const char * s)
Draw a string in the default font.
Parameters
x X-Coordinate
y Y-Coordinate
fg Foreground text color
bg Background color
s ASCII string
Returns
Width of the string that was drawn
Definition at line 473 of file lcd.c.
{
    u16 i;
    char c;
    i = 0;
    while((c = *s++))
    {
        i += lcd_char(x + i, y, fg, bg, c);
    }
    return i;
}
References lcd_char().
lcd_string_P()
u16 lcd_string_P (u16 x, u16 y, RGB565 fg, RGB565 bg, const char * s)
Draw a string from program memory in the default font.
Parameters
x X-Coordinate
y Y-Coordinate
fg Foreground text color
bg Background color
s ASCII string in PROGMEM
Returns
Width of the string that was drawn
Definition at line 487 of file lcd.c.
{
    u16 i;
    char c;
    i = 0;
    while((c = pgm_read_byte(s++)))
    {
        i += lcd_char(x + i, y, fg, bg, c);
    }
    return i;
}
References lcd_char().
Referenced by _lcd_log().