platform/avr/logger/logger.h File Reference
Boot message logger.
#include <types.h>
#include <avr/pgmspace.h>
#include <logo/logo_tiny.c>
#include <logo/logo_text.c>
Enumerations
enum LogLevel {
LOG_INIT
, LOG_DEBUG
, LOG_WARN
, LOG_ERROR
,
LOG_PANIC
, LOG_OFFSET
, LOG_NONE
, LOG_EXT
 }
Functions
void log_boot_P (LogLevel level, const char *msg,...)
Log boot message.
void panic (const char *msg,...)
Trigger a kernel panic.
void memory_dump (u32 addr, const void *data, u16 len)
Print a hexdump of a block memory.
void logger_lcd_init (void)
Initialize LCD Logger.
Detailed Description
Boot message logger.
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
16.05.2023
Definition in file logger.h.
Enumeration Type Documentation
LogLevel
enum LogLevel
Log Level enum
Definition at line 18 of file logger.h.
{
    LOG_INIT,
    LOG_DEBUG,
    LOG_WARN,
    LOG_ERROR,
    LOG_PANIC,
    LOG_OFFSET,
    LOG_NONE,
    LOG_EXT
} LogLevel;
Function Documentation
log_boot_P()
void log_boot_P (LogLevel level, const char * msg, ...)
Log boot message.
Parameters
level Log level (see enum above)
msg Format string
... Variable arguments
Definition at line 170 of file logger.c.
{
    char buf[128];
    va_list v;
    va_start(v, msg);
    vsnprintf_P(buf, sizeof(buf), msg, v);
    va_end(v);
    _lcd_log(level, buf);
    serial_tx('\n');
}
References _lcd_log(), and serial_tx().
Referenced by _memtest(), _sd_info_print(), adc_init(), initrd_load(), lcd_init(), main(), ps2_init(), random_init(), sd_init(), spi_init(), timer_init(), and xmem_init().
logger_lcd_init()
void logger_lcd_init (void)
Initialize LCD Logger.
Definition at line 237 of file logger.c.
{
    _lcd_initialized = true;
    lcd_logo_P(
        LOGO_X_OFFSET,
        LOGO_Y_OFFSET,
        LOGO_TINY_WIDTH,
        LOGO_TINY_HEIGHT,
        logo_tiny);
    lcd_logo_P(
        LOGO_X_OFFSET + LOGO_TEXT_X_OFFSET,
        LOGO_Y_OFFSET + LOGO_TINY_HEIGHT / 2 - LOGO_TEXT_HEIGHT / 2,
        LOGO_TEXT_WIDTH,
        LOGO_TEXT_HEIGHT,
        logo_text);
}
References _lcd_initialized, lcd_logo_P(), LOGO_TEXT_X_OFFSET, LOGO_X_OFFSET, and LOGO_Y_OFFSET.
Referenced by main().
memory_dump()
void memory_dump (u32 addr, const void * data, u16 len)
Print a hexdump of a block memory.
Parameters
addr Start address only for printing
data Data buffer
len Buffer size in bytes
Definition at line 206 of file logger.c.
{
    u8 j;
    const u8 *data8;
    u16 i;
    char c, buf[32];
    data8 = data;
    for(i = 0; i < len; i += DUMP_BYTES_PER_LINE, addr += DUMP_BYTES_PER_LINE)
    {
        snprintf(buf, sizeof(buf), "%08X | ", addr);
        serial_tx_str(buf);
        for(j = 0; j < DUMP_BYTES_PER_LINE; ++j)
        {
            snprintf(buf, sizeof(buf), "%02X ", data8[i + j]);
            serial_tx_str(buf);
        }
        serial_tx_str("| ");
        for(j = 0; j < DUMP_BYTES_PER_LINE; ++j)
        {
            c = data8[i + j];
            serial_tx(isprint(c) ? c : '.');
        }
        serial_tx('\n');
    }
    serial_tx('\n');
}
References DUMP_BYTES_PER_LINE, isprint(), serial_tx(), serial_tx_str(), and snprintf().
panic()
void panic (const char * msg, ...)
Trigger a kernel panic.
Parameters
msg Format string
... Variable arguments
Definition at line 183 of file logger.c.
{
    char buf[128];
    va_list v;
    va_start(v, msg);
    vsnprintf_P(buf, sizeof(buf), msg, v);
    va_end(v);
    _lcd_log(LOG_PANIC, buf);
    serial_tx('\n');
    strcpy_P(buf, PSTR("\n>>> RESET REQUIRED\n"));
    _lcd_log(LOG_NONE, buf);
    /* Disable interrupt */
    cli();
    /* Infinite loop */
    for(;;)
    {
    }
}
References _lcd_log(), and serial_tx().
Referenced by _memtest(), _sd_error(), _sd_timeout(), initrd_load(), and spi_xchg().