platform/avr/logger/logger.c File Reference
#include <logger.h>
#include <serial.h>
#include <lcd.h>
#include <avr/pgmspace.h>
#include <avr/interrupt.h>
#include <stdarg.h>
#include <stdio.h>
#include <ctype.h>
Macros
#define DUMP_BYTES_PER_LINE 16
#define LOG_Y_OFFSET 120
#define LOG_X_OFFSET 10
#define LOG_Y_ADVANCE 10
#define LOG_X_TEXT_OFFSET 49
#define LOG_START_WIDTH 8
#define LOGO_X_OFFSET 30
#define LOGO_Y_OFFSET 50
#define LOGO_TEXT_X_OFFSET 56
Functions
static void _lcd_log (LogLevel level, const char *msg)
Print a log message on both serial and LCD.
void log_boot_P (LogLevel level, const char *msg,...)
Log boot message.
void panic (const char *msg,...)
Trigger a kernel panic.
void memory_dump (u32 addr, const void *data, u16 len)
Print a hexdump of a block memory.
void logger_lcd_init (void)
Initialize LCD Logger.
Variables
static bool _lcd_initialized
static u16 _log_y = LOG_Y_OFFSET
Detailed Description
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
16.05.2023
Definition in file logger.c.
Macro Definition Documentation
DUMP_BYTES_PER_LINE
#define DUMP_BYTES_PER_LINE 16
How many bytes to print per line in a hexdump
Definition at line 18 of file logger.c.
LOG_START_WIDTH
#define LOG_START_WIDTH 8
Serial Log prefix width
Definition at line 33 of file logger.c.
LOG_X_OFFSET
#define LOG_X_OFFSET 10
LCD Log left margin
Definition at line 24 of file logger.c.
LOG_X_TEXT_OFFSET
#define LOG_X_TEXT_OFFSET 49
LCD Log prefix pixel width
Definition at line 30 of file logger.c.
LOG_Y_ADVANCE
#define LOG_Y_ADVANCE 10
LCD advance Y direction
Definition at line 27 of file logger.c.
LOG_Y_OFFSET
#define LOG_Y_OFFSET 120
LCD Log top margin
Definition at line 21 of file logger.c.
LOGO_TEXT_X_OFFSET
#define LOGO_TEXT_X_OFFSET 56
Text Logo X Offset
Definition at line 42 of file logger.c.
LOGO_X_OFFSET
#define LOGO_X_OFFSET 30
Image Logo X offset
Definition at line 36 of file logger.c.
LOGO_Y_OFFSET
#define LOGO_Y_OFFSET 50
Image Logo Y Offset
Definition at line 39 of file logger.c.
Function Documentation
_lcd_log()
static void _lcd_log (LogLevel level, const char * msg) [static]
Print a log message on both serial and LCD.
Parameters
level Log level depending on severity and desired appearance
msg Message to print
Definition at line 95 of file logger.c.
{
    if(level != LOG_EXT)
    {
        u8 len;
        u16 x;
        const char *level_str;
        if(level != LOG_NONE && level != LOG_OFFSET)
        {
            level_str = (const char *)pgm_read_word(&_log_msg[level]);
            serial_tx('[');
            serial_tx_str_P(level_str);
            serial_tx(']');
            len = 2 + strlen_P(level_str);
            while(len < LOG_START_WIDTH)
            {
                serial_tx(' ');
                ++len;
            }
            if(_lcd_initialized)
            {
                RGB565 fg;
                fg = pgm_read_word(&_log_color[level]);
                x = LOG_X_OFFSET;
                x += lcd_char(x, _log_y, COLOR_WHITE, COLOR_BLACK, '[');
                x += lcd_string_P(x, _log_y, fg, COLOR_BLACK, level_str);
                lcd_char(x, _log_y, COLOR_WHITE, COLOR_BLACK, ']');
            }
        }
        else if(level == LOG_OFFSET)
        {
            for(len = 0; len < LOG_START_WIDTH; ++len)
            {
                serial_tx(' ');
            }
        }
        if(_lcd_initialized)
        {
            const char *s;
            char c;
            x = LOG_X_TEXT_OFFSET;
            if(level == LOG_NONE)
            {
                x = 0;
            }
            s = msg;
            while((c = *s++))
            {
                if(c == '\n')
                {
                    x = 0;
                    _log_y += LOG_Y_ADVANCE;
                }
                else
                {
                    x += lcd_char(LOG_X_OFFSET + x, _log_y,
                        COLOR_WHITE, COLOR_BLACK, c);
                }
            }
            _log_y += LOG_Y_ADVANCE;
        }
    }
    serial_tx_str(msg);
}
References _lcd_initialized, _log_y, COLOR_BLACK, COLOR_WHITE, lcd_char(), lcd_string_P(), LOG_START_WIDTH, LOG_X_OFFSET, LOG_X_TEXT_OFFSET, LOG_Y_ADVANCE, serial_tx(), serial_tx_str(), and serial_tx_str_P().
Referenced by log_boot_P(), and panic().
log_boot_P()
void log_boot_P (LogLevel level, const char * msg, ...)
Log boot message.
Parameters
level Log level (see enum above)
msg Format string
... Variable arguments
Definition at line 170 of file logger.c.
{
    char buf[128];
    va_list v;
    va_start(v, msg);
    vsnprintf_P(buf, sizeof(buf), msg, v);
    va_end(v);
    _lcd_log(level, buf);
    serial_tx('\n');
}
References _lcd_log(), and serial_tx().
Referenced by _memtest(), _sd_info_print(), adc_init(), initrd_load(), lcd_init(), main(), ps2_init(), random_init(), sd_init(), spi_init(), timer_init(), and xmem_init().
logger_lcd_init()
void logger_lcd_init (void)
Initialize LCD Logger.
Definition at line 237 of file logger.c.
{
    _lcd_initialized = true;
    lcd_logo_P(
        LOGO_X_OFFSET,
        LOGO_Y_OFFSET,
        LOGO_TINY_WIDTH,
        LOGO_TINY_HEIGHT,
        logo_tiny);
    lcd_logo_P(
        LOGO_X_OFFSET + LOGO_TEXT_X_OFFSET,
        LOGO_Y_OFFSET + LOGO_TINY_HEIGHT / 2 - LOGO_TEXT_HEIGHT / 2,
        LOGO_TEXT_WIDTH,
        LOGO_TEXT_HEIGHT,
        logo_text);
}
References _lcd_initialized, lcd_logo_P(), LOGO_TEXT_X_OFFSET, LOGO_X_OFFSET, and LOGO_Y_OFFSET.
Referenced by main().
memory_dump()
void memory_dump (u32 addr, const void * data, u16 len)
Print a hexdump of a block memory.
Parameters
addr Start address only for printing
data Data buffer
len Buffer size in bytes
Definition at line 206 of file logger.c.
{
    u8 j;
    const u8 *data8;
    u16 i;
    char c, buf[32];
    data8 = data;
    for(i = 0; i < len; i += DUMP_BYTES_PER_LINE, addr += DUMP_BYTES_PER_LINE)
    {
        snprintf(buf, sizeof(buf), "%08X | ", addr);
        serial_tx_str(buf);
        for(j = 0; j < DUMP_BYTES_PER_LINE; ++j)
        {
            snprintf(buf, sizeof(buf), "%02X ", data8[i + j]);
            serial_tx_str(buf);
        }
        serial_tx_str("| ");
        for(j = 0; j < DUMP_BYTES_PER_LINE; ++j)
        {
            c = data8[i + j];
            serial_tx(isprint(c) ? c : '.');
        }
        serial_tx('\n');
    }
    serial_tx('\n');
}
References DUMP_BYTES_PER_LINE, isprint(), serial_tx(), serial_tx_str(), and snprintf().
panic()
void panic (const char * msg, ...)
Trigger a kernel panic.
Parameters
msg Format string
... Variable arguments
Definition at line 183 of file logger.c.
{
    char buf[128];
    va_list v;
    va_start(v, msg);
    vsnprintf_P(buf, sizeof(buf), msg, v);
    va_end(v);
    _lcd_log(LOG_PANIC, buf);
    serial_tx('\n');
    strcpy_P(buf, PSTR("\n>>> RESET REQUIRED\n"));
    _lcd_log(LOG_NONE, buf);
    /* Disable interrupt */
    cli();
    /* Infinite loop */
    for(;;)
    {
    }
}
References _lcd_log(), and serial_tx().
Referenced by _memtest(), _sd_error(), _sd_timeout(), initrd_load(), and spi_xchg().
Variable Documentation
_lcd_initialized
bool _lcd_initialized [static]
Flag that indicates if the LCD has been initialized
Definition at line 84 of file logger.c.
Referenced by _lcd_log(), and logger_lcd_init().
_log_y
u16 _log_y = LOG_Y_OFFSET [static]
Current log y position
Definition at line 87 of file logger.c.
Referenced by _lcd_log().