platform/avr/main.c File Reference
AVR Main.
#include <ps2.h>
#include <serial.h>
#include <adc.h>
#include <random.h>
#include <timer.h>
#include <xmem.h>
#include <logger.h>
#include <spi.h>
#include <lcd.h>
#include <gpio.h>
#include <sd.h>
#include <initrd.h>
#include <avr/pgmspace.h>
#include <emulator.h>
Functions
int main (void)
AVR Platform main function, loads drivers and starts kernel.
char byte_to_hex (u8 byte)
Convert 4-bit hex value to ASCII.
void ps2_event (u8 byte)
This function must be implemented by the user and is called by the driver when a byte is received.
Detailed Description
AVR Main.
Author
Anton Tchekov
Version
0.1
Date
25.05.2023
Definition in file main.c.
Function Documentation
byte_to_hex()
char byte_to_hex (u8 byte)
Convert 4-bit hex value to ASCII.
Parameters
byte Value from 0-15
Returns
'0'-'9' / 'A'-'F'
Definition at line 99 of file main.c.
{
    if(byte < 10)
    {
        return byte + '0';
    }
    return byte - 10 + 'A';
}
main()
int main (void)
AVR Platform main function, loads drivers and starts kernel.
Returns
Exit code
Definition at line 29 of file main.c.
{
    /* --- BOOT SEQUENCE --- */
    /* Enable interrupts */
    sei();
    /* First, configure GPIO, because all modules that do I/O depend on it */
    gpio_configure();
    /* Second, initialize serial port so that we can print boot messages */
    serial_init();
    /* Print startup message */
    log_boot_P(LOG_NONE, PSTR("\nImaginaryOS Version 0.1 Booting ...\n"));
    /* Initialize millisecond timer */
    timer_init();
    /* Initialize SPI (Needed for SD Card, External Memory and LCD) */
    spi_init();
    /* Initialize LCD driver early for boot image and messages */
    lcd_init(0xFF, COLOR_BLACK);
    /* Initialize LCD Logger */
    logger_lcd_init();
    /* Initialize keyboard (fast) */
    ps2_init();
    /* Initialize ADC (fast) */
    adc_init();
    /* Initialize RNG (fast) */
    random_init();
    /* Initialize external memory late because of slow memory test */
    xmem_init();
    /* Initialize SD card driver */
    sd_init();
    /* --- READY --- */
    /* Load initial ram disk */
    initrd_load();
    log_boot_P(LOG_NONE, PSTR("\nStarting RISC-V Emulator Kernel ...\n\n"));
    kernel_init();
    log_boot_P(LOG_EXT, PSTR("Setup done!"));
    /* Infinite loop */
    for(;;)
    {
    }
    /* Unreachable */
    return 0;
}
References adc_init(), COLOR_BLACK, gpio_configure(), initrd_load(), kernel_init(), lcd_init(), log_boot_P(), logger_lcd_init(), ps2_init(), random_init(), sd_init(), serial_init(), spi_init(), timer_init(), and xmem_init().
ps2_event()
void ps2_event (u8 byte)
This function must be implemented by the user and is called by the driver when a byte is received.
Parameters
byte The byte that was received from the PS/2 keyboard
Definition at line 109 of file main.c.
{
    /* Called when a byte is received from the keyboard */
    /* serial_tx('0'); */
    /* serial_tx('x'); */
    /* serial_tx(byte_to_hex((byte >> 4) & 0x0F)); */
    /* serial_tx(byte_to_hex(byte & 0x0F)); */
}
Referenced by _ps2_clock_falling_edge().