platform/platform.h File Reference
Interface between Emulator and Drivers. Arguably the most important file in this project.
#include <types.h>
#include <keyboard-shared.h>
Functions
u32 env_memory_size (void)
Get the size of the installed memory.
void env_memory_read (u32 addr, void *data, u32 size)
Read data from physical memory.
void env_memory_write (u32 addr, const void *data, u32 size)
Write data to physical memory.
void env_gfx_rect (i32 x, i32 y, i32 w, i32 h, u32 color)
Draw rectangle.
void env_gfx_image_rgba (i32 x, i32 y, i32 w, i32 h, u32 addr)
Draw an RGBA image.
void env_gfx_image_rgb (i32 x, i32 y, i32 w, i32 h, u32 addr)
Draw an RGB image.
void env_gfx_image_rgb565 (i32 x, i32 y, i32 w, i32 h, u32 addr)
Draw an RGB565 image.
void env_gfx_image_grayscale (i32 x, i32 y, i32 w, i32 h, u32 addr, u32 fg, u32 bg)
Draw a colored grayscale image.
void env_gfx_image_1bit (i32 x, i32 y, i32 w, i32 h, u32 addr, u32 fg, u32 bg)
Draw a colored 1-bit image.
void env_serial_write (const void *data, u32 len)
Send data over the serial interface.
u32 env_random_get (void)
Generate a pseudo-random number.
u32 env_millis (void)
Get the number of milliseconds since boot.
Detailed Description
Interface between Emulator and Drivers. Arguably the most important file in this project.
Author
Anton Tchekov
Version
0.3
Date
16.05.2023
Definition in file platform.h.
Function Documentation
env_gfx_image_1bit()
void env_gfx_image_1bit (i32 x, i32 y, i32 w, i32 h, u32 addr, u32 fg, u32 bg)
Draw a colored 1-bit image.
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h Height
addr Image memory address
fg ABGR foreground color
bg ABGR background color
Definition at line 93 of file platform.c.
{
    /*
    lcd_image_1bit(
        u16 x, u16 y, u16 w, u16 h, RGB565 fg, RGB565 bg, u32 addr);
    */
}
References _abgr_to_argb(), _memory, _pixels, and GFX_WIDTH.
Referenced by syscall_gfx_image_1bit().
env_gfx_image_grayscale()
void env_gfx_image_grayscale (i32 x, i32 y, i32 w, i32 h, u32 addr, u32 fg, u32 bg)
Draw a colored grayscale image.
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h Height
addr Image memory address
fg ABGR foreground color
bg ABGR background color
Definition at line 84 of file platform.c.
{
    /*
    lcd_image_grayscale(
        u16 x, u16 y, u16 w, u16 h, RGB565 fg, RGB565 bg, u32 addr);
    */
}
References _color_merge(), _memory, _pixels, and GFX_WIDTH.
Referenced by syscall_gfx_image_grayscale().
env_gfx_image_rgb()
void env_gfx_image_rgb (i32 x, i32 y, i32 w, i32 h, u32 addr)
Draw an RGB image.
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h Height
addr Image memory address
Definition at line 70 of file platform.c.
{
    /*
    lcd_image_rgb(u16 x, u16 y, u16 w, u16 h, u32 addr);
    */
}
References _memory, _pixels, gfx_color(), and GFX_WIDTH.
Referenced by syscall_gfx_image_rgb().
env_gfx_image_rgb565()
void env_gfx_image_rgb565 (i32 x, i32 y, i32 w, i32 h, u32 addr)
Draw an RGB565 image.
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h Height
addr Image memory address
Definition at line 77 of file platform.c.
{
    /*
    lcd_image_rgb565(u16 x, u16 y, u16 w, u16 h, u32 addr);
    */
}
References _memory, _pixels, _rgb565_to_bgra(), and GFX_WIDTH.
Referenced by syscall_gfx_image_rgb565().
env_gfx_image_rgba()
void env_gfx_image_rgba (i32 x, i32 y, i32 w, i32 h, u32 addr)
Draw an RGBA image.
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h Height
addr Image memory address
Definition at line 58 of file platform.c.
{
    /*
    xmem_read(args[0], &r, sizeof(r));
    fg = _abgr_to_rgb565(args[2]);
    bg = _abgr_to_rgb565(args[3]);
    lcd_image_rgba(u16 x, u16 y, u16 w, u16 h, u32 addr);
    */
}
References _abgr_to_argb(), _memory, _pixels, and GFX_WIDTH.
Referenced by syscall_gfx_image_rgba().
env_gfx_rect()
void env_gfx_rect (i32 x, i32 y, i32 w, i32 h, u32 color)
Draw rectangle.
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h Height
color Fill color
Definition at line 53 of file platform.c.
{
    lcd_rect(x, y, w, h, _abgr_to_rgb565(color));
}
References _abgr_to_argb(), _abgr_to_rgb565(), _pixels, GFX_WIDTH, and lcd_rect().
Referenced by syscall_gfx_rect().
env_memory_read()
void env_memory_read (u32 addr, void * data, u32 size)
Read data from physical memory.
Parameters
addr Start address
data Data buffer
size Size in bytes
Definition at line 23 of file platform.c.
{
    xmem_read(addr, data, size);
}
References _memory, memcpy(), and xmem_read().
Referenced by memory_lb(), memory_lbu(), memory_lh(), memory_lhu(), memory_lw(), syscall_gfx_image_1bit(), syscall_gfx_image_grayscale(), and syscall_serial_write().
env_memory_size()
u32 env_memory_size (void)
Get the size of the installed memory.
Returns
The size of the memory in bytes
Definition at line 18 of file platform.c.
{
    return xmem_size();
}
References _memory, and xmem_size().
Referenced by kernel_init().
env_memory_write()
void env_memory_write (u32 addr, const void * data, u32 size)
Write data to physical memory.
Parameters
addr Start address
data Data buffer
size Size in bytes
Definition at line 28 of file platform.c.
{
    xmem_write(addr, data, size);
}
References _memory, memcpy(), and xmem_write().
Referenced by memory_sb(), memory_sh(), and memory_sw().
env_millis()
u32 env_millis (void)
Get the number of milliseconds since boot.
Returns
The number of milliseconds
Definition at line 123 of file platform.c.
{
    return millis();
}
References _sec_start, _usec_start, and millis().
Referenced by syscall_millis().
env_random_get()
u32 env_random_get (void)
Generate a pseudo-random number.
Returns
The number
Definition at line 116 of file platform.c.
{
    return random_get();
}
References rand(), and random_get().
Referenced by syscall_rand().
env_serial_write()
void env_serial_write (const void * data, u32 len)
Send data over the serial interface.
Parameters
data The data to send
len The number of bytes
Definition at line 104 of file platform.c.
{
    u32 i;
    const char *data8 = data;
    for(i = 0; i < len; ++i)
    {
        serial_tx(data8[i]);
    }
}
References serial_tx().
Referenced by syscall_serial_write().