platform/avr/serial/serial.h File Reference
Serial interface driver.
Functions
void serial_init (void)
Initialize the serial port.
void serial_tx (char c)
Print a character.
void serial_tx_str (const char *s)
Print a null-terminated string.
void serial_tx_str_P (const char *s)
Print a null-terminated string from PROGMEM.
Detailed Description
Serial interface driver.
Author
Anton Tchekov
Version
0.1
Date
16.05.2023
Definition in file serial.h.
Function Documentation
serial_init()
void serial_init (void)
Initialize the serial port.
Definition at line 19 of file serial.c.
{
    UCSR0B = (1 << RXEN0) | (1 << TXEN0);
    UCSR0C = (1 << UCSZ01) | (1 << UCSZ00);
    UBRR0 = UART_PRESCALER;
}
References UART_PRESCALER.
Referenced by main().
serial_tx()
void serial_tx (char c)
Print a character.
Parameters
c The ASCII character to print
Definition at line 26 of file serial.c.
{
    while(!(UCSR0A & (1 << UDRE0))) {}
    UDR0 = c;
}
Referenced by _lcd_log(), env_serial_write(), log_boot_P(), memory_dump(), panic(), serial_tx_str(), and serial_tx_str_P().
serial_tx_str()
void serial_tx_str (const char * s)
Print a null-terminated string.
Parameters
s Pointer to string
Definition at line 32 of file serial.c.
{
    char c;
    while((c = *s++))
    {
        serial_tx(c);
    }
}
References serial_tx().
Referenced by _lcd_log(), and memory_dump().
serial_tx_str_P()
void serial_tx_str_P (const char * s)
Print a null-terminated string from PROGMEM.
Parameters
s Pointer to string in program memory
Definition at line 41 of file serial.c.
{
    char c;
    while((c = pgm_read_byte(s++)))
    {
        serial_tx(c);
    }
}
References serial_tx().
Referenced by _lcd_log().