platform/avr/ps2/ps2.c File Reference
#include <ps2.h>
#include <logger.h>
#include <gpio.h>
#include <avr/pgmspace.h>
#include <keys.h>
#include <keyboard-shared.h>
#include <layout.h>
#include <emulator.h>
Functions
void ps2_init (void)
Initialize PS/2 keyboard driver and interrupt, Interrupts must be enabled afterwards using sei().
static void ps2_event (u8 byte)
Event function that is called when a byte is received from the keyboard.
static u8 _ps2_data_read (void)
Get the PS/2 data line state.
static void _ps2_clock_falling_edge (void)
Called when a falling edge is detected on the PS/2 clock pin.
ISR (INT0_vect)
Variables
static u8 _byte
static u8 _bit
Detailed Description
Author
Haron Nazari, Anton Tchekov
Version
0.1
Date
16.05.2023
Definition in file ps2.c.
Function Documentation
_ps2_clock_falling_edge()
static void _ps2_clock_falling_edge (void) [inline], [static]
Called when a falling edge is detected on the PS/2 clock pin.
Definition at line 407 of file ps2.c.
{
    if(_bit == 0)
    {
        /* Start bit, reset byte */
        _byte = 0;
    }
    else if(_bit >= 1 && _bit <= 8)
    {
        /* Data bit */
        if(_ps2_data_read())
        {
            /* Set bit */
            _byte |= (1 << (_bit - 1));
        }
    }
    else if(_bit == 9)
    {
        /* Ignore parity bit */
        /* TODO: Check parity bit */
        ps2_event(_byte);
    }
    else if(_bit == 10)
    {
        /* Stop bit, reset bit counter */
        _bit = 0;
        /* Return immediately so it stays 0 */
        return;
    }
    ++_bit;
}
References _bit, _byte, _ps2_data_read(), and ps2_event().
Referenced by ISR().
_ps2_data_read()
static u8 _ps2_data_read (void) [inline], [static]
Get the PS/2 data line state.
Returns
0 if LOW, non-zero if HIGH
Definition at line 398 of file ps2.c.
{
    /* Read keyboard data pin */
    return PS2_DATA_PORT_IN & (1 << PS2_DATA_PIN);
}
References PS2_DATA_PIN, and PS2_DATA_PORT_IN.
Referenced by _ps2_clock_falling_edge().
ISR()
ISR (INT0_vect)
External interrupt
Definition at line 442 of file ps2.c.
{
    _ps2_clock_falling_edge();
}
References _ps2_clock_falling_edge().
ps2_event()
static void ps2_event (u8 byte) [static]
Event function that is called when a byte is received from the keyboard.
Parameters
byte The byte
Definition at line 189 of file ps2.c.
{
    static u8 state;
    static Key mods;
    Key key;
    /* TODO: Doesn't work, All keys, Buffering */
    /*
     * The following code translates PS/2 keyboard scancodes to USB HID
     * scancodes, which are then converted to characters by another
     * equally bad piece of code. This is horrible, but at least somewhat
     * maintainable.
     */
    key = 0;
    if(byte == PS2_BREAK)
    {
        state |= PS2_STATE_RELEASE;
        return;
    }
    else if(byte == PS2_EXTRA)
    {
        state |= PS2_STATE_EXTRA;
        return;
    }
    if(state & PS2_STATE_EXTRA)
    {
        switch(byte)
        {
            /* --- Keycodes with E0 prefix --- */
            case PS2_R_ALT: key = KEY_R_ALT; break;
            case PS2_R_CTRL: key = KEY_R_CTRL; break;
            case PS2_L_GUI: key = KEY_L_GUI; break;
            case PS2_R_GUI: key = KEY_R_GUI; break;
            case PS2_END: key = KEY_END; break;
            case PS2_HOME: key = KEY_HOME; break;
            case PS2_INSERT: key = KEY_INSERT; break;
            case PS2_DELETE: key = KEY_DELETE; break;
            case PS2_UP: key = KEY_UP; break;
            case PS2_DOWN: key = KEY_DOWN; break;
            case PS2_RIGHT: key = KEY_RIGHT; break;
            case PS2_LEFT: key = KEY_LEFT; break;
            case PS2_PAGE_UP: key = KEY_PAGE_UP; break;
            case PS2_PAGE_DOWN: key = KEY_PAGE_DOWN; break;
            case PS2_KP_DIVIDE: key = KEY_KP_DIVIDE; break;
            case PS2_KP_ENTER: key = KEY_KP_ENTER; break;
        }
        state &= ~PS2_STATE_EXTRA;
    }
    else
    {
        switch(byte)
        {
            /* --- 0 to 9 --- */
            case PS2_0: key = KEY_0; break;
            case PS2_1: key = KEY_1; break;
            case PS2_2: key = KEY_2; break;
            case PS2_3: key = KEY_3; break;
            case PS2_4: key = KEY_4; break;
            case PS2_5: key = KEY_5; break;
            case PS2_6: key = KEY_6; break;
            case PS2_7: key = KEY_7; break;
            case PS2_8: key = KEY_8; break;
            case PS2_9: key = KEY_9; break;
            /* --- A to Z --- */
            case PS2_A: key = KEY_A; break;
            case PS2_B: key = KEY_B; break;
            case PS2_C: key = KEY_C; break;
            case PS2_D: key = KEY_D; break;
            case PS2_E: key = KEY_E; break;
            case PS2_F: key = KEY_F; break;
            case PS2_G: key = KEY_G; break;
            case PS2_H: key = KEY_H; break;
            case PS2_I: key = KEY_I; break;
            case PS2_J: key = KEY_J; break;
            case PS2_K: key = KEY_K; break;
            case PS2_L: key = KEY_L; break;
            case PS2_M: key = KEY_M; break;
            case PS2_N: key = KEY_N; break;
            case PS2_O: key = KEY_O; break;
            case PS2_P: key = KEY_P; break;
            case PS2_Q: key = KEY_Q; break;
            case PS2_R: key = KEY_R; break;
            case PS2_S: key = KEY_S; break;
            case PS2_T: key = KEY_T; break;
            case PS2_U: key = KEY_U; break;
            case PS2_V: key = KEY_V; break;
            case PS2_W: key = KEY_W; break;
            case PS2_X: key = KEY_X; break;
            case PS2_Y: key = KEY_Y; break;
            case PS2_Z: key = KEY_Z; break;
            /* --- Function Keys --- */
            case PS2_F1: key = KEY_F1; break;
            case PS2_F2: key = KEY_F2; break;
            case PS2_F3: key = KEY_F3; break;
            case PS2_F4: key = KEY_F4; break;
            case PS2_F5: key = KEY_F5; break;
            case PS2_F6: key = KEY_F6; break;
            case PS2_F7: key = KEY_F7; break;
            case PS2_F8: key = KEY_F8; break;
            case PS2_F9: key = KEY_F9; break;
            case PS2_F10: key = KEY_F10; break;
            case PS2_F11: key = KEY_F11; break;
            case PS2_F12: key = KEY_F12; break;
            /* --- Keypad --- */
            case PS2_KP_0: key = KEY_KP_0; break;
            case PS2_KP_1: key = KEY_KP_1; break;
            case PS2_KP_2: key = KEY_KP_2; break;
            case PS2_KP_3: key = KEY_KP_3; break;
            case PS2_KP_4: key = KEY_KP_4; break;
            case PS2_KP_5: key = KEY_KP_5; break;
            case PS2_KP_6: key = KEY_KP_6; break;
            case PS2_KP_7: key = KEY_KP_7; break;
            case PS2_KP_8: key = KEY_KP_8; break;
            case PS2_KP_9: key = KEY_KP_9; break;
            case PS2_KP_PERIOD: key = KEY_KP_PERIOD; break;
            case PS2_KP_PLUS: key = KEY_KP_PLUS; break;
            case PS2_KP_MINUS: key = KEY_KP_MINUS; break;
            case PS2_KP_MULTIPLY: key = KEY_KP_MULTIPLY; break;
            /* --- Modifiers --- */
            case PS2_L_ALT: key = KEY_L_ALT; break;
            case PS2_L_SHIFT: key = KEY_L_SHIFT; break;
            case PS2_L_CTRL: key = KEY_L_CTRL; break;
            /* --- Other --- */
            case PS2_ESCAPE: key = KEY_ESCAPE; break;
            case PS2_TAB: key = KEY_TAB; break;
            case PS2_SPACE: key = KEY_SPACE; break;
            case PS2_BACKSPACE: key = KEY_BACKSPACE; break;
            case PS2_CAPSLOCK: key = KEY_CAPSLOCK; break;
            case PS2_RETURN: key = KEY_RETURN; break;
/*
            case PS2_COMMA: key = KEY_COMMA; break;
            case PS2_BACKTICK: key = KEY_BACKTICK; break;
            case PS2_PERIOD: key = KEY_PERIOD; break;
            case PS2_SLASH: key = KEY_SLASH; break;
            case PS2_SEMICOLON: key = KEY_SEMICOLON; break;
            case PS2_MINUS: key = KEY_MINUS; break;
            case PS2_APOSTROPHE: key = KEY_APOSTROPHE; break;
            case PS2_L_BRACKET: key = KEY_L_BRACKET; break;
            case PS2_EQUAL: key = KEY_EQUAL; break;
            case PS2_R_SHIFT: key = KEY_R_SHIFT; break;
            case PS2_R_BRACKET: key = KEY_R_BRACKET; break;
            case PS2_BACKSLASH: key = KEY_BACKSLASH; break;
*/
        }
    }
    if(key)
    {
        Key mod;
        /* handle modifiers */
        mod = 0;
        if(key == KEY_L_ALT)
        {
            mod = MOD_ALT;
        }
        else if(key == KEY_R_ALT)
        {
            mod = MOD_ALT_GR;
        }
        else if(key == KEY_L_SHIFT || key == KEY_R_SHIFT)
        {
            mod = MOD_SHIFT;
        }
        else if(key == KEY_L_CTRL || key == KEY_R_CTRL)
        {
            mod = MOD_CTRL;
        }
        else if(key == KEY_L_GUI || key == KEY_R_GUI)
        {
            mod = MOD_OS;
        }
        if(mod)
        {
            if(state & PS2_STATE_RELEASE)
            {
                mods &= ~mod;
            }
            else
            {
                mods |= mod;
            }
        }
        /* trigger key event */
        key |= mods;
        keyboard_event(key, key_to_codepoint(key),
            state & PS2_STATE_RELEASE ? KEYSTATE_RELEASED : KEYSTATE_PRESSED);
    }
    state &= ~PS2_STATE_RELEASE;
}
References key_to_codepoint(), and keyboard_event().
Referenced by _ps2_clock_falling_edge().
ps2_init()
void ps2_init (void)
Initialize PS/2 keyboard driver and interrupt, Interrupts must be enabled afterwards using sei().
Definition at line 172 of file ps2.c.
{
    /* Enable external interrupt 0 (PORTB2) */
    EIMSK |= (1 << PS2_EXT_INTERRUPT);
    /* Trigger interrupt on falling edge */
    EICRA |= (1 << ISC01);
    log_boot_P(LOG_INIT, PSTR("PS/2 keyboard initialized"));
}
References log_boot_P(), and PS2_EXT_INTERRUPT.
Referenced by main().
Variable Documentation
_bit
u8 _bit [static]
The number of the current bit:
0: Start bit 1-8: Data bit 9: Parity bit 10: Stop bit
Definition at line 170 of file ps2.c.
Referenced by _ps2_clock_falling_edge().
_byte
u8 _byte [static]
The byte that is currently being received
Definition at line 160 of file ps2.c.
Referenced by _ps2_clock_falling_edge().