platform/avr/random/random.c File Reference
#include <random.h>
#include <adc.h>
#include <logger.h>
#include <stdlib.h>
#include <avr/pgmspace.h>
Functions
void random_init (void)
Seeds the random module with hardware noise from the ADC. adc_init must be called before this function.
u32 random_get (void)
Generate a pseudo-random number.
Detailed Description
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
16.05.2023
Definition in file random.c.
Function Documentation
random_get()
u32 random_get (void)
Generate a pseudo-random number.
Returns
The number
Definition at line 20 of file random.c.
{
    return rand();
}
References rand().
Referenced by env_random_get().
random_init()
void random_init (void)
Seeds the random module with hardware noise from the ADC. adc_init must be called before this function.
Definition at line 14 of file random.c.
{
    srand(adc_read(ADC_CHANNEL_NOISE));
    log_boot_P(LOG_INIT, PSTR("RNG initialized"));
}
References ADC_CHANNEL_NOISE, adc_read(), and log_boot_P().