stdlib/rand/rand.c File Reference
#include <rand.h>
#include <syscall.h>
Functions
i32 rand (void)
Returns a pseudo-random integer. Generator is seeded with a hardware noise source.
Detailed Description
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
23.04.2023
Definition in file rand.c.
Function Documentation
rand()
i32 rand (void)
Returns a pseudo-random integer. Generator is seeded with a hardware noise source.
Definition at line 11 of file rand.c.
{
    return syscall0(SYSCALL_RAND);
}
References syscall0().
Referenced by _memtest(), env_random_get(), and random_get().