stdlib/rand/rand.h File Reference
(Pseudo-) Random number generation
#include <types.h>
Functions
i32 rand (void)
Returns a pseudo-random integer. Generator is seeded with a hardware noise source.
Detailed Description
(Pseudo-) Random number generation
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
23.04.2023
Definition in file rand.h.
Function Documentation
rand()
i32 rand (void)
Returns a pseudo-random integer. Generator is seeded with a hardware noise source.
Definition at line 11 of file rand.c.
{
    return syscall0(SYSCALL_RAND);
}
References syscall0().
Referenced by _memtest(), _new_piece(), env_random_get(), and random_get().