platform/avr/sd/sd.c File Reference
#include <sd.h>
#include <spi.h>
#include <logger.h>
#include <gpio.h>
#include <string.h>
#include <avr/io.h>
#include <avr/pgmspace.h>
#include <util/delay.h>
Macros
#define CMD_GO_IDLE_STATE 0x00
#define CMD_SEND_IF_COND 0x08
#define CMD_SEND_CSD 0x09
#define CMD_SEND_CID 0x0A
#define CMD_SET_BLOCKLEN 0x10
#define CMD_READ_SINGLE_BLOCK 0x11
#define CMD_WRITE_SINGLE_BLOCK 0x18
#define CMD_SEND_OP_COND 0x01
#define CMD_SD_SEND_OP_COND 0x29
#define CMD_APP 0x37
#define CMD_READ_OCR 0x3A
#define IDLE_STATE (1 << 0)
#define ILLEGAL_CMD (1 << 2)
#define SD_1 (1 << 0)
#define SD_2 (1 << 1)
#define SD_HC (1 << 2)
Functions
static void _spi_configure_slow (void)
Put SPI into slow mode for initialization.
static void _sd_timeout (void)
Trigger an SD timeout panic.
static void _sd_error (void)
Trigger an SD error panic.
static u8 _sd_command (u8 cmd, u32 arg)
Execute an SD command (panic if failed)
static Status _sd_command_try (u8 cmd, u32 arg)
Try to execute an SD command.
static u32 _sd_block_addr (u32 block)
Convert block number to internal SD address since SD uses byte address but SDHC uses block number.
static void _sd_info_print (void)
Print SD card info to serial port.
void sd_init (void)
Initialize SD driver and try to detect card.
u32 sd_size (void)
Get SD card capacity.
Status sd_read (u32 block, void *data)
Read a single 512-byte block from the SD card.
Status sd_write (u32 block, const void *data)
Write a single 512-byte block to the SD card.
Variables
static u32 _serial
static u32 _capacity
static u8 _oem [3]
static u8 _product [6]
static u8 _card_type
static u8 _manufacturer
static u8 _revision
static u8 _manufacturing_year
static u8 _manufacturing_month
static u8 _flag_copy
static u8 _flag_write_protect
static u8 _flag_write_protect_temp
static u8 _format
Detailed Description
Author
Anton Tchekov
Version
0.2
Date
20.05.2023
Definition in file sd.c.
Macro Definition Documentation
CMD_APP
#define CMD_APP 0x37
SD send app command
Definition at line 45 of file sd.c.
CMD_GO_IDLE_STATE
#define CMD_GO_IDLE_STATE 0x00
SD go to idle state command
Definition at line 18 of file sd.c.
CMD_READ_OCR
#define CMD_READ_OCR 0x3A
SD read operation conditions register
Definition at line 48 of file sd.c.
CMD_READ_SINGLE_BLOCK
#define CMD_READ_SINGLE_BLOCK 0x11
SD read single block command
Definition at line 33 of file sd.c.
CMD_SD_SEND_OP_COND
#define CMD_SD_SEND_OP_COND 0x29
SD set OP cond
Definition at line 42 of file sd.c.
CMD_SEND_CID
#define CMD_SEND_CID 0x0A
SD read card identification number
Definition at line 27 of file sd.c.
CMD_SEND_CSD
#define CMD_SEND_CSD 0x09
SD read card-specific data register
Definition at line 24 of file sd.c.
CMD_SEND_IF_COND
#define CMD_SEND_IF_COND 0x08
SD send IF cond
Definition at line 21 of file sd.c.
CMD_SEND_OP_COND
#define CMD_SEND_OP_COND 0x01
SDHC set OP cond
Definition at line 39 of file sd.c.
CMD_SET_BLOCKLEN
#define CMD_SET_BLOCKLEN 0x10
SD set block length command
Definition at line 30 of file sd.c.
CMD_WRITE_SINGLE_BLOCK
#define CMD_WRITE_SINGLE_BLOCK 0x18
SD write single block command
Definition at line 36 of file sd.c.
IDLE_STATE
#define IDLE_STATE (1 << 0)
SD idle
Definition at line 51 of file sd.c.
ILLEGAL_CMD
#define ILLEGAL_CMD (1 << 2)
SD illegal command
Definition at line 54 of file sd.c.
SD_1
#define SD_1 (1 << 0)
SD card type 1
Definition at line 57 of file sd.c.
SD_2
#define SD_2 (1 << 1)
SD card type 2
Definition at line 60 of file sd.c.
SD_HC
#define SD_HC (1 << 2)
SDHC card type
Definition at line 63 of file sd.c.
Function Documentation
_sd_block_addr()
static u32 _sd_block_addr (u32 block) [static]
Convert block number to internal SD address since SD uses byte address but SDHC uses block number.
Parameters
block Block number
Returns
Internal Address
Definition at line 217 of file sd.c.
{
    return _card_type & SD_HC ? block : (block << BLOCK_SIZE_POT);
}
References _card_type, BLOCK_SIZE_POT, and SD_HC.
Referenced by sd_read(), and sd_write().
_sd_command()
static u8 _sd_command (u8 cmd, u32 arg) [static]
Execute an SD command (panic if failed)
Parameters
cmd Command number
arg Address parameter
Returns
Output byte
Definition at line 142 of file sd.c.
{
    u8 i, response;
    spi_xchg(0xFF);
    spi_xchg(0x40 | cmd);
    spi_xchg((arg >> 24) & 0xFF);
    spi_xchg((arg >> 16) & 0xFF);
    spi_xchg((arg >> 8) & 0xFF);
    spi_xchg((arg >> 0) & 0xFF);
    switch(cmd)
    {
    case CMD_GO_IDLE_STATE:
        spi_xchg(0x95);
        break;
    case CMD_SEND_IF_COND:
        spi_xchg(0x87);
        break;
    default:
        spi_xchg(0xFF);
        break;
    }
    for(i = 0; i < 10 && ((response = spi_xchg(0xFF)) == 0xFF); ++i) ;
    return response;
}
References CMD_GO_IDLE_STATE, CMD_SEND_IF_COND, and spi_xchg().
Referenced by sd_init().
_sd_command_try()
static Status _sd_command_try (u8 cmd, u32 arg) [static]
Try to execute an SD command.
Parameters
cmd Command number
arg Address parameter
Returns
Status response
Definition at line 177 of file sd.c.
{
    u8 i, response;
    RETURN_IF(spi_tx_try(0xFF));
    RETURN_IF(spi_tx_try(0x40 | cmd));
    RETURN_IF(spi_tx_try(arg >> 24));
    RETURN_IF(spi_tx_try(arg >> 16));
    RETURN_IF(spi_tx_try(arg >> 8));
    RETURN_IF(spi_tx_try(arg));
    RETURN_IF(spi_tx_try(0xFF));
    for(i = 0; ; ++i)
    {
        RETURN_IF(spi_rx_try(&response));
        if(response != 0xFF)
        {
            break;
        }
        if(i >= 10)
        {
            return STATUS_TIMEOUT;
        }
    }
    if(response)
    {
        SD_DESELECT;
        return STATUS_FAIL;
    }
    return STATUS_OK;
}
References RETURN_IF, SD_DESELECT, spi_rx_try(), and spi_tx_try().
Referenced by sd_read(), and sd_write().
_sd_error()
static void _sd_error (void) [static]
Trigger an SD error panic.
Definition at line 129 of file sd.c.
{
    SD_DESELECT;
    panic(PSTR("SD error"));
}
References panic(), and SD_DESELECT.
Referenced by sd_init().
_sd_info_print()
static void _sd_info_print (void) [static]
Print SD card info to serial port.
Definition at line 225 of file sd.c.
{
    log_boot_P(LOG_DEBUG, PSTR("Card Type : %S"),
        _card_type & SD_HC ? PSTR("SDHC") : PSTR("SD"));
    log_boot_P(LOG_DEBUG, PSTR("Block Size : %d"),
        BLOCK_SIZE);
    log_boot_P(LOG_DEBUG, PSTR("Manufacturer ID : %02X"),
        _manufacturer);
    log_boot_P(LOG_DEBUG, PSTR("OEM : %s"),
        _oem);
    log_boot_P(LOG_DEBUG, PSTR("Product Name : %s"),
        _product);
    log_boot_P(LOG_DEBUG, PSTR("Revision : %c.%c"),
        (_revision >> 4) + '0', (_revision & 0x0F) + '0');
    log_boot_P(LOG_DEBUG, PSTR("Serial Number : 0x%08"PRIx32),
        _serial);
    log_boot_P(LOG_DEBUG, PSTR("Manufacture Date : %02d-%d"),
        _manufacturing_month, 2000 + _manufacturing_year);
    log_boot_P(LOG_DEBUG, PSTR("Capacity : %"PRIu32" blocks"),
        _capacity);
    log_boot_P(LOG_OFFSET, PSTR(" (%"PRIu32" bytes)"),
        _capacity * BLOCK_SIZE);
    log_boot_P(LOG_DEBUG, PSTR("Format : 0x%02X"),
        _format);
    log_boot_P(LOG_DEBUG, PSTR("Flags : %S%S"),
        _flag_copy ? PSTR("Copy, ") : PSTR("Original, "),
        _flag_write_protect_temp ? PSTR("Temporarily Write Protected") :
            (_flag_write_protect ? PSTR("Write Protected") :
            PSTR("Rewritable")));
}
References _capacity, _card_type, _flag_copy, _flag_write_protect, _flag_write_protect_temp, _format, _manufacturer, _manufacturing_month, _manufacturing_year, _oem, _product, _revision, _serial, BLOCK_SIZE, log_boot_P(), and SD_HC.
Referenced by sd_init().
_sd_timeout()
static void _sd_timeout (void) [static]
Trigger an SD timeout panic.
Definition at line 120 of file sd.c.
{
    SD_DESELECT;
    panic(PSTR("SD timeout"));
}
References panic(), and SD_DESELECT.
Referenced by sd_init().
_spi_configure_slow()
static void _spi_configure_slow (void) [static]
Put SPI into slow mode for initialization.
Definition at line 111 of file sd.c.
{
    SPCR |= (1 << SPR1) | (1 << SPR0);
    SPSR &= ~(1 << SPI2X);
}
Referenced by sd_init().
sd_init()
void sd_init (void)
Initialize SD driver and try to detect card.
Definition at line 268 of file sd.c.
{
    log_boot_P(LOG_INIT, PSTR("SD driver starting"));
    {
        u8 response;
        u16 i;
        u32 arg;
        SD_DESELECT;
        _spi_configure_slow();
        _card_type = 0;
        for(i = 0; i < 10; ++i)
        {
            spi_xchg(0xFF);
        }
        SD_SELECT;
        for(i = 0; ; ++i)
        {
            if(_sd_command(CMD_GO_IDLE_STATE, 0) == IDLE_STATE)
            {
                break;
            }
            if(i == 0x1FF)
            {
                _sd_timeout();
            }
        }
        if((_sd_command(CMD_SEND_IF_COND, 0x1AA) & ILLEGAL_CMD) == 0)
        {
            spi_xchg(0xFF);
            spi_xchg(0xFF);
            if(((spi_xchg(0xFF) & 0x01) == 0) ||
                (spi_xchg(0xFF) != 0xAA))
            {
                _sd_error();
            }
            _card_type |= SD_2;
        }
        else
        {
            _sd_command(CMD_APP, 0);
            if((_sd_command(CMD_SD_SEND_OP_COND, 0) & ILLEGAL_CMD) == 0)
            {
                _card_type |= SD_1;
            }
        }
        for(i = 0; ; ++i)
        {
            if(_card_type & (SD_1 | SD_2))
            {
                arg = 0;
                if(_card_type & SD_2)
                {
                    arg = 0x40000000;
                }
                _sd_command(CMD_APP, 0);
                response = _sd_command(CMD_SD_SEND_OP_COND, arg);
            }
            else
            {
                response = _sd_command(CMD_SEND_OP_COND, 0);
            }
            if((response & IDLE_STATE) == 0)
            {
                break;
            }
            if(i == 0x7FFF)
            {
                _sd_timeout();
            }
        }
        if(_card_type & SD_2)
        {
            if(_sd_command(CMD_READ_OCR, 0))
            {
                _sd_error();
            }
            if(spi_xchg(0xFF) & 0x40)
            {
                _card_type |= SD_HC;
            }
            spi_xchg(0xFF);
            spi_xchg(0xFF);
            spi_xchg(0xFF);
        }
        if(_sd_command(CMD_SET_BLOCKLEN, 512))
        {
            _sd_error();
        }
        SD_DESELECT;
        spi_fast();
        _delay_ms(20);
    }
    log_boot_P(LOG_INIT, PSTR("SD card initialized"));
    log_boot_P(LOG_INIT, PSTR("Reading SD card parameters"));
    {
        u8 i, b, csd_read_bl_len, csd_c_size_mult, csd_structure;
        u16 j, csd_c_size;
        spi_fast();
        SD_SELECT;
        /* Read CID register */
        _sd_command(CMD_SEND_CID, 0);
        j = 0;
        while(spi_xchg(0xFF) != 0xFE)
        {
            if(++j > 0x7FFF)
            {
                _sd_timeout();
            }
        }
        for(i = 0; i < 18; ++i)
        {
            b = spi_xchg(0xFF);
            switch(i)
            {
                case 0:
                    _manufacturer = b;
                    break;
                case 1:
                case 2:
                    _oem[i - 1] = b;
                    break;
                case 3:
                case 4:
                case 5:
                case 6:
                case 7:
                    _product[i - 3] = b;
                    break;
                case 8:
                    _revision = b;
                    break;
                case 9:
                case 10:
                case 11:
                case 12:
                    _serial |= (u32)b << ((12 - i) * 8);
                    break;
                case 13:
                    _manufacturing_year = b << 4;
                    break;
                case 14:
                    _manufacturing_year |= b >> 4;
                    _manufacturing_month = b & 0x0f;
                    break;
            }
        }
        /* Read CSD register */
        csd_read_bl_len = 0;
        csd_c_size_mult = 0;
        csd_structure = 0;
        csd_c_size = 0;
        _sd_command(CMD_SEND_CSD, 0);
        j = 0;
        while(spi_xchg(0xFF) != 0xFE)
        {
            if(++j > 0x7FFF)
            {
                _sd_timeout();
            }
        }
        for(i = 0; i < 18; ++i)
        {
            b = spi_xchg(0xFF);
            if(i == 0)
            {
                csd_structure = b >> 6;
            }
            else if(i == 14)
            {
                if(b & 0x40)
                {
                    _flag_copy = 1;
                }
                if(b & 0x20)
                {
                    _flag_write_protect = 1;
                }
                if(b & 0x10)
                {
                    _flag_write_protect_temp = 1;
                }
                _format = (b & 0x0C) >> 2;
            }
            else
            {
                if(csd_structure == 0x01)
                {
                    switch(i)
                    {
                        case 7:
                            b &= 0x3f;
                        case 8:
                        case 9:
                            csd_c_size <<= 8;
                            csd_c_size |= b;
                            ++csd_c_size;
                            _capacity = (u32)csd_c_size << 10;
                    }
                }
                else if(csd_structure == 0x00)
                {
                    switch(i)
                    {
                        case 5:
                            csd_read_bl_len = b & 0x0F;
                            break;
                        case 6:
                            csd_c_size = b & 0x03;
                            csd_c_size <<= 8;
                            break;
                        case 7:
                            csd_c_size |= b;
                            csd_c_size <<= 2;
                            break;
                        case 8:
                            csd_c_size |= b >> 6;
                            ++csd_c_size;
                            break;
                        case 9:
                            csd_c_size_mult = b & 0x03;
                            csd_c_size_mult <<= 1;
                            break;
                        case 10:
                            csd_c_size_mult |= b >> 7;
                            _capacity = ((u32)csd_c_size <<
                                (csd_c_size_mult + csd_read_bl_len + 2)) >> 9;
                            break;
                    }
                }
            }
        }
        SD_DESELECT;
    }
    /* Print disk info */
    _sd_info_print();
}
References _capacity, _card_type, _flag_copy, _flag_write_protect, _flag_write_protect_temp, _format, _manufacturer, _manufacturing_month, _manufacturing_year, _oem, _product, _revision, _sd_command(), _sd_error(), _sd_info_print(), _sd_timeout(), _serial, _spi_configure_slow(), CMD_APP, CMD_GO_IDLE_STATE, CMD_READ_OCR, CMD_SD_SEND_OP_COND, CMD_SEND_CID, CMD_SEND_CSD, CMD_SEND_IF_COND, CMD_SEND_OP_COND, CMD_SET_BLOCKLEN, IDLE_STATE, ILLEGAL_CMD, log_boot_P(), SD_1, SD_2, SD_DESELECT, SD_HC, SD_SELECT, spi_fast(), and spi_xchg().
Referenced by main().
sd_read()
Status sd_read (u32 block, void * data)
Read a single 512-byte block from the SD card.
Parameters
block SD card block id
data Data output
Returns
Read status
Definition at line 550 of file sd.c.
{
    u16 i;
    u8 *data8, response;
    data8 = data;
    SD_SELECT;
    /* Start read */
    RETURN_IF(_sd_command_try(CMD_READ_SINGLE_BLOCK,
        _sd_block_addr(block)));
    /* Wait for ready */
    for(i = 0; ; ++i)
    {
        RETURN_IF(spi_rx_try(&response));
        if(response == 0xFE)
        {
            break;
        }
        if(i == 0xFFFF)
        {
            SD_DESELECT;
            return STATUS_TIMEOUT;
        }
    }
    /* Read data */
    for(i = 0; i < BLOCK_SIZE; ++i)
    {
        RETURN_IF(spi_rx_try(&data8[i]));
    }
    RETURN_IF(spi_tx_try(0xFF));
    RETURN_IF(spi_tx_try(0xFF));
    RETURN_IF(spi_tx_try(0xFF));
    SD_DESELECT;
    return STATUS_OK;
}
References _sd_block_addr(), _sd_command_try(), BLOCK_SIZE, CMD_READ_SINGLE_BLOCK, RETURN_IF, SD_DESELECT, SD_SELECT, spi_rx_try(), and spi_tx_try().
Referenced by initrd_load().
sd_size()
u32 sd_size (void)
Get SD card capacity.
Returns
Capacity in 512-byte blocks
Definition at line 545 of file sd.c.
{
    return _capacity;
}
References _capacity.
sd_write()
Status sd_write (u32 block, const void * data)
Write a single 512-byte block to the SD card.
Parameters
block SD card block id
data Data input
Returns
Write status
Definition at line 591 of file sd.c.
{
    u16 i;
    u8 response;
    const u8 *data8;
    data8 = data;
    SD_SELECT;
    /* Start write */
    RETURN_IF(_sd_command_try(CMD_WRITE_SINGLE_BLOCK,
        _sd_block_addr(block)))
    RETURN_IF(spi_tx_try(0xFE));
    for(i = 0; i < 512; ++i)
    {
        RETURN_IF(spi_tx_try(*data8++));
    }
    RETURN_IF(spi_tx_try(0xFF));
    RETURN_IF(spi_tx_try(0xFF));
    /* Wait for ready */
    for(i = 0; ; ++i)
    {
        RETURN_IF(spi_rx_try(&response));
        if(response == 0xFF)
        {
            break;
        }
        if(i == 0xFFFF)
        {
            SD_DESELECT;
            return STATUS_TIMEOUT;
        }
    }
    RETURN_IF(spi_tx_try(0xFF));
    SD_DESELECT;
    return STATUS_OK;
}
References _sd_block_addr(), _sd_command_try(), CMD_WRITE_SINGLE_BLOCK, RETURN_IF, SD_DESELECT, SD_SELECT, spi_rx_try(), and spi_tx_try().
Variable Documentation
_capacity
u32 _capacity [static]
SD card capacity in 512-byte blocks
Definition at line 71 of file sd.c.
Referenced by _sd_info_print(), sd_init(), and sd_size().
_card_type
u8 _card_type [static]
SD card type: SD1 / SD2 / SDHC
Definition at line 80 of file sd.c.
Referenced by _sd_block_addr(), _sd_info_print(), and sd_init().
_flag_copy
u8 _flag_copy [static]
SD card copy/original flag
Definition at line 95 of file sd.c.
Referenced by _sd_info_print(), and sd_init().
_flag_write_protect
u8 _flag_write_protect [static]
SD card write protected flag
Definition at line 98 of file sd.c.
Referenced by _sd_info_print(), and sd_init().
_flag_write_protect_temp
u8 _flag_write_protect_temp [static]
SD card temporarily write protected flag
Definition at line 101 of file sd.c.
Referenced by _sd_info_print(), and sd_init().
_format
u8 _format [static]
SD card format ID
Definition at line 104 of file sd.c.
Referenced by _sd_info_print(), and sd_init().
_manufacturer
u8 _manufacturer [static]
SD manufacturer ID
Definition at line 83 of file sd.c.
Referenced by _sd_info_print(), and sd_init().
_manufacturing_month
u8 _manufacturing_month [static]
SD card manufacturing month number
Definition at line 92 of file sd.c.
Referenced by _sd_info_print(), and sd_init().
_manufacturing_year
u8 _manufacturing_year [static]
SD card manufacturing year after 2000
Definition at line 89 of file sd.c.
Referenced by _sd_info_print(), and sd_init().
_oem
u8 _oem[3] [static]
SD card OEM name: 2 characters + null-terminator
Definition at line 74 of file sd.c.
Referenced by _sd_info_print(), and sd_init().
_product
u8 _product[6] [static]
SD card product name: 5 characters + null-terminator
Definition at line 77 of file sd.c.
Referenced by _sd_info_print(), and sd_init().
_revision
u8 _revision [static]
SD card revision number as packed BCD
Definition at line 86 of file sd.c.
Referenced by _sd_info_print(), and sd_init().
_serial
u32 _serial [static]
SD card serial number
Definition at line 68 of file sd.c.
Referenced by _sd_info_print(), and sd_init().