platform/avr/sd/sd.h File Reference
SD card driver.
#include <types.h>
#include <status.h>
Macros
#define BLOCK_SIZE 512
#define BLOCK_SIZE_POT 9
Functions
void sd_init (void)
Initialize SD driver and try to detect card.
u32 sd_size (void)
Get SD card capacity.
Status sd_read (u32 block, void *data)
Read a single 512-byte block from the SD card.
Status sd_write (u32 block, const void *data)
Write a single 512-byte block to the SD card.
Detailed Description
SD card driver.
Author
Anton Tchekov
Version
0.1
Date
18.05.2023
Definition in file sd.h.
Macro Definition Documentation
BLOCK_SIZE
#define BLOCK_SIZE 512
SD card block size in bytes
Definition at line 16 of file sd.h.
BLOCK_SIZE_POT
#define BLOCK_SIZE_POT 9
SD card block size as a power of two
Definition at line 19 of file sd.h.
Function Documentation
sd_init()
void sd_init (void)
Initialize SD driver and try to detect card.
Definition at line 268 of file sd.c.
{
    log_boot_P(LOG_INIT, PSTR("SD driver starting"));
    {
        u8 response;
        u16 i;
        u32 arg;
        SD_DESELECT;
        _spi_configure_slow();
        _card_type = 0;
        for(i = 0; i < 10; ++i)
        {
            spi_xchg(0xFF);
        }
        SD_SELECT;
        for(i = 0; ; ++i)
        {
            if(_sd_command(CMD_GO_IDLE_STATE, 0) == IDLE_STATE)
            {
                break;
            }
            if(i == 0x1FF)
            {
                _sd_timeout();
            }
        }
        if((_sd_command(CMD_SEND_IF_COND, 0x1AA) & ILLEGAL_CMD) == 0)
        {
            spi_xchg(0xFF);
            spi_xchg(0xFF);
            if(((spi_xchg(0xFF) & 0x01) == 0) ||
                (spi_xchg(0xFF) != 0xAA))
            {
                _sd_error();
            }
            _card_type |= SD_2;
        }
        else
        {
            _sd_command(CMD_APP, 0);
            if((_sd_command(CMD_SD_SEND_OP_COND, 0) & ILLEGAL_CMD) == 0)
            {
                _card_type |= SD_1;
            }
        }
        for(i = 0; ; ++i)
        {
            if(_card_type & (SD_1 | SD_2))
            {
                arg = 0;
                if(_card_type & SD_2)
                {
                    arg = 0x40000000;
                }
                _sd_command(CMD_APP, 0);
                response = _sd_command(CMD_SD_SEND_OP_COND, arg);
            }
            else
            {
                response = _sd_command(CMD_SEND_OP_COND, 0);
            }
            if((response & IDLE_STATE) == 0)
            {
                break;
            }
            if(i == 0x7FFF)
            {
                _sd_timeout();
            }
        }
        if(_card_type & SD_2)
        {
            if(_sd_command(CMD_READ_OCR, 0))
            {
                _sd_error();
            }
            if(spi_xchg(0xFF) & 0x40)
            {
                _card_type |= SD_HC;
            }
            spi_xchg(0xFF);
            spi_xchg(0xFF);
            spi_xchg(0xFF);
        }
        if(_sd_command(CMD_SET_BLOCKLEN, 512))
        {
            _sd_error();
        }
        SD_DESELECT;
        spi_fast();
        _delay_ms(20);
    }
    log_boot_P(LOG_INIT, PSTR("SD card initialized"));
    log_boot_P(LOG_INIT, PSTR("Reading SD card parameters"));
    {
        u8 i, b, csd_read_bl_len, csd_c_size_mult, csd_structure;
        u16 j, csd_c_size;
        spi_fast();
        SD_SELECT;
        /* Read CID register */
        _sd_command(CMD_SEND_CID, 0);
        j = 0;
        while(spi_xchg(0xFF) != 0xFE)
        {
            if(++j > 0x7FFF)
            {
                _sd_timeout();
            }
        }
        for(i = 0; i < 18; ++i)
        {
            b = spi_xchg(0xFF);
            switch(i)
            {
                case 0:
                    _manufacturer = b;
                    break;
                case 1:
                case 2:
                    _oem[i - 1] = b;
                    break;
                case 3:
                case 4:
                case 5:
                case 6:
                case 7:
                    _product[i - 3] = b;
                    break;
                case 8:
                    _revision = b;
                    break;
                case 9:
                case 10:
                case 11:
                case 12:
                    _serial |= (u32)b << ((12 - i) * 8);
                    break;
                case 13:
                    _manufacturing_year = b << 4;
                    break;
                case 14:
                    _manufacturing_year |= b >> 4;
                    _manufacturing_month = b & 0x0f;
                    break;
            }
        }
        /* Read CSD register */
        csd_read_bl_len = 0;
        csd_c_size_mult = 0;
        csd_structure = 0;
        csd_c_size = 0;
        _sd_command(CMD_SEND_CSD, 0);
        j = 0;
        while(spi_xchg(0xFF) != 0xFE)
        {
            if(++j > 0x7FFF)
            {
                _sd_timeout();
            }
        }
        for(i = 0; i < 18; ++i)
        {
            b = spi_xchg(0xFF);
            if(i == 0)
            {
                csd_structure = b >> 6;
            }
            else if(i == 14)
            {
                if(b & 0x40)
                {
                    _flag_copy = 1;
                }
                if(b & 0x20)
                {
                    _flag_write_protect = 1;
                }
                if(b & 0x10)
                {
                    _flag_write_protect_temp = 1;
                }
                _format = (b & 0x0C) >> 2;
            }
            else
            {
                if(csd_structure == 0x01)
                {
                    switch(i)
                    {
                        case 7:
                            b &= 0x3f;
                        case 8:
                        case 9:
                            csd_c_size <<= 8;
                            csd_c_size |= b;
                            ++csd_c_size;
                            _capacity = (u32)csd_c_size << 10;
                    }
                }
                else if(csd_structure == 0x00)
                {
                    switch(i)
                    {
                        case 5:
                            csd_read_bl_len = b & 0x0F;
                            break;
                        case 6:
                            csd_c_size = b & 0x03;
                            csd_c_size <<= 8;
                            break;
                        case 7:
                            csd_c_size |= b;
                            csd_c_size <<= 2;
                            break;
                        case 8:
                            csd_c_size |= b >> 6;
                            ++csd_c_size;
                            break;
                        case 9:
                            csd_c_size_mult = b & 0x03;
                            csd_c_size_mult <<= 1;
                            break;
                        case 10:
                            csd_c_size_mult |= b >> 7;
                            _capacity = ((u32)csd_c_size <<
                                (csd_c_size_mult + csd_read_bl_len + 2)) >> 9;
                            break;
                    }
                }
            }
        }
        SD_DESELECT;
    }
    /* Print disk info */
    _sd_info_print();
}
References _capacity, _card_type, _flag_copy, _flag_write_protect, _flag_write_protect_temp, _format, _manufacturer, _manufacturing_month, _manufacturing_year, _oem, _product, _revision, _sd_command(), _sd_error(), _sd_info_print(), _sd_timeout(), _serial, _spi_configure_slow(), CMD_APP, CMD_GO_IDLE_STATE, CMD_READ_OCR, CMD_SD_SEND_OP_COND, CMD_SEND_CID, CMD_SEND_CSD, CMD_SEND_IF_COND, CMD_SEND_OP_COND, CMD_SET_BLOCKLEN, IDLE_STATE, ILLEGAL_CMD, log_boot_P(), SD_1, SD_2, SD_DESELECT, SD_HC, SD_SELECT, spi_fast(), and spi_xchg().
Referenced by main().
sd_read()
Status sd_read (u32 block, void * data)
Read a single 512-byte block from the SD card.
Parameters
block SD card block id
data Data output
Returns
Read status
Definition at line 550 of file sd.c.
{
    u16 i;
    u8 *data8, response;
    data8 = data;
    SD_SELECT;
    /* Start read */
    RETURN_IF(_sd_command_try(CMD_READ_SINGLE_BLOCK,
        _sd_block_addr(block)));
    /* Wait for ready */
    for(i = 0; ; ++i)
    {
        RETURN_IF(spi_rx_try(&response));
        if(response == 0xFE)
        {
            break;
        }
        if(i == 0xFFFF)
        {
            SD_DESELECT;
            return STATUS_TIMEOUT;
        }
    }
    /* Read data */
    for(i = 0; i < BLOCK_SIZE; ++i)
    {
        RETURN_IF(spi_rx_try(&data8[i]));
    }
    RETURN_IF(spi_tx_try(0xFF));
    RETURN_IF(spi_tx_try(0xFF));
    RETURN_IF(spi_tx_try(0xFF));
    SD_DESELECT;
    return STATUS_OK;
}
References _sd_block_addr(), _sd_command_try(), BLOCK_SIZE, CMD_READ_SINGLE_BLOCK, RETURN_IF, SD_DESELECT, SD_SELECT, spi_rx_try(), and spi_tx_try().
Referenced by initrd_load().
sd_size()
u32 sd_size (void)
Get SD card capacity.
Returns
Capacity in 512-byte blocks
Definition at line 545 of file sd.c.
{
    return _capacity;
}
References _capacity.
sd_write()
Status sd_write (u32 block, const void * data)
Write a single 512-byte block to the SD card.
Parameters
block SD card block id
data Data input
Returns
Write status
Definition at line 591 of file sd.c.
{
    u16 i;
    u8 response;
    const u8 *data8;
    data8 = data;
    SD_SELECT;
    /* Start write */
    RETURN_IF(_sd_command_try(CMD_WRITE_SINGLE_BLOCK,
        _sd_block_addr(block)))
    RETURN_IF(spi_tx_try(0xFE));
    for(i = 0; i < 512; ++i)
    {
        RETURN_IF(spi_tx_try(*data8++));
    }
    RETURN_IF(spi_tx_try(0xFF));
    RETURN_IF(spi_tx_try(0xFF));
    /* Wait for ready */
    for(i = 0; ; ++i)
    {
        RETURN_IF(spi_rx_try(&response));
        if(response == 0xFF)
        {
            break;
        }
        if(i == 0xFFFF)
        {
            SD_DESELECT;
            return STATUS_TIMEOUT;
        }
    }
    RETURN_IF(spi_tx_try(0xFF));
    SD_DESELECT;
    return STATUS_OK;
}
References _sd_block_addr(), _sd_command_try(), CMD_WRITE_SINGLE_BLOCK, RETURN_IF, SD_DESELECT, SD_SELECT, spi_rx_try(), and spi_tx_try().