platform/simulator/platform.c File Reference
OS simulator platform.
#include <emulator.h>
#include <platform.h>
#include <SDL2/SDL.h>
#include <sys/time.h>
#include <stdio.h>
#include <assert.h>
#include <time.h>
#include <stdlib.h>
#include <util.h>
#include <status.h>
#include <keyboard-shared.h>
#include <layout.h>
#include <gfx-types.h>
Macros
#define WINDOW_TITLE `OS Simulator`
#define READ_SIZE 1024
Functions
u32 env_memory_size (void)
Get the size of the installed memory.
void env_memory_read (u32 addr, void *data, u32 size)
Read data from physical memory.
void env_memory_write (u32 addr, const void *data, u32 size)
Write data to physical memory.
void memory_dump (u32 address, u32 length)
Dump emulator memory from address with length.
static void gfx_init (void)
Initialize SDL graphics.
static void gfx_destroy (void)
Destructor for SDL graphics renderer.
static u32 gfx_color (u8 r, u8 g, u8 b)
Generate ABGR color from red, green and blue channel values.
static u8 _abgr_r (u32 color)
Extract red channel from ABGR color.
static u8 _abgr_g (u32 color)
Extract green channel from ABGR color.
static u8 _abgr_b (u32 color)
Extract blue channel from ABGR color.
static u32 _abgr_to_argb (u32 color)
Convert a ABGR color to a ARGB color.
static u32 _color_merge (u32 color1, u32 color2, u32 ratio)
Mix two colors according to a ratio. A ratio of 255 means 100% of the first color and 0% of the second color will be mixed together.
static u32 _rgb565_to_bgra (u16 color)
Convert a RGB565 color to an BGRA color.
void env_gfx_rect (i32 x, i32 y, i32 w, i32 h, u32 color)
Draw rectangle.
void env_gfx_image_rgba (i32 x, i32 y, i32 w, i32 h, u32 addr)
Draw an RGBA image.
void env_gfx_image_rgb (i32 x, i32 y, i32 w, i32 h, u32 addr)
Draw an RGB image.
void env_gfx_image_rgb565 (i32 x, i32 y, i32 w, i32 h, u32 addr)
Draw an RGB565 image.
void env_gfx_image_grayscale (i32 x, i32 y, i32 w, i32 h, u32 addr, u32 fg, u32 bg)
Draw a colored grayscale image.
void env_gfx_image_1bit (i32 x, i32 y, i32 w, i32 h, u32 addr, u32 fg, u32 bg)
Draw a colored 1-bit image.
void env_serial_write (const void *data, u32 len)
Send data over the serial interface.
u32 env_random_get (void)
Generate a pseudo-random number.
static void timer_init (void)
Initialize simulated millisecond timer.
u32 env_millis (void)
Get the number of milliseconds since boot.
static Key _convert_key (i32 scancode, i32 mod)
Combine scancode and key modifiers into one value.
int main (int argc, char **argv)
Simulator main function.
Variables
static u8 _memory [3 *128 *1024]
static u32 _pixels [GFX_HEIGHT *GFX_WIDTH]
static u32 _sec_start
static u32 _usec_start
static SDL_Texture * _framebuffer
static SDL_Window * _window
static SDL_Renderer * _renderer
Detailed Description
OS simulator platform.
Author
Anton Tchekov
Version
0.1
Date
25.05.2023
Definition in file platform.c.
Macro Definition Documentation
READ_SIZE
#define READ_SIZE 1024
Number of bytes to read at once when loading binary
Definition at line 30 of file platform.c.
WINDOW_TITLE
#define WINDOW_TITLE `OS Simulator`
Title of the simulator window
Definition at line 27 of file platform.c.
Function Documentation
_abgr_b()
static u8 _abgr_b (u32 color) [inline], [static]
Extract blue channel from ABGR color.
Parameters
color ABGR Color
Returns
Blue value
Definition at line 197 of file platform.c.
{ return (color >> 8) & 0xFF; }
_abgr_g()
static u8 _abgr_g (u32 color) [inline], [static]
Extract green channel from ABGR color.
Parameters
color ABGR Color
Returns
Green value
Definition at line 189 of file platform.c.
{ return (color >> 16) & 0xFF; }
_abgr_r()
static u8 _abgr_r (u32 color) [inline], [static]
Extract red channel from ABGR color.
Parameters
color ABGR Color
Returns
Red value
Definition at line 181 of file platform.c.
{ return (color >> 24) & 0xFF; }
_abgr_to_argb()
static u32 _abgr_to_argb (u32 color) [static]
Convert a ABGR color to a ARGB color.
Parameters
color ABGR color value
Returns
ARGB color value
Definition at line 205 of file platform.c.
{
    return gfx_color(
        _abgr_r(color),
        _abgr_g(color),
        _abgr_b(color));
}
References _abgr_b(), _abgr_g(), _abgr_r(), and gfx_color().
Referenced by env_gfx_image_1bit(), env_gfx_image_rgba(), and env_gfx_rect().
_color_merge()
static u32 _color_merge (u32 color1, u32 color2, u32 ratio) [static]
Mix two colors according to a ratio. A ratio of 255 means 100% of the first color and 0% of the second color will be mixed together.
Parameters
color1 First ABGR color
color2 Second ABGR color
ratio Merge ratio from 0-255
Returns
Merged ARGB color value
Definition at line 222 of file platform.c.
{
    u8 r1, g1, b1, r2, g2, b2;
    r1 = _abgr_r(color1);
    g1 = _abgr_g(color1);
    b1 = _abgr_b(color1);
    r2 = _abgr_r(color2);
    g2 = _abgr_g(color2);
    b2 = _abgr_b(color2);
    return gfx_color(
        (r1 * ratio + r2 * (255 - ratio)) / 255,
        (g1 * ratio + g2 * (255 - ratio)) / 255,
        (b1 * ratio + b2 * (255 - ratio)) / 255);
}
References _abgr_b(), _abgr_g(), _abgr_r(), and gfx_color().
Referenced by env_gfx_image_grayscale().
_convert_key()
static Key _convert_key (i32 scancode, i32 mod) [static]
Combine scancode and key modifiers into one value.
Parameters
scancode Scancode
mod Key Modifiers
Returns
Combined Keycode
Definition at line 413 of file platform.c.
{
    Key key = scancode;
    if(mod & (KMOD_LCTRL | KMOD_RCTRL))
    {
        key |= MOD_CTRL;
    }
    if(mod & KMOD_LALT)
    {
        key |= MOD_ALT;
    }
    if(mod & KMOD_RALT)
    {
        key |= MOD_ALT_GR;
    }
    if(mod & (KMOD_LGUI | KMOD_RGUI))
    {
        key |= MOD_OS;
    }
    if(mod & (KMOD_LSHIFT | KMOD_RSHIFT))
    {
        key |= MOD_SHIFT;
    }
    return key;
}
Referenced by main().
_rgb565_to_bgra()
static u32 _rgb565_to_bgra (u16 color) [static]
Convert a RGB565 color to an BGRA color.
Parameters
color RGB565 color
Returns
BGRA color
Definition at line 246 of file platform.c.
{
    u32 r, g, b;
    r = (((((u32)color >> 11) & 0x1F) * 527) + 23) >> 6;
    g = (((((u32)color >> 5) & 0x3F) * 259) + 33) >> 6;
    b = ((((u32)color & 0x1F) * 527) + 23) >> 6;
    return gfx_color(r, g, b);
}
References gfx_color().
Referenced by env_gfx_image_rgb565().
env_gfx_image_1bit()
void env_gfx_image_1bit (i32 x, i32 y, i32 w, i32 h, u32 addr, u32 fg, u32 bg)
Draw a colored 1-bit image.
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h Height
addr Image memory address
fg ABGR foreground color
bg ABGR background color
Definition at line 335 of file platform.c.
{
    u8 byte, stride;
    i32 x0, y0, byte_offset, bit_mask;
    u8 *image;
    image = (u8 *)(_memory + addr);
    fg = _abgr_to_argb(fg);
    bg = _abgr_to_argb(bg);
    stride = (w + 7) / 8;
    for(y0 = y; y0 < y + h; ++y0)
    {
        bit_mask = 0x80;
        byte_offset = 0;
        for(x0 = x; x0 < x + w; ++x0)
        {
            if(bit_mask == 0x80)
            {
                byte = image[byte_offset++];
                bit_mask = 1;
            }
            _pixels[y0 * GFX_WIDTH + x0] = (byte & bit_mask) ? fg : bg;
            bit_mask <<= 1;
        }
        image += stride;
    }
}
References _abgr_to_argb(), _memory, _pixels, and GFX_WIDTH.
env_gfx_image_grayscale()
void env_gfx_image_grayscale (i32 x, i32 y, i32 w, i32 h, u32 addr, u32 fg, u32 bg)
Draw a colored grayscale image.
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h Height
addr Image memory address
fg ABGR foreground color
bg ABGR background color
Definition at line 318 of file platform.c.
{
    i32 x0, y0;
    u8 *image;
    image = (u8 *)(_memory + addr);
    for(y0 = y; y0 < y + h; ++y0)
    {
        for(x0 = x; x0 < x + w; ++x0)
        {
            _pixels[y0 * GFX_WIDTH + x0] =
                _color_merge(fg, bg, *image++);
        }
    }
}
References _color_merge(), _memory, _pixels, and GFX_WIDTH.
env_gfx_image_rgb()
void env_gfx_image_rgb (i32 x, i32 y, i32 w, i32 h, u32 addr)
Draw an RGB image.
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h Height
addr Image memory address
Definition at line 284 of file platform.c.
{
    u8 r, g, b;
    i32 x0, y0;
    u8 *image;
    image = (u8 *)(_memory + addr);
    for(y0 = y; y0 < y + h; ++y0)
    {
        for(x0 = x; x0 < x + w; ++x0)
        {
            r = *image++;
            g = *image++;
            b = *image++;
            _pixels[y0 * GFX_WIDTH + x0] = gfx_color(r, g, b);
        }
    }
}
References _memory, _pixels, gfx_color(), and GFX_WIDTH.
env_gfx_image_rgb565()
void env_gfx_image_rgb565 (i32 x, i32 y, i32 w, i32 h, u32 addr)
Draw an RGB565 image.
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h Height
addr Image memory address
Definition at line 303 of file platform.c.
{
    i32 x0, y0;
    u16 *image;
    image = (u16 *)(_memory + addr);
    for(y0 = y; y0 < y + h; ++y0)
    {
        for(x0 = x; x0 < x + w; ++x0)
        {
            _pixels[y0 * GFX_WIDTH + x0] = _rgb565_to_bgra(*image++);
        }
    }
}
References _memory, _pixels, _rgb565_to_bgra(), and GFX_WIDTH.
env_gfx_image_rgba()
void env_gfx_image_rgba (i32 x, i32 y, i32 w, i32 h, u32 addr)
Draw an RGBA image.
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h Height
addr Image memory address
Definition at line 269 of file platform.c.
{
    i32 x0, y0;
    u32 *image;
    image = (u32 *)(_memory + addr);
    for(y0 = y; y0 < y + h; ++y0)
    {
        for(x0 = x; x0 < x + w; ++x0)
        {
            _pixels[y0 * GFX_WIDTH + x0] = _abgr_to_argb(*image++);
        }
    }
}
References _abgr_to_argb(), _memory, _pixels, and GFX_WIDTH.
env_gfx_rect()
void env_gfx_rect (i32 x, i32 y, i32 w, i32 h, u32 color)
Draw rectangle.
Parameters
x X-Coordinate
y Y-Coordinate
w Width
h Height
color Fill color
Definition at line 255 of file platform.c.
{
    i32 x0, y0;
    color = _abgr_to_argb(color);
    for(y0 = y; y0 < y + h; ++y0)
    {
        for(x0 = x; x0 < x + w; ++x0)
        {
            _pixels[y0 * GFX_WIDTH + x0] = color;
        }
    }
}
References _abgr_to_argb(), _pixels, and GFX_WIDTH.
env_memory_read()
void env_memory_read (u32 addr, void * data, u32 size)
Read data from physical memory.
Parameters
addr Start address
data Data buffer
size Size in bytes
Definition at line 62 of file platform.c.
{
    memcpy(data, _memory + addr, size);
}
References _memory, and memcpy().
env_memory_size()
u32 env_memory_size (void)
Get the size of the installed memory.
Returns
The size of the memory in bytes
Definition at line 57 of file platform.c.
{
    return sizeof(_memory);
}
References _memory.
env_memory_write()
void env_memory_write (u32 addr, const void * data, u32 size)
Write data to physical memory.
Parameters
addr Start address
data Data buffer
size Size in bytes
Definition at line 67 of file platform.c.
{
    memcpy(_memory + addr, data, size);
}
References _memory, and memcpy().
env_millis()
u32 env_millis (void)
Get the number of milliseconds since boot.
Returns
The number of milliseconds
Definition at line 396 of file platform.c.
{
    struct timeval ts;
    gettimeofday(&ts, NULL);
    return (ts.tv_sec - _sec_start) * 1000 +
        (ts.tv_usec - _usec_start) / 1000;
}
References _sec_start, and _usec_start.
env_random_get()
u32 env_random_get (void)
Generate a pseudo-random number.
Returns
The number
Definition at line 376 of file platform.c.
{
    return rand();
}
References rand().
env_serial_write()
void env_serial_write (const void * data, u32 len)
Send data over the serial interface.
Parameters
data The data to send
len The number of bytes
Definition at line 368 of file platform.c.
{
    /* Debug print */
    printf("%.*s", len, (char *)data);
}
gfx_color()
static u32 gfx_color (u8 r, u8 g, u8 b) [static]
Generate ABGR color from red, green and blue channel values.
Parameters
r Red channel value (0-255)
g Green channel value (0-255)
b Blue channel value (0-255)
Returns
ABGR color value
Definition at line 167 of file platform.c.
{
    return ((u32)0xFF << 24) |
        ((u32)r << 16) |
        ((u32)g << 8) |
        ((u32)b);
}
Referenced by _abgr_to_argb(), _color_merge(), _rgb565_to_bgra(), and env_gfx_image_rgb().
gfx_destroy()
static void gfx_destroy (void) [static]
Destructor for SDL graphics renderer.
Definition at line 152 of file platform.c.
{
    SDL_DestroyRenderer(_renderer);
    SDL_DestroyWindow(_window);
    SDL_Quit();
}
References _renderer, and _window.
Referenced by main().
gfx_init()
static void gfx_init (void) [static]
Initialize SDL graphics.
Definition at line 109 of file platform.c.
{
    /* Init SDL */
    if(SDL_Init(SDL_INIT_VIDEO) < 0)
    {
        printf("Error initializing SDL; SDL_Init: %s\n",
            SDL_GetError());
        exit(1);
    }
    /* Create SDL_Window */
    if(!(_window = SDL_CreateWindow(WINDOW_TITLE,
        SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
        GFX_WIDTH, GFX_HEIGHT, 0)))
    {
        printf("Error creating SDL_Window: %s\n",
            SDL_GetError());
        SDL_Quit();
        exit(1);
    }
    /* Create SDL_Renderer */
    if(!(_renderer = SDL_CreateRenderer
        (_window, -1, SDL_RENDERER_ACCELERATED)))
    {
        printf("Error creating SDL_Renderer: %s\n",
            SDL_GetError());
        SDL_DestroyWindow(_window);
        SDL_Quit();
        exit(1);
    }
    SDL_SetRenderDrawColor(_renderer, 255, 255, 255, 255);
    _framebuffer = SDL_CreateTexture(_renderer,
        SDL_PIXELFORMAT_ARGB8888,
        SDL_TEXTUREACCESS_STREAMING,
        GFX_WIDTH, GFX_HEIGHT);
}
References _framebuffer, _renderer, _window, exit(), GFX_HEIGHT, GFX_WIDTH, and WINDOW_TITLE.
Referenced by main().
main()
int main (int argc, char ** argv)
Simulator main function.
Parameters
argc Number of command line parameters
argv Array of command line parameters
Returns
Exit code
Definition at line 454 of file platform.c.
{
    bool running = true;
    size_t len, offset;
    FILE *fp;
    if(argc != 2)
    {
        fprintf(stderr, "Usage: ./emu rv32i-binary\n");
        return 1;
    }
    /* Load binary into memory */
    if(!(fp = fopen(argv[1], "rb")))
    {
        fprintf(stderr, "Failed to open file \"%s\"\n", argv[1]);
        return 1;
    }
    offset = 0;
    do
    {
        len = fread(_memory + offset, 1, READ_SIZE, fp);
        offset += len;
    }
    while(len == READ_SIZE);
    timer_init();
    gfx_init();
    kernel_init();
    while(running)
    {
        SDL_Event e;
        while(SDL_PollEvent(&e))
        {
            switch(e.type)
            {
            case SDL_QUIT:
                running = false;
                break;
            case SDL_KEYDOWN:
                {
                    Key key;
                    if(e.key.keysym.sym == SDLK_ESCAPE)
                    {
                        running = false;
                        break;
                    }
                    key = _convert_key(e.key.keysym.scancode, e.key.keysym.mod);
                    keyboard_event(key, key_to_codepoint(key),
                        e.key.repeat ? KEYSTATE_REPEAT : KEYSTATE_PRESSED);
                }
                break;
            case SDL_KEYUP:
                {
                    Key key = _convert_key(e.key.keysym.scancode, e.key.keysym.mod);
                    keyboard_event(key, key_to_codepoint(key), KEYSTATE_RELEASED);
                }
                break;
            }
        }
        os_update();
        SDL_UpdateTexture(_framebuffer, NULL, _pixels, GFX_WIDTH * sizeof(u32));
        SDL_RenderClear(_renderer);
        SDL_RenderCopy(_renderer, _framebuffer, NULL, NULL);
        SDL_RenderPresent(_renderer);
    }
    gfx_destroy();
    return 0;
}
References _convert_key(), _framebuffer, _memory, _pixels, _renderer, gfx_destroy(), gfx_init(), GFX_WIDTH, kernel_init(), key_to_codepoint(), keyboard_event(), os_update(), READ_SIZE, and timer_init().
memory_dump()
void memory_dump (u32 address, u32 length)
Dump emulator memory from address with length.
Parameters
address Start address
length Number of bytes
Definition at line 78 of file platform.c.
{
    u32 start, end, i;
    start = (address >> 4) << 4;
    end = address + length;
    for(; start < end; start += 16)
    {
        printf("%08X | ", start);
        for(i = 0; i < 16; ++i)
        {
            printf("%02X ", _memory[start + i]);
        }
        printf("| ");
        for(i = 0; i < 16; ++i)
        {
            char c = _memory[start + i];
            printf("%c", (c < 32 || c > 126) ? '.' : c);
        }
        printf("\n");
    }
    printf("\n");
}
References _memory.
timer_init()
static void timer_init (void) [static]
Initialize simulated millisecond timer.
Definition at line 386 of file platform.c.
{
    struct timeval ts;
    gettimeofday(&ts, NULL);
    _sec_start = ts.tv_sec;
    _usec_start = ts.tv_usec;
    srand(time(NULL));
}
References _sec_start, and _usec_start.
Referenced by main().
Variable Documentation
_framebuffer
SDL_Texture* _framebuffer [static]
SDL Framebuffer containing pixel buffer
Definition at line 47 of file platform.c.
Referenced by gfx_init(), and main().
_memory
u8 _memory[3 *128 *1024] [static]
Emulated memory
Definition at line 35 of file platform.c.
Referenced by env_gfx_image_1bit(), env_gfx_image_grayscale(), env_gfx_image_rgb(), env_gfx_image_rgb565(), env_gfx_image_rgba(), env_memory_read(), env_memory_size(), env_memory_write(), main(), and memory_dump().
_pixels
u32 _pixels[GFX_HEIGHT *GFX_WIDTH] [static]
Screen pixel array buffer
Definition at line 38 of file platform.c.
Referenced by env_gfx_image_1bit(), env_gfx_image_grayscale(), env_gfx_image_rgb(), env_gfx_image_rgb565(), env_gfx_image_rgba(), env_gfx_rect(), and main().
_renderer
SDL_Renderer* _renderer [static]
SDL Renderer
Definition at line 53 of file platform.c.
Referenced by gfx_destroy(), gfx_init(), and main().
_sec_start
u32 _sec_start [static]
Seconds since start
Definition at line 41 of file platform.c.
Referenced by env_millis(), and timer_init().
_usec_start
u32 _usec_start [static]
Microseconds since start
Definition at line 44 of file platform.c.
Referenced by env_millis(), and timer_init().
_window
SDL_Window* _window [static]
SDL Window
Definition at line 50 of file platform.c.
Referenced by gfx_destroy(), and gfx_init().