platform/avr/spi/spi.h File Reference
SPI interface driver.
#include <types.h>
#include <status.h>
#include <avr/io.h>
Functions
void spi_init (void)
Initialize the SPI interface.
void spi_fast (void)
Enable fastest SPI mode.
u8 spi_xchg (u8 byte)
Send and receive one byte from the SPI interface Panics on timeout.
Status spi_xchg_try (u8 in, u8 *out)
Try to send and receive one byte from SPI.
Status spi_tx_try (u8 in)
Try to send one byte to the SPI interface.
Status spi_rx_try (u8 *out)
Try to receive one byte from the SPI interface.
Detailed Description
SPI interface driver.
Author
Anton Tchekov
Version
0.1
Date
16.05.2023
Definition in file spi.h.
Function Documentation
spi_fast()
void spi_fast (void)
Enable fastest SPI mode.
Definition at line 19 of file spi.c.
{
    SPCR &= ~((1 << SPR1) | (1 << SPR0));
    SPSR |= (1 << SPI2X);
}
Referenced by _lcd_window_start(), _memtest(), lcd_init(), and sd_init().
spi_init()
void spi_init (void)
Initialize the SPI interface.
Definition at line 13 of file spi.c.
{
    SPCR = (1 << SPE) | (1 << MSTR);
    log_boot_P(LOG_INIT, PSTR("SPI initialized"));
}
References log_boot_P().
Referenced by main().
spi_rx_try()
Status spi_rx_try (u8 * out)
Try to receive one byte from the SPI interface.
Parameters
out Output byte
Returns
Status
Definition at line 63 of file spi.c.
{
    return spi_xchg_try(0xFF, out);
}
References spi_xchg_try().
Referenced by _sd_command_try(), sd_read(), and sd_write().
spi_tx_try()
Status spi_tx_try (u8 in)
Try to send one byte to the SPI interface.
Parameters
in The byte to send
Returns
Status
Definition at line 57 of file spi.c.
{
    u8 dummy;
    return spi_xchg_try(in, &dummy);
}
References spi_xchg_try().
Referenced by _sd_command_try(), sd_read(), and sd_write().
spi_xchg()
u8 spi_xchg (u8 byte)
Send and receive one byte from the SPI interface Panics on timeout.
Parameters
byte The byte to send
Returns
The byte that was received
Definition at line 25 of file spi.c.
{
    u16 cnt = 0;
    SPDR = byte;
    while(!(SPSR & (1 << SPIF)))
    {
        if(cnt++ == 0xFFFF)
        {
            panic(PSTR("SPI timeout"));
        }
    }
    return SPDR;
}
References panic().
Referenced by _lcd_pixel(), _lcd_write_data(), _lcd_write_reg(), _memtest(), _sd_command(), _xmem_read(), _xmem_set(), _xmem_start(), _xmem_write(), and sd_init().
spi_xchg_try()
Status spi_xchg_try (u8 in, u8 * out)
Try to send and receive one byte from SPI.
Parameters
in Input byte
out Output byte
Returns
Status
Definition at line 40 of file spi.c.
{
    u16 cnt = 0;
    SPDR = in;
    while(!(SPSR & (1 << SPIF)))
    {
        if(cnt++ == 0xFFFF)
        {
            SD_DESELECT;
            return STATUS_TIMEOUT;
        }
    }
    *out = SPDR;
    return STATUS_OK;
}
References SD_DESELECT.
Referenced by spi_rx_try(), and spi_tx_try().