stdlib/serial/serial.c File Reference
#include <serial.h>
#include <syscall.h>
#include <stdarg.h>
#include <format.h>
Functions
void debug_print (const char *format,...)
Formatted debug output to serial interface.
i32 serial_write (const void *buf, i32 n)
Send n bytes over the serial interface.
Detailed Description
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
23.04.2023
Definition in file serial.c.
Function Documentation
debug_print()
void debug_print (const char * format, ...)
Formatted debug output to serial interface.
Parameters
format Format string
Definition at line 13 of file serial.c.
{
    char str[128];
    int r;
    va_list args;
    va_start(args, format);
    r = vsnprintf(str, UINT32_MAX, format, args);
    va_end(args);
    serial_write(str, r);
}
References serial_write(), and vsnprintf().
serial_write()
i32 serial_write (const void * buf, i32 n)
Send n bytes over the serial interface.
Parameters
buf Pointer to data buffer
n Number of bytes to write
Returns
Number of bytes written
Definition at line 25 of file serial.c.
{
    return syscall2(SYSCALL_SERIAL_WRITE, (u32)buf, n);
}
References syscall2().
Referenced by debug_print().