stdlib/string/string.c File Reference
#include <string.h>
#include <syscall.h>
Functions
char * strcpy (char *dest, const char *src)
Copy a string from source to destination.
char * strncpy (char *dest, const char *src, u32 count)
Copy a limited number of characters from one string to another.
u32 strlen (const char *str)
Get the length of a string.
i32 strcmp (const char *str1, const char *str2)
Compare two strings.
i32 strncmp (const char *str1, const char *str2, u32 count)
Compare a limited number of characters in two strings.
const char * strchr (const char *str, i32 c)
Locate the first occurrence of a character in a string.
void * memcpy (void *dest, const void *src, u32 count)
Copies count bytes from src to dest Source and destination blocks must NOT overlap.
void * memmove (void *dest, const void *src, u32 count)
Copies count bytes from src to dest Source and destination blocks are allowed to overlap.
i32 memcmp (const void *ptr1, const void *ptr2, u32 count)
Compares the first n bytes of two memory blocks pointed to by the provided pointers.
const void * memchr (const void *ptr, i32 value, u32 count)
Searches for the first occurrence of a specific character in the first n bytes of the memory block pointed to by the provided pointer.
void * memset (void *ptr, i32 value, u32 count)
Sets all bytes in a block of memory to value
Detailed Description
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
17.05.2023
Definition in file string.c.
Function Documentation
memchr()
const void * memchr (const void * ptr, i32 value, u32 count)
Searches for the first occurrence of a specific character in the first n bytes of the memory block pointed to by the provided pointer.
Parameters
ptr A pointer to the memory block to be searched.
value The value of the character to be searched for.
count The number of bytes to be searched.
Returns
A pointer to the first occurrence of the character, if found, or a null pointer if the character is not found in the first count bytes of the memory block.
Definition at line 162 of file string.c.
{
    u8 *p, *end;
    for(p = (u8 *)ptr, end = p + count; p < end; ++p)
    {
        if(*p == value)
        {
            return p;
        }
    }
    return NULL;
}
memcmp()
i32 memcmp (const void * ptr1, const void * ptr2, u32 count)
Compares the first n bytes of two memory blocks pointed to by the provided pointers.
Parameters
ptr1 A pointer to the first memory block.
ptr2 A pointer to the second memory block.
count The number of bytes to compare.
Returns
An integer less than, equal to, or greater than zero, indicating whether the first count bytes of the memory blocks pointed to by ptr1 and ptr2 are less than, equal to, or greater than each other, respectively.
Definition at line 141 of file string.c.
{
    u32 i;
    const u8 *p1, *p2;
    p1 = (const u8 *)ptr1;
    p2 = (const u8 *)ptr2;
    for(i = 0; i < count; ++i)
    {
        if(*p1 != *p2)
        {
            return *p1 - *p2;
        }
        ++p1;
        ++p2;
    }
    return 0;
}
Referenced by initrd_load().
memcpy()
void * memcpy (void * dest, const void * src, u32 count)
Copies count bytes from src to dest Source and destination blocks must NOT overlap.
Parameters
dest Pointer to destination address
src Pointer to source address
count Number of bytes
Returns
dest
Definition at line 94 of file string.c.
{
    u8 *d, *s, *end;
    s = (u8 *)src;
    d = (u8 *)dest;
    end = d + count;
    if(d != s)
    {
        while(d != end)
        {
            *d++ = *s++;
        }
    }
    return dest;
}
Referenced by emulator_call(), main(), vector_replace(), and vector_set().
memmove()
void * memmove (void * dest, const void * src, u32 count)
Copies count bytes from src to dest Source and destination blocks are allowed to overlap.
Parameters
dest Pointer to destination address
src Pointer to source address
count Number of bytes
Returns
dest
Definition at line 113 of file string.c.
{
    u8 *d, *s, *end;
    s = (u8 *)src;
    d = (u8 *)dest;
    end = s + count;
    if(d > s && d < end)
    {
        s = end;
        d += count;
        while(s > (u8 *)src)
        {
            *--d = *--s;
        }
    }
    else if(s != d)
    {
        while(s < end)
        {
            *d++ = *s++;
        }
    }
    return dest;
}
Referenced by vector_replace().
memset()
void * memset (void * ptr, i32 value, u32 count)
Sets all bytes in a block of memory to value
Parameters
ptr Pointer to block of memory
value Value to be written as byte
count Number of bytes
Returns
ptr
Definition at line 176 of file string.c.
{
    u8 *p, *end;
    for(p = (u8 *)ptr, end = p + count; p < end; ++p)
    {
        *p = value;
    }
    return ptr;
}
Referenced by main(), and setup().
strchr()
const char * strchr (const char * str, i32 c)
Locate the first occurrence of a character in a string.
Parameters
str Pointer to the null-terminated string to be searched.
c Character to be located.
Returns
Pointer to the first occurrence of c in str, or NULL if c is not found.
This function searches for the first occurrence of the character c in the null-terminated string pointed to by str. If c is found in str, the function returns a pointer to the first occurrence of c in str. If c is not found in str, the function returns NULL.
Definition at line 78 of file string.c.
{
    i32 d;
    while((d = *str))
    {
        if(d == c)
        {
            return str;
        }
        ++str;
    }
    return NULL;
}
Referenced by ispunct(), and isspace().
strcmp()
i32 strcmp (const char * str1, const char * str2)
Compare two strings.
Parameters
str1 Pointer to the first null-terminated string to be compared.
str2 Pointer to the second null-terminated string to be compared.
Returns
A negative value if the first character that does not match has a lower value in str1 than in str2, a positive value if the first character that does not match has a greater value in str1 than in str2, or zero if the contents of both strings are equal.
Definition at line 36 of file string.c.
{
    while(*str1 == *str2)
    {
        if(!*str1)
        {
            return 0;
        }
        ++str1;
        ++str2;
    }
    return *str1 - *str2;
}
strcpy()
char * strcpy (char * dest, const char * src)
Copy a string from source to destination.
Parameters
dest Pointer to the destination string
src Pointer to the source string
Returns
Pointer to the destination string
This function copies the content of the null-terminated string pointed to by src to the buffer pointed to by dest, including the null terminator.
Definition at line 11 of file string.c.
{
    char *d = dest;
    while((*d++ = *src++)) {}
    return dest;
}
strlen()
u32 strlen (const char * str)
Get the length of a string.
Parameters
str Pointer to the null-terminated string to be measured.
Returns
Length of the string.
This function calculates the length of the null-terminated string pointed to by str, not including the null terminator.
Definition at line 29 of file string.c.
{
    const char *s = str;
    while(*s) { ++s; }
    return s - str;
}
strncmp()
i32 strncmp (const char * str1, const char * str2, u32 count)
Compare a limited number of characters in two strings.
Parameters
str1 Pointer to the first null-terminated string to be compared.
str2 Pointer to the second null-terminated string to be compared.
count Maximum number of characters to be compared.
Returns
A negative value if the first character that does not match has a lower value in str1 than in str2, a positive value if the first character that does not match has a greater value in str1 than in str2, or zero if the contents of both strings are equal up to the first n
Definition at line 52 of file string.c.
{
    u32 i;
    const u8 *p1, *p2;
    p1 = (const u8 *)str1;
    p2 = (const u8 *)str2;
    for(i = 0; i < count; ++i)
    {
        if(*p1 != *p2)
        {
            return *p1 - *p2;
        }
        if(!*p1)
        {
            return 0;
        }
        ++p1;
        ++p2;
    }
    return 0;
}
strncpy()
char * strncpy (char * dest, const char * src, u32 count)
Copy a limited number of characters from one string to another.
Parameters
dest Pointer to the destination array
src Pointer to the source of data
count Maximum number of characters to be copied
Returns
Pointer to the destination array
Definition at line 18 of file string.c.
{
    u32 i, c;
    for(i = 0; i < count && (c = src[i]); ++i)
    {
        dest[i] = c;
    }
    return dest;
}