stdlib/syscall/syscall.h File Reference
System call interface to communicate with the kernel.
#include <types.h>
Enumerations
enum SyscallID {
SYSCALL_EXIT
, SYSCALL_FINISH
, SYSCALL_EVENT_REGISTER
, SYSCALL_GFX_RECT
,
SYSCALL_GFX_IMAGE_RGBA
, SYSCALL_GFX_IMAGE_RGB
, SYSCALL_GFX_IMAGE_RGB565
, SYSCALL_GFX_IMAGE_GRAYSCALE
,
SYSCALL_GFX_IMAGE_1BIT
, SYSCALL_RAND
, SYSCALL_SERIAL_WRITE
, SYSCALL_MILLIS
 }
Functions
static u32 syscall0 (SyscallID id)
System call with zero parameters.
static u32 syscall1 (SyscallID id, u32 a0)
System call with one parameter.
static u32 syscall2 (SyscallID id, u32 a0, u32 a1)
System call with two parameters.
static u32 syscall3 (SyscallID id, u32 a0, u32 a1, u32 a2)
System call with three parameters.
static u32 syscall4 (SyscallID id, u32 a0, u32 a1, u32 a2, u32 a3)
System call with four parameters.
static u32 syscall5 (SyscallID id, u32 a0, u32 a1, u32 a2, u32 a3, u32 a4)
System call with five parameters.
static u32 syscall6 (SyscallID id, u32 a0, u32 a1, u32 a2, u32 a3, u32 a4, u32 a5)
System call with six parameters.
static void exit (i32 status)
End program.
Detailed Description
System call interface to communicate with the kernel.
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
23.04.2023
Definition in file syscall.h.
Enumeration Type Documentation
SyscallID
enum SyscallID
List of all Syscalls
Definition at line 15 of file syscall.h.
{
    SYSCALL_EXIT,
    SYSCALL_FINISH,
    SYSCALL_EVENT_REGISTER,
    SYSCALL_GFX_RECT,
    SYSCALL_GFX_IMAGE_RGBA,
    SYSCALL_GFX_IMAGE_RGB,
    SYSCALL_GFX_IMAGE_RGB565,
    SYSCALL_GFX_IMAGE_GRAYSCALE,
    SYSCALL_GFX_IMAGE_1BIT,
    SYSCALL_RAND,
    SYSCALL_SERIAL_WRITE,
    SYSCALL_MILLIS,
} SyscallID;
Function Documentation
exit()
static void exit (i32 status) [inline], [static]
End program.
Parameters
status Exit status
Definition at line 206 of file syscall.h.
{
    syscall1(SYSCALL_EXIT, status);
}
References syscall1().
Referenced by loop(), and panic().
syscall0()
static u32 syscall0 (SyscallID id) [inline], [static]
System call with zero parameters.
Parameters
id System call ID. See SyscallID enum above
Returns
Return value
Definition at line 39 of file syscall.h.
{
    register u32 ra0 asm("a0");
    register u32 ra7 asm("a7") = id;
    asm volatile("ecall"
        : "=r"(ra0)
        : "r"(ra7));
    return ra0;
}
Referenced by finish(), millis(), and rand().
syscall1()
static u32 syscall1 (SyscallID id, u32 a0) [inline], [static]
System call with one parameter.
Parameters
id System call ID. See SyscallID enum above
a0 First parameter
Returns
Return value
Definition at line 58 of file syscall.h.
{
    register u32 ra0 asm("a0") = a0;
    register u32 ra7 asm("a7") = id;
    asm volatile("ecall"
        : "+r"(ra0)
        : "r"(ra7));
    return ra0;
}
Referenced by exit(), and keyboard_is_key_pressed().
syscall2()
static u32 syscall2 (SyscallID id, u32 a0, u32 a1) [inline], [static]
System call with two parameters.
Parameters
id System call ID. See SyscallID enum above
a0 First parameter
a1 Second parameter
Returns
Return value
Definition at line 78 of file syscall.h.
{
    register u32 ra0 asm("a0") = a0;
    register u32 ra1 asm("a1") = a1;
    register u32 ra7 asm("a7") = id;
    asm volatile("ecall"
        : "+r"(ra0)
        : "r"(ra1),
        "r"(ra7));
    return ra0;
}
Referenced by event_register(), and serial_write().
syscall3()
static u32 syscall3 (SyscallID id, u32 a0, u32 a1, u32 a2) [inline], [static]
System call with three parameters.
Parameters
id System call ID. See SyscallID enum above
a0 First parameter
a1 Second parameter
a2 Third parameter
Returns
Return value
Definition at line 101 of file syscall.h.
{
    register u32 ra0 asm("a0") = a0;
    register u32 ra1 asm("a1") = a1;
    register u32 ra2 asm("a2") = a2;
    register u32 ra7 asm("a7") = id;
    asm volatile("ecall"
        : "+r"(ra0)
        : "r"(ra1), "r"(ra2),
        "r"(ra7));
    return ra0;
}
syscall4()
static u32 syscall4 (SyscallID id, u32 a0, u32 a1, u32 a2, u32 a3) [inline], [static]
System call with four parameters.
Parameters
id System call ID. See SyscallID enum above
a0 First parameter
a1 Second parameter
a2 Third parameter
a3 Fourth parameter
Returns
Return value
Definition at line 126 of file syscall.h.
{
    register u32 ra0 asm("a0") = a0;
    register u32 ra1 asm("a1") = a1;
    register u32 ra2 asm("a2") = a2;
    register u32 ra3 asm("a3") = a3;
    register u32 ra7 asm("a7") = id;
    asm volatile("ecall"
        : "+r"(ra0)
        : "r"(ra1), "r"(ra2), "r"(ra3),
        "r"(ra7));
    return ra0;
}
Referenced by gfx_image_1bit(), and gfx_image_grayscale().
syscall5()
static u32 syscall5 (SyscallID id, u32 a0, u32 a1, u32 a2, u32 a3, u32 a4) [inline], [static]
System call with five parameters.
Parameters
id System call ID. See SyscallID enum above
a0 First parameter
a1 Second parameter
a2 Third parameter
a3 Fourth parameter
a4 Fifth parameter
Returns
Return value
Definition at line 153 of file syscall.h.
{
    register u32 ra0 asm("a0") = a0;
    register u32 ra1 asm("a1") = a1;
    register u32 ra2 asm("a2") = a2;
    register u32 ra3 asm("a3") = a3;
    register u32 ra4 asm("a4") = a4;
    register u32 ra7 asm("a7") = id;
    asm volatile("ecall"
        : "+r"(ra0)
        : "r"(ra1), "r"(ra2), "r"(ra3), "r"(ra4),
        "r"(ra7));
    return ra0;
}
Referenced by gfx_image_rgb(), gfx_image_rgb565(), gfx_image_rgba(), and gfx_rect().
syscall6()
static u32 syscall6 (SyscallID id, u32 a0, u32 a1, u32 a2, u32 a3, u32 a4, u32 a5) [inline], [static]
System call with six parameters.
Parameters
id System call ID. See SyscallID enum above
a0 First parameter
a1 Second parameter
a2 Third parameter
a3 Fourth parameter
a4 Fifth parameter
a5 Sixth parameter
Returns
Return value
Definition at line 182 of file syscall.h.
{
    register u32 ra0 asm("a0") = a0;
    register u32 ra1 asm("a1") = a1;
    register u32 ra2 asm("a2") = a2;
    register u32 ra3 asm("a3") = a3;
    register u32 ra4 asm("a4") = a4;
    register u32 ra5 asm("a5") = a5;
    register u32 ra7 asm("a7") = id;
    asm volatile("ecall"
        : "+r"(ra0)
        : "r"(ra1), "r"(ra2), "r"(ra3), "r"(ra4), "r"(ra5),
        "r"(ra7));
    return ra0;
}