platform/avr/timer/timer.c File Reference
#include <timer.h>
#include <serial.h>
#include <logger.h>
#include <avr/interrupt.h>
#include <avr/pgmspace.h>
Functions
void timer_init (void)
Initialize hardware timer/counter.
u32 millis (void)
Get milliseconds since startup.
ISR (TIMER0_COMPA_vect)
Variables
static volatile u32 _ms
Detailed Description
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
01.05.2023
Definition in file timer.c.
Function Documentation
ISR()
ISR (TIMER0_COMPA_vect)
Timer0 compare interrupt
Definition at line 43 of file timer.c.
{
    /* Increment overflows after approx. 50 days */
    ++_ms;
}
References _ms.
millis()
u32 millis (void)
Get milliseconds since startup.
Gets the number of milliseconds since startup.
Returns
Number of milliseconds
Definition at line 36 of file timer.c.
{
    /* Return number of milliseconds since boot */
    return _ms;
}
References _ms.
Referenced by _show_error(), env_millis(), and loop().
timer_init()
void timer_init (void)
Initialize hardware timer/counter.
Definition at line 17 of file timer.c.
{
    /* Initialize hardware timers */
    /* CTC Mode */
    TCCR0A = (1 << WGM01);
    /* Prescaler 64 */
    TCCR0B |= (1 << CS01) | (1 << CS00);
    /* 16000000 / 64 / 1000 = 250 */
    OCR0A = 250 - 1;
    /* Enable compare interrupt */
    TIMSK0 |= (1 << OCIE0A);
    log_boot_P(LOG_INIT, PSTR("Millisecond timer initialized"));
}
References log_boot_P().
Referenced by main().
Variable Documentation
_ms
volatile u32 _ms [static]
Millisecond counter
Definition at line 15 of file timer.c.
Referenced by ISR(), and millis().