stdlib/time/time.h File Reference
Timing functions.
#include <types.h>
Functions
u32 millis (void)
Gets the number of milliseconds since startup.
Detailed Description
Timing functions.
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
22.05.2023
Definition in file time.h.
Function Documentation
millis()
u32 millis (void)
Gets the number of milliseconds since startup.
Returns
Number of milliseconds (overflows after approximately 50 days)
Gets the number of milliseconds since startup.
Returns
Number of milliseconds
Definition at line 36 of file timer.c.
{
    /* Return number of milliseconds since boot */
    return _ms;
}
References _ms, and syscall0().
Referenced by _show_error(), env_millis(), and loop().