types/types.h File Reference
Shorthand type definitions inspired by Rust.
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
Typedefs
typedef int64_t i64
typedef int32_t i32
typedef int16_t i16
typedef int8_t i8
typedef uint64_t u64
typedef uint32_t u32
typedef uint16_t u16
typedef uint8_t u8
typedef float f32
typedef double f64
typedef uintptr_t ptr
Functions
static i32 i32_min (i32 a, i32 b)
Get the smaller of two i32 numbers.
static i32 i32_max (i32 a, i32 b)
Get the larger of two i32 numbers.
Detailed Description
Shorthand type definitions inspired by Rust.
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
01.05.2023
Definition in file types.h.
Typedef Documentation
f32
typedef float f32
32-bit float
Definition at line 41 of file types.h.
f64
typedef double f64
64-bit float
Definition at line 44 of file types.h.
i16
typedef int16_t i16
Signed 16-bit integer
Definition at line 23 of file types.h.
i32
typedef int32_t i32
Signed 32-bit integer
Definition at line 20 of file types.h.
i64
typedef int64_t i64
Signed 64-bit integer
Definition at line 17 of file types.h.
i8
typedef int8_t i8
Signed 8-bit integer
Definition at line 26 of file types.h.
ptr
typedef uintptr_t ptr
Pointer size integer
Definition at line 47 of file types.h.
u16
typedef uint16_t u16
Unsigned 16-bit integer
Definition at line 35 of file types.h.
u32
typedef uint32_t u32
Unsigned 32-bit integer
Definition at line 32 of file types.h.
u64
typedef uint64_t u64
Unsigned 64-bit integer
Definition at line 29 of file types.h.
u8
typedef uint8_t u8
Unsigned 8-bit integer
Definition at line 38 of file types.h.
Function Documentation
i32_max()
static i32 i32_max (i32 a, i32 b) [inline], [static]
Get the larger of two i32 numbers.
Parameters
a First number
b Second number
Returns
The larger number
Definition at line 68 of file types.h.
{
    return (a > b) ? a : b;
}
Referenced by input_render(), and input_selection_replace().
i32_min()
static i32 i32_min (i32 a, i32 b) [inline], [static]
Get the smaller of two i32 numbers.
Parameters
a First number
b Second number
Returns
The smaller number
Definition at line 56 of file types.h.
{
    return (a < b) ? a : b;
}
Referenced by input_render(), and input_selection_replace().