stdlib/vector/vector.h File Reference
Generic resizable array.
#include <types.h>
#include <string.h>
Data Structures
struct Vector
Functions
void vector_init (Vector *vector, u32 element_size, u32 initial_capacity)
Initialize a vector with an element size and an initial capacity.
static void vector_clear (Vector *vector)
Clears (empties) the vector.
void vector_destroy (Vector *vector)
Frees the internal memory buffer of the vector.
void vector_replace (Vector *vector, u32 index, u32 count, const void *elems, u32 new_count)
Replace a range of elements in the vector with new elements.
static void vector_set (Vector *vector, const void *elems, u32 count)
Replace all elements in a vector.
static void * vector_get (Vector *vector, u32 index)
Get a pointer to an element in the vector.
static void * vector_data (Vector *vector)
Get a pointer to the internal data area.
static u32 vector_len (Vector *vector)
Gets the number of elements in the vector.
static void vector_insert_range (Vector *vector, u32 index, u32 count, void *elems)
Insert a range of elements at an index in the vector.
static void vector_insert (Vector *vector, u32 index, void *elem)
Insert a single element.
static void vector_remove_range (Vector *vector, u32 index, u32 count)
Remove a range of elements.
static void vector_remove (Vector *vector, u32 index)
Remove a single element.
static void vector_push (Vector *vector, void *elem)
Insert an element after the last element of the vector.
static void vector_push_range (Vector *vector, u32 count, void *elem)
Insert a range of elements after the last element of the vector.
Detailed Description
Generic resizable array.
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
26.04.2023
Definition in file vector.h.
Function Documentation
vector_clear()
static void vector_clear (Vector * vector) [inline], [static]
Clears (empties) the vector.
Parameters
vector The vector
Definition at line 51 of file vector.h.
{
    vector->Length = 0;
}
References Vector::Length.
Referenced by input_clear().
vector_data()
static void * vector_data (Vector * vector) [inline], [static]
Get a pointer to the internal data area.
Parameters
vector The Vector
Returns
Pointer to the content
Definition at line 107 of file vector.h.
{
    return vector->Data;
}
References Vector::Data.
Referenced by _draw_code(), _input_get_display_text(), button_login_onclick(), and clipboard_get_text().
vector_destroy()
void vector_destroy (Vector * vector)
Frees the internal memory buffer of the vector.
Parameters
vector The vector
Definition at line 38 of file vector.c.
{
    memfree(vector->Data);
}
References Vector::Data, and memfree().
vector_get()
static void * vector_get (Vector * vector, u32 index) [inline], [static]
Get a pointer to an element in the vector.
Parameters
vector The Vector
index The index
Returns
Pointer to the element
Definition at line 96 of file vector.h.
{
    return (void *)((u8 *)vector->Data + vector->ElementSize * index);
}
References Vector::Data, and Vector::ElementSize.
Referenced by _selection_save().
vector_init()
void vector_init (Vector * vector, u32 element_size, u32 initial_capacity)
Initialize a vector with an element size and an initial capacity.
Example code for a vector of integers:
Vector vector;
vector_init(&vector, sizeof(i32), 16);
Parameters
vector The vector
element_size The size of each element in the vector
initial_capacity The vectors initial capacity
Definition at line 30 of file vector.c.
{
    vector->ElementSize = element_size;
    vector->Capacity = initial_capacity;
    vector->Length = 0;
    vector->Data = memalloc(element_size * initial_capacity);
}
References Vector::Capacity, Vector::Data, Vector::ElementSize, Vector::Length, and memalloc().
Referenced by _clipboard_init(), input_init(), and setup().
vector_insert()
static void vector_insert (Vector * vector, u32 index, void * elem) [inline], [static]
Insert a single element.
Parameters
vector The vector
index The index at which to insert the element
elem The element
Definition at line 144 of file vector.h.
{
    vector_insert_range(vector, index, 1, elem);
}
References vector_insert_range().
Referenced by vector_push().
vector_insert_range()
static void vector_insert_range (Vector * vector, u32 index, u32 count, void * elems) [inline], [static]
Insert a range of elements at an index in the vector.
Parameters
vector The vector
index The starting index of where to insert the elements
count The number of elements to insert
elems Pointer to the new elements
Definition at line 131 of file vector.h.
{
    vector_replace(vector, index, 0, elems, count);
}
References vector_replace().
Referenced by vector_insert(), and vector_push_range().
vector_len()
static u32 vector_len (Vector * vector) [inline], [static]
Gets the number of elements in the vector.
Parameters
vector The Vector
Returns
Number of elements
Definition at line 118 of file vector.h.
{
    return vector->Length;
}
References Vector::Length.
Referenced by _draw_code(), clipboard_get_text_len(), input_delete(), input_end(), input_render(), input_right(), input_select_all(), input_select_end(), input_select_right(), and input_selection_replace().
vector_push()
static void vector_push (Vector * vector, void * elem) [inline], [static]
Insert an element after the last element of the vector.
Parameters
vector The vector
elem The element to insert
Definition at line 180 of file vector.h.
{
    vector_insert(vector, vector->Length, elem);
}
References Vector::Length, and vector_insert().
vector_push_range()
static void vector_push_range (Vector * vector, u32 count, void * elem) [inline], [static]
Insert a range of elements after the last element of the vector.
Parameters
vector The vector
count The number of elements to insert
elem The elements to insert
Definition at line 192 of file vector.h.
{
    vector_insert_range(vector, vector->Length, count, elem);
}
References Vector::Length, and vector_insert_range().
vector_remove()
static void vector_remove (Vector * vector, u32 index) [inline], [static]
Remove a single element.
Parameters
vector The vector
index Index of the element to remove
Definition at line 167 of file vector.h.
{
    vector_remove_range(vector, index, 1);
}
References vector_remove_range().
Referenced by input_backspace(), and input_delete().
vector_remove_range()
static void vector_remove_range (Vector * vector, u32 index, u32 count) [inline], [static]
Remove a range of elements.
Parameters
vector The vector
index Start index of the range
count Number of elements to remove
Definition at line 156 of file vector.h.
{
    vector_replace(vector, index, count, NULL, 0);
}
References vector_replace().
Referenced by vector_remove().
vector_replace()
void vector_replace (Vector * vector, u32 index, u32 count, const void * elems, u32 new_count)
Replace a range of elements in the vector with new elements.
Parameters
vector The vector
index The starting index of the range of elements to replace
count The number of elements to replace
elems Pointer to the new elements
new_count Number of new elements to be inserted
Definition at line 43 of file vector.c.
{
    u32 new_length, element_size;
    element_size = vector->ElementSize;
    ASSERT(index + count <= vector->Length, "invalid range");
    /* Calculate new number of elements */
    new_length = vector->Length - count + new_count;
    if(new_length > vector->Capacity)
    {
        /* Resize necessary */
        u32 new_capacity, prev_bytes, new_bytes, old_bytes, last_bytes;
        void *new_data;
        new_capacity = _next_pot(new_length);
        prev_bytes = index * element_size;
        new_bytes = new_count * element_size;
        old_bytes = count * element_size;
        last_bytes = (vector->Length - index - count) * element_size;
        /* Calculate new capacity */
        vector->Capacity = new_capacity;
        /* Create new buffer */
        new_data = memalloc(new_capacity * element_size);
        /* Copy first part from previous buffer */
        memcpy(new_data, vector->Data, prev_bytes); // correct
        /* Copy new range */
        memcpy((u8 *)new_data + prev_bytes, elems, new_bytes); // correct
        /* Copy last part */
        memcpy((u8 *)new_data + prev_bytes + new_bytes,
            (u8 *)vector->Data + prev_bytes + old_bytes,
            last_bytes);
        /* Replace with new buffer */
        memfree(vector->Data);
        vector->Data = new_data;
    }
    else
    {
        u32 prev_bytes, new_bytes, old_bytes, last_bytes;
        prev_bytes = index * element_size;
        new_bytes = new_count * element_size;
        old_bytes = count * element_size;
        last_bytes = (vector->Length - index - count) * element_size;
        /* Shift last part */
        memmove((u8 *)vector->Data + prev_bytes + new_bytes,
            (u8 *)vector->Data + prev_bytes + old_bytes,
            last_bytes);
        /* Copy new range */
        memcpy((u8 *)vector->Data + prev_bytes, elems, new_bytes);
    }
    vector->Length = new_length;
}
References _next_pot(), ASSERT, Vector::Capacity, Vector::Data, Vector::ElementSize, Vector::Length, memalloc(), memcpy(), memfree(), and memmove().
Referenced by input_selection_replace(), vector_insert_range(), vector_remove_range(), and vector_set().
vector_set()
static void vector_set (Vector * vector, const void * elems, u32 count) [inline], [static]
Replace all elements in a vector.
Parameters
vector The vector
elems New elements
count Number of new elements
Definition at line 84 of file vector.h.
{
    vector_replace(vector, 0, vector->Length, elems, count);
}
References Vector::Length, and vector_replace().
Referenced by clipboard_save_text_len(), and setup().