stdlib/vector/vector.c File Reference
#include <vector.h>
#include <alloc.h>
#include <string.h>
#include <panic.h>
Functions
static u32 _next_pot (u32 n)
Next power of two.
void vector_init (Vector *vector, u32 element_size, u32 initial_capacity)
Initialize a vector with an element size and an initial capacity.
void vector_destroy (Vector *vector)
Frees the internal memory buffer of the vector.
void vector_replace (Vector *vector, u32 index, u32 count, const void *elems, u32 new_count)
Replace a range of elements in the vector with new elements.
Detailed Description
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
26.04.2023
Definition in file vector.c.
Function Documentation
_next_pot()
static u32 _next_pot (u32 n) [static]
Next power of two.
Parameters
n The number for which to get the next bigger power of two for
Returns
The power of two, for example for input 26 it would return 32
Definition at line 19 of file vector.c.
{
    u32 power = 1;
    while(power < n)
    {
        power <<= 1;
    }
    return power;
}
Referenced by vector_replace().
vector_destroy()
void vector_destroy (Vector * vector)
Frees the internal memory buffer of the vector.
Parameters
vector The vector
Definition at line 38 of file vector.c.
{
    memfree(vector->Data);
}
References Vector::Data, and memfree().
vector_init()
void vector_init (Vector * vector, u32 element_size, u32 initial_capacity)
Initialize a vector with an element size and an initial capacity.
Example code for a vector of integers:
Vector vector;
vector_init(&vector, sizeof(i32), 16);
Parameters
vector The vector
element_size The size of each element in the vector
initial_capacity The vectors initial capacity
Definition at line 30 of file vector.c.
{
    vector->ElementSize = element_size;
    vector->Capacity = initial_capacity;
    vector->Length = 0;
    vector->Data = memalloc(element_size * initial_capacity);
}
References Vector::Capacity, Vector::Data, Vector::ElementSize, Vector::Length, and memalloc().
Referenced by _clipboard_init(), input_init(), and setup().
vector_replace()
void vector_replace (Vector * vector, u32 index, u32 count, const void * elems, u32 new_count)
Replace a range of elements in the vector with new elements.
Parameters
vector The vector
index The starting index of the range of elements to replace
count The number of elements to replace
elems Pointer to the new elements
new_count Number of new elements to be inserted
Definition at line 43 of file vector.c.
{
    u32 new_length, element_size;
    element_size = vector->ElementSize;
    ASSERT(index + count <= vector->Length, "invalid range");
    /* Calculate new number of elements */
    new_length = vector->Length - count + new_count;
    if(new_length > vector->Capacity)
    {
        /* Resize necessary */
        u32 new_capacity, prev_bytes, new_bytes, old_bytes, last_bytes;
        void *new_data;
        new_capacity = _next_pot(new_length);
        prev_bytes = index * element_size;
        new_bytes = new_count * element_size;
        old_bytes = count * element_size;
        last_bytes = (vector->Length - index - count) * element_size;
        /* Calculate new capacity */
        vector->Capacity = new_capacity;
        /* Create new buffer */
        new_data = memalloc(new_capacity * element_size);
        /* Copy first part from previous buffer */
        memcpy(new_data, vector->Data, prev_bytes); // correct
        /* Copy new range */
        memcpy((u8 *)new_data + prev_bytes, elems, new_bytes); // correct
        /* Copy last part */
        memcpy((u8 *)new_data + prev_bytes + new_bytes,
            (u8 *)vector->Data + prev_bytes + old_bytes,
            last_bytes);
        /* Replace with new buffer */
        memfree(vector->Data);
        vector->Data = new_data;
    }
    else
    {
        u32 prev_bytes, new_bytes, old_bytes, last_bytes;
        prev_bytes = index * element_size;
        new_bytes = new_count * element_size;
        old_bytes = count * element_size;
        last_bytes = (vector->Length - index - count) * element_size;
        /* Shift last part */
        memmove((u8 *)vector->Data + prev_bytes + new_bytes,
            (u8 *)vector->Data + prev_bytes + old_bytes,
            last_bytes);
        /* Copy new range */
        memcpy((u8 *)vector->Data + prev_bytes, elems, new_bytes);
    }
    vector->Length = new_length;
}
References _next_pot(), ASSERT, Vector::Capacity, Vector::Data, Vector::ElementSize, Vector::Length, memalloc(), memcpy(), memfree(), and memmove().
Referenced by input_selection_replace(), vector_insert_range(), vector_remove_range(), and vector_set().