platform/avr/xmem/xmem.h File Reference
External memory driver (23LC1024)
#include <types.h>
Functions
void xmem_init (void)
Initialize external memory and run memory test.
void xmem_read (u32 addr, void *data, u16 size)
Read the specified number of bytes from the external memory.
void xmem_write (u32 addr, const void *data, u16 size)
Write the specified number of bytes to the external memory.
void xmem_set (u32 addr, u8 value, u16 size)
Set a specified number of bytes in the external memory to a value.
u32 xmem_size (void)
Get external memory size.
Detailed Description
External memory driver (23LC1024)
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
01.05.2023
Definition in file xmem.h.
Function Documentation
xmem_init()
void xmem_init (void)
Initialize external memory and run memory test.
Definition at line 279 of file xmem.c.
{
    /* Initialize XMEM */
    log_boot_P(LOG_INIT, PSTR("External memory driver initialized"));
    _memtest();
}
References _memtest(), and log_boot_P().
Referenced by main().
xmem_read()
void xmem_read (u32 addr, void * data, u16 size)
Read the specified number of bytes from the external memory.
Parameters
addr Start address
data Destination buffer
size Number of bytes to read
Definition at line 286 of file xmem.c.
{
    AddrHelper h;
    _xmem_overlap(addr, size, &h);
    _xmem_read(h.BankFirst, h.AddrFirst, data, h.SizeFirst);
    if(h.BankSecond != h.BankFirst)
    {
        _xmem_read(h.BankSecond, 0, (u8 *)data + h.SizeFirst, h.SizeSecond);
    }
}
References _xmem_overlap(), _xmem_read(), AddrHelper::AddrFirst, AddrHelper::BankFirst, AddrHelper::BankSecond, AddrHelper::SizeFirst, and AddrHelper::SizeSecond.
Referenced by env_memory_read(), lcd_image_1bit(), lcd_image_grayscale(), and lcd_image_rgb565().
xmem_set()
void xmem_set (u32 addr, u8 value, u16 size)
Set a specified number of bytes in the external memory to a value.
Parameters
addr Start address
value The value to write
size Number of bytes to set
Definition at line 309 of file xmem.c.
{
    AddrHelper h;
    _xmem_overlap(addr, size, &h);
    _xmem_set(h.BankFirst, h.AddrFirst, value, h.SizeFirst);
    if(h.BankSecond != h.BankFirst)
    {
        _xmem_set(h.BankSecond, 0, value, h.SizeSecond);
    }
}
References _xmem_overlap(), _xmem_set(), AddrHelper::AddrFirst, AddrHelper::BankFirst, AddrHelper::BankSecond, AddrHelper::SizeFirst, and AddrHelper::SizeSecond.
xmem_size()
u32 xmem_size (void)
Get external memory size.
Returns
Size of the external memory in bytes
Definition at line 320 of file xmem.c.
{
    return BANK_COUNT * BANK_SIZE;
}
References BANK_COUNT, and BANK_SIZE.
Referenced by env_memory_size().
xmem_write()
void xmem_write (u32 addr, const void * data, u16 size)
Write the specified number of bytes to the external memory.
Parameters
addr Start address
data Source buffer
size Number of bytes to write
Definition at line 297 of file xmem.c.
{
    AddrHelper h;
    _xmem_overlap(addr, size, &h);
    _xmem_write(h.BankFirst, h.AddrFirst, data, h.SizeFirst);
    if(h.BankSecond != h.BankFirst)
    {
        _xmem_write(h.BankSecond, 0, (const u8 *)data + h.SizeFirst,
            h.SizeSecond);
    }
}
References _xmem_overlap(), _xmem_write(), AddrHelper::AddrFirst, AddrHelper::BankFirst, AddrHelper::BankSecond, AddrHelper::SizeFirst, and AddrHelper::SizeSecond.
Referenced by env_memory_write(), and initrd_load().