platform/avr/xmem/xmem.c File Reference
#include <xmem.h>
#include <spi.h>
#include <logger.h>
#include <gpio.h>
#include <avr/io.h>
#include <avr/pgmspace.h>
#include <stdlib.h>
Data Structures
struct AddrHelper
Macros
#define MEMTEST_SIMPLE
#define BANK_COUNT 3
#define BANK_SIZE_POT 17
#define BANK_SIZE 0x20000UL
#define OUTPUT_INTERVAL 0x2000UL
#define DUMMY 0xFF
#define SEED 42
#define SRAM_COMMAND_WRITE 2
#define SRAM_COMMAND_READ 3
Functions
static void _xmem_start (u8 bank, u8 command, u32 addr)
Start a transmission to the external memory.
static void _memtest (void)
Perform a memory test on the external memoryy.
static void _xmem_read (u8 bank, u16 addr, void *data, u16 size)
Read data from a memory bank.
static void _xmem_write (u8 bank, u16 addr, const void *data, u16 size)
Write data to a memory bank.
static void _xmem_set (u8 bank, u16 addr, u8 value, u16 size)
Set an area within a memory bank to 0.
static u8 _addr_to_bank (u32 addr)
Calculate which bank an address falls onto.
static u16 _addr_bank_offset (u32 addr)
Calculate the offset from the start of a memory bank for an address.
static void _xmem_overlap (u32 addr, u16 size, AddrHelper *h)
Calculate which bank will be affected by a memory operation.
void xmem_init (void)
Initialize external memory and run memory test.
void xmem_read (u32 addr, void *data, u16 size)
Read the specified number of bytes from the external memory.
void xmem_write (u32 addr, const void *data, u16 size)
Write the specified number of bytes to the external memory.
void xmem_set (u32 addr, u8 value, u16 size)
Set a specified number of bytes in the external memory to a value.
u32 xmem_size (void)
Get external memory size.
Detailed Description
Author
Tim Gabrikowski, Anton Tchekov
Version
0.1
Date
01.05.2023
Definition in file xmem.c.
Macro Definition Documentation
BANK_COUNT
#define BANK_COUNT 3
How many memory banks there are
Definition at line 21 of file xmem.c.
BANK_SIZE
#define BANK_SIZE 0x20000UL
The size of each memory bank in bytes
Definition at line 27 of file xmem.c.
BANK_SIZE_POT
#define BANK_SIZE_POT 17
The size of each memory bank as a power of two
Definition at line 24 of file xmem.c.
DUMMY
#define DUMMY 0xFF
Dummy SPI value when receiving
Definition at line 33 of file xmem.c.
MEMTEST_SIMPLE
#define MEMTEST_SIMPLE
Do a simple checkerboard memory test. Comment this out to do a more thorough memory test using random numbers
Definition at line 18 of file xmem.c.
OUTPUT_INTERVAL
#define OUTPUT_INTERVAL 0x2000UL
The interval in bytes at which to do progress updates in a memory test
Definition at line 30 of file xmem.c.
SEED
#define SEED 42
Random seed for extended memory test
Definition at line 36 of file xmem.c.
SRAM_COMMAND_READ
#define SRAM_COMMAND_READ 3
Read block command
Definition at line 42 of file xmem.c.
SRAM_COMMAND_WRITE
#define SRAM_COMMAND_WRITE 2
Write block command
Definition at line 39 of file xmem.c.
Function Documentation
_addr_bank_offset()
static u16 _addr_bank_offset (u32 addr) [static]
Calculate the offset from the start of a memory bank for an address.
Parameters
addr Full memory address
Returns
Bank address
Definition at line 227 of file xmem.c.
{
    return addr & (BANK_SIZE - 1);
}
References BANK_SIZE.
Referenced by _xmem_overlap().
_addr_to_bank()
static u8 _addr_to_bank (u32 addr) [static]
Calculate which bank an address falls onto.
Parameters
addr Full memory address
Returns
Bank number
Definition at line 216 of file xmem.c.
{
    return addr >> BANK_SIZE_POT;
}
References BANK_SIZE_POT.
Referenced by _xmem_overlap().
_memtest()
static void _memtest (void) [static]
Perform a memory test on the external memoryy.
Definition at line 65 of file xmem.c.
{
    u8 bank, w, v;
    u32 i;
    /* Run checkerboard memory test */
    log_boot_P(LOG_INIT, PSTR("Starting complete memory test"));
    spi_fast();
    for(bank = 0; bank < BANK_COUNT; ++bank)
    {
        log_boot_P(LOG_INIT, PSTR("Testing memory bank [%02d]"), bank + 1);
        /* Write */
        log_boot_P(LOG_INIT, PSTR("Writing pattern"));
        _xmem_start(bank, SRAM_COMMAND_WRITE, 0);
#ifdef MEMTEST_SIMPLE
        v = 0xAA;
#else
        srand(SEED);
#endif
        for(i = 0; ; ++i)
        {
#ifdef MEMTEST_SIMPLE
            v = ~v;
#else
            v = rand();
#endif
            if(i % OUTPUT_INTERVAL == 0)
            {
                log_boot_P(LOG_EXT, PSTR("0x%06lX"), i);
            }
            if(i >= BANK_SIZE)
            {
                break;
            }
            spi_xchg(v);
        }
        XMEM_DESELECT(bank);
        /* Read */
        log_boot_P(LOG_INIT, PSTR("Verifying pattern"));
        _xmem_start(bank, SRAM_COMMAND_READ, 0);
#ifdef MEMTEST_SIMPLE
        v = 0xAA;
#else
        srand(SEED);
#endif
        for(i = 0; ; ++i)
        {
#ifdef MEMTEST_SIMPLE
            v = ~v;
#else
            v = rand();
#endif
            if(i % OUTPUT_INTERVAL == 0)
            {
                log_boot_P(LOG_EXT, PSTR("0x%06lX"), i);
            }
            if(i >= BANK_SIZE)
            {
                break;
            }
            w = spi_xchg(DUMMY);
            if(w != v)
            {
                XMEM_DESELECT(bank);
                panic(PSTR(
                    "Memory test failed at address 0x%06lX\n"
                    " [0x%02X != 0x%02X]"),
                    i, w, v);
            }
        }
        XMEM_DESELECT(bank);
    }
}
References _xmem_start(), BANK_COUNT, BANK_SIZE, DUMMY, log_boot_P(), OUTPUT_INTERVAL, panic(), rand(), SEED, spi_fast(), spi_xchg(), SRAM_COMMAND_READ, SRAM_COMMAND_WRITE, and XMEM_DESELECT.
Referenced by xmem_init().
_xmem_overlap()
static void _xmem_overlap (u32 addr, u16 size, AddrHelper * h) [static]
Calculate which bank will be affected by a memory operation.
Parameters
addr Start address
size Number of bytes affected
h Output information
Definition at line 258 of file xmem.c.
{
    u32 addr_end;
    h->AddrFirst = _addr_bank_offset(addr);
    addr_end = addr + size;
    h->BankFirst = _addr_to_bank(addr);
    h->BankSecond = _addr_to_bank(addr_end);
    if(h->BankFirst == h->BankSecond)
    {
        h->SizeFirst = size;
    }
    else
    {
        h->SizeSecond = _addr_bank_offset(addr_end);
        h->SizeFirst = size - h->SizeSecond;
    }
}
References _addr_bank_offset(), _addr_to_bank(), AddrHelper::AddrFirst, AddrHelper::BankFirst, AddrHelper::BankSecond, AddrHelper::SizeFirst, and AddrHelper::SizeSecond.
Referenced by xmem_read(), xmem_set(), and xmem_write().
_xmem_read()
static void _xmem_read (u8 bank, u16 addr, void * data, u16 size) [static]
Read data from a memory bank.
Parameters
bank Bank number
addr Start address
data Buffer for the read data
size Number of bytes to read
Definition at line 156 of file xmem.c.
{
    u16 i;
    u8 *data8 = data;
    _xmem_start(bank, SRAM_COMMAND_READ, addr);
    for(i = 0; i < size; ++i)
    {
        data8[i] = spi_xchg(DUMMY);
    }
    XMEM_DESELECT(bank);
}
References _xmem_start(), DUMMY, spi_xchg(), SRAM_COMMAND_READ, and XMEM_DESELECT.
Referenced by xmem_read().
_xmem_set()
static void _xmem_set (u8 bank, u16 addr, u8 value, u16 size) [static]
Set an area within a memory bank to 0.
Parameters
bank Bank number
addr Start address
value Byte to write
size Number of bytes to write
Definition at line 198 of file xmem.c.
{
    u16 i;
    _xmem_start(bank, SRAM_COMMAND_WRITE, addr);
    for(i = 0; i < size; ++i)
    {
        spi_xchg(value);
    }
    XMEM_DESELECT(bank);
}
References _xmem_start(), spi_xchg(), SRAM_COMMAND_WRITE, and XMEM_DESELECT.
Referenced by xmem_set().
_xmem_start()
static void _xmem_start (u8 bank, u8 command, u32 addr) [static]
Start a transmission to the external memory.
Parameters
bank Memory bank number
command Read/Write command
addr Start address
Definition at line 53 of file xmem.c.
{
    XMEM_SELECT(bank);
    spi_xchg(command);
    spi_xchg(addr >> 16);
    spi_xchg(addr >> 8);
    spi_xchg(addr);
}
References spi_xchg(), and XMEM_SELECT.
Referenced by _memtest(), _xmem_read(), _xmem_set(), and _xmem_write().
_xmem_write()
static void _xmem_write (u8 bank, u16 addr, const void * data, u16 size) [static]
Write data to a memory bank.
Parameters
bank Bank number
addr Start address
data Buffer with the data to write
size Number of bytes to write
Definition at line 177 of file xmem.c.
{
    u16 i;
    const u8 *data8 = data;
    _xmem_start(bank, SRAM_COMMAND_WRITE, addr);
    for(i = 0; i < size; ++i)
    {
        spi_xchg(data8[i]);
    }
    XMEM_DESELECT(bank);
}
References _xmem_start(), spi_xchg(), SRAM_COMMAND_WRITE, and XMEM_DESELECT.
Referenced by xmem_write().
xmem_init()
void xmem_init (void)
Initialize external memory and run memory test.
Definition at line 279 of file xmem.c.
{
    /* Initialize XMEM */
    log_boot_P(LOG_INIT, PSTR("External memory driver initialized"));
    _memtest();
}
References _memtest(), and log_boot_P().
Referenced by main().
xmem_read()
void xmem_read (u32 addr, void * data, u16 size)
Read the specified number of bytes from the external memory.
Parameters
addr Start address
data Destination buffer
size Number of bytes to read
Definition at line 286 of file xmem.c.
{
    AddrHelper h;
    _xmem_overlap(addr, size, &h);
    _xmem_read(h.BankFirst, h.AddrFirst, data, h.SizeFirst);
    if(h.BankSecond != h.BankFirst)
    {
        _xmem_read(h.BankSecond, 0, (u8 *)data + h.SizeFirst, h.SizeSecond);
    }
}
References _xmem_overlap(), _xmem_read(), AddrHelper::AddrFirst, AddrHelper::BankFirst, AddrHelper::BankSecond, AddrHelper::SizeFirst, and AddrHelper::SizeSecond.
Referenced by env_memory_read(), lcd_image_1bit(), lcd_image_grayscale(), and lcd_image_rgb565().
xmem_set()
void xmem_set (u32 addr, u8 value, u16 size)
Set a specified number of bytes in the external memory to a value.
Parameters
addr Start address
value The value to write
size Number of bytes to set
Definition at line 309 of file xmem.c.
{
    AddrHelper h;
    _xmem_overlap(addr, size, &h);
    _xmem_set(h.BankFirst, h.AddrFirst, value, h.SizeFirst);
    if(h.BankSecond != h.BankFirst)
    {
        _xmem_set(h.BankSecond, 0, value, h.SizeSecond);
    }
}
References _xmem_overlap(), _xmem_set(), AddrHelper::AddrFirst, AddrHelper::BankFirst, AddrHelper::BankSecond, AddrHelper::SizeFirst, and AddrHelper::SizeSecond.
xmem_size()
u32 xmem_size (void)
Get external memory size.
Returns
Size of the external memory in bytes
Definition at line 320 of file xmem.c.
{
    return BANK_COUNT * BANK_SIZE;
}
References BANK_COUNT, and BANK_SIZE.
Referenced by env_memory_size().
xmem_write()
void xmem_write (u32 addr, const void * data, u16 size)
Write the specified number of bytes to the external memory.
Parameters
addr Start address
data Source buffer
size Number of bytes to write
Definition at line 297 of file xmem.c.
{
    AddrHelper h;
    _xmem_overlap(addr, size, &h);
    _xmem_write(h.BankFirst, h.AddrFirst, data, h.SizeFirst);
    if(h.BankSecond != h.BankFirst)
    {
        _xmem_write(h.BankSecond, 0, (const u8 *)data + h.SizeFirst,
            h.SizeSecond);
    }
}
References _xmem_overlap(), _xmem_write(), AddrHelper::AddrFirst, AddrHelper::BankFirst, AddrHelper::BankSecond, AddrHelper::SizeFirst, and AddrHelper::SizeSecond.
Referenced by env_memory_write(), and initrd_load().